### ISSUE TITLE
React 18 Migration: Refactor the React test suite to use React Testing Library

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10184]
This issue is to track the refactoring of our React test suite to use React Testing Library. 

<details>
  <summary>Links and resources</summary>
  
  - https://www.notion.so/carbondesignsystem/Audits-ca3fe640ffe242ac91bf3ab0749cb499?p=b1b911fa52a147d3af63d177c0a0ec3b&showMoveTo=true
  - https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/
  - https://kentcdodds.com/blog/avoid-nesting-when-youre-testing
</details>

<details>
  <summary>How to find enzyme usages</summary>
  
  The list below was generated by searching for `enzyme` within files having names containing our test suffix:
  
  https://user-images.githubusercontent.com/3360588/145886255-373f50c4-d3d3-4322-9963-bbea094192b4.mov
</details>

### Please use [the script to scaffold out new test files](https://github.com/carbon-design-system/carbon/issues/10184#issuecomment-1282894448)

```[tasklist]
### Wave 2
- [ ] https://github.com/carbon-design-system/carbon/issues/12665
- [ ] https://github.com/carbon-design-system/carbon/issues/12666
- [ ] https://github.com/carbon-design-system/carbon/issues/12667
- [ ] https://github.com/carbon-design-system/carbon/issues/12668
- [ ] https://github.com/carbon-design-system/carbon/issues/12669
- [ ] https://github.com/carbon-design-system/carbon/issues/12670
- [ ] https://github.com/carbon-design-system/carbon/issues/12671
- [ ] https://github.com/carbon-design-system/carbon/issues/12672
- [ ] https://github.com/carbon-design-system/carbon/issues/12673
- [ ] https://github.com/carbon-design-system/carbon/issues/12674
- [ ] https://github.com/carbon-design-system/carbon/issues/12675
- [x] https://github.com/carbon-design-system/carbon/issues/11736
- [ ] https://github.com/carbon-design-system/carbon/issues/12153
- [x] https://github.com/carbon-design-system/carbon/issues/12155
- [x] https://github.com/carbon-design-system/carbon/issues/12157
- [x] https://github.com/carbon-design-system/carbon/issues/12158
- [x] https://github.com/carbon-design-system/carbon/issues/12159
- [x] https://github.com/carbon-design-system/carbon/issues/12160
- [x] https://github.com/carbon-design-system/carbon/issues/12676
- [x] https://github.com/carbon-design-system/carbon/issues/12663
- [x] https://github.com/carbon-design-system/carbon/issues/12354
- [x] https://github.com/carbon-design-system/carbon/issues/12677
- [x] https://github.com/carbon-design-system/carbon/issues/12678
- [x] https://github.com/carbon-design-system/carbon/issues/12679
- [x] https://github.com/carbon-design-system/carbon/issues/12680
- [x] https://github.com/carbon-design-system/carbon/issues/12681
- [x] https://github.com/carbon-design-system/carbon/issues/12683
- [x] https://github.com/carbon-design-system/carbon/issues/12682
- [x] https://github.com/carbon-design-system/carbon/issues/12684
- [ ] https://github.com/carbon-design-system/carbon/issues/12685
- [ ] https://github.com/carbon-design-system/carbon/issues/12686
- [ ] https://github.com/carbon-design-system/carbon/issues/12687
- [ ] https://github.com/carbon-design-system/carbon/issues/12688
- [ ] 
```

```[tasklist]
### Initial wave of refactor (complete)
- [x] Use RTL for testing in `Accordion/__tests__/Accordion.Skeleton-test.js`
- [x] Use RTL for testing in `Accordion/__tests__/AccordionItem-test.js`
- [x] #10273
- [x] Use RTL for testing in `Breadcrumb/__tests__/Breadcrumb.Skeleton-test.js`
- [x] Use RTL for testing in `Button/Button-test.js`
- [x] Use RTL for testing in `ButtonSet/ButtonSet-test.js`
- [x] Use RTL for testing in `Checkbox/Checkbox-test.js`
- [x] #10272
- [x] #11706
- [x] https://github.com/carbon-design-system/carbon/issues/11883
- [x] https://github.com/carbon-design-system/carbon/issues/11886
- [x] https://github.com/carbon-design-system/carbon/issues/11884
- [x] https://github.com/carbon-design-system/carbon/issues/11885
- [x] #11509
- [x] #11510
- [x] #11511
- [x] Use RTL for testing in `DataTable/__tests__/Table-test.js`
- [x] Use RTL for testing in `DataTable/__tests__/TableActionList-test.js`
- [x] Use RTL for testing in `DataTable/__tests__/TableBatchAction-test.js`
- [x] Use RTL for testing in `DataTable/__tests__/TableBatchActions-test.js`
- [x] Use RTL for testing in `DataTable/__tests__/TableBody-test.js`
- [x] Use RTL for testing in `DataTable/__tests__/TableCell-test.js`
- [x] Use RTL for testing in `DataTable/__tests__/TableContainer-test.js`
- [x] Use RTL for testing in `DataTable/__tests__/TableHead-test.js`
- [x] Use RTL for testing in `DataTable/__tests__/TableRow-test.js`
- [x] #11512
- [x] #11704
- [x] https://github.com/carbon-design-system/carbon/issues/11956
- [x] #11994 
- [x] #11641
- [x] #11642
- [x] #11643
- [x] #11644
- [x] #11559
- [x] #11560
- [x] #11561
- [x] Use RTL for testing in `ListBox/__tests__/ListBox-test.js`
- [x] Use RTL for testing in `ListBox/__tests__/ListBoxField-test.js`
- [x] Use RTL for testing in `ListBox/__tests__/ListBoxMenu-test.js`
- [x] Use RTL for testing in `ListBox/__tests__/ListBoxMenuIcon-test.js`
- [x] Use RTL for testing in `ListBox/__tests__/ListBoxMenuItem-test.js`
- [x] Use RTL for testing in `ListBox/__tests__/ListBoxSelection-test.js`
- [x] #11824
- [x] https://github.com/carbon-design-system/carbon/issues/11957
- [x] #11710
- [x] #11711
- [x] #11712
- [x] #11713
- [x] #11705
- [x] #11707
- [x] #11714
- [x] #11729
- [x] #10277
- [x] #11730
- [x] #11731
- [x] #11732
- [x] https://github.com/carbon-design-system/carbon/issues/12021
- [x] https://github.com/carbon-design-system/carbon/issues/12022
- [x] https://github.com/carbon-design-system/carbon/issues/12023
- [x] https://github.com/carbon-design-system/carbon/issues/11958
- [x] #12087
- [x] #11733
- [x] #11734
- [x] #11735
- [x] #12088
- [x] #12154
- [x] #12156
- [x] #11630
- [x] #11629
- [x] #11709
- [x] #11708
- [x] #10274
- [x] #11995
- [x] #10275
- [x] Use RTL for testing in `UIShell/__tests__/Header-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/HeaderGlobalAction-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/HeaderGlobalBar-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/HeaderMenu-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/HeaderMenuButton-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/HeaderMenuItem-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/HeaderName-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/Link-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNav-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavDetails-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavFooter-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavHeader-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavIcon-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavItem-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavItems-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavLink-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavLinkText-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavMenu-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavMenuItem-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SideNavSwitcher-test.js`
- [x] Use RTL for testing in `UIShell/__tests__/SkipToContent-test.js`
- [x] Use RTL for testing in `UIShell/next/__tests__/SideNavMenu-test.js`
- [x] #10276
- [x] Use RTL for testing in `TimePicker/TimePicker-test.js`
```

**Comment by tay1orjones** [comment]
## High level steps

1. Get familiar with the component, gather list of functionality/api to be tested
1. Comment out or rename existing tests
1. Include RTL imports
1. Create new structure based on details to be tested
1. Write tests
   1. Render the component using `render` inside each `it` block
   1. If applicable, interact with the component as a person would using `userEvent`
   1. `expect` pieces of the component to be valid/correct using [`jest-dom` matchers](https://github.com/testing-library/jest-dom#table-of-contents)
1. Validate that the test coverage from new tests is the same or higher as the old tests

**Comment by tay1orjones** [comment]
## Patterns

### What should we test?
- How does a person use the component?
  - Click, hover
  - Keyboard
    - focus
    - special keys relating to functionality - `<kbd>esc to close</kbd>`
  - Opening/closing
  - Selecting/de-selecting
  - Toggling/disclosure
  - Choosing from a list
- How does a developer configure the component?
  - Internal composition via children
  - Potential common external composition? Like via `Stack`, `Grid`, etc?
  - Callbacks/event handlers
  - Refs
  - i18n, `translateById`
  - Other props
- What else is part of the public API, or is depended upon by consumers?
  - "Should place class name, data-testid on the outermost DOM node"
  - "Should place forwardRef ref on the {intended element}" (input, label, outermost DOM node, etc)
  - "Should place extra props on the {intended element}" (input, label, outermost DOM node, etc)
  - ... what else?

### Including RTL imports
```js
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
```
- `cleanup` from `@testing-library/react` should not be needed

### Find parts of a component to interact with
- Use [Queries accessible to everyone](https://testing-library.com/docs/queries/about)
- Prefer use of `screen` (defaults to `document.body`), rather than `container`
```js
screen.getByRole('button', {name: /submit/i});
```

### [Avoid nesting while you're testing](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing)
- `render()` in each `it()` block
  - [avoid hasty abstractions](https://kentcdodds.com/blog/aha-programming) that use `beforeEach`, `afterAll`, etc. unless absolutely necessary (mocking or something similar)
- The less `describe()` blocks the better

**Comment by jnm2377** [comment]
These are some helpful things I used a lot to refactor the tabs tests to RTL 

### Examples of RTL tests in our components
- `Notification`: https://github.com/carbon-design-system/carbon/pull/9494/files
-  v11 `Tabs` and `Tab`: https://github.com/carbon-design-system/carbon/pull/9722/files

### Helpful docs
- [jest expect matchers](https://jestjs.io/docs/expect) (what we're expecting the test to look for)
- [RTL queries](https://testing-library.com/docs/queries/about#types-of-queries) for selecting elements
- [RTL `fireEvent`](https://testing-library.com/docs/dom-testing-library/api-events) for testing events (keyboard, click, etc)
- [RTL `userEvent`](https://testing-library.com/docs/ecosystem-user-event/) for testing events (keyboard, click, etc)
- [RTL cheatsheet](https://testing-library.com/docs/react-testing-library/cheatsheet)

**Comment by joshblack** [comment]
> Reference for old test code and how it could be updated



### Renders as expected

**About**

This is a common pattern in the codebase that uses `describe` and `it` blocks to assert that a component renders or has the appropriate classes.

**What does it look like**

```jsx
describe('ProgressIndicatorSkeleton', () => {
  describe('Renders as expected', () => {
    it('should have the expected classes', () => {
      const wrapper = mount(<ProgressIndicatorSkeleton />);
      expect(wrapper.hasClass(`${prefix}--skeleton`)).toEqual(true);
      expect(wrapper.hasClass(`${prefix}--progress`)).toEqual(true);
    });
  });
});
```

**What about this is problematic**

Tests that assert if a component renders are not needed as this would be caught by other tests that are asserting what happens as a user interacts with a component. For tests that assert on class names, these are not being tested in Jest and instead would be tested by appearance in VRT.

**What to do about it**

In most cases, you can remove these tests. If the test is for class names, replace it with a Visual Regression Test.

### Component is mounted in an outer scope

**About**

In parts of our tests, you will see a component mounted outside of an `it` or `beforeEach` block. Often times, it will be at the top of a describe block

**What does it look like**

```jsx
describe('SomeComponent', () => {
  const wrapper = mount(/* ... */);

  it('should do ...', () => {
    // Interacts with wrapper
  });
});
```

**What about this is problematic**

This outermost wrapper is inherently stateful. This means that if your tests are interacting with it, reading data from it, etc that you could run into flaky tests that depend on a specific ordering in order to pass. Overall, this leads to tests that are harder to debug when things go wrong.

**What to do about it**

You can move the `wrapper` into the `it` block directly if there are only several tests. For many tests that use the same setup, move the `wrapper` into a `beforeEach` with this pattern:

```jsx
describe('SomeComponent', () => {
  let wrapper;

  beforeEach(() => {
    wrapper = mount(/* ... */);
  });

  it('should do ...', () => {
    // Interacts with wrapper
  });
});
```

This will ensure that the component is reset across test runs

**Comment by tay1orjones** [comment]
We need to resurrect https://github.com/carbon-design-system/carbon/pull/4467 so that `jest-dom` matchers like `toBeVisible` will work.

**Comment by joshblack** [comment]
@tay1orjones PR for it over in: https://github.com/carbon-design-system/carbon/pull/10302 👍

**Comment by tay1orjones** [comment]
### Testing against `next` component versions

- We'll move to a single file approach for these. One test file per component instead of duplicating a test file into `/next`.
- Thanks to https://github.com/carbon-design-system/carbon/pull/10304, CI will run tests with and without the v11 flag to ensure the test is ran against existing and `next` component versions
- In the event that a test is no longer applicable due to changes in `next` (or vice versa), the internal feature flag module/component can be used to ensure a test only applies to a `next` or non-`next` component version.

**Comment by tay1orjones** [comment]
### Do not use relative paths for component imports

- #10304 adds a config for `moduleNameMapper` to ensure imports from common packages (`@carbon/react`, `@carbon/react/icons`, `carbon-components-react`) within test files are resolved to the package central entrypoint.
- In practice this means that we should no longer use relative paths to import components and can use the same syntax consumers would use:

```diff
- import { default as Accordion, AccordionItem } from '../';
+ import { Accordion, AccordionItem } from 'carbon-components-react';
```

**Comment by tay1orjones** [comment]
### Where to place component composition (children) integration tests

- For components that leverage composition of specific children, place composition integration tests in the parent component's test file.
- As an example, `Breadcrumb` is intended to be augmented with `BreadcrumbItem` children. `BreadcrumbItem` also has specific conditions for when an `OverflowMenu` is passed as its children. 
  - Tests covering the full composition of Breadcrumb, BreadcrumbItems and the OverflowMenu should be placed in the `Breadcrumb-test.js` file. 
  - `BreadcrumbItem` tests testing individual props or functionality scoped to only the BreadcrumbItem should be placed in the `BreadcrumbItem-test.js file.

**Comment by tay1orjones** [comment]
### Testing pseudo elements

- jsdom does not currently support pseudo elements, so any component utilizing pseudo elements for core functionality can't really be fully tested through RTL.
- We'll need to address these in two ways:
  1. Test what we can in RTL. Typically this will result in asserting a particular element receives a specific class name.
  2. Test this functionality in a browser-based environment via Cypress in an e2e test file. This can be deferred for now in the context of this refactor workstream.

**Comment by joshblack** [comment]
# Test file archetypes

## Snapshot tests

A snapshot test is a test file that only tests the structural output of a component. For example, `expect(wrapper).toMatchSnapshot()`

<details>
  <summary>Example</summary>

```jsx
import React from 'react';
import { BreadcrumbSkeleton } from '../';
import { mount } from 'enzyme';

describe('BreadcrumbSkeleton', () => {
  it('should render', () => {
    const wrapper = mount(<BreadcrumbSkeleton />);
    expect(wrapper).toMatchSnapshot();
  });
});
```
</details>

This test should be refactored to test the following applicable parts of a component:

- Behavior (can the user interact with this component in some way?)
- Configuration (can the developer change props on this component in some way?)

<details>
  <summary>Refactor</summary>

```jsx
import React from 'react';
import { BreadcrumbSkeleton } from '../';
import { render } from '@testing-library/react';

describe('BreadcrumbSkeleton', () => {
  it('should support a custom `className` prop on the outermost element', () => {
    const { container } = render(<BreadcrumbSkeleton className="test" />);
    expect(container.firstChild).toHaveClass('test');
  });

  it('should spread additional props on the outermost element', () => {
    const { container } = render(<BreadcrumbSkeleton data-testid="test" />);
    expect(container.firstChild).toHaveAttribute('test');
  });
});
```
</details>


## Checklist

- Does the component have state?
- Can a user interact with this in some way?
- Does the component have props?
  - What element do the props get applied to?
  - Does the prop change the behavior of the component in some way?

**Comment by tay1orjones** [comment]
@abbeyhrt could you write up a comment on how to use the script you made to help scaffold these out?

**Comment by abbeyhrt** [comment]
Yeah! 

Directions to use `build-tests` script: 

1. In your terminal, change directories to `packages/react` 
2. Run `node tasks/build-test-rtl.js` and choose the component you are wanting to create tests for. If for some reason, a file cannot be made, you will be prompted to copy the created tests if you want to paste them in the appropriate place. 
3. That command will create a new test file called `<Component>-test.js--copy` in the component's directory. To get the test-runner to find the new tests, you will need to update the file name to `<Component>-test.js` and either rename or remove the currently existing test file.

**Comment by tay1orjones** [comment]
We're about 72% through this effort. Something additional to consider here would be if we could segment our enzyme tests to run against React 17, while the RTL ones run against 17 and 18.
