### ISSUE TITLE
v11 Release Candidate 0

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#10245]
**Date**

January 27th, 2022

**Scope**

This release will include all additions to the Design System. After this release is published, our team will shift focus to bug fixes, docs, and migration-related work.

- [ ] Styles
  - [x] https://github.com/carbon-design-system/carbon/issues/10292
  - [ ] Verify styles are in sync with `main`
  - [x] IBM Plex
    - [x] https://github.com/carbon-design-system/carbon/issues/10353
- [ ] React
  - [ ] Verify all changes are reflected in the migration guide
  - [x] Finalize all new components
  - [x] Finalize all changes to components
    - [x] Tabs
    - [x] Grid
    - [x] Tooltip
    - [ ] ContentSwitcher
- [ ] Grid
  - [x] Add clear migration path for existing flex grid users
  - [x] Verify all grid features are included for v11
  - [ ] Add % span support to column in React
- [x] Migration
  - [x] Migration CLI
    - [x] Support v11 upgrade path for React users
    - [x] Apply codemods for updating import paths

**Checklist**

- [x] Write out the scope for the release and break it down into issues in our Design System project
- [x] Create milestone
- [x] Create [feedback discussion post](https://github.com/carbon-design-system/carbon/discussions/10533)
- [ ] Publish blog post announcing the release

**Deferred**

- RC1
  - Website
    - Migration guide updates
    - Content updates
      - Element pages
    - Token updates / page / components
  - Migration
    - Migration CLI
      - Apply codemods for updating component APIs
- GA
- Post-GA
