### ISSUE TITLE
MultiSelect: Show selected items in the MultiSelect itself

### ISSUE THREAD

**Issue by adamalston** [carbon-design-system/carbon#10345]
### Summary

Show selected items in a MultiSelect field removing the need to open the dropdown to see what is selected.

### Justification

Users and engineers have requested this feature in alpha and beta testing.

If a MultiSelect is disabled and there are items within that are selected, how is a user supposed to know what those items are?

### Desired UX and success metrics

Template:
![Template](https://user-images.githubusercontent.com/18297826/148283354-990ca8e8-1900-48d3-8eef-1eb9ec1ccd42.png)

Concept (expanded):
![concept-expanded](https://user-images.githubusercontent.com/18297826/148283561-14fd95f4-50aa-4b61-8b45-a4c257b241ff.png)

Concept (collapsed):
![concept-collapsed](https://user-images.githubusercontent.com/18297826/148285340-99c18ca0-9283-48eb-8340-ca638b29f193.png)

Obviously the design in this concept may need to be changed but the functionality is there - the selected items are shown within the field itself without the need to expand the dropdown to see what is selected.

To generate this concept I put in a workaround to concatenate the display names of the selected items into a label:
```tsx
const label = initialSelectedItems
  .map((item: MultiSelectItem) => item.display)
  .join(', ');

return <MultiSelect label={label} initialSelectedItems={initialSelectedItems} ... />;
```

### Specific timeline issues / requests

Yes, this request is related to an upcoming release which I probably cannot detail here.

### Available extra resources

The images above.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/13435
- [ ] MultiSelect (selected items in field): implementation
- [ ] MultiSelect (selected items in field): website docs
- [ ] MultiSelect (selected items in field): figma kit
```

**Comment by abbeyhrt** [comment]
@adamalston Thank you for making this proposal! Would you be able to provide some user scenarios of when a Multiselect would be disabled but would have items selected?

**Comment by adamalston** [comment]
Here is a screenshot of a field that is read only - all of the options are disabled and some of them are selected by default:

![user interface](https://user-images.githubusercontent.com/18297826/148825954-8bc4699a-4de9-4d6f-876d-44332f37ba23.png)

This field is represented in Carbon using a MultiSelect with all options disabled and some selected by default.

**Comment by TannerS** [comment]
@abbeyhrt  if this proposal gets accepted, I made a PR for it, still may need some testing and unit test but seems to be possible, feel free to take a look if this is even needed https://github.com/carbon-design-system/carbon/pull/10389

**Comment by thyhmdo** [comment]
Thanks for making this proposal. Our team will have to review and do more visual research on this.

**Comment by sstrubberg** [comment]
[Bootstrap --- Multiselect w/ Label](https://mdbootstrap.com/docs/standard/extended/multiselect/)

**Comment by jt-helsinki** [comment]
Yes, please. The current implementation which only displays the number of selected items without displaying the selected items can certainly be improved. This proposal may not be viewed as 100% but it's certainly on the right track.

**Comment by n8allan** [comment]
Allow me to suggest that rather than showing the number as a tag, show each selected item as a separate tag with its own delete icon.  This then works like so many tag selection UIs (e.g. Stack Overflow)

**Comment by laurenmrice** [comment]
### Action items

- [ ] Research existing designs of a MultiSelect dropdown with individual tag selections in the field.
- [ ] Create different design iterations.
- [ ] Review with the Carbon team and Accessibility.
- [ ] Adjust designs with team feedback.
- [ ] Finalize spec.

**Comment by caseyg** [comment]
Just wanted to share that a request for this came up in a (totally unrelated) feedback session I was running today — and I'm so happy to find out that it's being acivevly worked on. 🎉 The proposed solution in Figma (below) is exactly what I was looking for. Thanks team!

<img width="583" alt="Screenshot 2024-02-20 at 2 48 15 PM" src="https://github.com/carbon-design-system/carbon/assets/462020/e68855f1-8752-46ef-b929-8e8c14c03ad2">

**Comment by alina-jacob** [comment]
**This could be a possible solution to this problem:** 
https://github.com/carbon-design-system/carbon/issues/16120#issuecomment-2038075215

Reference screenshot from website:
![image](https://github.com/carbon-design-system/carbon/assets/159760598/fcd93bf5-a903-4189-9c11-6e103bd7ae6d)

---

ℹ️ Note:
- This solution solves the [visibility issue ](https://github.com/carbon-design-system/carbon/issues/10345#issue-1094729193)
- This solution doesn't allow to dismiss selected options as shown in a possible solution [here](https://github.com/carbon-design-system/carbon/issues/10345#issuecomment-1954945361).
