### ISSUE TITLE
v11 Release Candidate 1

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#10350]
**Date**

February 24th, 2022

**Scope**

- [ ] Components
  - [ ] Styles
  - [ ] React
    - [ ] Add `auto` alignment option to popover
    - [ ] Finalize ContentSwitcher, postpone or address use case mismatches
    - [ ] CodeSnippet
      - [ ] Update copy button to use icon button (for tooltip to appear on focus)
    - [ ] Button
      - [ ] Instances of an icon-only button no longer have their tooltip rendering correctly
    - [ ] Docs
      - [x] Fix AspectRatio story, it seems to not have CSS being applied correctly
      - [ ] Make sure all components with `unstable_*` that should be unprefixed in v11 are unprefixed in code and in the stories
      - [ ] Add documentation for Stack usage, see impact on form layout
- [ ] Elements
  - [ ] Color
  - [ ] Grid
  - [ ] Icons
  - [ ] Pictograms
  - [ ] Layout
  - [ ] Motion
    - [ ] Add token for easing curves in package
    - [ ] Update v11 migration doc to specify migration path for: `$carbon--ease-in`, `$carbon--ease-out`, etc.
  - [ ] Themes
  - [ ] Type
- [ ] Website
  - [ ] Elements QA, make sure all content is up-to-date (design, dev)
  - [ ] Tutorial
    - [ ] Verify tutorial is up-to-date with changes
- [ ] Migration
  - [ ] Migration CLI
    - [ ] Investigate codemods for styles, in particular for tokens
  - [ ] Website
  - [ ] Documentation
    - [ ] Finish migration guide from `carbon-components` to `@carbon/styles` or `@carbon/react`
- [ ] Repo
  - [ ] Add codesandbox link for reporting issues for `@carbon/react`
  - [ ] Add codesandbox link for reporting issues for `@carbon/styles`
  - [ ] Update issue template to include `@carbon/react` and `@carbon/styles`

**Checklist**

- [ ] Write out scope for this release and break it down into issues in the Design Systems project
- [x] Create milestone for this release
- [ ] Post-release
  - [ ] Create feedback discussion post
  - [ ] Publish blog post announcing the release
  - [ ] Create Slack announcement and link blog post and feedback discussion post
