### ISSUE TITLE
[Umbrella] Grid

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#10392]
**About**

Features and supporting documentation for CSS Grid needs to be completed for v11. This work includes adding in missing features, defining migration paths for teams using our existing grid, along with syncing up with design on our overall grid direction in v11.

**Features**

- [ ] All grid modes supported
  - [ ] Wide
  - [ ] Narrow
  - [ ] Condensed
  - [ ] No gutter
- [ ] Full width support
- [ ] Supports responsive column classes
  - [ ] Spanning different amounts of columns at different breakpoints
  - [ ] Spanning no columns at specific breakpoints
- [ ] Subgrid support
  - [ ] Includes responsive column classes
- [ ] Mixed grid modes
  - Invariant: starts as wide and goes narrow
- [ ] Offset
- [ ] Gutter
  - [ ] Change gutter per-column
  - [ ] Change gutter per-row
  - [ ] Responsive classes

**Checklist**
- [x] #10472
- [x] #10473
  - For example, span covers the "offset" case, does it make sense to use that?
- [x] #10474
  - [ ] Add codemod to change `Grid` to `FlexGrid`
  - [ ] How does `Row` map over?
- [x] #10475
- [x] #10476
- [x] #10562
- [x] #10563
- [x] #10845

**Constraints**

- Mixing grid modes results in the incorrect layout when rows wrap
- CSS Grid does not have a gutter on the left/right
- Margin on the outer side only works if full grid
- Full width versus snap to breakpoints ???

**Things to consider**

- How easy would it be to move from flexbox to CSS Grid?
- Could we change narrow from an asymmetric grid to a symmetric grid with 16px gutter?
- Could we opt specific columns into a hang? Could we opt a column _not_ to hang?

**Deferred**

- Bring back auto column-span support
  - Still exists in flexbox grid for now

**Comment by joshblack** [comment]
**Meetings**

_January 12th, 2020_

- Created umbrella issue
- Documented features, checklist, and constraints we ran into
- Next steps
  - API Design doc
  - Mixed grid mode is still an issue, need to explore hang on column

**Comment by tay1orjones** [comment]
@joshblack With the re-addition of narrow mode in #10934, I think this is complete. Closing.
