### ISSUE TITLE
Pop-over: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10426]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] ~Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))~ NA

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] ~Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)~ NA
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [ ] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [ ] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [x] Develop

**Comment by laurenmrice** [comment]
## Visual bugs

### scss


### Storybook
- [ ] Fix alignment of caret, container and trigger button https://github.com/carbon-design-system/carbon/pull/10539#issuecomment-1031958977

**Comment by laurenmrice** [comment]
## Website

### Live demo
- [ ] We need a Live demo built for Popover. https://github.com/carbon-design-system/carbon-website/issues/2487

### Code tab
- [ ] We need to add a code tab. https://github.com/carbon-design-system/carbon-website/issues/2474

### A11y tab
- [ ] We need to add an a11y tab. https://github.com/carbon-design-system/carbon-website/issues/2475

**Comment by tay1orjones** [comment]
Closing since we've got the remaining items covered via #2487, #2474, #2475.
