### ISSUE TITLE
v11 Migration Content

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#10488]
**About**

This issue tracks all migration-related content across all packages and upgrade paths for v11. Migration content for v11 lives in either the v11 guide on our website or in an all-in-one document for development-related migration content.

**Upgrade Paths**

- [ ] Styles-only track
- [ ] Styles and React track
- [ ] Styles, React, and React icons track

**Packages**

- [ ] `carbon-components`
- [ ] `carbon-components-react`
- [ ] `@carbon/styles`
  - [ ] Sass API Documentation available at `docs/sass.md`
- [ ] `@carbon/react`
- [x] `carbon-icons`
- [x] `@carbon/icons`
- [ ] `@carbon/icons-react`
- [ ] `@carbon/colors`
  - [ ] Document changes to imports
  - [ ] Document changes to public exports per-file
  - [ ] Document re-exports for this package in `@carbon/styles` or `@carbon/react`
  - [ ] Sass API Documentation available at `docs/sass.md`
- [ ] `@carbon/elements`
  - [ ] Document changes to imports
  - [ ] Document changes to public exports per-file
  - [ ] Sass API Documentation available at `docs/sass.md`
- [ ] `@carbon/grid`
  - [ ] Document changes to imports
  - [ ] Document changes to public exports per-file
  - [ ] Document re-exports for this package in `@carbon/styles` or `@carbon/react`
  - [ ] Sass API Documentation available at `docs/sass.md`
- [ ] `@carbon/layout`
  - [ ] Document changes to imports
  - [ ] Document changes to public exports per-file
  - [ ] Document re-exports for this package in `@carbon/styles` or `@carbon/react`
  - [ ] Sass API Documentation available at `docs/sass.md`
- [ ] `@carbon/motion`
  - [ ] Document changes to imports
  - [ ] Document changes to public exports per-file
  - [ ] Document re-exports for this package in `@carbon/styles` or `@carbon/react`
  - [ ] Sass API Documentation available at `docs/sass.md`
- [ ] `@carbon/pictograms`
- [ ] `@carbon/pictograms-react`
- [ ] `@carbon/themes`
  - [ ] Document changes to imports
  - [ ] Document changes to public exports per-file
  - [ ] Document re-exports for this package in `@carbon/styles` or `@carbon/react`
  - [ ] Sass API Documentation available at `docs/sass.md`
- [ ] `@carbon/type`
  - [ ] Document changes to imports
  - [ ] Document changes to public exports per-file
  - [ ] Document re-exports for this package in `@carbon/styles` or `@carbon/react`
  - [ ] Sass API Documentation available at `docs/sass.md`

**Questions**

- How do we best demonstrate the multiple ways you can import something?
  - For example, you can get colors from `@carbon/colors`, `@carbon/styles/scss/colors`, or `@carbon/react/scss/colors`

**Checklist**
- [x] #10848

**Comment by joshblack** [comment]
## Templates

### Sass package

```md
## @carbon/package-name

**Changes**

- Change 1
- Change 2
- Change 3

| Filename | v10 | v11 |
| :------- | :-- | :-- |

For full Sass API documentation, visit the [Sass Documentation](#todo) for the package.
```

**Comment by joshblack** [comment]
## Change types

- No change
- Removed (no replacement)
- Removed, use <export> instead
- Updated to <new type>
