### ISSUE TITLE
Modals have no easy way of showing the recommended loading state

### ISSUE THREAD

**Issue by alexandertrefz** [carbon-design-system/carbon#10495]
### Summary

The Modal guidelines recommend [2 variants of a loading state](https://carbondesignsystem.com/components/modal/usage/#loading), however neither are easy to accomplish with the (react) library out of the box.

### Justification

Developers should be enabled to achieve the recommended visual states, in the easiest way possible, to enable a consistent UX, as well as improving DX.

### Desired UX and success metrics

The Modals should have a trivial way of achieving all the properties of the recommended loading states.

### My proposal

The Modals should have a `loading` property that takes 3 values: `"none" | "inline" | "overlay"`, and a `loadingText` property that either shows on the overlay loader (if `loading === "overlay")`, or overrides the `submitButtonText` (if `loading === "inline"`) and disables the button while `loading !== "none"`.

### Specific timeline issues / requests

I think this should be included in the upcoming v11 release.

### Available extra resources

I am happy to attempt my first PR.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/13180
- [ ] Modal loading state: design spec for overlay
- [ ] https://github.com/carbon-design-system/carbon/issues/13181
```

Surya.K.V@ibm.com - design specs
lucasfeol@ibm.com - development

**Comment by TannerS** [comment]
@alexandertrefz  (im not on the carbon team) but this is a cool PR, if you dont attempt it, let me know, ill give it a shot

**Comment by alexandertrefz** [comment]
I am happy to let other people take a shot first, feel free to go for it @TannerS. The only difficulty that I can see from my personal testing is that the overlay of the `Loading` component needs to be somehow tamed such that it only affects the modal. The rest should be pretty easy, I think.

**Comment by thyhmdo** [comment]
We will update the visual for doc enhancement. But we're not pursuing to put this into our coding system.

**Comment by alexandertrefz** [comment]
This would provide a significant benefit to developers. We need proper loading state/async handling all the time in all the Apps that our company builds. With the current implementation of Carbons Modals in React, we simply can not use them, while the design side clearly acknowledges the need for this as well. This change would add 2 properties, with barely any maintenance required to keep this feature working - So why would you not pursue to add this to the system?

**Comment by alexandertrefz** [comment]
@thyhmdo Any further explanation on this? Having to build these modals on our own is a pretty significant burden in adopting carbon.

**Comment by thyhmdo** [comment]
hi @alexandertrefz I think at the moment, this is not our list for V11 prioritization. But we will have our devs clarify more about the feasibility of this request. Thanks for your patience.

**Comment by jnm2377** [comment]
Hey @alexandertrefz thanks for bringing this up. We are going to do some research on the dev side to see what would be the best way to support these loading states, but the design pattern may also change. We'll post an update on this issue. 👍🏽

**Comment by alexandertrefz** [comment]
@jnm2377 Has anything happened on this front?

**Comment by sstrubberg** [comment]
Checking with our design team on the "completeness" on the spec. Once confirmed, we would totally be open to a community contribution. Stay tuned!

**Comment by sstrubberg** [comment]
Looks like the spec still needs some love from design to be complete. We're reviewing this along with our other priorities to determine the best course of action.

**Comment by Surya-kv** [comment]
### Design Specs : Inline & Overlay loader
--------------------------------------------------------------------------------------------------------------------------
![Inline loader_white](https://github.com/carbon-design-system/carbon/assets/135205291/775f028e-d902-4fd3-a1a9-6eddaf06513c)

![Inline loader_grey](https://github.com/carbon-design-system/carbon/assets/135205291/5b05fd8c-37c3-4b21-a5de-dd7385b76915)

--------------------------------------------------------------------------------------------------------------------------
![overlay loader_white](https://github.com/carbon-design-system/carbon/assets/135205291/c2e62433-1fa6-4304-89ec-37b842fcfa4b)

![overlay loader_grey](https://github.com/carbon-design-system/carbon/assets/135205291/34c177a4-7f1b-4847-b58b-4d720244c1f6)

**Comment by thyhmdo** [comment]
@Surya-kv Thank you for the contribution! 


The Carbon Design team discussed and here is the note in general.

**For design**
- We need to think more about the relation between the text and the status icon in the Inline loading
- We may want to consider the Success icon to be outline vs filled in the Overlay loading
- We may need to clarify the time usage for each style or for this component as a whole (also determined by the backend for the usage of it) 
- Review this Design https://react.carbondesignsystem.com/?path=/story/components-inlineloading--ux-example
- We may want to design flows for this component to understand the interaction of this component 

**For developing**
- We would move forward with two options but will likely implement the Inline loading first (after the final approval from the design team)

**Comment by Surya-kv** [comment]
@thyhmdo I really appreciate the recommendations that you made! 

I'm hoping that we can adhere to the carbon guidelines of time usage for this component .

We can utilize an overlay loader whenever the anticipated wait time exceeds three seconds. You can refer to the guidelines provided by carbon. check out this guideline from carbon : #https://carbondesignsystem.com/components/loading/usage/ . Alternatively, for wait times shorter than three seconds, we can employ an inline loader.

Sharing the updated designs of the inline and overlay loaders within the modal :
### Inline loader design updated design
![Option 2 -Modal _ Inline loader](https://github.com/carbon-design-system/carbon/assets/135205291/1555f9a3-d0f3-47f0-afc3-036e8be9dcad)

### Overlay loader updated design
![Overlay loader option _1](https://github.com/carbon-design-system/carbon/assets/135205291/b2f9f77e-11d2-4e27-944b-85c1659ddde1)
This images helps us understand how this component interacts with one another.

I can work on the spec and share it here if the updates are ok. Please share your thoughts with me.

**Comment by tay1orjones** [comment]
@thyhmdo @Surya-kv the disabling of the cancel/close button should be reconsidered. If the "saving" action fails silently for whatever reason, the UI is completely locked and the user will have to refresh the entire screen.

**Comment by alexandertrefz** [comment]
No action should ever fail silently, and a cancel button that is always available means that the user can cancel any action, which then must be handled by every developer and supported by any API call you might make. This tradeoff would be monumentally bad.

**Comment by Tomahaawk** [comment]
Which is the expected loading spinner position in the Inline loader? Should I consider the updated design you posted @Surya-kv or the one in Figma?

**Comment by Tomahaawk** [comment]
@Surya-kv Another question, I was talking to @tay1orjones about the inline loader when in active state and in the design it looks like the button gets replaced by the loader with that white background, but we may want to keep the button and show the loader replacing the text, this way we can set the button as disabled while the loading is active and inherit the disabled styles. Which one would be expected? 
As Taylor said to me, the disabled tokens are specifically created for this scenario to ensure improved color contrast, etc.

**Comment by Surya-kv** [comment]
@Tomahaawk Please use the below figma file  for the updated design spec. 
In reference to your query about the button style during the loading state,  I would propose changing the button's color to transparent. This approach aligns with accessibility considerations, as it ensures that the color contrast remains optimal.

[**Figma**](https://www.figma.com/file/uSSXI5VprCEcnuLgkfThtz/Loader-in-modal_-Spec?type=design&node-id=424%3A4266&mode=design&t=fPb0EFxK2eRgIzdB-1)

![Inline loader_white](https://github.com/carbon-design-system/carbon/assets/135205291/62d1aa49-6c28-46f6-b5ac-fc9ad96ae35b)

![Inline loader_grey](https://github.com/carbon-design-system/carbon/assets/135205291/ced38669-5b40-4e13-bad3-c2102d409113)

**Comment by tw15egan** [comment]
It seems like this feature was added in #14490; thanks for that, @Tomahaawk!
