### ISSUE TITLE
Updating the progress bar in code 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#10670]
## Updating the progress bar in code 
Related issue: https://github.com/carbon-design-system/carbon-website/pull/2688

**Tasks** 
- [x] Adding statuses (error, success, loading)
- [x] Adding alignment variants 
- [x] Adding sizes (big and small)
- [x] RTL support

**Comment by jnm2377** [comment]
@thyhmdo is there a design spec for all the things that need to be updated?

**Comment by janhassel** [comment]
@thyhmdo I guess this issue can be closed now that the four PRs are merged

**Comment by thyhmdo** [comment]
@janhassel yes
