### ISSUE TITLE
Add `auto` alignment option to popover

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10716]
With the addition of Popover, it would be nice if the Popover could detect when it is rendering outside of a browser edge boundary and reflow to a different direction/alignment to ensure popovers are always rendered inside/visible within the browser window.

This could live behind a new `auto` option for the `align` prop.

- [ ] https://github.com/carbon-design-system/carbon/issues/11385
- [ ] Adjust Popover to be visible when scrolling (decided not to pursue)
- [ ] Adjust Popover to be visible on resize (decided not to pursue)

**Comment by abbeyhrt** [comment]
Research Phase: 
1. What is auto alignment to us? 
  - first render 
  - scroll 
  - resize 
2. What do we want the component to do? 
Find existing examples. 
3. Can we do that ourselves easily? 
- dug into their code. what do they do, can we do it? 
- Loop recursively through ancestors - 2000 lines 

Research and development: 
4. Can we use their package? 
- I could go the floating container as expected 
- The caret doesn't move as expected 
5. Talk to design. Agree on a path forward 

Now: 
 For now, getting it to work first render

**Comment by tay1orjones** [comment]
> The tooltip adjusting on scroll and resize are stretch goals.

Update - based on new discussions, we're not going to pursue these stretch goals at this time. We have no user data to back up the need for them. We're open to reevaluate in the future but for right now we haven't heard scroll and resize are necessary functionality.
