### ISSUE TITLE
Migrate currently deployed CF services 

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#10834]
**About**

We would like to transition services on CF (CloudFoundry) to another hosting strategy. Some of our options include GitHub Pages for static sites along with alternatives on IBM Cloud such as CodeEngine. This issue will determine the hosting strategy for each of our services and will serve as an umbrella for updating each of the services listed below.

**Services**

- [x] Carbon Design System
  - Type: Gatsby, static
  - URL: https://carbondesignsystem.com
- [x] Versioned Carbon Websites
  - [x] Design System
    - [x] https://v6.carbondesignsystem.com
    - [x] https://v7.carbondesignsystem.com
    - [x] https://v8.carbondesignsystem.com
    - [x] https://v9.carbondesignsystem.com
    - [x] https://github.com/carbon-design-system/carbon/issues/12170
    - [x] https://github.com/carbon-design-system/carbon/issues/12171
  - [x] React Storybook
    - [x] https://v6-react.carbondesignsystem.com/
    - [x] https://github.com/carbon-design-system/carbon/issues/12169
    - [x] https://github.com/carbon-design-system/carbon/issues/12172
       - Repo already created, need to update the pipeline
       - [x] #12860
- [x] DPO/Brand
  - [x] https://github.com/carbon-design-system/carbon/issues/12175
  - [x] https://github.com/carbon-design-system/carbon/issues/12177
  - [x] https://github.com/carbon-design-system/carbon/issues/12186
  - [x] https://github.com/carbon-design-system/carbon/issues/12189
  - [x] https://github.com/carbon-design-system/carbon/issues/12190
  - [x] https://github.com/carbon-design-system/carbon/issues/12191

---

- Carbon for IBM
  - Not on CF  
  - Type: Next.js
  - URL: https://ibm.carbondesignsystem.com
- Badges
  - Not on CF
  - Type: Next.js
  - https://vercel.com/carbon-design-system/carbon-badges
- Gatsby Theme
  - Not on CF
  - Type: Next.js
  - https://vercel.com/carbon-design-system/gatsby-theme-carbon
- Themes (no longer supporting)
  - Type: static
  - URL: https://themes.carbondesignsystem.com
- https://github.com/carbon-design-system/carbon-website/issues/2951
  - Type: static
  - Potential strategy: move to gh pages
  - EDIT: Not part of this epic, this epic should focus on migrating existing running CF applications

**Comment by tay1orjones** [comment]
https://www.ibm.com/cloud/blog/configuring-a-custom-domain-for-your-ibm-cloud-code-engine-application

**Comment by jeffchew** [comment]
Instructions on how to SSH into a CF app and downloading the static contents from it:
https://themorgan.io/feature/2020/07/13/download-apps-ibm-cloud.html

Used this method to extract the v6-v9 website and react storybook contents.

**Comment by tay1orjones** [comment]
All sites have been migrated, all CloudFoundry apps have been stopped.
