### ISSUE TITLE
Finalize v11 usage experience content

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10850]
Usage documentation needs to be finalized. Schedule a meeting to go through the **website and storybook*, find what's missing in the following areas (make issues/PRs to resolve):

- [x] #10895
- [x] #10894
- [ ] #10973
- [ ] #10974
- [x] #10975 
- [x] #10889
- [x] #10976
- [x] #10977
- [x] #10980
- [x] #10978 
- [x] #10979

**Comment by joshblack** [comment]
**Usage**

- [ ] Website
  - [ ] Component purpose and behavior is documented in a usage page
  - [ ] Component style is documented in a style page
  - [ ] Component implementations are documented in a code page
  - [ ] Component a11y considerations are documented in an accessibility page
  - [ ] Component has an up-to-date code playground
  - [ ] Each feature of the component is documented and has is shown on the storybook
  - [ ] Images are up-to-date and mirror storybook
- [ ] Storybook
  - [ ] Component has at least one story that demonstrates usage and props
  - [ ] Component has a docs page that follows our template and includes
    - [ ] A prop table for the component and any sub-components
  - [ ] Component has controls
  - [ ] Component has configurable controls in at least one story
- [ ] Migration
  - [ ] Component has migration guide, if applicable, from v10 to v11
