### ISSUE TITLE
Carbon v11 mini-series

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#11294]
### Summary

Ideas for a FEDucation mini series on Carbon v11 to get more people excited about it, answer any questions they may have, help people migrate, etc. 

[Associated spreadsheet](https://ibm.ent.box.com/notes/984236552788?s=envg62fuu0t386mqbwwlga1jzos8qmf5)

<details>
  <summary>Initial/Possible topic ideas</summary>
  
- React package update, API & sass changes
    - single package management
    - updating imports
    - icon sizes
    - component prop changes
    - changing to sass modules
    - token name changes
- Theming & Layering
    - how to set global theme
    - how to do inline/zoned theming
    - how to do light/dark mode
    - how to use `Layer`
- CSS Grid vs. flex grid
    - how to continue building with flex grid
    - how to build the same ui with CSS grid
    - using subgrid
- A11y changes
    - what components changed (might be helpful to explain why, a11y reasoning)
        - notification
        - tooltip
        - toggle tip
        - popover
        - tabs (was this an a11y refactor?)
    - what changed about these components
    - how is it more accessible
- Other smaller topics 
    - net new things (not pertaining to these broader topics above)
    - contribution: what does that look like now with the single package
    - v11 office hours
</details>

#### Checklist
Initial Planning:
- [x] https://github.com/carbon-design-system/carbon/issues/11462
  - [x] #11809
  - [x] #11810

Make the content:
- [ ] Carbon v11 mini-series: Intro to v11 & package management
- [x] #11808
- [ ] Carbon v11 mini-series: Theming
- [ ] Carbon v11 mini-series: a11y refactors & new components
- [ ] Carbon v11 mini-series: Grid

Publish it:
- [ ] Carbon v11 mini-series: Execute share-out strategy

**Comment by joshblack** [comment]
Some topics that might be helpful for adoption:

- Understanding the compatibility mode
- Moving to v11 incrementally

**Comment by sstrubberg** [comment]
I'd love to see something around migration itself. Here are some headline ideas..

- Myth-busting Migration to Carbon v11
- Five things teams worry about when migrating to v11.. and how to solve for them!
- You need Codemods? We have Codemods!
- How we migrated the Carbon Tutorial to v11

**Comment by jnm2377** [comment]
> I'd love to see something around migration itself. Here are some headline ideas..
> 
> * Myth-busting Migration to Carbon v11
> * Five things teams worry about when migrating to v11.. and how to solve for them!
> * You need Codemods? We have Codemods!
> * How we migrated the Carbon Tutorial to v11

@sstrubberg these headlines are good. I wanted to get more context, though, since I don't really know what you imagined the content would actually be. 

I had imagined the talks being something along the lines of helping people migrate, going over the changes in detail + showing examples (which should also help with migration). That is all content that I think any of our devs could take on since it's all stuff we know. I think the codemods definitely fall into this category. But in terms of the talks you suggested, I was wondering:

- what are the myths you're talking about? I haven't heard of any.
- what things teams are worried about? who have we talked to?

**Comment by sstrubberg** [comment]
Good questions. A lot of my ideas were based off a meeting we had with devs from Carbon for IBM Products. Probably some additional learnings need to be had before going full myth busters ;) Let's break this issue down further based on the topics you've been brainstorming about.
