### ISSUE TITLE
Increase `a11y-checker`  coverage, test component states (focus, hover, open/close, etc.)

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11370]
- [ ] Complete a11y-checker coverage for Dropdown, (open close hover disabled keyboard etc.)
  - [ ] Present at CAG to see if we're hitting everything they expect, or need to modify
  - [ ] Repeat the approved pattern across all other components

**Comment by tay1orjones** [comment]
We've decided to close this due to the following:

- There haven't been many bugs relating to component states
- This would be costly to implement with little benefit/outcome (due to above)

Testing component states is a valuable part of Carbon's testing strategy though. We'd welcome new issues focused on _individual components_ that would benefit from covering component states in tests via `a11y-checker`.
