### ISSUE TITLE
Fluid inputs: update design specs to v11

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#11443]
**Original issue** (v10): https://github.com/carbon-design-system/carbon/issues/5416

Revisit and update the Fluid Input spec with v11 tokens 
- [x] v1 pass of all fluid component updates
- [x] v1 Design Review
- [x] https://github.com/carbon-design-system/carbon/issues/11728
- [x] v2 Design Review
- [x] Finalize specs
   - [x] [Text input](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/v11---Fluid-input---Text-input?node-id=0%3A1)
   - [x] Text area
   - [x] Dropdown
   - [x] ComboBox
   - [x] Multi-select
   - [x] Date picker
   - [x] Number input
   - [x] Select
   - [Form](https://github.com/carbon-design-system/carbon/issues/12014): on-going work now has its own issue

**Comment by aagonzales** [comment]
## Outstanding decision that need to still be addressed (affects all fluid inputs)

1. Focus state style

<img width="772" alt="image" src="https://user-images.githubusercontent.com/11670886/176944148-1ff7df36-fed0-4580-838c-2d6ccac2e2ad.png">

2. Warning text appearance 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/11670886/176944218-693f14d0-f133-4012-aa5c-962b157a1e6a.png">

3. Error message overflow

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/11670886/176945590-1d9a5bca-cb56-4fe1-a1fb-aae37b4aa810.png">

**Comment by aagonzales** [comment]
Going to close this as complete, Form has its own issue now and will need additional work
https://github.com/carbon-design-system/carbon/issues/12014
