### ISSUE TITLE
[New] "list" component design

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#11442]
## "List" component

Proposal discussion: https://github.com/carbon-design-system/carbon/discussions/10263
**Accepted:** 
- Need from multiple product team and business units
- Generalized component that can easily be used across products with little customization 
- External dev resources promised for development (Jan)

**Define component:**
- [x] Aggregate design use-cases for "list" across products
   - How is it different than existing `list` and `structured-list` 
- [x] Create design spec with all variations for delivery 
- [x] Define the name of component and variants (`list` and `structured-list` already exists)
   - [x] Define name of component variants
- [x] Design review and sign-off
- [x] Developer review (can be included in same design review)
- [x] Hand-off to dev for experimental development 

**Website:**
- [x] [Usage tab/ Style tab content](https://github.com/carbon-design-system/carbon-website/pull/3145) (in review)
- [x] [Live demo](https://github.com/carbon-design-system/carbon-website/issues/3153) (dev issue)
- [x] [Code tab content](https://github.com/carbon-design-system/carbon-website/issues/3152) (dev issue)
- [ ] [Accessibility tab content](https://github.com/carbon-design-system/carbon-website/issues/3154) (Michael Gower)

**Design kit:**
- [x] [Add to Figma (priority) ](https://github.com/carbon-design-system/carbon-design-kit/issues/569)
- [ ] ~~[Add to Sketch (deprioritized)](https://github.com/carbon-design-system/carbon-design-kit/issues/570)~~
- [ ] ~~[Add to XD (deprioritized)](https://github.com/carbon-design-system/carbon-design-kit/issues/497)~~
