### ISSUE TITLE
Bring TreeView to stable

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#11722]
Bring Treeview to stable. Definition of done.

#### Code
REF [11687](https://github.com/carbon-design-system/carbon/pull/11697)

#### Accessibility
- https://github.com/carbon-design-system/carbon/issues/6792

#### Designs
- [Latest design spec](https://ibm.box.com/s/r5wi7wkt4f50bo1kw6zamurl3kbbwst0)
- https://github.com/carbon-design-system/carbon/issues/5180: Original design issue
- https://github.com/carbon-design-system/carbon/issues/6203: Design enhancements issues

Variants
- [x] https://github.com/carbon-design-system/carbon/issues/11874
- ~Multi-select~ Deferred for later development. 

#### Website
- [x] https://github.com/carbon-design-system/carbon-website/issues/2210
- [x] https://github.com/carbon-design-system/carbon-website/issues/2211
- [x] https://github.com/carbon-design-system/carbon-website/issues/2216 
- https://github.com/carbon-design-system/carbon-website/issues/2209 - TBD
- [x] https://github.com/carbon-design-system/carbon-website/issues/3112

#### Design kits
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/548
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/549 (lower priority)
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/550 (can ship without XD)
