### ISSUE TITLE
ContextMenu: Bring to `stable` ☂️ 

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11770]
Originally proposed in https://github.com/carbon-design-system/carbon/issues/6830, it's been over a year since the original submission and likely this is ready to move from `unstable` to `stable`

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/674
- [ ] https://github.com/carbon-design-system/carbon/issues/13514
```

**Comment by tay1orjones** [comment]
@janhassel thanks for meeting today about this one! Capturing some notes below - feel free to add or reclarify any pieces:

> Needs storybook updates, remove generator config, replace with usage examples, figure out left nav hierarchy/naming

- [ ] Move OverflowV2 out from under "Menu" to be it's own root level item in the storybook left nav
- [ ] Add some basic stories for Menu showing off the Menu components in isolation
  - [ ] Add these basic stories to the e2e tests so they're covered by Percy/Visual regression tests
- [ ] Rename "ContextMenu" story folder to "useContextMenu"
- [ ] Add a .mdx docs page for Menu and include there a blurb about `useContextMenu` and how it can be a useful augmentation w/ Menu components. Provide a link to the useContextMenu default story.

**Comment by janhassel** [comment]
@tay1orjones With the recent changes, would you mind re-assessing this checklist and the completion status?
Irt the two points "Add to Figma kit" and "Finish website docs" I will need some assistance from a Carbon designer to tackle this.

**Comment by sstrubberg** [comment]
@janhassel I stub out the work. We'll have a designer on our team handle the website docs and figma kit. You'll just take care of the implementation :)

**Comment by sstrubberg** [comment]
Need to talk to design and dev about the naming of this.

**Comment by sstrubberg** [comment]
Documentation is being tracked in [Menu and Friends](https://github.com/carbon-design-system/carbon-website/issues/3563).
