### ISSUE TITLE
Update elements previews to v11

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12089]
The elements previews need to be updated to v11. Sass modules are not working in parcel v2

https://github.com/carbon-design-system/carbon/issues/12089#tasklist-block-5d46fea5-8c12-4c25-9445-af9ceab77bb0

Checklist for each item above:

- [ ] Update to use vite or nextjs
- [ ] Update package deps to v11/current
- [ ] Update `@import` to `@use`
- [ ] Fix any issues
- [ ] Ensure example is up to date
  - [ ] `bx` classnames updated to `cds`
  - [ ] migrate design tokens
  - [ ] update mixins to no longer have `carbon--` prefix
  - [ ] etc.
- [ ] Double check package docs (readme.md, etc) to ensure they're up to date with v11 content
