### ISSUE TITLE
[Read-only Inputs]: Epic

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#12241]
### User story

> As an `IBM Maker`:

> I need to: build forms that allow Read-only component content to be parsed

> so that: my users can more semantically and accessibly mark-up their forms.

### Additional information

- _#2177_
- Read-only textinput has the work done. Use it as a reference. Make sure the visuals line up.

#### Acceptance Criteria

```[tasklist]
### Update website docs
- [x] https://github.com/carbon-design-system/carbon-website/issues/3248
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3263
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3264
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3265
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3266
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3267
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3268
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3269
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3262
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3270
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3271
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3272
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3273
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3274
```

```[tasklist]
### Update design kits
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/601
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/632
```

```[tasklist]
### Primary implementation
- [x] https://github.com/carbon-design-system/carbon/issues/12243
- [x] https://github.com/carbon-design-system/carbon/issues/12401
- [x] https://github.com/carbon-design-system/carbon/issues/12409
- [x] https://github.com/carbon-design-system/carbon/issues/12432
- [x] https://github.com/carbon-design-system/carbon/issues/12613
- [x] https://github.com/carbon-design-system/carbon/issues/12419
- [x] https://github.com/carbon-design-system/carbon/issues/12415
- [x] https://github.com/carbon-design-system/carbon/pull/12382
- [x] https://github.com/carbon-design-system/carbon/issues/12407
- [x] https://github.com/carbon-design-system/carbon/issues/12423
- [x] https://github.com/carbon-design-system/carbon/issues/12451
- [x] https://github.com/carbon-design-system/carbon/issues/12438
- [x] https://github.com/carbon-design-system/carbon/pull/12388
- [ ] https://github.com/carbon-design-system/carbon/issues/13032
```

**Comment by lee-chase** [comment]
OK. So straw men are all created @sstrubberg 

@tay1orjones the only outstanding issue you raised (unless I've missed some) is the property name `readOnly`. Before I started this work the `TextInput` and `NumberInput` components already had a property `readOnly`. I replicated this for consistency, however, like you I would prefer `readonly` as we are adhering to the pattern of this standard attribute. I could update all to have a `readonly` property, mark `readOnly` as deprecated in TextInput and NumberInput while treating it as `readonly` if a `readonly` property is not supplied.

@aagonzales has raised a question regarding cursors. Ordinarily, an 'input' does not change the text cursor when read-only. We have extended the concept beyond textual input boxes to checkboxes, radio buttons and a number of other scenarios which have buttons displayed but disabled. I think this requires a sync up with the read-only pattern designers to discuss. I'll suggest they organise something.
