### ISSUE TITLE
Tile: add experimental variant

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#12278]
Original discussion issue reference: https://github.com/carbon-design-system/carbon/issues/11351

This issue is to close out the exploratory work Thy has been doing regarding accessibility concerns with interactive tiles. The outcome will be a new experimental variant of tile visuals that will pass contrast minimums. Product teams will be allowed to test it out in product through an opt-in approach with the new variant. Below is the final task-list needed to bring the variant to stable. 

### Phase 1: Finalize design spec

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/issues/12343
- [x] https://github.com/carbon-design-system/carbon/issues/12279
```

### Phase 2: Ready for development + production

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/issues/12464
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3261
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/591
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/590
- [ ] https://github.com/carbon-design-system/carbon/issues/13217
- [ ] https://github.com/carbon-design-system/carbon/issues/13221
- [ ] https://github.com/carbon-design-system/carbon/issues/13222
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/650
```

### Phase 3: Comms

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/12925
- [ ] https://github.com/carbon-design-system/carbon/issues/12926
- [x] Experimental tile: Post annoucement
```
