### ISSUE TITLE
[Read-only Inputs]: Toggle

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12318]
This issue is to contain future information about the implementation and tasks related to implementing a read-only version of the Toggle component. This is part of a larger workstream to provide a read-only variant for all inputs, #12241 

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/12407
- [ ] [Read only inputs]: Toggle website docs
- [ ] [Read only inputs]: Toggle - Figma kit
- [ ] [Read only inputs]: Toggle - Sketch kit
```
