### ISSUE TITLE
Icon content switcher: add implementation

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12461]
This issue is to contain the primary development implementation items for the Icon content switcher

The spec and more info is in the parent issue, https://github.com/carbon-design-system/carbon/issues/6982

Open Questions
- [ ] Is this possible/correct with the current a11y makeup of ContentSwitcher?
- [ ] If a11y modifications are needed (changing roles, etc), does this need to be a separate export?
- [ ] Can we make these changes without a breaking change? (experimental if so)

### Tasks
- [ ] Review the above open questions against the POC with CAG
- [ ] Based on the outcome of POC and CAG review, implement Icon content switcher

**Comment by laurenmrice** [comment]
@tw15egan Here is the final design spec #12855

**Comment by francinelucca** [comment]
@tw15egan we see https://github.com/carbon-design-system/carbon/pull/13378 is merged in, are we good to close this issue or is there any outstanding tasks here? do we need to do an a11y review to close this out?

**Comment by tw15egan** [comment]
No a11y violations when testing, and the screenreader was working as expected. Closing as complete 👍
