### ISSUE TITLE
Deprecate end-of-support v10 assets

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12494]
This issue and all child issues within are part of the plan to deprecate `carbon-components` and `carbon-components-react` as originally proposed in the GitHub discussion:

- https://github.com/carbon-design-system/carbon/discussions/12179

This also includes v10.x versions of all packages in the monorepo, @carbon/colors, etc.

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/issues/12495
- [ ] https://github.com/carbon-design-system/carbon/issues/12496
- [x] Deprecate v10.x versions of elements packages on npm
- [ ] https://github.com/carbon-design-system/carbon/issues/12497
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4112
- [ ] https://github.com/carbon-design-system/carbon/issues/17374
- [ ] https://github.com/carbon-design-system/carbon/issues/17633
- [x] Deprecate any straggler versions published after the initial deprecation for all impacted packages
```

**Comment by GraceeFlower** [comment]
Hi team, could you please provide the rough DDL of the v12 release which will totally deprecate `carbon-components-react`? Thank you!
