### ISSUE TITLE
Grid docs: ☂️ 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#12854]
The grid is documented in several places throughout our docs. We need a combined design/dev effort to reorganize / consolidate these docs so they are easy to follow and understand. 

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/12954
- [ ] https://github.com/carbon-design-system/carbon/issues/13387
- [ ] https://github.com/carbon-design-system/carbon/issues/13388
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3515
- [ ] https://github.com/carbon-design-system/carbon/issues/13813
- [ ] https://github.com/carbon-design-system/carbon/issues/13909
- [ ] https://github.com/carbon-design-system/carbon/issues/13908
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3529
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3508
- [ ] https://github.com/carbon-design-system/carbon/issues/13723
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3528
- [x] Grid docs update style model guidance
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3619
```

<details><summary>Notes/links</summary>
<p>

**Website** 
Flex Grid
https://carbondesignsystem.com/guidelines/2x-grid/implementation

**Storybook**
CSS Grid
https://react.carbondesignsystem.com/?path=/docs/elements-grid--default

Flex Grid
https://react.carbondesignsystem.com/?path=/docs/elements-flexgrid--auto-columns

**Readme**
Flex Grid
https://github.com/carbon-design-system/carbon/tree/main/packages/grid

Open questions:
- How could we simplify the docs while also making them _more_ useful?
- How many products are using our grid packages?
- Primarily what modes are being used by those products?
- How critical is it that products use our grid package? If projects roll their own grid implementation and are compliant, how acceptable is that?
- Should an update to documentation be primarily subtractive or additive?
  - Are there usage examples that are not often used and not well supported that we could remove?
  - Are there new things driven by implementation that we should highlight (subgrid, nesting)?

</p>
</details>

**Comment by abdonrd** [comment]
Is there somewhere right now that documents how to use CSS Grid without React?

We just import `@use '@carbon/styles/scss/grid';` and use the CSS classes.

**Comment by tay1orjones** [comment]
@abdonrd The elements preview site shows how to use it with bare HTML and css classes" 

https://carbon-elements.netlify.app/grid/examples/css-grid/

**Comment by alisonjoseph** [comment]
Moved enhancements to new umbrella issue https://github.com/carbon-design-system/carbon/issues/14090 FYI @sstrubberg
