### ISSUE TITLE
[Feature Request]: word limit for textArea component

### ISSUE THREAD

**Issue by matejoslav** [carbon-design-system/carbon#12905]
### The problem

I would like for the textArea component in the react package to be able to limit the amount of words that user can enter. At the moment it can only limit the amount of characters.

### The solution

Allow textArea component in the react package to count words entered by the user and prevent user from typing more words once the word limit is reached.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/13788
- [ ] https://github.com/carbon-design-system/carbon/issues/13789
```
