### ISSUE TITLE
Platform indexing: sync approach between monorepo and platform

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#12933]
This issue is for updating the indexing strategy within the monorepo to match the platform - include all (new) components, variants, and have them properly categorized.

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/issues/12948
- [x] https://github.com/carbon-design-system/carbon/issues/12932
- [x] https://github.com/carbon-design-system/carbon-website/issues/3339
```
