### ISSUE TITLE
Enhance issue triage process via automation

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13138]
There's a lot of pieces of our issue triage process that we should automate to reduce the load on maintainers when triaging issues.

### Ideas to explore
- [x] Ensure "needs triage" label and project field are always applied to new issues, no matter who opens it
- [ ] Ensure "carbon champions" (org members) issues are always addressed and do not fall through any cracks in triage automation
- [ ] Triage automation: apply `status: needs reproduction` label when no sandbox, stackblitz, or storybook url is provided in issue body, remove label if issue body or any comments have a sandbox, stackblitz, or storybook link
- [ ] Triage automation: Auto close issues that have `needs reproduction` label for x days (7 days ?)
- [ ] Triage automation: apply `package: *` labels based on the response of the `Package` field in the issue template
- [ ] ~Triage automation: apply `version: 10`/`version: 11` label based on the response of the `Version` field in the issue template~
- [ ] Triage automation: apply `browser: *` labels based on the response of the `Browser` field in the issue template
- [ ] Triage automation: apply `component: *` labels based on any references to components in the issue or comment body
- [ ] Triage automation: apply `screen reader: *` labels based on the response of the field in the issue template
- [x] A11y issue template should also apply a `bug` label
- [ ] Triage automation: when `severity: 1` label is applied, notify in team slack channel

### Open questions
- Is there a way we can keep this automation in sync with if/when our issue templates change?

**Comment by ghost** [comment]
Hey! I maintain an open-source tool that might help with this.

**GitScope** uses AI agents to automatically triage GitHub issues:
- Auto-classify issues (bug/feature/question/docs)
- Detect semantic duplicates (catches 3x more than keyword matching)
- Flag sentiment issues before they escalate

Free for public repos: https://gitscope.dev

Here's your current health badge:
[![Repository Health](https://api.gitscope.dev/api/badges/carbon-design-system/carbon.svg)](https://gitscope.dev)

Check out how simonmichael/hledger organized 8 different GitScope badges in their README: https://github.com/simonmichael/hledger

Happy to give you a walkthrough if useful! 🙌
