### ISSUE TITLE
Interactive tag ☂️ 

### ISSUE THREAD

**Issue by MaxHam** [carbon-design-system/carbon#13145]
### The problem

I am from the IBM Cloud PAL team and reviewed differences between the Carbon `Tag` component and the Cloud `Tag` component. The only difference is that the Carbon Tag does not provide a "clickable" design. Meaning when you add an `onClick` handler to the component it is just rendered with default HTML button design. 
Before overwriting the Tag component in the Cloud PAL repository, I want to propose adding a click state for the Carbon `Tag` component. 
There are a few use cases for the click state for the tags in the Cloud context and I think a clickable state could be useful for other use cases as well. 

### The solution

A solution could be adding  styles for the "clickable" `Tag` state.

As reference I can add the design of Cloud PALs Tag. This is just an example how it could look like.
I am open for feedback to this proposal and also about the design.

### Examples

<img width="114" alt="Screenshot 2023-02-14 at 13 43 48" src="https://user-images.githubusercontent.com/45538872/218741948-43a9561d-d657-4079-bfc9-764701c68ff5.png">

### Application/PAL

Cloud PAL

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/13305
- [ ] https://github.com/carbon-design-system/carbon/issues/15227
- [ ] https://github.com/carbon-design-system/carbon/issues/15546
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/668
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3449
- [ ] https://github.com/carbon-design-system/carbon/issues/13337
- [ ] https://github.com/carbon-design-system/carbon/issues/15529
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3914
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3959
- [ ] https://github.com/carbon-design-system/carbon/issues/15893
```

**Comment by tay1orjones** [comment]
Thanks for this suggestion! The last time this was proposed it seemed like there was interest in an "interactive" or "selectable" tag variant, https://github.com/carbon-design-system/carbon/issues/7592

On the technical side, this would have a few implications as it would essentially be a new type of button.

- The element would need to change from `div` to `button`
- All interactive states would need designed - hover, focus, active, etc.
- Figure out how to handle the existing `filter` prop. Interactive elements can't be nested because screen readers ignore them. So at first glance these two may be incompatible unless we change the `x` button to be a sibling element and use styling to place it properly overlaid the tag.
- As you mentioned, an `onClick` prop would need to be added to proptypes
- It may need an `href` prop added as well?
- Based on the above changes significantly deviating from the existing component, we would need to consider making this it's own component. Perhaps `TagButton` or something.

**Comment by MaxHam** [comment]
Hi,

- looking at the code the component already switches from a `div` to a `button` element when adding an `onChange` prop.
- I think it should not be possible to have a filter and selectable state at the same time. Since it would nest two buttons when you add `onChange` and `filter` I think it should not be allowed to add both.
- Here you can find a quick summary how the `clickable` tag is used in the Cloud environment at the moment. It also shows the interactive states. [Invision Board](https://ibm.invisionapp.com/freehand/Clickable-Tag-Q1gvnAvWm?landingTemplate=true) 

I hope that helps understanding the use cases we had in mind.

**Comment by sstrubberg** [comment]
We need to define the "click" behavior. The tags in the Freehand are different than the tags in the issue. Recommend ya'll head to [Design Office Hours](https://ec.yourlearning.ibm.com/w3/join/event/10323408) and chat with our designer about this.

**Comment by aagonzales** [comment]
@sstrubberg we talked to them in office hours and this is something we want to take on in the core library. There is additional design exploration and spec-ing that will need to happen. We want to collaborate with the cloud pal team to get this done and they have said they are also willing to contribute. 

From @laurenmrice 
> My understanding is we have three different kinds of tags:
1 Our normal tag (read-only and filterable)
2 Clickable tag (navigational)
3 Selectable tag (on or off, like we have on platform)
And all of them need to have their distinct visual differences for their states.

The full work stream would include: 
- Design spec for variations
- Website docs
- Code (contributed?)
- Kit work

Do we want to take this issue to refinement? Or set up a workstream kick-off with Max and team

**Comment by aagonzales** [comment]
Related [discussion](https://github.com/carbon-design-system/carbon/discussions/11215) from Gower. 
We have also previously talked about clickable tags with Zak Crapo

**Comment by sstrubberg** [comment]
> @sstrubberg we talked to them in office hours and this is something we want to take on in the core library. There is additional design exploration and spec-ing that will need to happen. We want to collaborate with the cloud pal team to get this done and they have said they are also willing to contribute.
> 
> From @laurenmrice
> 
> > My understanding is we have three different kinds of tags:
> > 1 Our normal tag (read-only and filterable)
> > 2 Clickable tag (navigational)
> > 3 Selectable tag (on or off, like we have on platform)
> > And all of them need to have their distinct visual differences for their states.
> 
> The full work stream would include:
> 
> * Design spec for variations
> * Website docs
> * Code (contributed?)
> * Kit work
> 
> Do we want to take this issue to refinement? Or set up a workstream kick-off with Max and team
> 
> Related [discussion](https://github.com/carbon-design-system/carbon/discussions/11215) from Gower. We have also previously talked about clickable tags with Zak Crapo

Let's do a little of both. Maybe a kick-off call where we refine and scope out the work. It'll be good for everyone to get on the same page.

**Comment by aagonzales** [comment]
[Figma file](https://www.figma.com/file/ORkjLMu6gxZLTHmsBJkYDM/Interactive-Tag-Specs?type=design&node-id=17%3A1905&mode=design&t=AusDzq0HvEdBTI6H-1)
