### ISSUE TITLE
Remove the `light` prop from all components

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13260]
With the `light` prop deprecated in all components, the prop needs to be removed as part of the next major release.

### Tasks
- [ ] Gather a list of components with this prop and add it to this issue as a task list
- [ ] Remove the `light` prop, it's usages, and the associated styles/scss used for the prop
- [ ] Document this change in the v12 changelog
- [ ] Document this migration in the v12 migration guide, include how to run the codemod
- [ ] Evaluate if there are any lingering light-related usages in Carbon Web Components

**Comment by pmweeks98** [comment]
### Components 
- [ ] CodeSnippet
- [ ] ComboBox
- [ ] ContentSwitcher
- [ ] DatePicker
- [ ] Dropdown
- [ ] FluidTextArea
- [ ] ListBox
- [ ] FilterableMultiSelect
- [ ] MultiSelect
- [ ] NumberInput
- [ ] OverflowMenu
- [ ] RadioTile
- [ ] Search
- [ ] Select
- [ ] Slider
- [ ] Tabs
- [ ] TextArea
- [ ] ControlledPasswordInput
- [ ] PasswordInput
- [ ] TextInput
- [ ] Tile
- [ ] TimePicker

**Comment by tay1orjones** [comment]
Sorry for the lack of clarity here - this is currently blocked because it's a breaking change. We'll be reserving this issue for the future in v12.

**Comment by tay1orjones** [comment]
I've updated this issue to be fully decoupled from #13257 to instead be solely tracked by https://github.com/carbon-design-system/carbon/issues/15803 

We've done everything we can to deprecate and prepare for the removal, but the actual removal is blocked by being a breaking change that must wait to be shipped in the next major version.
