### ISSUE TITLE
Update `carbon-website`, `design-language-website` to Node 18

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13322]
### IDL
```[tasklist]
- [ ] https://github.com/carbon-design-system/design-language-website/pull/1199
```

### Carbon website attempt 1
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/pull/3440
```

### Carbon website attempt 2
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/pull/3456
```

### Carbon website attempt 3
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3510
```

**Comment by tay1orjones** [comment]
The regression was fixed in https://github.com/carbon-design-system/carbon-website/pull/3547, this is complete 🎉
