### ISSUE TITLE
Status Indicators ☂️

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13429]
Devs have been asking how to achieve the designs for the icon indicator guidance we provide in the pattern (most of the time asking about the indicators that have fills and strokes or inner paths), but we have been telling them they need to hardcode it for now.

IBM Products has a subset of the icon indicators we mention in our pattern, probably for PAL specific usage, but some of the names and iconography they use are inconsistent with what we have in our guidance. It would make sense for us to offer the full set of the icon indicators so people can reuse and leverage them.

#### C4IBMP guidance
- [This link](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/StatusIcon/StatusIcon.js) does not work anymore, does anyone know where the link new is?
- [React storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-status-icons-statusicon--default)
- [Status icons Pattern](https://pages.github.ibm.com/cdai-design/pal/patterns/status-icons/usage/)

#### Carbon Core guidance
- [Status indicators pattern](https://carbondesignsystem.com/patterns/status-indicator-pattern/)

#### Stakeholders
- Eric Brown (email: embrown@us.ibm.com) (slack: @embrown)
- Jan Christensen (email: jan.christensen@ibm.com ) (slack: @jan-christensen1)

#### Carbon PAL contacts
Note: We are deprecating the statuses page on PAL sites. Having documentation provided to users on what our unified status perspective is. Could be developed for v12
- Olivia Flory 
- Aubrey O'Neal

### Renaming icon assets
- [x] https://github.com/carbon-design-system/carbon-website/issues/2539
- [x] [Status indicators] Playback and review with Conrad, design, and dev? (design)
- [ ] [Status indicators] Devs to remove the current support tokens: undefined, caution-major, caution-minor (due to the new status tokens update) Check https://carbon-elements.netlify.app/themes/examples/preview/
- [ ] [Badge indicator] Consider New (blue) shape indicator as a specific use case

**Comment by kingtraceyj** [comment]
Example from NS1 (using MUI currently and moving to Carbon)

![image](https://github.com/carbon-design-system/carbon/assets/20582179/874fa2fe-3914-4ae4-9899-21c08401a2a8)
Tag with status indicator

**Comment by laurenmrice** [comment]
Related: [Status indicators] Updating the naming convention and the visual](https://github.com/carbon-design-system/carbon-website/issues/2539)

**Comment by laurenmrice** [comment]
Listing here, but we will be de-prioritizing the Cloud PAL work for Carbon for IBM Products

### C4IBMC Guidance (de-prioritize)
Which one is the most updated?
- https://pages.github.ibm.com/cdai-design/cloud-pal/components/resource-status-indicator/usage/
- https://pages.github.ibm.com/cdai-design/cloud-pal/components/status/usage/

**Comment by sstrubberg** [comment]
REF https://github.com/carbon-design-system/carbon/issues/17335

**Comment by thyhmdo** [comment]
## Note
This [issue](https://github.com/carbon-design-system/carbon/pull/18342) has the implementation of bade indicator on the Icon button.

The Icon button in the UI Shell header is pulled directly from the Icon button. By default, it has a 16px icon inside it. The use case doesn't include the badge indicator with 16px icon in the button yet. But we'll observe to see if people would use it anywhere or be confused about it.
