### ISSUE TITLE
React 18 Enhancements: Refactor defaultProps to default function parameters

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13424]
React 18.3 will introduce a deprecation of defaultProps. Components will need to move off defaultProps and instead use default function parameters. 

Additionally, we'll need to ensure that default values are static https://github.com/carbon-design-system/carbon/issues/10777 - this mostly includes function props

We probably should wait to tackle this until React 18.3 lands to see if the react team has additional recommendations for this work and/or a codemod available to automate this refactor.

```js
// TODO: provide code example
```

```[tasklist]
### Components to refactor
- [x] Use default function parameters in `.../icon-build-helpers/src/builders/react/components/Icon.js`
- [x] Use default function parameters in `.../react/examples/custom-data-table-state-manager/src/components/CustomDataTablejs:`
- [x] Use default function parameters in `Accordion/Accordion.Skeleton.js`
- [x] Use default function parameters in `Checkbox/Checkbox.tsx`
- [x] Use default function parameters in `CodeSnippet/CodeSnippet.js`
- [x] Use default function parameters in `ComboBox/ComboBox.tsx`
- [x] Use default function parameters in `ComposedModal/ComposedModal.js`
- [x] Use default function parameters in `ComposedModal/ModalFooter.js`
- [x] Use default function parameters in `ComposedModal/ModalHeader.js`
- [x] Use default function parameters in `ContentSwitcher/ContentSwitcher.js`
- [x] Use default function parameters in `Copy/Copy.js`
- [x] Use default function parameters in `CopyButton/CopyButton.js`
- [x] Use default function parameters in `DataTable/DataTable.js`
- [x] Use default function parameters in `DataTable/Table.js`
- [x] Use default function parameters in `DataTable/TableBatchAction.js`
- [x] Use default function parameters in `DataTable/TableBatchActions.js`
- [x] Use default function parameters in `DataTable/TableBody.js`
- [x] Use default function parameters in `DataTable/TableHeader.js`
- [x] Use default function parameters in `DataTable/TableSelectAll.tsx`
- [x] Use default function parameters in `DataTable/TableToolbar.tsx`
- [x] Use default function parameters in `DataTable/TableToolbarMenu.tsx`
- [x] Use default function parameters in `DataTable/TableToolbarSearch.js`
- [x] Use default function parameters in `DataTableSkeleton/DataTableSkeleton.tsx`
- [x] Use default function parameters in `Dropdown/Dropdown.tsx`
- [x] Use default function parameters in `FileUploader/Filename.js`
- [x] Use default function parameters in `FileUploader/FileUploader.js`
- [x] Use default function parameters in `FileUploader/FileUploaderDropContainer.js`
- [x] Use default function parameters in `FileUploader/FileUploaderItem.js`
- [x] Use default function parameters in `FluidSearch/FluidSearch.js`
- [x] Use default function parameters in `FormGroup/FormGroup.js`
- [x] Use default function parameters in `ListBox/ListBox.tsx`
- [x] Use default function parameters in `ListBox/ListBoxMenuIcon.tsx`
- [x] Use default function parameters in `ListBox/ListBoxMenuItem.tsx`
- [x] Use default function parameters in `ListBox/ListBoxSelection.tsx`
- [x] Use default function parameters in `ListBox/next/ListBoxSelection.js`
- [x] Use default function parameters in `ListBox/next/ListBoxTrigger.js`
- [x] Use default function parameters in `Modal/Modal.js`
- [x] Use default function parameters in `ModalWrapper/ModalWrapper.js`
- [x] Use default function parameters in `MultiSelect/FilterableMultiSelect.js`
- [x] Use default function parameters in `MultiSelect/MultiSelect.tsx`
- [x] Use default function parameters in `Notification/Notification.js`
- [x] Use default function parameters in `OrderedList/OrderedList.js`
- [x] Use default function parameters in `OverflowMenu/OverflowMenu.js`
- [x] Use default function parameters in `Pagination/experimental/PageSelector.js`
- [x] Use default function parameters in `Pagination/experimental/Pagination.js`
- [x] Use default function parameters in `ProgressIndicator/ProgressIndicator.js`
- [x] Use default function parameters in `RadioTile/RadioTile.js`
- [x] Use default function parameters in `Search/Search.Skeleton.js`
- [x] Use default function parameters in `Select/Select.tsx`
- [x] Use default function parameters in `SelectItem/SelectItem.tsx`
- [x] Use default function parameters in `SelectItemGroup/SelectItemGroup.tsx`
- [x] Use default function parameters in `SkeletonText/SkeletonText.js`
- [x] Use default function parameters in `Slider/Slider.tsx`
- [x] Use default function parameters in `StructuredList/StructuredList.js`
- [x] Use default function parameters in `StructuredList/StructuredList.Skeleton.js`
- [x] Use default function parameters in `Switch/Switch.js`
- [x] Use default function parameters in `Tab/Tab.js`
- [x] Use default function parameters in `TabContent/TabContent.js`
- [x] Use default function parameters in `TextArea/TextArea.tsx`
- [x] Use default function parameters in `TextInput/ControlledPasswordInput.js`
- [x] Use default function parameters in `Tile/Tile.js`
- [x] Use default function parameters in `TileGroup/TileGroup.js`
- [x] Use default function parameters in `Toggle/Toggle.Skeleton.js`
- [x] Use default function parameters in `ToggleSmall/ToggleSmall.Skeleton.js`
- [x] Use default function parameters in `UIShell/Content.js`
- [x] Use default function parameters in `UIShell/HeaderContainer.js`
- [x] Use default function parameters in `UIShell/HeaderName.js`
- [x] Use default function parameters in `UIShell/HeaderSideNavItems.js`
- [x] Use default function parameters in `UIShell/Link.js`
- [x] Use default function parameters in `UIShell/SideNav.js`
- [x] Use default function parameters in `UIShell/SideNavFooter.js`
- [x] Use default function parameters in `UIShell/SideNavIcon.js`
- [x] Use default function parameters in `UIShell/SkipToContent.js`
- [x] Use default function parameters in `UnorderedList/UnorderedList.js`
- [x] Refactor defaultProps to default function parameters in `.../react/src/internal/FloatingMenu.js`
- [x] Refactor defaultProps to default function parameters in `.../react/src/internal/Selection.js`
```

**Comment by tuccitj** [comment]
Current getting this error on UIShell.Content.js. If someone can share a sample of a fix, I can start banging the rest out.

**Comment by tw15egan** [comment]
@tuccitj that would be great if you want to start working on this. One example of a component that has been converted is `IconSwitch`. [These lines specifically](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Switch/IconSwitch.js#L14-L32). For example, in `UIShell/Content` you'd remove 

```jsx
Content.defaultProps = {
  tagName: 'main',
};
```
and instead, make it a default function parameter 

```jsx
const Content = ({
  className: customClassName,
  children,
  tagName = 'main',
  ...rest
}) => {
```

For functions, you';d do something like this:

```jsx
const noopFn = () => {};

const Content = ({
    onClick = noopFn,
     ...
}) => {
```

**Comment by kubijo** [comment]
Is there any plan to backport this to pre-11 release? We have to stay back because still lacking typescript support...
