### ISSUE TITLE
[ Feature Request ] : Add rich text option and toolbar to TextArea React component

### ISSUE THREAD

**Issue by JoshuaHorowitz** [carbon-design-system/carbon#13462]
### The story
Many developers use 3rd party components for their rich text needs, whether it be for text that is bolded, underlined, bulleted lists,  sized differently, etc.

 ### The problem
The ability to add a "Rich text" option to the textarea component would be very helpful for those developers so as not to rely on 3rd party components that can either have: 
1. Vulnerabilities that IBM and the developers creating IBM applications has no control over
2. Lack of extensibility and uniformity. And as such, the products may lack a certain style or uniformity that our high quality frontend designs sometimes demand.

### The solution
These two problems can be solved with a native carbon react component that allows for rich text.

### Tasks
1. [ ] Create a boolean prop for TextArea that can toggle between rich text and non rich text (when true, allow a toolbar to pop up for rich text options)
2. [ ] Allow the user to choose 1 or more tiles from the toolbar and then the text typed while the tile(s) are selected will be styled in accordance with the character of the tile
3. [ ] Allow a user to highlight text with their mouse and select 1 or more tiles to then style said highlighted text
4. [ ] Allow a user to remove styling from text if they highlight said text and the uncheck 1 or more tiles from the toolbar
5. [ ] May require: removal of script tags that a user type in order to protect against XSS attacks

An example of one such third party editor would be a ckeditor (pictured below) as found [here](https://github.com/ckeditor/ckeditor5) which may get the job done, but as mentioned above, lack uniformity, extensibility, and confidence in being able to resolve vulnerabilities that are critical to IBMers.

**Comment by tw15egan** [comment]
There have been design explorations, but there is no coded component available. There is currently no plan to implement the feature at this moment in time

Refs https://github.com/carbon-design-system/carbon/issues/10320
Refs https://github.com/carbon-design-system/carbon/issues/11272
Refs https://github.com/carbon-design-system/carbon/issues/2447

**Comment by tay1orjones** [comment]
Providing something to assist in the "uniformity" category makes sense to me.

Writing our own rich text editor from the ground up seems like a poor choice though considering how robust the popular third party solutions are. Leaning into these third party libraries might be a more sustainable path. Maybe we could provide a set of presentational components that could help teams implement the [design pattern for rich text editor (toolbar)](https://carbondesignsystem.com/patterns/text-toolbar-pattern/) with popular third party libraries.

Also I'm not sure if it makes sense for this to be part of TextArea. Instead it's own component or set of components composed together maybe.
