### ISSUE TITLE
Q2 Support Tracker [Experiment]

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13510]
### 🔩 Engineering
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/13465
- [ ] https://github.com/carbon-design-system/carbon/issues/5232
- [ ] https://github.com/carbon-design-system/carbon/issues/12610
- [ ] https://github.com/carbon-design-system/carbon/issues/12980
- [ ] https://github.com/carbon-design-system/carbon/issues/10181
- [ ] https://github.com/carbon-design-system/carbon/issues/13122
- [ ] https://github.com/carbon-design-system/carbon/issues/13408
- [ ] https://github.com/carbon-design-system/carbon/issues/13490
- [ ] https://github.com/carbon-design-system/carbon/issues/13499
- [ ] https://github.com/carbon-design-system/carbon/issues/13459
- [ ] https://github.com/carbon-design-system/carbon/issues/13505
```

### ♿ A11y
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/12722
- [ ] https://github.com/carbon-design-system/carbon/issues/12995
- [ ] https://github.com/carbon-design-system/carbon/issues/13163
- [ ] https://github.com/carbon-design-system/carbon/issues/10634
- [ ] https://github.com/carbon-design-system/carbon/issues/11083
- [ ] https://github.com/carbon-design-system/carbon/issues/11202
- [ ] https://github.com/carbon-design-system/carbon/issues/12814
- [ ] https://github.com/carbon-design-system/carbon/issues/12720
- [ ] https://github.com/carbon-design-system/carbon/issues/13616
```

### 🖌️ Design
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/609
- [ ] https://github.com/carbon-design-system/carbon/issues/6382
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/669
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/653
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3399
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/666
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3450
- [ ] https://github.com/carbon-design-system/carbon/issues/13397
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/658
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/658
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/658
- [ ] https://github.com/carbon-design-system/carbon/issues/13485
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3370
```
