### ISSUE TITLE
React 18 Enhancements

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13623]
Now that React 18 is formally supported https://github.com/carbon-design-system/carbon/issues/11308, there are a few extra items we can now tackle.

```[tasklist]
- [ ] https://github.com/carbon-design-system/carbon/issues/11513
- [ ] https://github.com/carbon-design-system/carbon/issues/13630
- [x] Update types package version (https://github.com/carbon-design-system/carbon/pull/12607)
- [ ] https://github.com/carbon-design-system/carbon/issues/10777
- [ ] https://github.com/carbon-design-system/carbon/issues/13424
- [x] ~Ensure anywhere we use create-react-app that we properly install 17 or 18 where necessary, https://github.com/facebook/create-react-app/issues/12269~
- [ ] https://github.com/carbon-design-system/carbon/issues/14283
```

**Comment by tay1orjones** [comment]
I crossed out the line item for updating CRA-based examples and apps due to #13637
