### ISSUE TITLE
Migrate examples off of Create React App

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13637]
Create React App project is [moving in a new direction](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741), and there are quite a few examples within the repo using it or `react-scripts`. I think it makes sense to move off of it to avoid future hassle with outdated dependencies and errant dependabot vulnerability errors.

#### What should we move to?

We should consider the recommended options outlined by [the new react docs](https://react.dev/learn/start-a-new-react-project). This is where the majority of new react-based projects will begin their journey with Carbon and we should have examples that follow suit. Two in particular stand out

1. Vite - great for isolated and small/lightweight examples showcasing component prop configuration or usage 
2. NextJS - suitable for more complicated examples that involve needs provided by a framework - routing, SSR, etc.

Quite a few of the examples in the repo are old and outdated. In some cases they're using react-scripts v3 and causing errant dependabot vulnerability alerts. This includes the following directories:

- https://github.com/carbon-design-system/carbon/tree/main/examples
- https://github.com/carbon-design-system/carbon/tree/main/packages/react/examples

### Goals

- Remove examples that no longer provide value
  - Could we gather install stats for these to determine ones that aren't used much? Install may not be the perfect metric, sometimes examples are just used as a reference
- Update remaining examples to either vite or nextjs
- Examples should be able to be run: 
  - locally
  - on stackblitz
  - preferably on codesandbox as well though this may not be feasible due to their lack of scss support

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/14599
- [ ] https://github.com/carbon-design-system/carbon/issues/14771
- [x] https://github.com/carbon-design-system/carbon/issues/14462
- [ ] https://github.com/carbon-design-system/carbon/issues/14768
- [ ] https://github.com/carbon-design-system/carbon/issues/14769
- [ ] https://github.com/carbon-design-system/carbon/issues/15201
- [ ] https://github.com/carbon-design-system/carbon/issues/15202
- [ ] https://github.com/carbon-design-system/carbon/issues/15203
```

**Comment by falsepopsky** [comment]
It would be good if we actually made use of the [examples directory](https://github.com/carbon-design-system/carbon/tree/main/examples) in the root of the project. This was my first problem when I wanted to learn Carbon in the past: the documentation was outdated or in transition with the new v11, and I found many examples scattered everywhere, but didn't know where to start. Additionally, as a suggestion because of the new direction of CRA, I think it would be good to deprecate this template [@carbon/cra-template](https://github.com/carbon-design-system/carbon/tree/main/packages/cra-template)

**Comment by tay1orjones** [comment]
The other thing to consider with this is now that we have the separate `sandboxes` repo, we could move ancillary examples there to avoid having them in the monorepo.

From my perspective we only need examples in the monorepo if we want them tied to the release process (lerna incrementing the versions of carbon deps used in the example)

**Comment by guidari** [comment]
All tasks were validated and completed in this issue.
