### ISSUE TITLE
Compat tokens: Add more v10 sass token compatibility modes ☂️ 

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13661]
### Background

The compat theme is a theme consumers can configure that allows them to use the old v10 tokens as a fallback. The following are examples of where is shows up in our migration guidance.

- https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#compatibility
- https://carbondesignsystem.com/migrating/guide/develop/#step-8:-update-color-tokens

### Problem

The compat theme does not include tokens for type, layout, or motion. Currently when migrating from v10 to v11 these tokens must be updated to their new v11 name. This issue is for extending the idea of a compat theme to the other elements packages/modules available through the system by ensuring all v10 tokens are available in the existing elements stylesheets/modules.

We also need to document that the v10 tokens are available in these modules and revisit existing documentation for the compat theme to ensure that consumers know it exists and feel comfortable using it.

### Examples

Usage for a consumer would look something like this:

```scss
@use '@carbon/react/scss/type' as *;
@use '@carbon/react/scss/layout' as *; // if using the layout/spacing tokens
@use '@carbon/react/scss/motion' as *; // if using the motion tokens

@use '@carbon/react';


:root {
  font-family: $caption-01;
}
```

### Scope of changes to include

- For tokens that did not change name between v10 and v11, are the values the same between v10 and v11 or have they changed? If they've changed, we need to provide the v10 value under the v10 name.
- For tokens that _*did*_ change names between v10 and v11, we need to ensure that the old name maps to the v10 value
- For tokens that were removed, these tokens need to be added back in under the compat module/stylesheet with their v10 values

```[tasklist]
### Tasks
- [x] Audit to determine what tokens are not included in the compat theme
- [ ] https://github.com/carbon-design-system/carbon/issues/13687
- [ ] https://github.com/carbon-design-system/carbon/issues/13686
- [ ] https://github.com/carbon-design-system/carbon/issues/13688
- [ ] https://github.com/carbon-design-system/carbon/issues/13689
- [ ] https://github.com/carbon-design-system/carbon/issues/13690
- [ ] https://github.com/carbon-design-system/carbon/issues/13691
- [ ] https://github.com/carbon-design-system/carbon/issues/13692
- [ ] https://github.com/carbon-design-system/carbon/issues/13693
- [ ] https://github.com/carbon-design-system/carbon/issues/13694
```

**Comment by tay1orjones** [comment]
### Beter document `carbon--` removal

We will not be mapping old token values using `carbon--` to new token values. This is a simple find and replace and shouldn't impact the time to migrate much at all. The docs on the website need to be updated to clearly state "Do a find all and replace to remove `carbon--`. 

### Type tokens

https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#type-tokens

Goals:
- v10 type tokens can continue to be used in a consumer's stylesheet by `@use`ing a new sass module/stylesheet

Usage for a consumer could look something like this:
```scss
// Option 1: ala cart
@use '@carbon/react/scss/type/tokens/compat' as *;
@use '@carbon/react/scss/layout/tokens/compat' as *;
@use '@carbon/react/scss/motion/tokens/compat' as *;

// Option 2: the kitchen sink
@use '@carbon/react/scss/tokens/compat' as *;



// Either way you'll also need this
@use '@carbon/react';


:root {
  font-family: $caption-01;
}

```

How:

- Audit v10 vs v11 tokens
  - For tokens that did not change name between v10 and v11, are the values the same between v10 and v11 or have they changed? If they've changed, we need to provide the v10 value under the v10 name.
  - For tokens that were removed, these tokens need to be added back in under the compat module/stylesheet with their v10 values
  - For tokens that did change names, we need to ensure that the old name maps to the v10 value
- Add a compat module to `@carbon/type` that includes tokens from the audit
- Re-export this compat module through `@carbon/react`
  - `@carbon/react/scss/type/compat` maybe?
  - optionally, we could roll up all compat token modules (not incuding theme) under one module
    - `@carbon/react/scss/tokens/compat` maybe?

### Layout/spacing tokens

Follow the same approach as above with the type tokens but for layout/spacing tokens

### Motion tokens

Follow the same approach as above with the type tokens but for [motion token changes](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#carbonmotion)

### Are there any other tokens that need a compat module?

### Open questions

- Can we provide deprecation warnings for compat token usage via sass `@warn`?
