### ISSUE TITLE
Medium: Deprecating legacy packages 🏖️ 

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13676]
Related to https://github.com/carbon-design-system/carbon/discussions/12179

```[tasklist]
### Tasks
- [x] Medium: Deprecating legacy packages: Draft 1
- [x] Medium: Deprecating legacy packages: Draft 2
- [x] Medium: Deprecating legacy packages: Draft 3
- [ ] https://github.com/carbon-design-system/carbon/issues/13677
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3507
```
