### ISSUE TITLE
Dividers in Components 🏖️

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#13682]
### Overview

There is currently an inconsistency of the presence or lack of dividers that we provide in our components, specifically in instances where there are multiple icons inside of a component that live next to each other. 

We need to decide when and how we use dividers like this across our components to create better consistency. We also need to consider how the AI slug is being used in these situations when AI is present. (Ref: [Carbon for AI Figma file](https://www.figma.com/file/4aMIX5zjux2LhbW1aI3xgD/Carbon-for-AI---AI-Essentials-Kit?type=design&node-id=1971%3A23010&mode=design&t=XkV29oDHqya9OAzS-1))

Here are a couple of examples of where we do and don't use them:

-----

**Example: Number input**
 - Enabled state: The number input component dividers help separate the `- / +` controls visually. 
 - Hover state: Unlike most of our other form components, the number input  `- / +` controls additionally get a color background change on hover because they are treated as icon buttons instead of just icons.
 - Error state: There is an addition of the error icon in the field, and another divider appears next to the `-` control.

<img width="608" alt="number input" src="https://github.com/carbon-design-system/carbon/assets/43969356/afa63d9a-636b-4502-8c12-8a385bdd735b"> 

-----

**Example: Combobox**
- Selected state: The combobox component, when an option is selected, the close and chevron icons only get a mouse cursor change and have no dividers between them
- Hover state: The close and chevron icons only get a cursor hover change and no background color change because they are icons, not icon buttons. They also don't have a divider between them.
- Error state: There is an addition of the error icon in the field, and there is no divider. 

<img width="608" alt="combobox" src="https://github.com/carbon-design-system/carbon/assets/43969356/99487616-c469-4116-9c3c-6f9b9a211d12">

-----

```[tasklist]
### Default component tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/14101
- [ ] https://github.com/carbon-design-system/carbon/issues/15286
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/745
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3865
- [ ] https://github.com/carbon-design-system/carbon/issues/15753
- [ ] https://github.com/carbon-design-system/carbon/issues/15492
```
```[tasklist]
### AI component tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/16091
- [ ] https://github.com/carbon-design-system/carbon/issues/15552
- [x] Dividers in components: Website docs - Dropdown Family - Dos and don'ts update
```

**Comment by tay1orjones** [comment]
Things to answer in refinement:

- Do we want this?
  - How did the discrepancy between figma and storybook happen? s this part of the original spec, or an updated one?
- How many components would this impact?

**Comment by sstrubberg** [comment]
Audit the inputs. Where are the dividers? What is the original spec?
