### ISSUE TITLE
Reduce the time it takes to migrate to v11

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13696]
We've received feedback that the time it takes to migrate from v10 to v11 is too long for some teams/projects. Our team has ideated on this[^1] and believe the following ideas are worth exploring to reduce the time it takes to migrate:

```[tasklist]
- [ ] #13661
- [ ] https://github.com/carbon-design-system/carbon/issues/13664
- [ ] https://github.com/carbon-design-system/carbon/issues/14001
- [ ] ~Improve and document [`stylelint-plugin-carbon-tokens`](https://www.npmjs.com/package/stylelint-plugin-carbon-tokens) `--fix` modes to automate sass token migration~
- [ ] ~Reintroduce legacy v10 code paths behind opt-in feature flags~
- [ ] https://github.com/carbon-design-system/carbon/issues/13878
- [ ] https://github.com/carbon-design-system/carbon/issues/14324
```

[^1]: [link to mural](https://app.mural.co/invitation/mural/ibm14/1681920154740?sender=taylorjones2&key=b3fa0e65-39f5-47c8-a75b-065680734e76)
