### ISSUE TITLE
Component Accessibility Status: EAC Complex state coverage

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13747]
REF https://github.com/carbon-design-system/carbon/issues/13780

We'll need to add tests for each of these components on the list below to cover problematic states with EAC accessibility-checker

### List of components to tackle, in order
- [ ] https://github.com/carbon-design-system/carbon/pull/14045
- [ ] https://github.com/carbon-design-system/carbon/pull/14059
- [ ] https://github.com/carbon-design-system/carbon/issues/14118
- [ ] https://github.com/carbon-design-system/carbon/issues/14209
- [ ] https://github.com/carbon-design-system/carbon/issues/14199
- [ ] https://github.com/carbon-design-system/carbon/issues/14210
- [ ] https://github.com/carbon-design-system/carbon/issues/14119
- [ ] https://github.com/carbon-design-system/carbon/issues/14186
- [ ] https://github.com/carbon-design-system/carbon/issues/14120
- [ ] https://github.com/carbon-design-system/carbon/issues/14211
- [ ] https://github.com/carbon-design-system/carbon/issues/14212
- [ ] https://github.com/carbon-design-system/carbon/issues/14213
- [ ] https://github.com/carbon-design-system/carbon/issues/14214
- [ ] https://github.com/carbon-design-system/carbon/issues/14304
- [ ] https://github.com/carbon-design-system/carbon/issues/14325
- [ ] https://github.com/carbon-design-system/carbon/issues/14121
- [ ] https://github.com/carbon-design-system/carbon/issues/14293
- [ ] https://github.com/carbon-design-system/carbon/issues/14326
- [ ] https://github.com/carbon-design-system/carbon/issues/14122
- [ ] https://github.com/carbon-design-system/carbon/issues/14327
- [ ] https://github.com/carbon-design-system/carbon/issues/14328
- [ ] https://github.com/carbon-design-system/carbon/issues/14329
- [ ] https://github.com/carbon-design-system/carbon/issues/14330
- [ ] https://github.com/carbon-design-system/carbon/issues/14331
- [ ] https://github.com/carbon-design-system/carbon/issues/14332
- [ ] https://github.com/carbon-design-system/carbon/issues/14215
- [ ] https://github.com/carbon-design-system/carbon/issues/14333
- [ ] https://github.com/carbon-design-system/carbon/issues/14334
- [ ] https://github.com/carbon-design-system/carbon/issues/14335
- [ ] https://github.com/carbon-design-system/carbon/issues/14369
- [ ] https://github.com/carbon-design-system/carbon/issues/14367
- [ ] https://github.com/carbon-design-system/carbon/issues/14368
- [ ] https://github.com/carbon-design-system/carbon/issues/14416
- [ ] https://github.com/carbon-design-system/carbon/issues/14417

#### Potential High value states in addition to those listed in the tasklist above:

- Open/Close states
  - Dropdown
  - Accordion
  - Data table-batch action
  - Date picker
  - ???
- Warning/invalid states (a11y, vrt)
  - Form controls
- Determinate/indeterminate states
  - Progress bar
- Default/inline
  - Select
- Selected states
   - Multi-select

#### Low value states we probably will not focus on for now
- Hover states
- Active states
- Focus states
