### ISSUE TITLE
Ideas for future articles on Medium

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13826]
```[tasklist]
### Ideas for future articles on Medium
- [ ] Future flags - feature flags, a follow up to our [previous article on feature flags](https://medium.com/carbondesign/feature-flags-in-a-design-system-a-true-love-story-504a1d4c5889)
- [ ] Write medium article on test refactor/react 18 support, challenges of test refactor, benefits for community
- [ ] Our team process and practices
- [ ] The new improvements to the migration guide - "compat modes" and v11 migration
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3653
- [ ] AI article (jeannie
```
