### ISSUE TITLE
Grid docs: Implementation page rev2

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#13908]
- Review Grid Implementation page with Olivia and Mike, etc.

Jeannie to drop tasks from DSAG notes.
```[tasklist]
### Tasks
- [x] Mike review
- [x] incorporate odd column guidance in Denser layouts section
- [x] Add usage image for 12 column grid guidance (diagram)
- [x] Add usage image for 12 column grid guidance (actual image)
- [x] Add INTERNAL notification where (do quick audit of internal only links; gallery, cloud prototype, etc)
- [x] Add Mike's content in the Contrast section
- [x] DSAG Review
- [x] Refine Laura's grid influencer image
- [x] Incorporate basic Style Model section from Shixie's guidance
- [x] Replace Shixie's high-density UI image with the Cloud catalog behavior
- [x] Incorporate Alison's Mixing gutter mode content
- [x] Add corresponding usage images
- [x] Add simple Figma guidance/links at the end of the usage tab
```

**Comment by jeanservaas** [comment]
- [x] **Mike review**
- [ ] incorporate odd column guidance in Denser layouts section
- [ ] Add usage image for 3 column grid guidance (diagram)
- [ ] Add usage image for 3 column grid guidance (actual image)
- [ ] Add INTERNAL notification where (do quick audit of internal only links; gallery, cloud prototype, etc)
- [ ] Add Mike's content in the Contrast section

- [x] **DSAG Review**
- [ ] Refine Laura's grid influencer image

**Comment by jeanservaas** [comment]
Walked through grid docs on 6/8/23 DSAG.

This was ALL great feedback, but shouldn't block the first version of the updated grid docs. All of this documentation refinement can be included in follow-on issues to add even more clarity to the docs.

## Notes from DSAG:

**Button usage on grid**
- Update button guidance style tab content to communicate grid aware intent more clearly (this is a sep. issue for button docs)

**Gutter modes and mixing** (all of this is great, but maybe include in next round of grid docs work)
- Help designers understand gutter modes better, there's still a lot of confusion about when to use what and what components are compatible with each gutter mode
- Carrie suggested maybe an animation around gutter modes to show how they mix?
- Could also add gutter mode guidance to component page to help people understand which mode can be used with each component

**Breakpoints** (This content is actually on the Overview tab)
- Carrie also thought there could be more clarity around breakpoints; maybe an animation that shows responsive progression

**Grid influencers** (follow-on issue)
- need more guidance around when to use a grid influencer shell
- CIO is using grid influencer shell and grid template with a persistent left nav because of confusion

**Max plus grid size and high density style model** (follow-on issue)
- How do side panels transition in max + grid
- Kevin Camelo would love to be a part of future Max plus grid working group

**Comment by jeanservaas** [comment]
@alisonjoseph @sstrubberg  Here is the final of the grid usage tab.

## Figma specs

https://github.com/orgs/carbon-design-system/projects/39/views/28?pane=issue&itemId=23535662

Here are the images. There is ONE image that Mike would like me to make into an animated GIF...but I'm not going to let that hold this up. I can work on that on the side, if it's done in time cool. If not, we'll get to it later.

## PNGs

[Final_grid_images.zip](https://github.com/carbon-design-system/carbon/files/12458495/Final_grid_images.zip)

Also there is one video that we're pulling off the current Grid Implementation tab, so that's not included in this file:



![Image](https://github.com/carbon-design-system/carbon/assets/43144260/7d2674c9-622b-4d9c-bc2b-c280f9143f79)

**Comment by alisonjoseph** [comment]
🥳 closing this to work on the dev implementation! https://github.com/carbon-design-system/carbon-website/issues/3619
