### ISSUE TITLE
Component Screenreader Support: QA manual testing

### ISSUE THREAD

**Issue by andreancardona** [carbon-design-system/carbon#13962]
This issue contains items resulting from manual screenreader testing by Ram.

```[tasklist]
### Items identified during 2024 testing
- [ ] ... TBD
```

```[tasklist]
### Items identified during 2023 testing
- [ ] https://github.com/carbon-design-system/carbon/issues/13888
- [ ] https://github.com/carbon-design-system/carbon/issues/13938
- [ ] https://github.com/carbon-design-system/carbon/issues/13939
- [ ] https://github.com/carbon-design-system/carbon/issues/13940
- [ ] https://github.com/carbon-design-system/carbon/issues/13943
- [ ] https://github.com/carbon-design-system/carbon/issues/13944
- [ ] https://github.com/carbon-design-system/carbon/issues/13945
- [ ] https://github.com/carbon-design-system/carbon/issues/13946
- [ ] https://github.com/carbon-design-system/carbon/issues/13947
- [ ] https://github.com/carbon-design-system/carbon/issues/13948
- [ ] https://github.com/carbon-design-system/carbon/issues/13941
- [ ] https://github.com/carbon-design-system/carbon/issues/13978
- [ ] https://github.com/carbon-design-system/carbon/issues/13979
- [ ] https://github.com/carbon-design-system/carbon/issues/13980
- [ ] https://github.com/carbon-design-system/carbon/issues/14255
- [ ] https://github.com/carbon-design-system/carbon/issues/14257
- [ ] https://github.com/carbon-design-system/carbon/issues/14259
- [ ] https://github.com/carbon-design-system/carbon/issues/14260
- [ ] https://github.com/carbon-design-system/carbon/issues/14261
- [ ] https://github.com/carbon-design-system/carbon/issues/14262
- [ ] https://github.com/carbon-design-system/carbon/issues/14264
- [ ] https://github.com/carbon-design-system/carbon/issues/14268
- [ ] https://github.com/carbon-design-system/carbon/issues/14269
- [ ] https://github.com/carbon-design-system/carbon/issues/14271
- [ ] https://github.com/carbon-design-system/carbon/issues/14637
- [ ] https://github.com/carbon-design-system/carbon/issues/14681
- [ ] https://github.com/carbon-design-system/carbon/issues/14683
- [ ] https://github.com/carbon-design-system/carbon/issues/14691
- [ ] https://github.com/carbon-design-system/carbon/issues/14817
- [ ] https://github.com/carbon-design-system/carbon/issues/14818
- [ ] https://github.com/carbon-design-system/carbon/issues/14819
- [ ] https://github.com/carbon-design-system/carbon/issues/14824
- [ ] https://github.com/carbon-design-system/carbon/issues/15251
- [ ] https://github.com/carbon-design-system/carbon/issues/15252
- [ ] https://github.com/carbon-design-system/carbon/issues/15256
- [ ] https://github.com/carbon-design-system/carbon/issues/15257
- [ ] https://github.com/carbon-design-system/carbon/issues/15258
- [ ] https://github.com/carbon-design-system/carbon/issues/15265
- [ ] https://github.com/carbon-design-system/carbon/issues/15268
```
