### ISSUE TITLE
PAL Audit: Carbon for Sustainability

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#14057]
We have crafted some next steps for the Carbon Core team to keep the momentum up on the consolidation effort for PAL content. We are also waiting on some follow-up steps from Sustainability around usage. 

Audit Spreadsheet https://ibm.box.com/s/mc7s5mn2np026uuwmuzgbzs17px1vzw9

```[tasklist]
### Tasks
- [x] Component mapping for React components (duplicates only first)
- [x] Prioritize and give effort to the list of enhancements to core.
- [ ] https://github.com/carbon-design-system/carbon/issues/14447
- [ ] https://github.com/carbon-design-system/carbon/issues/14445
- [ ] https://github.com/carbon-design-system/carbon/issues/14446
```

**Comment by aagonzales** [comment]
Prioritization and effort list can be found on the `Component mapping code dupes` inside the original Audit excel spreadsheet. Priority has not yet been assigned as the Sustainability pal's input should influence the most needed components. 

<img width="1273" alt="image" src="https://github.com/carbon-design-system/carbon/assets/11670886/394abef5-7921-4c7c-82f3-78585df56db3">

**Comment by alisonjoseph** [comment]
Audit Spreadsheet https://ibm.box.com/s/mc7s5mn2np026uuwmuzgbzs17px1vzw9
