### ISSUE TITLE
Grid docs enhancements: ☂️

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#14090]
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/13837
- [ ] https://github.com/carbon-design-system/carbon/issues/13704
- [ ] Grid docs: Create / finalize designs for gutter mode examples to be coded
```
