### ISSUE TITLE
Clarify `danger` is not a valid type of `IconButton` or `<Button hasIconOnly/>`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14300]
This has been a point of confusion for some time (https://github.com/carbon-design-system/carbon/issues/11484, https://github.com/carbon-design-system/carbon/issues/14295) and we have not clearly stated anywhere on the website or storybook (that I can find) that we do not support `danger` for the icon only button(s). 

This includes both `IconButton`, and `Button` with `hasIconOnly`.

```[tasklist]
### Pieces to fix
- [x] Double check the types for IconButton do not allow `danger`
- [ ] https://github.com/carbon-design-system/carbon/pull/14307
- [ ] https://github.com/carbon-design-system/carbon/issues/17036
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4176
```

**Comment by albert-schilling** [comment]
I don't understand why Danger should not be allowed as a kind for the IconButton. We use it a lot in our app. For example for delete buttons or any kind of IconButton that does something destructive.
