### ISSUE TITLE
[PAL audit] Next steps: Deprecation comms

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#14445]
```[tasklist]
### Tasks
- [ ] Make simplified MDX version of spreadsheet with a table that helps users map asset alternatives & add to a migration.md file in Sustainability repo
- [ ] Add messaging to Sustainability repo/storybook telling people that the library no longer has a dedicated maintainer and urging them to migrate (link to migration.md table) and create issues if these components don't meet their needs (hold until survey results are in)
- [ ] Add deprecation notices to the components that have duplicates in core and C4IBMP (hold until survey results are in)
```

**Comment by alisonjoseph** [comment]
Proposed messaging to add to storybook
> This library no longer has a dedicated development resource maintaining it. When you are able to [migrate to Carbon v11](https://carbondesignsystem.com/migrating/guide/overview/) we recommend you reference the [related component guide](https://docs.google.com/document/d/1MBn5yIxBwIkjW3GD2iitJD3ez4EuKd4hLtOP8SfcdBA/edit#) and use components from [Carbon for IBM Products](https://carbon-for-ibm-products.netlify.app/?path=/story/overview-welcome--overview) and core [Carbon](https://react.carbondesignsystem.com/).

Proposed `migration.md` file content

---

# Related component guide

When [migrating to v11](https://carbondesignsystem.com/migrating/guide/overview/) we recommend transitioning your components to their related components in core [Carbon](https://github.com/carbon-design-system/carbon) and [Carbon for IBM Products](https://github.com/carbon-design-system/ibm-products). Please be aware that in certain cases, there may not be an exact 1:1 match in functionality. If necessary, please open an enhancement request or issue in the respective repository.

If your component is not in this list, it means there is currently no related component in either library. You will need to evaluate whether the component is necessary, and if so, incorporate it into your repository and perform the migration to v11 on your own.

## Carbon

| Sustainability v10                                                                                                                                                        | Carbon v11                                                                                                                                                     |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [FileUploader](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-file-uploader--browse)                                                                  | [FileUploader](https://react.carbondesignsystem.com/?path=/story/components-fileuploader--default)                                                             |
| [IconSwitch](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-icon-content-switcher--example-used-in-content-switcher-two-icons)                        | [ContentSwitcher: Icon only](https://react.carbondesignsystem.com/?path=/story/components-contentswitcher--icon-only)                                          |
| [List: basic (single column)](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list-list--basic-single-column)                                          | [ContainedList](https://react.carbondesignsystem.com/?path=/story/components-containedlist--default)                                                           |
| [List: basic (single column) with search](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list-list--basic-single-column-with-search)                  | [ContainedList: With persistent search](https://react.carbondesignsystem.com/?path=/story/components-containedlist--with-persistent-search&globals=theme:g10)  |
| [List: with selectable items](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list-list--selectable-items)                                             | [ContainedList: With interactive items?](https://react.carbondesignsystem.com/?path=/story/components-containedlist--with-interactive-items&globals=theme:g10) |
| [List: with secondaryValue](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list-list--with-secondary-value)                                           | [ContainedList: With multi-columns](https://react.carbondesignsystem.com/?path=/story/components-containedlist--usage-examples&globals=theme:g10)              |
| [List: with row actions (single)](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list-list--with-row-actions-single)                                  | [ContainedList: With actions](https://react.carbondesignsystem.com/?path=/story/components-containedlist--with-actions&globals=theme:g10)                      |
| [List: with row actions (multiple)](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list-list--with-row-actions-multiple)                              | [ContainedList: With overflow](https://react.carbondesignsystem.com/?path=/story/components-containedlist--usage-examples&globals=theme:g10)                   |
| [List: with isLargeRow and icon](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list-list--with-is-large-row-and-icon)                                | [ContainedList: with icons](https://react.carbondesignsystem.com/?path=/story/components-containedlist--with-icons)                                            |
| [ResourceList](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list-resourcelist)                                                                      | [Structured list](https://react.carbondesignsystem.com/?path=/story/components-structuredlist--selection)                                                      |
| [FlyoutMenu: Default Example](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-menus-flyoutmenu--default-example)                                       | [Menu](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-menu--playground)                                                               |
| [MenuButton: menu button](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-menubutton--single-menu-button)              | [Menu button](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-menubutton--default)                                                     |
| [MenuButton: split menu button](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-menubutton--split-menu-button)         | [Combo button](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-combobutton--default)                                                   |
| [MenuButton: icon only menu button](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-menubutton--icon-only-menu-button) |                                                                                                                                                                |
| [Modal](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-modal-composedmodal)                                                                           | [Modal](https://react.carbondesignsystem.com/?path=/story/components-modal--default)                                                                           |
| [ComposedModal](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-modal-composedmodal--warning-dialog)                                                   | [Composed modal](https://react.carbondesignsystem.com/?path=/story/components-composedmodal--default)                                                          |
| [OverflowMenu](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-menus-overflowmenu--basic)                                                              | [Overflow menu](https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--playground)                                                         |
| [SimplePagination](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagination-simplepagination)                                                        | [Pagination v2](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-pagination--with-no-sizer-child-input-or-child-selector)               |
| [FilterTags](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-tags-filtertags--default-example)                                                         | [Tags with filter](https://react.carbondesignsystem.com/?path=/story/components-tag--playground&args=filter:true)                                              |
| [Tooltip](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-tooltip--default-bottom)                                                                     | [Tooltip](https://react.carbondesignsystem.com/?path=/story/components-tooltip--default)                                                                       |

## Carbon for IBM Products

| Sustainability v10                                                                                                                                                         | Carbon for IBM Products v11                                                                                                        |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------- |
| [Table](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--playground)                                                                              | [DataGrid](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--basic-usage) |
| [Card (basics)](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-card-card)                                                                              | [Cards](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-cards-productivecard--default)            |
| [DashboardEditor](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor)                                      | [Dashboards edits](https://pages.github.ibm.com/cdai-design/pal/patterns/dashboards/dashboard-functions/edit)                      |
| [DashboardEditorHeader](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor-dashboardeditorheader--default) | [Page headers](https://pages.github.ibm.com/cdai-design/pal/patterns/dashboards/layouts#page-elements)                             |
| [EmptyState](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-empty-states--first-time-use)                                                              | [EmptyState](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-empty-state-emptystate--docs)           |
| [TableDetailWizard](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-tabledetailwizard--stateful-example)                                                | [Tearsheet](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheet--with-influencer) |
| [PageTitleBar](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-page-header-pagetitlebar--base)                                                          | [Page header](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--with-tabs)  |
| [SidePanel](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-sidepanel)                                                                                  | [Side panel](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-side-panel-sidepanel--slide-over)    |
| [Tearsheet](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-tearsheet)                                                                                  | [Tearsheet](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheet--tearsheet)       |
