### ISSUE TITLE
Component Accessibility Status: Update all tests to use the proper naming convention for tags

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14595]
In https://github.com/carbon-design-system/carbon/pull/14538 a new naming convention was established for tags placed on avt e2e tests. At the time, only Accordion was updated to use this new naming convention.

Every e2e test file needs to be updated to follow the new naming convention for tags. Without this, avt test status will not be properly surfaced on the website, https://github.com/carbon-design-system/carbon-website/pull/3735

```[tasklist]
### Tasks for each component
- [x] Update component tests to use the proper tags
- [x] Ensure every e2e test file name is CamelCased (accordion and breadcrumb are not, etc.)
```

<details><summary><h3>Click to expand list of component test files to update in './e2e/components'</h3></summary>
<p>

```[tasklist]
### List of `*-test.avt.e2e.js` component test files to update
- [x] Provide proper avt tags in `accordion/accordion-test.avt.e2e.js`
- [x] Provide proper avt tags in `breadcrumb/breadcrumb-test.avt.e2e.js`
- [x] Provide proper avt tags in `Button/Button-test.avt.e2e.js`
- [x] Provide proper avt tags in `Checkbox/Checkbox-test.avt.e2e.js`
- [x] Provide proper avt tags in `CodeSnippet/CodeSnippet-test.avt.e2e.js`
- [x] Provide proper avt tags in `ComboBox/ComboBox-test.avt.e2e.js`
- [x] Provide proper avt tags in `ComboButton/ComboButton-test.avt.e2e.js`
- [x] Provide proper avt tags in `ComposedModal/ComposedModal-test.avt.e2e.js`
- [x] Provide proper avt tags in `ContainedList/ContainedList-test.avt.e2e.js`
- [x] Provide proper avt tags in `CopyButton/CopyButton-test.avt.e2e.js`
- [x] Provide proper avt tags in `DataTable/DataTable-test.avt.e2e.js`
- [x] Provide proper avt tags in `DatePicker/DatePicker-test.avt.e2e.js`
- [x] Provide proper avt tags in `DefinitionTooltip/DefinitionTooltip-test.avt.e2e.js`
- [x] Provide proper avt tags in `Dropdown/Dropdown-test.avt.e2e.js`
- [x] Provide proper avt tags in `ErrorBoundary/ErrorBoundary-test.avt.e2e.js`
- [x] Provide proper avt tags in `FileUploader/FileUploader-test.avt.e2e.js`
- [x] Provide proper avt tags in `IconButton/IconButton-test.avt.e2e.js`
- [x] Provide proper avt tags in `Link/Link-test.avt.e2e.js`
- [x] Provide proper avt tags in `MenuButton/MenuButton-test.avt.e2e.js`
- [x] Provide proper avt tags in `Modal/Modal-test.avt.e2e.js`
- [x] Provide proper avt tags in `MultiSelect/MultiSelect-test.avt.e2e.js`
- [x] Provide proper avt tags in `Notifications/Notifications-test.avt.e2e.js`
- [x] Provide proper avt tags in `NumberInput/NumberInput-test.avt.e2e.js`
- [x] Provide proper avt tags in `OrderedList/OrderedList-test.avt.e2e.js`
- [x] Provide proper avt tags in `OverflowMenu/OverflowMenu-test.avt.e2e.js`
- [x] Provide proper avt tags in `Pagination/Pagination-test.avt.e2e.js`
- [x] Provide proper avt tags in `ProgressBar/ProgressBar-test.avt.e2e.js`
- [x] Provide proper avt tags in `ProgressIndicator/ProgressIndicator-test.avt.e2e.js`
- [x] Provide proper avt tags in `RadioButton/RadioButton-test.avt.e2e.js`
- [x] Provide proper avt tags in `Search/Search-test.avt.e2e.js`
- [x] Provide proper avt tags in `Select/Select-test.avt.e2e.js`
- [x] Provide proper avt tags in `Slider/Slider-test.avt.e2e.js`
- [x] Provide proper avt tags in `StructuredList/StructuredList-test.avt.e2e.js`
- [x] Provide proper avt tags in `Tabs/Tabs-test.avt.e2e.js`
- [x] Provide proper avt tags in `TextArea/TextArea-test.avt.e2e.js`
- [x] Provide proper avt tags in `TextInput/TextInput-test.avt.e2e.js`
- [x] Provide proper avt tags in `Tile/Tile-test.avt.e2e.js`
- [x] Provide proper avt tags in `Toggle/Toggle-test.avt.e2e.js`
- [x] Provide proper avt tags in `Tooltip/Tooltip-test.avt.e2e.js`
- [x] Provide proper avt tags in `TreeView/TreeView-test.avt.e2e.js`
- [x] Provide proper avt tags in `UIShell/UIShell-test.avt.e2e.js`
- [x] Provide proper avt tags in `UnorderedList/UnorderedList-test.avt.e2e.js`
```

</p>
</details> 

```[tasklist]
### Delivery
- [ ] https://github.com/carbon-design-system/carbon/pull/14915
- [ ] https://github.com/carbon-design-system/carbon/pull/14913
```

**Comment by tay1orjones** [comment]
Copied content from the [naming convention documentation](https://github.com/carbon-design-system/carbon/blob/main/docs/testing.md#tags):

> #### Tags
> 
> Playwright tests are divided into different tag categories for reporting
> purposes. `@avt` test tags are used to populate accessibility test statuses
> within component pages on https://carbondesignsystem.com
> 
> For avt tests, the test title should always include one of the following:
> 
> | Tag                    | Description                                                                                                                    |
> | ---------------------- | ------------------------------------------------------------------------------------------------------------------------------ |
> | `@avt`                 | High level/root tag that should wrap all avt tests. This is usually placed in a `describe` block title.                        |
> | `@avt-default-state`   | Sub-tag of `@avt`, used to tag individual tests covering the default state of a component.                                     |
> | `@avt-advanced-states` | Sub-tag of `@avt`, used to tag individual tests covering advanced states of a component (open/close, invalid, expanded, etc.). |
> | `@avt-keyboard-nav`    | Sub-tag of `@avt`, used to tag individual tests covering keyboard navigation flows.                                            |
