### ISSUE TITLE
LTS Communication improvements

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#14736]
We want to make sure we broadcast our LTS Release Schedule anywhere and everywhere. 
* Announcement: https://medium.com/carbondesign/announcing-the-carbon-design-system-release-schedule-f33144e9141
* Living document: https://github.com/carbon-design-system/carbon/blob/main/docs/release-schedule.md

Running notes:
- We can reuse the imagery from Francine's article earlier this year: https://medium.com/carbondesign/moving-forward-on-deprecating-carbon-components-and-carbon-components-react-4f2f0c3d8448#:~:text=While%20carbon%2Dcomponents%20and%20carbon,the%20upcoming%20months%20before%20v10
- Devs can take the lead with verbiage, layout, design, etc. and we'll just do a thorough review with the team to ensure we're all confident in the outcome.
- Do we want these notifications to funnel people directly to the release schedule, or should we funnel them into a discussion/issue that jumps off with a list of other links?

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/14764
- [ ] https://github.com/carbon-design-system/carbon/issues/14765
- [ ] ~Add LTS to readme v10/main~
- [ ] ~Add LTS link pinned to slack channels~
- [x] Announce LTS plans in our support channels - slack blast, pinned github issue, do we have or need an open discussion?
```

**Comment by tay1orjones** [comment]
Yes, perfect timing for this. As of tomorrow we're exactly a year out from the planned EOL of v10. I'd like to get this into next sprint if we could.
