### ISSUE TITLE
Slug styles and React component

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14931]
Some previous notes on this are housed in the parent issue, https://github.com/carbon-design-system/carbon/issues/14928

```[tasklist]
- [ ] https://github.com/carbon-design-system/carbon/issues/14948
- [ ] https://github.com/carbon-design-system/carbon/issues/14947
- [ ] https://github.com/carbon-design-system/carbon/issues/15051
- [ ] https://github.com/carbon-design-system/carbon/pull/15036
```

**Comment by mattrosno** [comment]
@tay1orjones I moved the web components task to its own issue so we can see that on the roadmap view.

**Comment by mattrosno** [comment]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11072
