### ISSUE TITLE
AI gradient tokens and mixins

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14930]
Some previous notes on this are housed in the parent issue, https://github.com/carbon-design-system/carbon/issues/14928

```[tasklist]
- [ ] https://github.com/carbon-design-system/carbon/issues/15071
- [ ] https://github.com/carbon-design-system/carbon/issues/15072
- [ ] https://github.com/carbon-design-system/carbon/issues/15073
- [ ] https://github.com/carbon-design-system/carbon/issues/14929
- [ ] https://github.com/carbon-design-system/carbon/issues/15074
```
