### ISSUE TITLE
C4AI Slug: Create an interactive Slug component spec (focus states, popover, etc.)

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14948]
See comments below for specs

```[tasklist]
### Tasks
- [x] Standard slug spec
- [x] Inline slug spec
- [x] Hollow spec
- [x] Functional slug spec
```

**Comment by aagonzales** [comment]
## Standard slug spec

Figma file 
<img width="1312" alt="Slug - Standard - Specs" src="https://github.com/carbon-design-system/carbon/assets/11670886/49115d83-baeb-4f5a-9f16-c6b5633c8275">

**Comment by aagonzales** [comment]
## Hollow slug spec

<img width="1312" alt="Slug - Hollow - Specs" src="https://github.com/carbon-design-system/carbon/assets/11670886/1bda2831-b3e1-4184-b713-6e6bb7e2fd6c">

**Comment by aagonzales** [comment]
## Inline slug spec

<img width="1312" alt="Slug - Inline - Specs" src="https://github.com/carbon-design-system/carbon/assets/11670886/5d59864e-3dc1-4e09-afe6-9017c9a615af">

**Comment by aagonzales** [comment]
## Functional spec

<img width="1312" alt="Slug - Interaction - Specs" src="https://github.com/carbon-design-system/carbon/assets/11670886/74682ce3-cd88-4649-9c58-77a45b89606d">
