### ISSUE TITLE
C4AI Slug: Update callout in the Figma library to match what was built

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15066]
```[tasklist]
### Tasks
- [x] Make callout more composable with variants
- [x] Update styles to match code
- [ ] Add shark fin
```

**Comment by mattrosno** [comment]
Anna:
>The [callout] sharkfin wasn't originally included so we need to add it to the shared Figma library asset.

**Comment by aagonzales** [comment]
Closing this issue, in favor of a new kit issue that will combine the call and slug together in one component and include the slug. 
https://github.com/carbon-design-system/carbon-design-kit/issues/760
