### ISSUE TITLE
Core React components AI enhancements

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15097]
This issue tracks the effort to add the AI enhancements (slug and gradient) to the first wave of core components for phase 1. On a per-component basis, once the enhancement has been made to a React component (via the styles package), that component can then be enhanced in the web components package.

**Acceptance criteria**

- Enhancements designated with experimental status

**Out of scope**

- This effort is not the "full AI" theme that has layer styling like opacity and blur
- Adding the AI enhancements to the following components will likely happen in phase 2: toggle, breadcrumb, code snippet, structured list, progress indicator, slider, tree view
- The following components will likely not need AI enhancements: contained list, file uploader, link, lists, notifications, search, tabs, accordion, button, content switcher, loading, menu, menu button, pagination, popover, progress
bar, toggletip, tooltip, UI shell header, UI shell left nav, UI shell right panel

### Design
- [ ] https://github.com/carbon-design-system/carbon/issues/15181
- [ ] https://github.com/carbon-design-system/carbon/issues/15184
- [ ] https://github.com/carbon-design-system/carbon/issues/15185
- [ ] https://github.com/carbon-design-system/carbon/issues/15182
- [ ] https://github.com/carbon-design-system/carbon/issues/15183

### Development
- [ ] https://github.com/carbon-design-system/carbon/issues/15089
- [ ] https://github.com/carbon-design-system/carbon/issues/15186
- [ ] https://github.com/carbon-design-system/carbon/issues/15187
- [ ] https://github.com/carbon-design-system/carbon/issues/15188
- [ ] https://github.com/carbon-design-system/carbon/issues/15189
- [ ] https://github.com/carbon-design-system/carbon/issues/15190
- [ ] https://github.com/carbon-design-system/carbon/issues/15191
- [ ] https://github.com/carbon-design-system/carbon/issues/15192
- [ ] https://github.com/carbon-design-system/carbon/issues/15193
