### ISSUE TITLE
[Illustration] Visual for the Town Hall deck

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#15226]
### Goal
Help the DPO team modify the visual on the deck for Town Hall on 11/29
Deadline: 11/27
Conatcts: Derek Castillo, Jessica Tremblay, Danielle Jenkins

-----
### Resources
Box note: https://ibm.box.com/s/hgxymp2z9r8yz0tvfl9fuqslaz5g6nbg
Deck: https://ibm.box.com/s/6f8br0v0usz1jrk02v2ump59d4581ol6

-----
### Tasks

- [x] Image - Probably add an Austin illustration on the opening page
- [x] Organize images on the slides from each VP (deadline to submit to Derek is Tues 11/21)
- [x] Cleaning up text and images if needed
- [x] Finalize the visual for the deck early in the morning of 11/27
