### ISSUE TITLE
Component Accessibility Status: Final Design Deliverable

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#15279]
Designer | Make sure to get a developer up to speed with the current final stage and work closely with him/her when he/she has questions or concerns.

### Tasks
- [x]  Update the final design based on design feedback
- [x]  Finalize the features with developers
- [x]  Finalize the content with @tay1orjones 
- [x]  Finalize the design
- [x]  Hand off the dev specs or redline

--- 

### Acceptance criteria 
- [x] Provide tables with tags scaled at different breakpoints (less columns + stacked tags) 
- [x] Content update by Taylor 
- [x] Doable customized build for Dropdown + Tags
