### ISSUE TITLE
[AI] Create design spec for AI `Code-snippet` 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15301]
Create a design spec for an AI flavor of code snippet (inline, single line and multi-line), incorporating the slug and aura gradient where appropriate. Design a solution for both light and dark themes.

**Tasks**
- [ ] Create a design spec for Carbon devs based off the design in[ Carbon for AI file](https://www.figma.com/design/QObDMbLENUSCyaLAToeoli/SANDBOX---C4AI-Code-snippet?node-id=2088-65344&t=TnKriOedkJEz6xID-1).

**Features AI Chat needs**
- [ ] https://github.com/carbon-design-system/carbon/issues/6519
- [ ] Highlight syntax (Highlight JS) 
- [ ] Rounder corners 
- [ ] Full screen “pop out” icon/ feature 
- [ ] Is “show more” optional if there is internal scrolling
- [ ] Streaming text

See: https://labs-canary.carbondesignsystem.com/?path=/story/components-chat-code--showcase

**Comment by RichKummer** [comment]
[Figma design specs](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=1306%3A126488&mode=design&t=Xk9lO3uHWimi9NNS-1)



![Image](https://github.com/carbon-design-system/carbon/assets/15643582/df838960-774f-47c9-ab9d-1d0129f76019)
