### ISSUE TITLE
Dividers in components: Dev Implementation

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#15492]
### **Developer implementation**

_Important Links_
[Design Solutions and Guidelines for Dividers in Components - Figma](https://www.figma.com/file/VIapeeP8TSM77qYIjdMiIY/Dividers-in-Carbon-Components?type=design&node-id=78-32710&mode=design)

---

### Tasks
- [x] Introduce vertical divider across all states under "Option Selected" for Combobox - Default
- [x] Introduce vertical divider across all states under "Option Selected" or Combobox - Fluid
- [x] Introduce vertical divider across all states "Option Selected" for Filterable Multiselect - Default
- [x] Introduce vertical divider across all states "Option Selected" for Filterable Multiselect - Fluid
- [x] Remove vertical divider from the Search component - Fluid 
- [x] Ensure that the following updates are reflected in the Form and Modal components as well

---

Visual Context to the Specs
![Specs for Dividers in Combobox and Filterable Multiselect](https://github.com/carbon-design-system/carbon/assets/159760598/565a72c3-2e0c-44f4-983a-8925860f6c41)

Combobox Default and Fluid
![Combo box - Default](https://github.com/carbon-design-system/carbon/assets/159760598/8ed44c03-0c57-4e64-8a9c-8efd95a4f3d9)

![Combo box - Fluid](https://github.com/carbon-design-system/carbon/assets/159760598/bae6062e-f132-44bd-a422-397345f488bc)

Filterable Multiselect Default and Fluid
![Filterable Multiselect - Default](https://github.com/carbon-design-system/carbon/assets/159760598/ad12f293-f0ce-4822-ada3-88c72ce04f67)

![Filterable Multiselect - Fluid](https://github.com/carbon-design-system/carbon/assets/159760598/648cde1d-f5fe-44c3-a0a5-1b93a47b70c7)

Search Fluid
![Search Fluid](https://github.com/carbon-design-system/carbon/assets/159760598/62075992-0c5e-46d9-8adf-febc6d0fb50a)

Visual Context to the Guidelines (EXTRA INFORMATION)
![Dividers in Carbon Components (Input fields)](https://github.com/carbon-design-system/carbon/assets/148988115/1f103657-9769-45c8-9e3b-0766625a3a4d)
