### ISSUE TITLE
Add AI enhancements to React `Button` enhancements

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15621]
Related #15620 

**Tasks** (Phase 1): 
- [x] Rounded corner prop
- [x] New "selected-disabled" state (works like a visited link)
- [x] Custome `Quick action` button for chat

[Figma file](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=1743%3A80479&mode=design&t=Jo9H2opjALVAM2g7-1)

<img width="1312" alt="AI Buttons - Phase 1" src="https://github.com/carbon-design-system/carbon/assets/11670886/3cbb5e25-5d96-4537-8f4b-450e2a7d0db2">
