### ISSUE TITLE
[Enhancing Awareness: Poster] Conception & Initiation Phase: Setting the Foundation

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#15759]
This is a Carbon Initiative Project to encourage IBM designers to join Carbon Design and Dev Office hours.

**Conception & Initiation phase:** This phase involved laying groundwork for our poster project by having the initial discussions with key stakeholders to flesh out our ideas.
 
---

**Tasks:**
- [x] Discuss poster ideas with Jean
- [x] Connect with Scott to gather feedback on ideas
    ↳ _"I love ya'lls passion on this, but keep it simple. You don't need approval for this. Try something. See if it resonates with people. Iterate. Take a picture of it in your studio space and celebrate it with the rest of the team here in the 'States. Think of this as a extracurricular activity to generate excitement for Carbon. Have fun with it."_
- [x] Put initial thoughts into the Figma file
- [x] Reach out to Lauren for further collaboration and refinement

**Comment by Kritvi-bhatia17** [comment]
I have allocated 3 story points to this issue, considering the time investment of approximately 2-3 days spent engaging with key stakeholders, consolidating all those insights into Figma, and subsequently discussing them with Lauren.
