### ISSUE TITLE
[Enhancing Awareness: Poster] Design Phase: Work on fine-tuning the Drafts based on Feedback

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#15751]
This is a Carbon Initiative Project to encourage IBM designers to join Carbon Design and Dev Office hours.
**Important Links:** [Figma File](https://www.figma.com/file/Btw3gqRmgPE4RtYSI2cZpq/POSTER?type=design&node-id=15-4&mode=design&t=qJDlYbC1zy5LhQmY-0), [Slack Discussion](https://ibm.enterprise.slack.com/archives/C06JKAQLDL2), [Umbrella Issue](https://github.com/carbon-design-system/carbon/issues/15749)

Design Phase: This phase would involve working on feedback received from the Ideation phase and discussing the iterations with the Carbon and IBM Design Team

---

**Tasks:**
- [ ] Finalise the copy of the Poster
- [ ] Work on: Simple stacked type, maybe add an arrow @Kritvi-bhatia17 
- [ ] Work on: Large C and arrow @alina-jacob 
- [ ] Play it back to the team
