### ISSUE TITLE
Dividers in components: Website docs - Fluid Search Component

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#15753]
**_Important Links:_** [Doc Work - Figma File](https://www.figma.com/file/VIapeeP8TSM77qYIjdMiIY/Dividers-in-Carbon-Components?type=design&node-id=260-34893&mode=design)

## Doc Update for Search component (Fluid Search)

---

**Tasks**

Usage Tab
- [x] - Update 7 Images
- [x] - Improve Do-Don't alignment

Style Tab
- [x] - Update 2 image

Final Review
- [x] - VS Code update
- [x] - VS Code review by Lauren
