### ISSUE TITLE
Enhancing Awareness: Carbon Design System ☂️

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#15761]
_Promoting the Carbon Design System_

**Background:** During conversations with many of the Carbon design system's stakeholders (including designers, developers, and product managers) it became apparent that while numerous initiatives are in place, there is a notable `lack of awareness surrounding these initiatives`, particularly within the India office.

---

### Problem
The lack of awareness hinders the effective utilization of available resources and opportunities for collaboration and improvement. Consequently, addressing this issue becomes imperative to ensure that the full potential of the Carbon Design System is realized and leveraged across all IBM offices, including India, for enhanced design and development outcomes.

```[tasklist]
### CIOH - Carbon India Office Hours
- [x] 🗣️ Preparation, marketing and initial set up
- [x] https://github.com/carbon-design-system/carbon/issues/16353
- [ ] https://github.com/carbon-design-system/carbon/issues/16204
- [x] https://github.com/carbon-design-system/carbon/issues/16351
- [ ] https://github.com/carbon-design-system/carbon/issues/16775
- [ ] https://github.com/carbon-design-system/carbon/issues/16515#issue-2307517336
- [ ] https://github.com/carbon-design-system/carbon/issues/16889
- [ ] https://github.com/carbon-design-system/carbon/issues/16352
- [x] ✏️ Edu decks
- [x] https://github.com/carbon-design-system/carbon/issues/16350
- [ ] https://github.com/carbon-design-system/carbon/issues/16487
- [ ] https://github.com/carbon-design-system/carbon/issues/16513
- [ ] https://github.com/carbon-design-system/carbon/issues/16906
- [x] 🤝 Workshops (PinUps)
- [ ] https://github.com/carbon-design-system/carbon/issues/16482
- [x] [CIOH] Connected with Apptio team for general discussions - 27th June'24
- [x] [CIOH] Connected withv WebMethod designer - 9th Aug'24
- [x] 🥳 Engagement
- [ ] https://github.com/carbon-design-system/carbon/issues/16516
- [ ] https://github.com/carbon-design-system/carbon/issues/16514
- [ ] https://github.com/carbon-design-system/carbon/issues/16822
```

---

```[tasklist]
### Poster
- [ ] https://github.com/carbon-design-system/carbon/issues/15759
- [ ] #15750
- [ ] #15751
- [ ] https://github.com/carbon-design-system/carbon/issues/15755
- [ ] [Enhancing Awareness: Poster] Execution Phase: Print out the Posters and Display across offices
- [ ] [Enhancing Awareness: Poster] Observation and Iteration Phase: Observe and incorporate feedback for next set of Carbon Office hours initiative.
```

---

```[tasklist]
### Carbon intro-workshops
- [ ] https://github.com/carbon-design-system/carbon/issues/15762
```
