### ISSUE TITLE
[Education]: Carbon curriculum ☂️

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#16008]
## Description
We need to organize a series of information sessions on Carbon Design System, tailored to different audiences within our organization. These sessions aim to educate team members about Carbon's features, benefits, applications specific to their roles and many more. By providing targeted information, we can ensure that each team effectively integrates Carbon into their workflows.

### Target audience (carbon user)
- **Designers**: Learn about Carbon's design capabilities, components, and tools to enhance design consistency and quality.
- **Researchers**: Gain insights into Carbon's best practices and accessibility features.
- **Developers**: Focus on technical integration, customization, and best practices for using Carbon in code, Figma, and GitHub.
- **UX Engineers**: Explore the intersection of design and development to create seamless user experiences.
- **Project Managers (PMs)**: Improve project workflows, efficiency, and collaboration using Carbon, with practical tips and case studies.

_Note: The presentation deck will be tailored and updated according to the specific audience for each Carbon info session._

```[tasklist]
### Hursley audience (Front end developers)
- [ ] https://github.com/carbon-design-system/carbon/issues/16517
- [ ] https://github.com/carbon-design-system/carbon/issues/16024
- [ ] https://github.com/carbon-design-system/carbon/issues/16025
- [ ] https://github.com/carbon-design-system/carbon/issues/16026
- [ ] https://github.com/carbon-design-system/carbon/issues/16027
```

---

```[tasklist]
### Session types
- [ ] https://github.com/carbon-design-system/carbon/issues/16518
```
