### ISSUE TITLE
Normalize usage of types `ReactNode` and `ReactNodeLike`

### ISSUE THREAD

**Issue by cuppajoey** [carbon-design-system/carbon#16054]
### Package

@carbon/react

### Package version

v1.53.0

### React version

v16.140

### Description

The types defined for `TextArea.labelText` and `TextInput.labelText` do not match. The former is typed as `prop-types.ReactNodeLike` while the latter is typed as `React.ReactNode`. In older versions of `React`, `ReactNode` included support for `{}`, but has [since been removed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210). Consumers who haven't yet upgraded to React 18 can experience type errors (as demonstrated in the included StackBlitz demo) between two props which _should_ accept the same data types.

<img width="600" alt="Screenshot 2024-03-25 at 11 40 19 AM" src="https://github.com/carbon-design-system/carbon/assets/14837881/834dc8dc-fe2f-41a2-86a9-6e6c063a1eb1">

---

While this issue can be worked around, I wanted to take this opportunity to highlight an inconsistent practice when writing types for props that accept a `ReactNode`. Currently many component props accept [`ReactNode`](https://github.com/eps1lon/DefinitelyTyped/blob/master/types/react/index.d.ts#L479) while others accept [`ReactNodeLike`](https://github.com/eps1lon/DefinitelyTyped/blob/master/types/prop-types/index.d.ts#L14), e.g., `TextArea` and `TextInput`. In some cases both types are being used within the same component (`TextInput.labelText` vs `TextInput.slug`).

From my understanding, `ReactNodeLike` is meant to match `ReactNode` without being dependent on React itself (See DefinitelyTyped/DefinitelyTyped#29194). However, since `@carbon/react` has a direct dependency on `react`, we should use `ReactNode` exclusively instead of relying on two packages for what is essentially the same type definition.

If the maintainers agree, I'm happy to contribute a fix for this myself 👍.

All the components that have the intertwining between the typescript `interface` and type annotations from the `prop-types` library:
```[tasklist]
- [ ] https://github.com/carbon-design-system/carbon/issues/16449
- [ ] https://github.com/carbon-design-system/carbon/issues/16481
- [ ] https://github.com/carbon-design-system/carbon/issues/16450
- [ ] https://github.com/carbon-design-system/carbon/issues/16451
- [ ] https://github.com/carbon-design-system/carbon/issues/16452
- [ ] https://github.com/carbon-design-system/carbon/issues/16459
- [ ] https://github.com/carbon-design-system/carbon/issues/16460
- [ ] https://github.com/carbon-design-system/carbon/issues/16461
- [ ] https://github.com/carbon-design-system/carbon/issues/16462
- [ ] https://github.com/carbon-design-system/carbon/issues/16463
- [ ] https://github.com/carbon-design-system/carbon/issues/16464
- [ ] https://github.com/carbon-design-system/carbon/issues/16410
- [ ] https://github.com/carbon-design-system/carbon/issues/16411
- [ ] https://github.com/carbon-design-system/carbon/issues/16412
- [ ] https://github.com/carbon-design-system/carbon/issues/16414
- [ ] https://github.com/carbon-design-system/carbon/issues/16416
- [ ] https://github.com/carbon-design-system/carbon/issues/16417
- [ ] https://github.com/carbon-design-system/carbon/issues/16419
- [ ] https://github.com/carbon-design-system/carbon/issues/16420
- [ ] https://github.com/carbon-design-system/carbon/issues/16421
- [ ] https://github.com/carbon-design-system/carbon/issues/16422
- [ ] https://github.com/carbon-design-system/carbon/issues/16423
- [ ] https://github.com/carbon-design-system/carbon/issues/16424
- [ ] https://github.com/carbon-design-system/carbon/issues/16425
- [ ] https://github.com/carbon-design-system/carbon/issues/16426
- [ ] https://github.com/carbon-design-system/carbon/issues/16427
- [ ] https://github.com/carbon-design-system/carbon/issues/16480
```
You can take up each component as a separate issue and work on it.

### Reproduction/example

https://stackblitz.com/edit/github-bcs3rp?file=src%2FInput.tsx

### Steps to reproduce

1. Wait for the application to start and for Typescript to load.
2. Open `src/Input.tsx`.
3. Hover over `labelText` in the `TextArea` on line 12.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for opening this up. The mismatch here should definitely be fixed. Which way to fix it I'm unsure on. We state support for react 16, 17, and 18. It sounds like using ReactNode might cause typescript errors for 17 and 18 users in certain scenarios. Avoiding using `prop-types` within TypeScript interfaces seems reasonable despite the downsides. 

I'm not opposed to consolidating on using ReactNode for now, and we'll keep an eye on feedback if it's problematic.

**Comment by cuppajoey** [comment]
> Thanks for opening this up. The mismatch here should definitely be fixed. Which way to fix it I'm unsure on. We state support for react 16, 17, and 18. It sounds like using ReactNode might cause typescript errors for 17 and 18 users in certain scenarios. Avoiding using `prop-types` within TypeScript interfaces seems reasonable despite the downsides.

Could you point me to some info regarding the potential errors with `ReactNode` with 17 and 18 users?

> I'm not opposed to consolidating on using ReactNode for now, and we'll keep an eye on feedback if it's problematic.

Are you open to contributions on this? We could consolidate these incrementally as we work on other issues.

**Comment by tay1orjones** [comment]
@cuppajoey Yes here's one example from [slack](https://ibm-studios.slack.com/archives/C03C8VASVED/p1714465564282039)

![image](https://github.com/carbon-design-system/carbon/assets/3360588/28782fbf-9df2-469e-8ce0-4b050befccf6)

> Are you open to contributions on this?

Yes absolutely, we can do them incrementally as we work on other stuff. @Gururajj77 could you add a list here of all components that need to be modified?

**Comment by 2nikhiltom** [comment]
Hey ! All the components are covered via following PR's #16453, #16465, #16418, #16428

**Comment by 2nikhiltom** [comment]
Hey ! All the components are covered via following PR's #16453, #16465, #16418, #16428 and https://github.com/carbon-design-system/carbon/issues/16449
