### ISSUE TITLE
Out-of-compliance additional website issues ☔

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#16078]
Follow on to https://github.com/carbon-design-system/carbon/issues/15634

```[tasklist]
### Carbon websites
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4173
- [ ] https://github.com/carbon-design-system/carbon/issues/16968
- [ ] https://github.com/carbon-design-system/carbon/issues/16967
- [ ] https://github.com/carbon-design-system/carbon-components-vue/pull/1614
- [x] Take down v6.carbondesignsystem.com
- [x] Take down v7.carbondesignsystem.com
- [x] Take down v8.carbondesignsystem.com
- [x] Take down v9.carbondesignsystem.com
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4213
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4264
- [ ] https://github.com/carbon-design-system/carbon-website/pull/4268
```

```[tasklist]
### IBM Design websites
- [x] Racial Equity in Design - remove Vimeo (jess tremblay to handle)
```

```[tasklist]
### Charts
- [x] Fonts
```

**Comment by tay1orjones** [comment]
For what it's worth, the v6, v7, v8 sites are technically still hosted on github pages, but the pathing is now broken due to the repo name subdirectory.

* https://github.com/carbon-design-system/carbon-website-v6/issues/1
* https://github.com/carbon-design-system/carbon-website-v7/issues/1
* https://github.com/carbon-design-system/carbon-website-v8/issues/1
