### ISSUE TITLE
[Content switcher] Naming convention and usage 🏖️ 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#16087]
Ref issue 1: https://github.com/carbon-design-system/carbon/issues/9519 (refactoring ContentSwitcher to properly implement the tabs aria design pattern) 
Ref issue 2: https://github.com/carbon-design-system/carbon-website/issues/3364 (child content of content switcher)

---
### Problems

1. The name "Content switcher" is unclear, implying that this should be using tabs to actually switch content. Therefore, it's hard to figure out a consistent and proper name for individual items/sections within the component. 

![image](https://github.com/carbon-design-system/carbon-website/assets/77697351/e91359bc-184e-4462-ad74-f21dffc14616)

2. The usage is unclear for guidance and code implementation of how the component impacts the child content. See [this issue](https://github.com/carbon-design-system/carbon/issues/9519) for high level differences between CS and Tabs

![image](https://github.com/carbon-design-system/carbon-website/assets/77697351/033d2942-ca18-46b2-93de-faaae95f2b83)

----

```[tasklist]
### Possible Tasks
- [ ] Research and Discuss to confirm the existing problems
- [ ] Reconsider the naming for "Content Switcher"
- [ ] Clearly define the usage of content switcher
```
