### ISSUE TITLE
Dividers in AI components: Update Figma Kit

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#16091]
## Acceptance criteria

- Update the v11 All themes Figma kit to reflect the changes that came out of the [final design solutions](https://github.com/carbon-design-system/carbon/issues/15286) for dividers in components.

---

**Tasks**
- [x] Update dividers for Dropdown
- [x] Update dividers for Combobox
- [x] Update dividers for Multi-select
- [x] Update dividers for Filterable-multi-select
- [x] Update dividers for Number-input
- [x] Update dividers for Select
- [x] Figma review (figma expert/Juan)
