### ISSUE TITLE
Carbon orientation Q2 2024 ☂️

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#16105]
In this 4-week training, we will:
- Learn about Carbon and Carbon for IBM Products PAL through their respective websites and storybooks
- Present on how to use all components properly (ex: tabs vs switcher)
- Document questions and suggest improvements
- Go through your team’s designs to see what components are not being properly applied
- Practice ownership through knowing different patterns to guide new hires and your team
- Receive 6 hours of YourLearning credits

[Box note link](https://ibm.box.com/s/lj113enfoqq79h1gx7wy8jyvp2gs0kfx)

## To do:
- [x] Prepare a presentation on the chosen topic from the list, review the documentation, and present a summary of the topic.

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/16136
- [ ] https://github.com/carbon-design-system/carbon/issues/16137
```
