### ISSUE TITLE
Combobox (Unique Value): Feedback for unique values

### ISSUE THREAD

**Issue by benjamin-kurien** [carbon-design-system/carbon#16102]
The Problem and Solution description: We now have a way of adding a unique value in the combobox component. However, this is confusing because no feedback is provided to the user while entering/inputting a unique value, and it lacks visual cues that such an action is possible. This can be resolved by providing instruction to the user that they can add unique values by pressing enter and having visual feedback that the unique value has been accepted and stored after pressing enter.

### The need
Adding custom values to a list of options in a dropdown provides flexibility to products to leverage such info in user journeys.

### The problem
However adding custom values to a combobox is confusing because it lacks visual cues that such an action is even possible.  Moreover no feedback is provided to the user while they try to enter custom values, nor after they input the custom value.

### The solution
This can be solved by catering to the user needs, by providing the following visual cues and feedback to the user:
- Instruction to the user that they can add custom values by pressing enter.
- Visual feedback that the custom value has been accepted and stored after pressing enter.

-------

Ref example:
https://vaadin.com/docs/latest/components/combo-box
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/16498
- [ ] https://github.com/carbon-design-system/carbon/issues/16307
- [ ] https://github.com/carbon-design-system/carbon/issues/16313
- [ ] https://github.com/carbon-design-system/carbon/issues/16310
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4090
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4091
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/831
- [ ] https://github.com/carbon-design-system/carbon/issues/16312
```

**Comment by benjamin-kurien** [comment]
@RheaM29- Thankyou for highlighting the need for this feature enhancement within your product.

**Comment by RheaM29** [comment]
> @RheaM29 - Thankyou for highlighting the need for this feature enhancement within your product.

Thank you @benjamin-kurien for taking this issue ahead! Really appreciate the initiative :)

**Comment by sstrubberg** [comment]
Follow on visual enhancement to https://github.com/carbon-design-system/carbon/issues/6102
