### ISSUE TITLE
[Feature Request]: Export props for TypeScript components

### ISSUE THREAD

**Issue by Sam-Wool** [carbon-design-system/carbon#16154]
### The problem

In the `@carbon/react` project multiple components which have been converted into TypeScript in Carbon 11 are lacking either exports on their props,. Without access to the props, it is much more difficult to create wrappers for components, pass along props as part of parent components, and assigning types to objects that can help build out components neatly. This has affected my team's efforts to move over from Carbon 10 to 11.

For example, in my team's product we leverage the base component's props (aliased here as `CarbonAccordionProps`) to create the typings for a wrapper for the `Accordion` component with a simple overwrite. Without these props, we would have to redefine all of the parameters in our codebase by hand, which would open us up to issues down the road if the Carbon component's props change.

![image](https://github.com/carbon-design-system/carbon/assets/77698508/c624e2e3-9a2f-4679-a4b7-ce159c6945ce)

Included here is a list of all props that are missing exports that my team have found. Note that there may be additional components with this issue that we haven't identified yet.
```[tasklist]
- [ ] https://github.com/carbon-design-system/carbon/issues/16364
- [ ] https://github.com/carbon-design-system/carbon/issues/16365
- [ ] https://github.com/carbon-design-system/carbon/issues/16366
- [ ] https://github.com/carbon-design-system/carbon/issues/16367
- [ ] https://github.com/carbon-design-system/carbon/issues/16368
- [ ] https://github.com/carbon-design-system/carbon/issues/16369
- [ ] https://github.com/carbon-design-system/carbon/issues/16370
- [ ] https://github.com/carbon-design-system/carbon/issues/16371
- [ ] https://github.com/carbon-design-system/carbon/issues/16372
- [ ] https://github.com/carbon-design-system/carbon/issues/16373
- [ ] https://github.com/carbon-design-system/carbon/issues/16374
- [ ] https://github.com/carbon-design-system/carbon/issues/16375
- [ ] https://github.com/carbon-design-system/carbon/issues/16376
- [ ] https://github.com/carbon-design-system/carbon/issues/16377
- [ ] https://github.com/carbon-design-system/carbon/issues/16378
- [ ] https://github.com/carbon-design-system/carbon/issues/16379
- [ ] https://github.com/carbon-design-system/carbon/issues/16380
- [ ] https://github.com/carbon-design-system/carbon/issues/16381
- [ ] https://github.com/carbon-design-system/carbon/issues/16382
- [ ] https://github.com/carbon-design-system/carbon/issues/16383
- [ ] https://github.com/carbon-design-system/carbon/issues/16384
- [x] TileGroupProps (completed via #16384)
```
We've also noticed some components are missing an `index.ts` or `.d.ts` file - this has caused a similar issue when trying to import props belonging to that component. Below is a list of the components we've found with this issue:
```[tasklist]
- [x] MultiSelect (completed via #16147)
- [ ] https://github.com/carbon-design-system/carbon/issues/16386
- [ ] https://github.com/carbon-design-system/carbon/issues/16385
- [ ] https://github.com/carbon-design-system/carbon/issues/16444
- [ ] https://github.com/carbon-design-system/carbon/issues/16547
```
### The solution

To fix this, we need to export the props (see attached for example of an interface lacking an export).

![image](https://github.com/carbon-design-system/carbon/assets/77698508/8a224541-93bd-4355-9907-32677f9a65c1)

There are also some instances where a prop is missing an `index.ts` or `.d.ts` file - in those cases, we should be able to fix this issue by refactoring an existing `index.js` to `index.ts`. See below for an example of a healthy `index.ts` file.

![image](https://github.com/carbon-design-system/carbon/assets/77698508/e6594cbd-400c-4f7a-8b9b-9ef35d6c839f)

### Application/PAL

IBM Storage Fusion

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Thanks for opening this, I think it's worthwhile to consider exporting these. I'm not sure if there's any downsides, but if I'm not mistaken, consumers have always been able to pluck proptypes off the exported components. Makes sense to enable the same through TypeScript.

> There are also some instances where a prop is missing an index.ts or .d.ts file

Majority of these cases are due to a sibling component not yet being migrated. Once all exports in the component(s) `index.js` have been migrated, `index.js` can be renamed to `index.ts` and then the `.d.ts` file will start being automatically generated. 

If you notice any that have all their exports migrated, but it's still `index.js`, you can open a PR or an issue to track those individually. We have a couple of these issues already. Also all this should be fully resolved once everything has types, #12513, which we're really close to completing.

**Comment by gillesdandrea** [comment]
As a work-around, in typescript it's possible to extract the type of a parameter of a function. So
```TypeScript
type MyExtractedProps = Parameters<typeof MyFunctionalComponent>[0];
```
allow to use the Props of a functional components even if not exported.

**Comment by wkeese** [comment]
I was going to suggest the same thing, except with `ComponentProps`, ex:

```js
ComponentProps<typeof TableToolbarSearch>
```

It's a bit easier to use since you don't need the `[0]`, and IIRC it works for old-school class components too.

Having said that, I have no object to exporting all the properties explicitly again.  That's how it worked in Carbon 10.

**Comment by tay1orjones** [comment]
@Sam-Wool What do your type imports usually look like? Could you confirm that you're not able to import `ModalProps`? It's currently [exported](https://unpkg.com/browse/@carbon/react@1.56.0/es/components/Modal/Modal.d.ts). It isn't exported from the root but is in the Modal module.


```
// So I believe this won't work:
import { type ModalProps } from "@carbon/react";

// whereas this should work
import { type ModalProps } from "@carbon/react/es/components/Modal";
```

I don't know that we'll be able to export these from the root until everything is converted and the root `index.js` goes to `index.tsx` and can export types.

**Comment by tay1orjones** [comment]
> We've also noticed some components are missing an `index.ts` or `.d.ts` file - this has caused a similar issue when trying to import props belonging to that component. Below is a list of the components we've found with this issue:
> 
> * [ ]  CopyButton
> * [ ]  MultiSelect
> * [ ]  PasswordInput
> * [ ]  TileGroup

I've opened a new issue to contain this work:

* https://github.com/carbon-design-system/carbon/issues/16360

**Comment by mbarrer** [comment]
@tay1orjones so traditionally our type imports look like this:

```
import { type ModalProps } from "@carbon/react";
```

as you point out though, ModalProps is already exported from `@carbon/react/es/components/Modal/Modal`.

Importing ModalProps would actually look like this since we have to target the Modal.ts instead of the index.ts:

```
import { type ModalProps } from "@carbon/react/es/components/Modal/Modal";
```

ModalProps can be easily raised to the `@carbon/react` bucket if you exported it as well from the `/Modal/index.ts` bucket. Since the main index.ts of carbon uses the `export * from` pattern it will pick up those type exports and add them to the bucket. 


We've been working a lot this past week on moving things over to carbon11, writing ambient modules to help ease the transition and fill in the missing prop exports. The team was wondering what the expectation is for the end goal of the prop exports. Should we ultimately expect to be able to pull types from the main `@carbon/react` bucket or should we expect to grab typings from the component files directly?

**Comment by haschek** [comment]
The workarounds mentioned by @gillesdandrea and @wkeese may work to get type info for the transpiler but the comments are completely lost, no IDE or tool like Storybook can include that documentation anymore.

Also the import approach mentioned by @tay1orjones does not work in any case because there are still components without exported interfaces, e.g. `AccordionItem`.

So, let's hope we can get it soon directly from the root `@carbon/react`.

**Comment by tay1orjones** [comment]
@haschek we're tracking it in https://github.com/carbon-design-system/carbon/issues/16436
