### ISSUE TITLE
Figma Code Connect ☂️ 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#16273]
Research and test feasibility of using [Figma Code Connect](https://github.com/figma/code-connect/blob/main/cli/README.md) to link Carbon Figma and Carbon React for AI readiness.

Demo video https://www.youtube.com/watch?v=5GVNfbltrQg
Demo repo https://github.com/jake-figma/code-connect-demo

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/issues/16349
- [x] Figma Code Connect: Research Storybook integration
- [x] Research/Connect simple component (Button)
- [x] Research/Connect (Dropdown)
- [x] Research/Connect nested component (Accordion)
- [x] Research/Connect nested component (Tabs)
- [x] https://github.com/carbon-design-system/carbon/issues/16560
- [ ] https://github.com/carbon-design-system/carbon/issues/16561
- [ ] https://github.com/carbon-design-system/carbon/issues/16429
- [ ] https://github.com/carbon-design-system/carbon/issues/16526
- [ ] https://github.com/carbon-design-system/carbon/issues/16527
- [ ] #16815
```

### Audit/connect all components
Connect / attempt to connect all components. 
Document mismatch between Figma / code & create issues where appropriate.
Followup with Figma / create issues on needed functionality.

```[tasklist]
### Components
- [x] https://github.com/carbon-design-system/carbon/issues/16661
- [x] Code Connect : Breadcrumb
- [x] Code Connect : Button
- [x] Code Connect : Checkbox
- [x] Code Connect : Code snippet
- [x] Code Connect : Tabs
- [x] Code Connect : Notification
- [x] Code Connect : Link
- [ ] https://github.com/carbon-design-system/carbon/issues/16657
- [ ] https://github.com/carbon-design-system/carbon/issues/16663
- [ ] https://github.com/carbon-design-system/carbon/issues/16664
- [ ] https://github.com/carbon-design-system/carbon/issues/16686
- [ ] https://github.com/carbon-design-system/carbon/issues/16683
- [ ] https://github.com/carbon-design-system/carbon/issues/16682
- [ ] https://github.com/carbon-design-system/carbon/issues/16681
- [ ] https://github.com/carbon-design-system/carbon/issues/16680
- [ ] https://github.com/carbon-design-system/carbon/issues/16674
- [ ] https://github.com/carbon-design-system/carbon/issues/16656
- [ ] https://github.com/carbon-design-system/carbon/issues/16658
- [ ] https://github.com/carbon-design-system/carbon/issues/16659
- [ ] https://github.com/carbon-design-system/carbon/issues/16660
- [ ] https://github.com/carbon-design-system/carbon/issues/16662
- [ ] https://github.com/carbon-design-system/carbon/issues/16665
- [ ] https://github.com/carbon-design-system/carbon/issues/16666
- [ ] https://github.com/carbon-design-system/carbon/issues/16687
- [ ] https://github.com/carbon-design-system/carbon/issues/16685
- [ ] https://github.com/carbon-design-system/carbon/issues/16684
- [ ] https://github.com/carbon-design-system/carbon/issues/16679
- [ ] https://github.com/carbon-design-system/carbon/issues/16678
- [ ] https://github.com/carbon-design-system/carbon/issues/16677
- [ ] https://github.com/carbon-design-system/carbon/issues/16676
- [ ] https://github.com/carbon-design-system/carbon/issues/16675
- [ ] https://github.com/carbon-design-system/carbon/issues/16673
- [ ] https://github.com/carbon-design-system/carbon/issues/16672
- [ ] https://github.com/carbon-design-system/carbon/issues/16671
- [ ] https://github.com/carbon-design-system/carbon/issues/16670
- [ ] https://github.com/carbon-design-system/carbon/issues/16669
- [ ] https://github.com/carbon-design-system/carbon/issues/16667
- [ ] https://github.com/carbon-design-system/carbon/issues/16956
- [ ] https://github.com/carbon-design-system/carbon/issues/16955
- [ ] https://github.com/carbon-design-system/carbon/issues/16954
- [ ] https://github.com/carbon-design-system/carbon/issues/17044
- [ ] https://github.com/carbon-design-system/carbon/issues/17050
- [ ] https://github.com/carbon-design-system/carbon/issues/16668
- [ ] https://github.com/carbon-design-system/carbon/issues/17073
```

**Comment by alisonjoseph** [comment]
### Issues

#### Button
- No issues 

#### Dropdown / DropdownSkeleton
- DropdownSkeleton doesn't support helper text

#### Accordion / AccordionItem / AccordionSkeleton
- In Figma all properties are set on the AccordionItem component vs. the Accordion.
- AccordionSkeleton in code refers to an entire component, in Figma it is a state on one of the AccordionItems

**Comment by juanencalada** [comment]
Hey @alisonjoseph regarding this comment above

> DropdownSkeleton doesn't support helper text

Is that in Figma we are missing it, or it's not supported in code but we're showing it in Figma?

**Comment by juanencalada** [comment]
Hey @alisonjoseph regarding this comment above

> DropdownSkeleton doesn't support helper text

Is that in Figma we are missing it, or it's not supported in code but we're showing it in Figma?

**Comment by juanencalada** [comment]
Hey @alisonjoseph regarding this comment above:

> DropdownSkeleton doesn't support helper text

Is that in Figma we are missing it, or it's not supported in code but we're showing it in Figma?

**Comment by juanencalada** [comment]
Hey @alisonjoseph regarding this comment above:

> DropdownSkeleton doesn't support helper text

Is that in Figma we are missing it, or it's not supported in code but we're showing it in Figma?

**Comment by alisonjoseph** [comment]
@juanencalada I'm still pretty new to Figma, but was looking at seeing if there was a way to bring nested properties from children into their parent and found this. https://forum.figma.com/t/add-a-forward-props-property-on-parent-component-inherit-props-from-a-selected-child-component/27875/2 Would this work with the way things are built in Carbon?

**Comment by juanencalada** [comment]
Hey @alisonjoseph, yes this is possible and something we do in several components already. However, it happens for each nested component, so we don't do it in cases where we have lots of nested components like in an accordion or dropdown because it would make the properties panel really long and harder to navigate. Unfortunately, there's currently also no control over which nested props we want to surface, so it's all or nothing. Meaning, we might expose properties we don't want to expose. If for example we have an accordion with left aligned, and we exposed the props of all accordion items, the right align prop would be visible there too which would just be noise.

**Comment by alisonjoseph** [comment]
@juanencalada hmm, for Accordion specifically I think we would want most of the properties exposed. I suppose the ones that would be weird/confusing would be the state or titleText since those need to be set on the individual item. There should never be an instance where someone is right and left aligning items within the same Accordion.

**Comment by alisonjoseph** [comment]
@juanencalada another thing to keep in mind is that anything that changes or gets renamed in Figma will break Code Connect. It looks like sometime in the last few days Dropdown changed "Label text" to "Label" and that completely broke publishing. I was able to fix the error, however my sample Figma file with dropdown didn't update and code connect stopped working with an error that Label didn't exist when swapping to dev mode. Not sure how often changes like this happen?

**Comment by juanencalada** [comment]
Hey Alison, that makes sense and thanks for highlighting this! I don't think this happens too often. Most common would be around times when there are new feature releases or a component is getting updated for some reason.

This one in particular I had noticed the other day that the naming of the props wasn't matching how we name similar props in other components so that's probably what changed here.

I think something we could do is a full audit of the component props to ensure we have the consistency we want at least within Figma to minimize any breaking changes, as well communicate around release schedules to ensure component props are aligned across design and dev.

Something that comes to mind is I wonder if good feedback for Figma might be having some alias associated with the props so that if a prop name changes it's not entirely dependent on that to make a connection from the Figma side. Just a thought but might not be much there.

**Comment by alisonjoseph** [comment]
Closing, remaining work being tracked here https://github.com/carbon-design-system/carbon/issues/17606
