### ISSUE TITLE
Carbon v11 Coverage Figma Plugin Alpha ☂️

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon#16318]
### The problem
A recurring challenge is connecting a particular design to development. Some teams create custom coded elements instead of using Carbon code directly. 

### The solution
A custom Figma plugin that acts as a design linter, displaying the components and patterns used within a design and aiding with hand-off to development.

### Carbon contacts
* Eliad Moosavi (development) 
* Rich Kummer (design) 

```[tasklist]
### Preliminary tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/16550
- [ ] https://github.com/carbon-design-system/carbon/issues/16500
- [ ] https://github.com/carbon-design-system/carbon/issues/16499
- [ ] https://github.com/carbon-design-system/carbon/issues/16342
- [x] Identify meaningful information to surface in Figma
- [x] Identify product specs for testing
- [x] Identifying the Figma library origin to scope to correct kits
- [x] Can web components be leveraged in the plugin modal
```

## Phase 01: Core functionality

```[tasklist]
### Design
- [ ] https://github.com/carbon-design-system/carbon/issues/16986
- [ ] https://github.com/carbon-design-system/carbon/issues/17069
- [ ] https://github.com/carbon-design-system/carbon/issues/17299
- [ ] https://github.com/carbon-design-system/carbon/issues/17162
- [ ] https://github.com/carbon-design-system/carbon/issues/16692
- [ ] https://github.com/carbon-design-system/carbon/issues/17318
- [ ] https://github.com/carbon-design-system/carbon/issues/17343
- [ ] https://github.com/carbon-design-system/carbon/issues/17599
- [ ] https://github.com/carbon-design-system/carbon/issues/17635
- [ ] https://github.com/carbon-design-system/carbon/issues/17945
- [ ] https://github.com/carbon-design-system/carbon/issues/18013
- [ ] https://github.com/carbon-design-system/carbon/issues/18105
```

```[tasklist]
### Development
- [ ] https://github.com/carbon-design-system/carbon/issues/16549
- [ ] https://github.com/carbon-design-system/carbon/issues/16550
- [ ] https://github.com/carbon-design-system/carbon/issues/17161
- [ ] https://github.com/carbon-design-system/carbon/issues/17344
- [ ] https://github.com/carbon-design-system/carbon/issues/17068
- [ ] https://github.com/carbon-design-system/carbon/issues/17638
- [ ] https://github.com/carbon-design-system/carbon/issues/17636
- [ ] https://github.com/carbon-design-system/carbon/issues/17703
- [ ] https://github.com/carbon-design-system/carbon/issues/17704
- [ ] https://github.com/carbon-design-system/carbon/issues/17637
- [ ] https://github.com/carbon-design-system/carbon/issues/17947
```

**Comment by ljcarot** [comment]
@RichKummer Is this Epic ready to close or keep open into next year?

**Comment by RichKummer** [comment]
@ljcarot there's a few open items here, but I'll move them out of this epic and into 2025 and close this out.
