### ISSUE TITLE
Deprecate PopoverAlignment type values

### ISSUE THREAD

**Issue by 2nikhiltom** [carbon-design-system/carbon#16326]
```[tasklist]
### Tasks : part of <https://github.com/carbon-design-system/carbon/issues/16009>
- [x] Pull the old values out into their own type, mark it as deprecated via jsdoc
- [x] Update PopoverAlignment to be a union of the new values and the new deprecated type
- [x] Write a custom validator function for proptypes that pops a warning when a deprecated value is used
```
