### ISSUE TITLE
[CIOH] Educational deck: Carbon intro

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#16350]
**Task List**

- [x] Create a draft deck
- [x] Review with team
- [x] Fix changes
- [x] Publish and present
- [x] [Deck link ](https://ibm.box.com/s/uosiv1d5jag1102zs9rmsapja3f9z2iq)
