### ISSUE TITLE
[Bug]: Data table page-nav bug

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#16454]
### Package

carbon-components

### Package version

V11 All Themes Figma kit

### Description

**Current**
The Data table page-nav is supposed to look like this as per Carbon website guidelines
![Image](https://github.com/carbon-design-system/carbon/assets/159760598/67a59cc5-6152-4873-a3c5-e2878cb97bb5)

**Expected**
However the Figma file has the page-nav component slightly different, this needs to be consistent across documentation. 
![Image](https://github.com/carbon-design-system/carbon/assets/159760598/b4573a16-307c-4eb6-85a6-d9887decd5d7)

### Screenshots

_Shared above_

### Steps to reproduce

**Task list** 

- [ ] Add "Items per page" as a string component next to the page dropdown in the page-nav.
- [ ] Figma expert review
- [ ] Carbon expert review

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems
