### ISSUE TITLE
[CIOH] Educational deck: Contributing to carbon

### ISSUE THREAD

**Issue by benjamin-kurien** [carbon-design-system/carbon#16513]
```[tasklist]
### Tasks
- [x] understand rewards for contribution
- [x] understand differences between core & pal contributions
- [x] Create a deck to motivate contributions
- [x] Present deck for India Office Hours
```

**Comment by benjamin-kurien** [comment]
Deck built & presented, motivating the community of designers & developers in India to start contributing to Carbon.
