### ISSUE TITLE
[AI] Bring `slug` component to stable

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#16619]
We need to bring the "slug" component to stable so the product developers trust it. There are some tasks we need to complete first though. 

Notes from Jeff
> Nice, we should check if there is anything additional that needs to be added. Wondering if any test coverage needs to be added at all, like playwright tests, enable the flag and do additional VRT shots, etc.

```[tasklist]
### Dev Tasks
- [ ] #16618
- [ ] https://github.com/carbon-design-system/carbon/issues/16755
- [ ] https://github.com/carbon-design-system/carbon/issues/16756
- [ ] https://github.com/carbon-design-system/carbon/issues/16762
- [ ] [AI] Update airtable with new status
```

```[tasklist]
### Design Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/16757
- [ ] https://github.com/carbon-design-system/carbon/issues/16766
```
