### ISSUE TITLE
Floating UI: Close out related issues listed in the umbrella by writing an example stackblitz proving the issue is fixed and closing the issue linking to the umbrella issue

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#16698]
```[tasklist]
- [x] ContainedList in Popover @tay1orjones
- [ ] https://github.com/carbon-design-system/carbon/issues/16982
- [x] DataTable (Tooltip, OverflowMenu) @riddhybansal
- [x] DataTable (DefinitionTooltip with Sticky Header) @guidari
```

**Comment by preetibansalui** [comment]
> @preetibansalui this your final piece of this dependent on #16879 ?

Yes @tay1orjones, I have raised a PR for the same. Will take detectOverflow thing as a saperate task.
