### ISSUE TITLE
Communication components ☂️

### ISSUE THREAD

**Issue by benjamin-kurien** [carbon-design-system/carbon#16703]
### User story

Evaluate and improve communication components within carbon

### What are communication components?

Communication components include components that help the product/business communicate with their users by providing information, collecting data through various inputs, and providing the necessary feedback. 

1. Information components exist on the software by default and are essential for its function. They provide data to the user that help them engage with the platform and take necessary actions. These include components like data tables, cards, tiles, lists, accordions etc. 
2. Input components help to collect data from the user at various stages and often feeds into the information components. These include components like text input fields, dropdown, etc.
3. Feedback components are additional information provided realtime by the software to the user -triggered by either system or user action. These components are not crucial for the functioning of the software - but play an important role in improving its experience.

--

(The other primary classification of components in DS include Navigation components & Action components)

```[tasklist]
### Feedback components
- [ ] https://github.com/carbon-design-system/carbon/issues/16708
- [ ] https://github.com/carbon-design-system/carbon/issues/16220
- [ ] https://github.com/carbon-design-system/carbon/issues/16704
- [ ] https://github.com/carbon-design-system/carbon/issues/16705
- [ ] https://github.com/carbon-design-system/carbon/issues/16706
```

**Comment by benjamin-kurien** [comment]
This umbrella work-stream helped provide clarity to the various communication components within the design system and how they could be classified in the future.
