### ISSUE TITLE
Upgrade TypeScript to v5.7 🟦 

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#16827]
### Problem

Carbon packages are still using Typescript 4, which should be upgraded to Typescript 5.

### References

![image (10)](https://github.com/carbon-design-system/carbon/assets/15822070/3d3721fe-10fb-465a-a08c-180b5bafe31c)

Based on data provide by IBM Telemetry, a majority of Carbon consumers are using TS5.x, which means, we should follow suit.

### Solution

Upgrade relevant Carbon packages to use Typescript 5 and fix any build/compilation errors that result from it.

### Tasks 
- [x] `typescript-config-carbon`
- [x] `@carbon/utilities`
- [x] `@carbon/utilities-react`
- [x] bump affected packages minor version
