### ISSUE TITLE
Vertical Tab variant

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon#16853]
Add new variant to tabs component.

PLG teams need a new tab variant for their orientation flows. Since this is a general update, this will live in Core components instead of a PAL. 

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/16297
- [ ] https://github.com/carbon-design-system/carbon/issues/16305
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/841
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4160
```
