### ISSUE TITLE
[CIOH] Identify and automate repetitive tasks

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#16889]
**Objective:** To streamline our workflow and improve efficiency, we need to identify tasks that can be automated and determine the best methods for automation.

## Task lists 
(tasks that can be automated)

- [x] Book a meeting room (Alina)
- [x] Task rotation workflow (Kritvi)
- [ ] Slack Automated Message Setup (Kritvi)
  > 1. Change #carbon-user-india to public to allow the Slack bot to send invitations, as it currently cannot send invites in a private channel.
  > 2. Set up automated messages for:
  >     - Invitation + Agenda forms
  >     - Playback updates
  > 3. Determine how to connect Slack Block Kit with Slack automation.
