### ISSUE TITLE
Carbon coverage: Plugin user testing prep

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon#16986]
[Updated Carbon plugin proto-functional spec](https://www.figma.com/design/KmqzQ2qSP9VZcOugrE9YyP/Carbon-coverage-plugin-explo?node-id=624-20294&t=h7ruD0veKJdxDKvp-1)

[Example v11 dashboard design for testing](https://www.figma.com/design/TJtxwwUpQjlKN7wehCeCYf/Sample-v11-dashboard?node-id=14-119998&t=nNMK2BWX5fNSjHbX-1)

```[tasklist]
### Tasks
- [x] Prepare user testing background
- [x] Prepare user testing questions
- [x] Create design for test version of plugin
- [x] Create v11 dashboard for testing
```

**Comment by RichKummer** [comment]
## Mid-fi to code update 07/31/24

- We could weigh the different issues for the percentage version, adjusting the score based on how important the issue is. For example, component issues might be considered higher priority and have a higher weight to the core (4 pts) versus effects which are lower priority (1 pt).
