### ISSUE TITLE
Floating UI: Memoize problematic downshift prop getters to prevent infinite loops

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17007]
There's a longstanding interop issue between floating ui and downshift where in certain cases when setting a `ref` an infinite loop can happen causing the component to crash.

The solution is to memoize the result of downshift's `getMenuProps()`. We've already had to do this for two components, we should expand this solution out to all the rest of the downshift components.

```[tasklist]
- [ ] https://github.com/carbon-design-system/carbon/pull/16866
- [ ] https://github.com/carbon-design-system/carbon/pull/17002
- [ ] https://github.com/carbon-design-system/carbon/issues/17020
- [ ] https://github.com/carbon-design-system/carbon/issues/17021
```
