### ISSUE TITLE
Carbon for AI Wave 4☔ 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#17037]
This is a working issue for tracking the next issues for the Carbon for AI workstream. 

### Add `with AI Label` to the following components
Note: Issues for design spec already created, see sub-issues. We'll need dev, docs and kit issues later for these tasks.

- Code snippet
- Tree view 
- Toggle 
- File uploader 
- Content Switcher 
- Tabs 
- Accordion

### Other bugs or enhancements
- [ ] https://github.com/carbon-design-system/carbon/issues/17081
- [x] https://github.com/carbon-design-system/carbon/issues/17697
- [ ] [AI Label] Design responsive and overflow behavior for explainability popover
- [ ] [AI Label] Add tooltip on hover [See Slack thread](https://ibm-studios.slack.com/archives/C07RV4MPJNL/p1743601956745019)
- [ ] [AI Label] Determine if we need to make an icon-only button variant [See Slack thread](https://ibm-studios.slack.com/archives/C07RV4MPJNL/p1743601956745019)

**Comment by heinsj** [comment]
Create Figma component / spec for accordion with AI theme. We are using the accordion to show AI recommendations so that they can easily be expanded or collapsed in the UI.
