### ISSUE TITLE
[ Structured List ] Remove flush states from selectable variant with background layer

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#17030]
### Package

@carbon/react

### Package version

1.62.1

### React version

18.2.0

### Tasks:
The flush states in the Structured List for Selectable variant need to be removed from:

- [ ] [With background layer](https://deploy-preview-16789--v11-carbon-react.netlify.app/?path=/story/components-structuredlist--with-background-layer)
   > ![image](https://github.com/user-attachments/assets/c614fd04-663f-43b2-ae75-44fe99e33f4d)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-structuredlist--with-background-layer

### Steps to reproduce

-

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems
