### ISSUE TITLE
[Status indicators] Explore color tokens for status icons and shapes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#17117]
## Acceptance criteria
- After determining the name of the status icons and shapes, we need to explore if we should create new color tokens for them. We also need to add a color token for inner fills (white and black) for a11y reasons.

There are three different ways we could approach this and we need to explore them in this issue:
- **Option 1:** Keep the existing color tokens
- **Option 2:** Create new color tokens on the component level
- **Option 3:** Create new support tokens

----

### Tasks

- [x] Explore the three different color token options. [Figma file](https://www.figma.com/design/lkFSmkmHSZKk3cO5oBUvJ8/Status-Indicators-(Thy)?node-id=471-13183&t=sXYOjjPNvWmSjD6J-4)
- [x] Playback exploration to team on the different options. (Anna and Taylor)
- [x] Finalize one direction to move forward with.

**Comment by thyhmdo** [comment]
Suggested by Anna G.

> Making these names more generic since most categories have multiple statuses is not very semantic, but it could help lessen confusion around the name itself by simply naming them by the color

This generic direction could be flexible for both Status and Shape indicators 

![image](https://github.com/user-attachments/assets/d0fe298d-c2f8-4e0a-859d-95b511da0f7c)

**Comment by laurenmrice** [comment]
@thyhmdo Awesome!
