### ISSUE TITLE
[Badge indicator] Create specs for dot and number badges, pairing with icons

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#17121]
## Acceptance criteria
Create design specs for the dot and number badges, pairing with icons.

----

### Tasks
- [x] Audit [Badge notification on Sustainability ](https://pages.github.ibm.com/ai-applications/design/components/notification-badge/usage)
- [x] Document specs in our Figma file 
- [x] Playback to the team
- [x] Update and add it here 
- [x] Review with Diana S. and the Carbon team

**Comment by thyhmdo** [comment]
![Image](https://github.com/user-attachments/assets/ece8ad50-e88e-4271-89a2-24eca11ad5cd)

**Comment by thyhmdo** [comment]
Effort: changed 3 to 5 because of the Review
