### ISSUE TITLE
Inline loading: Updating the text size

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#17134]
### Problem
There is inconsistency in inline loading text size in two places:
- [Inline loading in this Button group](https://react.carbondesignsystem.com/?path=/story/components-inlineloading--ux-example) example has the 12px text.
- [Inline loading in the Modal ](https://react.carbondesignsystem.com/?path=/story/components-modal--with-inline-loading)has the 14px text.

----

### Solution 
They need to be the same at 14px or `body-compact-01`

```[tasklist]
### Tasks
- [x] Update Figma https://github.com/carbon-design-system/carbon-design-kit/issues/746
- [x] Update the Storybook [here](https://react.carbondesignsystem.com/?path=/story/components-inlineloading--playground)
- [ ] Update the Website [here](https://carbondesignsystem.com/components/inline-loading/style)
```
