### ISSUE TITLE
Carbon coverage: User testing rd 2

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon#17162]
Plan and test a prototype of the Carbon coverage Figma plugin with volunteer designers across IBM.

**Volunteers:**
- [x]  Laura Marshall
- [x]  Jacki Walkin
- [x]  Meme Betadam
- [x]  Shaun Lynch
- [x]  Tyler Watson
- [ ]  Luke Firth *

```[tasklist]
### Tasks
- [x] Schedule discussions
- [x] Plan user testing sessions
- [x] Testing with prototype
- [x] Package functional prototype and send to slack channel/volunteers
- [x] Send local Figma plugin quickstart guide
- [x] Refine design specs based on feedback
- [x] Schedule installation meeting (30min)
```

**Comment by RichKummer** [comment]
## Session 03: Jacki Wakin, Meme Betadam, Shaun Lynch, Tyler Watson

[Recording](https://ibm.enterprise.slack.com/archives/C07F0RESYDB)

### Key takeaways
- TBD

### Considerations
- [ ] TBD
