### ISSUE TITLE
Away mission (Envizi)

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#17177]
## Scope and Deliverables
**References**
- Keynote presentation brief: https://ibm.ent.box.com/file/1622029439138?s=t67pay13a126dm7cj6ktpkqimsiz8wt0
- Figma file: https://www.figma.com/files/902667414815738345/project/96278755?fuid=986627824895103999

### Goal
Help Envizi explore visuals while integrating Carbon and other design systems' UI, focusing on:
- hierarchy
- data table
- dashboard
- others: detail page and form

```[tasklist]
## Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/17179
- [x] https://github.com/carbon-design-system/carbon/issues/17275
- [x] Playback visual audit + 1st visual explorations
- [ ] https://github.com/carbon-design-system/carbon/issues/17341
```
