### ISSUE TITLE
Update `@carbon/cli` to ESM

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17194]
[`@carbon/cli`](https://github.com/carbon-design-system/carbon/tree/main/packages/cli) houses a broad collection of commands used throughout the repository. This package needs to be updated to ESM so we can take updates for it's various dependencies. Many are moving to ESM-only versions leaving us unable to update. Once example is [`execa`](https://github.com/sindresorhus/execa/releases/tag/v6.0.0).

### Commands

Many commands within the package are used currently within the repo. Things like generating our changelogs, generating sass docs, running checks in ci, etc. Some commands are intended to be external-facing, such as `contribute`. It aimed to assist new contributors to Carbon with getting started, such as setting up their fork and other tasks. Some are no longer used, like `publish`.

### Tasks
- [ ] Research and separate commands in 3 categories: Currently used by the repo, external-facing, and unused. 
- [ ] Determine which commands no longer provide value, and delete them
- [ ] Update the rest of the package to ESM
- [ ] We **must** publish this as a major version bump due to the breaking changes. This can be done off-cycle from our main release schedule. Weekly downloads are only ~<500 on npm.

### Resources

* [The official ESM guide](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext)
* [Sindresorhus' FAQ](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)
