### ISSUE TITLE
[Status indicators] Playback with PAL and Core to align

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#17289]
## Acceptance criteria

Playback to people on the PAL and Core teams the current work and to align on how we want to make a plan to transfer and consolidate the following:   
- Website documentation
- Code
- Figma assets

---

### Tasks

- [x] Playback to team
- [x] Align on a decision
- [x] Create a list of next steps
 
---

### Next steps
**Design**
- Figure out color tokens.
- Finish all design specs for the following to give to dev:
   - Status indicators
   - Status shapes
   - Badge indicators
   - Text + indicators

**Dev**
- Devs will take the design specs and figure out an initial proposal of how this could be implemented. We decided it would be best to make this flexible enough if we ever need to add more status indicators and shapes in the future. 

**Cross-discipline** 
- Have a call with devs to figure out how this will appear and function in React and align on a direction.

**Comment by laurenmrice** [comment]
### Next steps

**Design**
- Figure out color tokens.
- Finish all design specs for the following to give to dev:
  - Status indicators
  - Status shapes
  - Badge indicators
  - Text + indicators

**Dev**
- Devs will take the design specs and figure out an initial proposal of how this could be implemented. We decided it would be best to make this flexible enough if we ever need to add more status indicators and shapes in the future.

**Cross-discipline**
- Have a call with devs to figure out how this will appear and function in React and align on a direction.
