### ISSUE TITLE
Carbon coverage: Installation session

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon#17299]
To better understand designer needs with the Carbon coverage plugin, we want to run a feedback session with designers. Before then, we want to make sure everyone is able to install and begin using the plugin locally in Figma.

```[tasklist]
### Tasks
- [x] Schedule Installation session
- [x] Run installation session with designers
- [x] Schedule feedback session
```
