### ISSUE TITLE
[Feature]: Data table interactive cell has inconsistent guidance around disabled states.

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#17307]
### Description

**Code functionality** 
As per [code](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--disable-select-row&globals=viewport:basic), if a row is selectable and the feature needs to be disabled, only the button is disabled, the cell text is readable. 
[Note: The code attached here is from C4IP because Carbon data table doesn't have a "disable" prop yet.]

![image](https://github.com/user-attachments/assets/d205c557-5c2b-49fd-9abe-673585577a39)

<br>

**Usage guidance**
In our [docs](https://carbondesignsystem.com/components/data-table/style/#row), when we show disabled state we show both the button and the text disabled (entire cell is disabled)
![image](https://github.com/user-attachments/assets/ee055e06-db4d-466b-ab86-af51e346eab1)

<br>

**Thoughts**
- Both use-cases can be valid in their own ways, however disabling cell text makes it completely inaccessible from a color contrast perspective. 
- If the selectable checkbox is disabled and cell text has `read-only` token colours then it solves both purposes, inability to interact with the checkbox but still readable and accessible. 

<br>

**Expectations**
- Add the disabled state for row / cell in the data table component. 
- Update docs to reflect this (just the button/s should be disabled, not the text) (if a disabled styling is required for text consider using read-only token color)
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

```[tasklist]
### Tasks
- [ ] DataTable: Selection - Implement a story with `TableSelectRow` disabled
- [ ] DataTable: Selection - Update website
- [ ] DataTable: Selection - Figma kit 
```

**Comment by sstrubberg** [comment]
Expose this as a story

![Image](https://github.com/user-attachments/assets/ee4ad241-fc24-4acc-a1cb-b4a5f15110ee)

Make a website issue to edit the images, docs, and in figma.
