### ISSUE TITLE
Figma Code Connect: Connect Carbon Web Components

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#17459]
Connect all web components with Figma using code connect 
https://www.figma.com/code-connect-docs/

[Demo figma file](https://www.figma.com/design/NwXsMCCoMg1po4KK2oUK3o/Code-connect-demo---Carbon-Design-System?node-id=612-252440&m=dev) (to view all components)

### Components
- [x] Code Connect: Web Components - Accordion  
- [ ] Code Connect: Web Components - AI popover  
- [ ] Code Connect: Web Components - AI label  
- [ ] Code Connect: Web Components - Checkbox  
- [ ] Code Connect: Web Components - Code snippet  
- [ ] Code Connect: Web Components - Contained list  
- [ ] Code Connect: Web Components - Content switcher  
- [ ] Code Connect: Web Components - DataTable  
- [ ] Code Connect: Web Components - Date picker  
- [ ] Code Connect: Web Components - Dropdown  
- [ ] Code Connect: Web Components - Combobox  
- [ ] Code Connect: Web Components - Multiselect  
- [ ] Code Connect: Web Components - File uploader  
- [ ] Code Connect: Web Components - Time picker  
- [ ] Code Connect: Web Components - Loading  
- [ ] Code Connect: Web Components - Menu  
- [ ] Code Connect: Web Components - Menu button  
- [ ] Code Connect: Web Components - Modal  
- [ ] Code Connect: Web Components - Notification  
- [ ] Code Connect: Web Components - Number input  
- [ ] Code Connect: Web Components - Pagination  
- [ ] Code Connect: Web Components - Password input  
- [ ] Code Connect: Web Components - Popover  
- [ ] Code Connect: Web Components - Progress bar  
- [ ] Code Connect: Web Components - Progress indicator  
- [ ] Code Connect: Web Components - Radio button  
- [ ] Code Connect: Web Components - Search  
- [ ] Code Connect: Web Components - Select  
- [ ] Code Connect: Web Components - Slider  
- [ ] Code Connect: Web Components - Structured list  
- [ ] Code Connect: Web Components - Tabs  
- [ ] Code Connect: Web Components - Tag  
- [ ] Code Connect: Web Components - Textarea  
- [ ] Code Connect: Web Components - Text input  
- [ ] Code Connect: Web Components - Tile  
- [ ] Code Connect: Web Components - Treeview  
- [ ] Code Connect: Web Components - Combo button  
- [ ] Code Connect: Web Components - Overflow menu  
- [ ] Code Connect: Web Components - UI Shell  
- [ ] Code Connect: Web Components - Form  
- [ ] Code Connect: Web Components - Vertical tabs

**Comment by tay1orjones** [comment]
Aiming to tackle this once the parity work is complete https://github.com/carbon-design-system/carbon/issues/17326
