### ISSUE TITLE
Component Design Audit v1.1

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1749]
## Date Picker

- Update icons in calendar

![image](https://user-images.githubusercontent.com/3901764/52445927-21db8e80-2af2-11e9-9ceb-caac117604da.png)

## Time Picker

- text-03 for placeholder text

![image](https://user-images.githubusercontent.com/3901764/52445592-218ec380-2af1-11e9-8d76-ec1efe393e01.png)

- Space should be 2px

![image](https://user-images.githubusercontent.com/3901764/52445688-6b77a980-2af1-11e9-8fdf-89f3dbdf5acc.png)

- Should be 16px on both sides of chevron

![image](https://user-images.githubusercontent.com/3901764/52445799-bdb8ca80-2af1-11e9-9ee6-6d6357dcc239.png)

### Light

- should be using field-02 color

![image](https://user-images.githubusercontent.com/3901764/52445820-d6c17b80-2af1-11e9-99cd-dae8af6a17a9.png)

## Dropdown

- Update padding to 16px on left/right, vertically centered text

![image](https://user-images.githubusercontent.com/3901764/52446043-75e67300-2af2-11e9-9d01-d500a82dbcd8.png)

- Needs hover state

- Rulers need to not show on hover

![image](https://user-images.githubusercontent.com/3901764/52446137-bc3bd200-2af2-11e9-8735-1a15349218a6.png)

- When open, label should change color to match spec

![image](https://user-images.githubusercontent.com/3901764/52446258-1177e380-2af3-11e9-9ca5-812ac9cd17b3.png)

- focus outline should be against the sides of the menu

![image](https://user-images.githubusercontent.com/3901764/52446492-cf9b6d00-2af3-11e9-99ab-fe32253c7af6.png)

- remove bottom margin from label when helper text is present

![image](https://user-images.githubusercontent.com/3901764/52447059-51d86100-2af5-11e9-9662-4f64dd381a5b.png)

- should return back to field-01 when not hovered

![image](https://user-images.githubusercontent.com/3901764/52447102-6ddc0280-2af5-11e9-8043-57664b4b88d8.png)

- should keep field-01 rule when open

![image](https://user-images.githubusercontent.com/3901764/52447118-77656a80-2af5-11e9-9378-051fb8f28810.png)

- border bottom color should persist (gray-20, not gray-50) ui-03

![image](https://user-images.githubusercontent.com/3901764/52447192-af6cad80-2af5-11e9-9a9d-8d4bea100a1b.png)

- show selected state (selected-ui token)

![image](https://user-images.githubusercontent.com/3901764/52447245-d1fec680-2af5-11e9-8e57-d13f147f7238.png)

- busted focus (react)

![image](https://user-images.githubusercontent.com/3901764/52447264-e93db400-2af5-11e9-9041-d4199b5395d1.png)

- change height to 320px(ish)

- look into shadow colors

### Inline

- No bar should be present

![image](https://user-images.githubusercontent.com/3901764/52447457-6537fc00-2af6-11e9-819e-12d3b9fe860f.png)

- should have hover state

- 15px on left-hand side

![image](https://user-images.githubusercontent.com/3901764/52447535-9a444e80-2af6-11e9-8ebf-0ff0fcc98c3a.png)

- height should be 32px

- text alignment between field and options

## Link

- Focus should be box

![image](https://user-images.githubusercontent.com/3901764/52447727-38d0af80-2af7-11e9-876d-a475be1f82ec.png)

- Should use visited color token

![image](https://user-images.githubusercontent.com/3901764/52447829-906f1b00-2af7-11e9-86b8-8917967ea0eb.png)

- link should not navigate if disabled

## Inline Loading

- Loading icon needs update

- Text should be 8px away from loader

![image](https://user-images.githubusercontent.com/3901764/52448124-7f72d980-2af8-11e9-8238-4eaef8861920.png)

- Weird issue with gray, it disappears after changing loading state

## Search

- Close icon should be icon-01

- background color on x on hover (hover-ui)

![image](https://user-images.githubusercontent.com/3901764/52448893-f90bc700-2afa-11e9-8563-496747d99626.png)

## Overflow Menu

- menu color should be ui-01

![image](https://user-images.githubusercontent.com/3901764/52449287-62400a00-2afc-11e9-846b-a50ff4f37e3f.png)

- menu options should overflow with ellipsis

![image](https://user-images.githubusercontent.com/3901764/52449358-a59a7880-2afc-11e9-8897-19f11f57c1fb.png)

- change to text-01 on hover (should be in dropdown too?), text should be text-02 (darken on hover)

![image](https://user-images.githubusercontent.com/3901764/52449406-e3979c80-2afc-11e9-9ea6-28a21b02e6d7.png)

## Radio Button

- Focus state on un-selected needs to not have black stroke

![image](https://user-images.githubusercontent.com/3901764/52449200-05445400-2afc-11e9-9b0a-21d8f27daf36.png)

- double-check that vertical has 8px of spacing between each

## Select

- Select should have hover state

## Tabs

- Update width of bottom portion of tab (border-bottom) to 3px

![image](https://user-images.githubusercontent.com/3901764/52448645-302da880-2afa-11e9-8438-3fd33503548a.png)

- 2px space between tabs (versus 1px)

- See if we can keep type alignment between tabs and content

## Tile

- square icon in corner

![image](https://user-images.githubusercontent.com/3901764/52449495-2bb6bf00-2afd-11e9-9dfa-786ee10c256c.png)

--

## Misc

- Change examples to sentence case

**Comment by shixiedesign** [comment]
👍 🌮

**Comment by asudoh** [comment]
* [x] Date picker https://github.com/IBM/carbon-components/issues/1788 https://github.com/IBM/carbon-components/pull/1789 (Refs: carbon-design-system/issue-tracking#67 carbon-design-system/issue-tracking#64)
* [x] Time picker https://github.com/IBM/carbon-components/issues/1790 https://github.com/IBM/carbon-components/pull/1791
* [x] Dropdown #1792 #1793
* [x] Link #1801 #1802 (Refs: #1263)
* [x] Inline loading (Refs: #1607) #1803 #1869
* [x] Search #1805 #1806
* [x] Overflow menu #1807 #1808 (Refs: carbon-design-system/issue-tracking#63)
* [x] Radio button #1810 #1811
* [x] Select #1821
* [x] Tabs #1838 #1839
* [ ] Tile

**Comment by emyarod** [comment]
@asudoh I will be updating your comment with links to PRs as I open them

**Comment by emyarod** [comment]
I think there needs to be clearer distinction between React component issues and vanilla component issues. It takes a nontrivial amount of time to make comparisons between the two implementations when it is ambiguous which variant the issues are referring to, especially for those who were not present during the auditing session

edit: some of the component issues may also be part of a larger issue (e.g. dropdown label bottom margins when helper text is present), but it's not entirely clear if this is meant to be specific to the component it is filed under or if it should be a library-wide change

some of the points reference the specs, while other points contradict the specs, so it is confusing and unclear as to which portions of the spec or this ticket can be referred to as the source of truth

**Comment by emyarod** [comment]
all comments addressed in https://github.com/IBM/carbon-components/issues/1749#issuecomment-461706343 or superseded by [Feb/Mar 2019 audits](https://github.com/IBM/carbon-components/milestone/14)
