### ISSUE TITLE
[IBM Carbon Design to Code] Plugin UX - Design + feedback 2

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#17604]
## Acceptance criteria

Partner with Will for IBM Carbon Design to Code plugin user experience
**Continuation of: https://github.com/carbon-design-system/carbon/issues/17372**

### Tasks
- [x] Incorporate feedback from the first playback to Will
- [x] Create the end to end user-flow (MVP, MDP)
- [x] Get feedback from designers
- [x] Get feedback from Will and designers
