### ISSUE TITLE
Carbon coverage: Detect detached component from v11 libraries

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon#17638]
One of the requests from the designer/developer cohort was to enable the plugin to call out detached components from the All themes v11 library.

We should add a specific issue type that surfaces detached v11 components so that designers and developers can view which design components have been detached.

**Tasks:**
- [ ] Add new logic to highlight detached v11 components
- [ ] Add new messaging for detached v11 components
- [ ] Test with cohort
