### ISSUE TITLE
[IBM Carbon Design to Code] Plugin UX - Design + feedback 3

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#17726]
## Acceptance criteria

Partner with Will for IBM Carbon Design to Code plugin user experience
**Continuation of: https://github.com/carbon-design-system/carbon/issues/17604**

### Tasks
- [x] Incorporate feedback from working session 1 and 2
- [x] Get feedback from designers
- [x] Create the end to end user-flow (MVP, MDP)
- [x] Get feedback from Will
