### ISSUE TITLE
[IBM Carbon Design to Code] Finalise full design and UX flow

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#17914]
## Acceptance criteria

Partner with Will for IBM Carbon Design to Code plugin user experience
**Consolidation of: https://github.com/carbon-design-system/carbon/issues/17372, https://github.com/carbon-design-system/carbon/issues/17604, https://github.com/carbon-design-system/carbon/issues/17726**

### Tasks
- [x] Design the full UX flow
- [x] Playback to designers
- [x] Playback to Will
- [x] Content introduction to Aubrey
- [x] Playback to Carbon and Accessibility teams
- [x] Incorporate feedback from the playbacks
