### ISSUE TITLE
[IBM Carbon Design to Code] Redlining and handover

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#18047]
## Acceptance criteria

Partner with Will for IBM Carbon Design to Code plugin user experience
**Continuation of: https://github.com/carbon-design-system/carbon/issues/17914**

### Tasks
- [x] Incorporate content and copy feedback from Aubrey
- [x] Playback to whole Mid-fi-code team lead by Charlie Hill
- [x] Redline and handover the full UX flow
