### ISSUE TITLE
[IBM Carbon Design to Code] Content review of the plugin support docs, and survey form

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#18060]
## Acceptance criteria

This issue focuses on the content review for the Plugin, Support docs and the Survey form

### Tasks
- [x] Content review for plugin
- [x] Content review for support docs
- [x] Content review for feedback survey form
