### ISSUE TITLE
Carbon v11 Coverage plugin Snapshot ☂️

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon#18141]
Follow on from #16318 

For the Carbon v11 Coverage Figma plugin, we identified an opportunity to display a snapshot of how covered a particular file or frame is for Carbon v11. The plugin would calculate and show a design which breaks down the coverage and follow up with individual issues.

## Phase 03: Snapshot 

```[tasklist]
### Future work
- [ ] https://github.com/carbon-design-system/carbon/issues/17078
- [ ] Carbon coverage plugin: Explore multiple elements in a single item
- [ ] Carbon coverage plugin: Providing specific suggestions on how to bring design into Carbon compliance
- [ ] Carbon coverage plugin: AI enhancement to automatically suggest and complete updates
- [ ] Carbon coverage plugin: Consider mapping links from plugin components to documentation/Storybook/repo.
- [ ] Carbon coverage plugin: Explore highlighting the corresponding issue element on hover
- [ ] Carbon coverage plugin: Add color theming based on Figma settings
- [ ] Carbon coverage plugin: Providing additional help on grid usage
```
