### ISSUE TITLE
[IBM Carbon Design to Code] Development support

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#18184]
## Acceptance criteria

Partner with Will for IBM Carbon Design to Code plugin user experience

### Tasks
- [x] Incorporate UX and content feedback from Charlie
- [x] Stress test UX flows
- [ ] Stress test components
