### ISSUE TITLE
Design tooling Tutorial and Template file for UI Shell

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2337]
### Tasks:
- [x] Add to design kit:
   - [x] White theme
   - [x] Gray 10 theme
   - [x] Gray 90 theme
   - [x] Gray 100 theme
------------------------
- [x] Create template file (Sketch)

**Comment by chrisconnors-ibm** [comment]
silly stale[bot]

**Comment by aagonzales** [comment]
**Design Kit symbol assets:**
- Assets will be added to the kit on Monday 6/3/19 as part of the 10.3 release.
- ~Only white and Gray 100 theme files will have the UI Shell for now. (not sure how we're handling/recommending shell to be used with themes. The Gray 100 and White are currently the recommended two colors shell colors).~
- UI Shell has been added to all 4 theme kits
- **Sketch files**: https://ibm.box.com/s/gam3oo0wnvxcwdgaot3coa972atham67

**To do:**
- [x] Shell responsive template file

**Comment by aagonzales** [comment]
Template file is here: https://ibm.box.com/s/eaqr4hrm173xnn9m0duofkb792jwxysb
(will be added to Sketch cloud and on the website with release)

**Comment by aagonzales** [comment]
Side rail symbols are here and will be added day of to the kits:
https://ibm.box.com/s/yeu4q1t4vu5pphc0e4z8dfw5xbeykp71
