### ISSUE TITLE
[Component Architecture] 10.3 Iteration Plan 

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2376]
# 10.3 Iteration Plan

This plan captures our work on the Component Architecture project for **May**. This work will introduce updates to the underlying development process, from introducing a new structure to the system through a monorepo to tackling component testing through a formal specification.

## Endgame

- **May 27th, 2019**: Code freeze for the endgame
- **May 31st, 2019**: Endgame done

The endgame details for this iteration are tracked in TBD.

## Component Anatomy

This is a continued effort originating from the [carbon-spec](https://github.com/carbon-design-system/carbon-spec) repo.

Our **primary goal** is to abstract component artifacts to new carbon specification packages that each component implementation consumes. The focus is on a select few components initially (e.g. button, checkbox, icon, modal).

- [x] Create component spec packages #2389
- [ ] Determine spec directory structure #2390
- [ ] Generate README.md via sync script #2391
- [ ] Create demo objects #2392

Our **stretch goal** is to apply the new component anatomy to all components.

## Component Testing

Also originating from the [carbon-spec](https://github.com/carbon-design-system/carbon-spec) repo, this effort is to have the component specification packages include tests that can be consumed by each component implementation to provide a framework to achieve standardization.

Our **primary goal** is to create test case and test runner structure that can be used by vanilla and React components. The focus is on a select few components initially (e.g. button, checkbox, icon, modal).

- [ ] Create spec test format #2393
- [ ] Run spec tests in vanilla components #2394
- [ ] Run spec tests in React components #2395

Our **stretch goal** is to have the specification tests consumable by Angular and Vue components.

Our **ideal goal** is to provide a specification test reporting framework so we can generate a component status page to the likes of https://github.com/carbon-design-system/carbon-spec/pull/13.

## Monorepo

This is a new effort to update the Carbon Design System ecosystem to a monorepo structure following our [RFC](https://github.com/carbon-design-system/rfcs/pull/5). 

Our **primary goal** is to introduce this setup following phase 1:

- [x] Setup `carbon-components` as a monorepo #2382
- [x] Introduce `carbon-components-react` to the monorepo #2383
- [x] Introduce `carbon-elements` to the monorepo #2385
- [x] Migrate over issues from projects to the `carbon` repo #2386
- [ ] Write documentation and guidelines around the monorepo #2387

Our **stretch goal** would include beginning to create per-component packages. This work would include:

- Separating out components from `carbon-components` into discrete packages
  - `carbon-components/src/components/button` becomes `@carbon/button`
  - Includes introduction of testing to prevent regressions
  - Includes work to figure out inline strategy based on existing elements work
- Separating out components from `carbon-components-react` into discrete packages
  - `carbon-components-react/src/components/Button` becomes `@carbon/button-react`
- Consolidate configs to top-level, where appropriate. This includes:
  - Test setup (Jest)
  - Linting (ESLint, Stylelint)
  - Formatting (prettier)
- [x] Setup Netlify previews per-package

Our **ideal goal** would be all of the above in addition to:

- Setting up a `@carbon/cli` internal project to help with component development
  - One could type `yarn develop <component-name>` and the development environment is dynamically created for them
  - This setup should prioritize fast storybook rebuilds while still allowing us to publish a storybook for all components

---

## Deferred Items

- Creating component specification tests for all components

**Comment by joshblack** [comment]
Logistical items:

- [ ] Update migration guide links for:
  - [ ] `carbon-components`
  - [ ] `carbon-components-react`
  - [ ] `carbon-elements`
- [ ] Move over issues from the following repos:
  - [ ] `carbon-components-react`
  - [ ] `carbon-elements`
- [ ] Move over, or refactor, PRs from the following repos:
  - [ ] `carbon-components`
  - [ ] `carbon-components-react`
  - [ ] `carbon-elements`
- [ ] Update Netlify deployments for the following projects:
  - [ ] `carbon-components`
  - [ ] `carbon-components-react`
  - [ ] `carbon-elements`
- [ ] Release comms
  - [ ] Draft medium post discussing move
  - [ ] Draft Slack post to share
  - [ ] Newsletter?
- [ ] GitHub files
  - [ ] Update issue template(s) to reflect new repo structure and advise on how to write an issue
  - [ ] Update `CONTRIBUTING.md` to reflect new steps to contribute
- [ ] Project
  - [ ] Add top-level `ci-check` command
  - [ ] Pull out test runner (jest)
  - [ ] Pull out prettier config
  - [ ] Pull out ESLint into own package(s)
  - [ ] Pull over stylelint from Elements
  - [ ] Clean-up peer dependency warnings
  - [ ] Consolidate README generation between `carbon-components`, `carbon-components-react` and Carbon Elements
- [ ] Archive the following repos:
  - [ ] `carbon-components-react`
  - [ ] `carbon-elements`


Open questions:

- Should we move GitHub releases in projects over to carbon-components?
