### ISSUE TITLE
[v10 Enhancements] 10.3 Milestone Plan 

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon#2416]
# 10.3 Milestone plan

This plan captures our work on the v10 Enhancements project for **May**. Includes work toward resolving technical debt and fixes found by internal team members. 

## Dates

- **May 27th, 2019**: Code freeze for v10 Enhancements Milestone 1 
- **May 31st, 2019**: v10 Enhancements Milestone 1 complete for 10.3 release.

## Issues

All issues tracked in [project board](https://github.com/orgs/carbon-design-system/projects/8)

**High-priority**
- [x] ~~https://github.com/carbon-design-system/carbon-components/issues/2438 Generate elements sketch library from carbon-elements~~
  - ~~**NOTE**: This depends on the completion level/feasibility of the earlier work. The milestone team's recent look at the earlier work revealed some blockers that may make the idea not feasible, and/or the effort of work goes beyond a single milestone~~ (moved to Component Architecture)

- [x] [Button] Add 40px height option aka "field button" https://github.com/carbon-design-system/carbon/issues/2365
- [x] [Button, sketch kit] https://github.com/carbon-design-system/carbon/issues/2752
- [ ] ~~[Button, website] Height/sizing guidance https://github.com/carbon-design-system/carbon-website/issues/1700~~ deferred to next release since it's a bigger issue, and not a stop ship for 40px button

- [x] [Button] Danger button accessibility issues on Gray 90/100 themes (design fix issue) https://github.com/carbon-design-system/carbon/issues/2364

- [ ] [DataTable] sticky header https://github.com/carbon-design-system/carbon/issues/2862

- [x] [Text input] Add character limit/counter https://github.com/carbon-design-system/carbon/issues/1672
- [x] [Text input, sketch kit] https://github.com/carbon-design-system/carbon/issues/2750
- [x] [Text input, website] https://github.com/carbon-design-system/carbon-website/issues/1477

- [x] Add Orange and Yellow to clr file for color palette https://github.com/carbon-design-system/carbon-design-kit/issues/98
- [x] Make clr file available on Carbon website https://github.com/carbon-design-system/carbon-website/issues/1624

**Bonus-if-done issues**

- [x] [Data table] Add option to render Overflow visible by default https://github.com/carbon-design-system/carbon/issues/1156
- [ ] [Data table, sketch kit] Add persistent overflow https://github.com/carbon-design-system/carbon/issues/2770
- [x] [Data table, website] Add guidance on when to turn on persistent overflow, issue https://github.com/carbon-design-system/carbon-website/issues/1659

- [x] [Data table] Expand all for tables https://github.com/carbon-design-system/carbon/issues/679
- [x] [Data table, sketch kit] Expand all https://github.com/carbon-design-system/carbon/issues/2832
- [x] [Data table, website] Expand all https://github.com/carbon-design-system/carbon-website/issues/1659

- [ ] [Text input] Read only variant https://github.com/carbon-design-system/carbon/issues/2177
- [ ] [Text input, sketch kit] Read only variant TBD
- [ ] [Text input, website] Read only variant TBD

- [x] [Multiselect] design feedback https://github.com/carbon-design-system/carbon/issues/2399
- [x] [Multiselect, design kit] https://github.com/carbon-design-system/carbon/issues/2463

- [x] [Tooltip] Support left/right tooltip positioning https://github.com/carbon-design-system/carbon/issues/2678
- [x] [Tooltip] Refactor and cleanup https://github.com/carbon-design-system/carbon/issues/2748
- [x] [Tooltip, design kit] Design kit update issue for #2678 https://github.com/carbon-design-system/carbon/issues/2768
- [x] [Tooltip, website] Content issue to update **usage** guidance https://github.com/carbon-design-system/carbon-website/issues/1640

- [x] [Modal] 1 button should take up 100% width https://github.com/carbon-design-system/carbon/issues/2325
- [x] [Modal, website] Add guidance to 1-3 button usage & component width https://github.com/carbon-design-system/carbon-website/issues/1695
- [ ] [Modal, sketch kit] Add 1 button modal symbol to sketch kit https://github.com/carbon-design-system/carbon/issues/2910

- [ ] [File uploader] Drag and drop https://github.com/carbon-design-system/carbon/issues/2288
- [ ] [File uploader, sketch kit] Add drag&drop file uploader symbol, issue TBD
- [ ] [File uploader, website] Usage documentation, issue TBD

- [x] [Icon package] Add not-editable icon https://github.com/carbon-design-system/carbon/issues/2708 (a dependency for #2177)
- [ ] implement token for accessible border width #2437
- [x] Add skeleton-ui token https://github.com/carbon-design-system/carbon/issues/1824
- [ ] Explore strategies for enabling fully controlled components https://github.com/carbon-design-system/carbon/issues/2489

**Non-white theme related**

- [x] [Notification] Change to default to high contrast https://github.com/carbon-design-system/carbon/issues/2354
- [ ] [Notification, website] Update images https://github.com/carbon-design-system/carbon/issues/2926
- [x] [Notification, sketch kit] Kit already have the correct High contrast styling symbol

- [ ] [Notification, design] Secondary styling spec https://github.com/carbon-design-system/carbon/issues/2927
- [ ] [Notification, code] Low contrast style fix to spec, issue TBD
- [ ] [Notification, website] issue TBD
- [ ] [Notification, sketch kit] issue TBD

- [x] [Color] Accessibility fix for 60s grade colors https://github.com/carbon-design-system/carbon/issues/2729
- [x] Add $invert-support color tokens https://github.com/carbon-design-system/carbon/issues/2684 (dependency for #2729)
- [x] Update Color>Usage & Theme page with new tokens https://github.com/carbon-design-system/carbon-website/issues/1686

---

## Deferred Items

Issues filed under the purview of this project, but which need to be deferred to a later workstream, can be tracked here.

- [ ] [DataTable] sticky header (additional functionality requested which is not covered in this milestone) https://github.com/carbon-design-system/carbon-components/issues/1587 
- [ ] [All fields and inputs] Helper text update https://github.com/carbon-design-system/carbon/issues/2329
- [ ] Resolve layer tokens & add guidance on usage #2674
- [ ] [Text input] Dynamic list #2679

## Awaiting contribution

- [ ] [Tabs] Add a secondary style #1329
- [ ] [Tags] Tag input, tags group #2422
