### ISSUE TITLE
DataTable - sticky header v10.3/4 implementation

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon#2862]
ref milestone plan: https://github.com/carbon-design-system/carbon/issues/2416
ref original issue request: https://github.com/carbon-design-system/carbon/issues/1587
ref akira's first look at merging (now closed): https://github.com/carbon-design-system/carbon/pull/2711/

---

this issue will specify what we plan to design, spec out, and implement as part of this milestone of work. for any requests in #1587 that are not covered here, we can revisit as part of a later milestone.

**what we plan to implement this milestone**
- DataTable's full header being sticky
- solutions for technical limitations around this implementation
- design specs and guidance as necessary

**tasks**
- [ ] design spec
- [x] learn @jnm2377 's existing implementation
- [ ] merge existing functionality into new monorepo
- [ ] further improvements to sticky header architecture/implementation as it makes sense

**Comment by asudoh** [comment]
Let's close this as #2965 has landed. We can track specific issues/enhancement with new issues. Thank you for entering this @lovemecomputer!

**Comment by lovemecomputer** [comment]
@asudoh awesome, thanks!!
