### ISSUE TITLE
[v10 Components/Enhancements] June Iteration Plan

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2963]
# June Iteration Plan

This plan captures our work on the Components project for **June**. This work will not only resolve technical debt but also add feature enhancements to library components.

## Endgame

• *July 8th, 2019*: Code freeze for the endgame
• *July 12th, 2019*: Endgame done (edited) 

The endgame details for this iteration are tracked in TBD.

## <Project Area>

Our **primary goal** is to resolve in-progress items (meaning items where design work is completed or mostly completed, or development is under way) as well as address areas of technical debt identified by the support group. 

- [ ] Data table sticky header https://github.com/carbon-design-system/carbon/issues/2862
- [ ] Read only input controls https://github.com/carbon-design-system/carbon/issues/2177
  - [ ] text input https://github.com/carbon-design-system/carbon/issues/3018
  - [ ] number input
  - [ ] date picker
- [ ] File uploader error state https://github.com/carbon-design-system/carbon/issues/2962
- [ ] File uploader drag and drop container https://github.com/carbon-design-system/carbon/issues/2917
- [ ] File uploader item/status component https://github.com/carbon-design-system/carbon/issues/2916
- [ ] Drag and drop file uploader https://github.com/carbon-design-system/carbon/issues/2288

Our **stretch goal** is to gather design resources and complete specifications for triaged issues to pass off to dev

Candidates (that should be triaged) are:
- Inline link https://github.com/carbon-design-system/carbon/issues/1465
- Reduced motion for skeleton state  https://github.com/carbon-design-system/carbon/issues/2440
- Toggle and ToggleSmall a11y https://github.com/carbon-design-system/carbon/pull/2885
- Modal a11y https://github.com/carbon-design-system/carbon/pull/2851
- Better application-level control of several React components
- [Data table] Horizontal scrolling https://github.com/carbon-design-system/carbon/issues/2824
- [Notification] Secondary style (low contrast style) fixes (still in design phase) https://github.com/carbon-design-system/carbon/issues/2927
- remove *transactional modal's* click-outside-to-close, but this is still in design-decision stage
https://github.com/carbon-design-system/carbon/issues/2935

---

## Deferred Items (stuff moved from primary/stretch to another iteration

TBD
