### ISSUE TITLE
[Contribution] June Iteration plan

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#2977]
# June Iteration Plan

This plan captures our work on the contribution project for **June**. This work will provide guidance and content for contribution on the Carbon Design System website.

## Members

- @janchild 
- @connor-leech 
- @aagonzales 
- @laurenmrice 

## Endgame

- **July 8th, 2019**: Code freeze for the endgame
- **July 12th, 2019**: Endgame done

The endgame details for this iteration are tracked in TBD.

## Contribution

Our **primary goals** are to:

**Content**
- [x] Map users (who), tasks (what), and how they are interacting/contributing:  https://github.com/carbon-design-system/carbon-website/issues/1746
- [x] Identify pain points for users and Carbon team: https://github.com/carbon-design-system/carbon-website/issues/1747
- [x] Identify contribution must-haves: https://github.com/carbon-design-system/carbon-website/issues/1748
- [ ] Write guidance for each type of contribution: https://github.com/carbon-design-system/carbon/issues/3090
- [ ] Explore Badging or other credit (or swag) for each type of contribution, or quantity of each: https://github.com/carbon-design-system/carbon/issues/3091
- [ ] Explore Community evaluation/rating criteria https://github.com/carbon-design-system/carbon/issues/3101
- [ ] Create a plan of action for Axure design kit: https://github.com/carbon-design-system/carbon/issues/3102
- [ ] Production guidelines (page templates for each of our pages): https://github.com/carbon-design-system/carbon-website/issues/1754

**Design**
- [ ] Patterns status
- [ ] Contribution page designs
- [ ] Have ongoing assistance with members of teams who are currently in the process of contributing. Eg Symbol contribution, component guidance.

---

**Comment by jan** [comment]
@laurenmrice I'm not a child anymore!

**Comment by chrisconnors-ibm** [comment]
Make sure any related issues are represented here and show progress via the [Project Kanban](https://github.com/orgs/carbon-design-system/projects/21)
