### ISSUE TITLE
[Theming] June Iteration Plan

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2978]
# June Iteration Plan

This plan captures our work on the Theming project for **June**. This work will demonstrate the Carbon components in our non-white themes and define our theming strategy for how we will support theming going forward including component-level tokens, inline theming, runtime theming, and how styling can be consumed.

## Members

- @mattrosno 
- @shixiedesign  
- @vpicone (half time)
- @asudoh (half time)

## Endgame

• **July 8th, 2019**: Code freeze for the endgame
• **July 12th, 2019**: Endgame done

The endgame details for this iteration are tracked in TBD.

## Carbon Theming

Our **primary goal** is to render the Carbon components in the non-white themes (Gray 10, Gray 90, and Gray 100) in both development and demonstration environments using the existing Sass build methodologies.

This work will include the following:

- [ ] Update theme sandbox to include v10 tokens and components but no new functionality https://github.com/carbon-design-system/carbon/issues/3046 https://github.com/carbon-design-system/carbon/issues/3066 
- [ ] Document process of choosing a theme when developing components https://github.com/carbon-design-system/carbon/issues/3068
- [ ] Provide alternate theme CSS bundles that we can use for demonstration purposes (TBD) https://github.com/carbon-design-system/carbon/issues/3069
- [ ] Modify component examples in the website so you can view the components in any of the four supported themes https://github.com/carbon-design-system/carbon-website/issues/1736 https://github.com/carbon-design-system/carbon-website/issues/1737

Our **secondary goal(s)** is to explore more theming needs that may result in proof-of-concept deliverables during June. These concepts include:

- Runtime theming strategy to minimize dependance on Sass builds https://github.com/carbon-design-system/carbon/issues/3070
- Inline theming strategy so certain zones of a web page can use an alternate theme https://github.com/carbon-design-system/carbon/issues/3070
- Component-level token strategy and naming conventions so more specific theming changes can be made without global side-effects https://github.com/carbon-design-system/carbon/issues/3067
- Update our theming documentation prevent stale examples as tokens are updated https://github.com/carbon-design-system/carbon-website/issues/1738

---

## Deferred Items

**Comment by joshblack** [comment]
> using the existing Sass build methodologies.

Do we want to explore using Custom Properties or is that a non-starter because of IE11?

---

With respect to primary versus stretch, would we say that rendering on the website is a primary goal over things like zone/inline/component theming?

**Comment by mattrosno** [comment]
Supporting our designers to ensure non-white theme tokens are solid - top priority. And supporting the community by showing non-white components in website a close second. That makes up the primary goals.

Custom properties and other exploratory techniques fall into secondary goals.
