### ISSUE TITLE
[IBM Color Palette] Create palette V2 to satisfy AA & AAA accessibility requirements

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3226]
IBM Color Palette V1 has been in circulation and usage for a few months now and we have identified areas for improvement. This issue tracks the work done on IBM Color Palette V2. 

Currently I've created a draft for Palette V2 that satisfies AA & AAA accessibility requirements at specific intervals: 

Sketch file https://ibm.box.com/s/ehviuw5uumkk1i7tonymke3tuwd7x3y4 )

Palette is now with Sadek who is working on tweaking the hues to stay true across the spectrum of bright and dark. 

![image](https://user-images.githubusercontent.com/15144993/60356226-151ee080-9996-11e9-8214-89b6e0c38e7a.png)

**Comment by shixiedesign** [comment]
Not stale. Pending update from Sadek.

**Comment by shixiedesign** [comment]
Issue is finally complete! Final V2 color palette sketchfile: https://ibm.box.com/s/uuc0792cw6lg3ovkoeo8sec3nr6vfghh

Next steps: 
- [x] Decide best place to host the sketch & ai file for both Carbon and Language site, & update
- [ ] Update `carbon-elements` repo with new hex values https://github.com/carbon-design-system/carbon/issues/3737
- [ ] Update design kit (or export elements via @joshblack 's magic) https://github.com/carbon-design-system/carbon-design-kit/issues/174
- [ ] Re-visit component enhancement issues: helper text https://github.com/carbon-design-system/carbon/issues/2329 , and buttons https://github.com/carbon-design-system/carbon/issues/3736
- [ ] Look into the repercussions on Hover & Active colors. Do we still need tokens?
- [ ] Update Carbon site color page guidance 
- [ ] Update Language site color page guidance
