### ISSUE TITLE
[Colors] V2 palette October delivery work tracking

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3904]
Final V2 color palette sketchfile: https://ibm.box.com/s/1n2c9h1ap7z05t6d2d84wkglhnfrz9bx

# Next steps: 

**Website: Carbon**
- [x] Create accurate CLR & ASE files https://github.com/carbon-design-system/carbon/issues/3969
- [x] Decide best place to host the sketch & ai file for both Carbon and Language site, & update https://github.com/carbon-design-system/carbon-website/issues/236 and fix https://github.com/carbon-design-system/carbon-website/issues/279
- ~~Update Carbon website color page with new images using new colors~~ https://github.com/carbon-design-system/carbon-website/issues/237 _Update: removing from this sprint because it's low impact and can be done slowly later._
- [x] Update typography page token description of `$helper-text-01` https://github.com/carbon-design-system/carbon-website/issues/314
- [x] Add new tokens to Carbon website Colors/Usage page https://github.com/carbon-design-system/carbon-website/issues/295
- [x] Update Color/Usage page swatches' hex codes https://github.com/carbon-design-system/carbon-website/issues/319

**Website: Language**
- ~~Update [Language website color page ](https://www.ibm.com/design/language/elements/color) with new images using new colors~~ https://github.com/carbon-design-system/design-language-website/issues/272 _Update: removing from this sprint because it's low impact and can be done slowly later._

**Carbon repo**
- [x] Update `carbon-elements` repo with new hex values https://github.com/carbon-design-system/carbon/issues/3737
- [x] Add new color token for `$text-05` https://github.com/carbon-design-system/carbon/issues/3960
- [x] Add new color token `$danger` https://github.com/carbon-design-system/carbon/issues/3736

Sync updates in design kit
- [x] Design kit https://github.com/carbon-design-system/carbon-design-kit/issues/189

Re-visit component enhancement/bug fix issues 
- [x] helper text https://github.com/carbon-design-system/carbon/issues/3961
- [x] buttons https://github.com/carbon-design-system/carbon/issues/3736
- [x] toggle https://github.com/carbon-design-system/carbon/issues/3614
- ~~Look into the repercussions on Hover & Active colors. Do we still need tokens?~~ Update: to be done for v11 so token deprecation can be done. Issue for this work https://github.com/carbon-design-system/carbon/issues/4049

**Design kit repo**
- [ ] Update design kit https://github.com/carbon-design-system/carbon-design-kit/issues/174
