### ISSUE TITLE
MultiSelect: Select All option ☂️ 

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4593]
### Summary

There is an option to remove all the selected items from the multi select list, however if a user selected all the items and then clicked on remove all by mistake (for instance, if there is a narrow dropdown showing a list of 2 digit codes or something similar its not hard to press the remove all button by mistake), there is no way to select all with one click other than by clicking on individual items. In our case, we have drop downs with about a thousand items. 

### Justification

Business reason is that if there is an option to remove all selections, there should be an option to select all to undo if you remove all selections by mistake.

### Desired UX and success metrics

A sample can be seen on the [mdbootstrap multiselect](https://mdbootstrap.com/docs/jquery/forms/multiselect/) page.

### "Must have" functionality

There should be a way to select all the items in multiselect list with one click

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/13611
- [ ] https://github.com/carbon-design-system/carbon/issues/13612
- [ ] https://github.com/carbon-design-system/carbon/issues/13434
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3977
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3973
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3974
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/789
- [ ] https://github.com/carbon-design-system/carbon/issues/16117
```

**Comment by tahaimt** [comment]
Wow, it hasnt even been looked at and its about to be closed.

**Comment by tahaimt** [comment]
@dakahn can you please take a look at this?

**Comment by ganisback** [comment]
need this feature

**Comment by dakahn** [comment]
~~Apologies for the lack of action on this issue. We've started porting enhancement requests over to our Github Discussions board where they can get maintainer responses and community interaction more reliably.~~

~~I've done that for this issue and you can find that discussion [here](https://github.com/carbon-design-system/carbon/discussions/7622). Feel free to upvote and discuss (or suggest edits if your original proposal has changed/evolved)~~
_Misunderstood our (currently evolving) process._ 

This is triaged as an open proposal and should be seen in our next proposals meeting

thanks for your patience

**Comment by tanoargie** [comment]
Also need this feature. Seems to be repeated in carbon-design-system/carbon#7705

**Comment by sstrubberg** [comment]
@ganisback & @tahaimt what product or PAL are you supporting?

**Comment by laurenmrice** [comment]
### Action items

- [ ] Research existing designs of a MultiSelect dropdown with a select all option.
- [ ] Create different design iterations.
- [ ] Review with the Carbon team.
- [ ] Adjust designs with team feedback.
- [ ] Finalize spec.

**Comment by jimmydyer** [comment]
@sstrubberg Are there any updates or designs related to the `Select all` use case for the multi-select dropdown?

Our product desperately needs this because our users have to manage lots of data sources, and if they clear the pill from the dropdown, they would need to select each option in the list individually tens to hundreds of times. 

Here's a screenshot for reference:

![Screenshot 2023-06-20 at 10 01 25 AM](https://github.com/carbon-design-system/carbon/assets/54411478/8860cd31-5b49-47b0-a554-4eb3baf20798)

What we need is something like the sketch below:

![IMG_7D2B5BA963C3-1](https://github.com/carbon-design-system/carbon/assets/54411478/3ff68b68-0f7e-49a7-80d1-f310b5d8777f)

**Comment by jjennings7** [comment]
DataStage needs this feature as well. Looks like this is on the roadmap but I don't see any designs in [13434](https://github.com/carbon-design-system/carbon/issues/13434). Is there any update on the design or when it will be consumable? Thanks.

**Comment by sstrubberg** [comment]
hey @jjennings7, this is still queued up to work on, but we're knee-deep in docs debt on the design side of the house. I'd like to start designs soon though. If you have an early designs or use-cases that ya'll have been working on, that might help us expedite things when we start working on it though. Let me know!

**Comment by benjamin-kurien** [comment]
Hey, We have now started working on this issue. Please [vote here](https://github.com/carbon-design-system/carbon/discussions/15807) to help us clarify the problem you're facing.

**Comment by benjamin-kurien** [comment]
A parent checkbox has been added to the multiselect dropdown, allowing users to easily select all options from the dropdown.
