### ISSUE TITLE
Known component enhancements 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#5303]
General component enhancements required for system support. 
(priority: most important at top of each list)

## Proposal research
- [x] Phone number input with country selector  #3948 
- [ ] Status icons/component

## Needs design work:

- **Tree structure**: new component https://github.com/carbon-design-system/carbon/issues/5180
   - [x] Final spec of development 
   - [ ] Component usage and style guidelines
   - [ ] Kit symbols
- [x] **Toast notifications:** with 2 actions and define usage.  https://github.com/carbon-design-system/carbon/issues/5055
   - MVP add to notification pattern if dev accessibility concern block implementation.
- [ ] **ComboButton** - pending proposal acceptance
- [ ] **Data Table**: search + batch action https://github.com/carbon-design-system/carbon/issues/2275
- [ ] **ComboBox**: what is a combobox and is ours acting accordingly 
   - https://github.com/carbon-design-system/carbon/issues/4468
   - https://github.com/carbon-design-system/carbon/issues/4992
- [ ] **Form** read only variants https://github.com/carbon-design-system/carbon/issues/2177

## Dev ready:

- [x] **Tab**: Scrolling behavior: https://github.com/carbon-design-system/carbon/issues/4758
- [ ] **Fluid Inputs:** https://github.com/carbon-design-system/carbon/issues/5416
- **Modal** enhancements: https://github.com/carbon-design-system/carbon/issues/4607
   - [x] 1 button
   - [ ] 3 button groups
   - [ ] Progress modal
- [ ] **Structured list**: add option with background: https://github.com/carbon-design-system/carbon/issues/5410 (currently blocked)
- [x] **File uploader** size and variant options https://github.com/carbon-design-system/carbon/pull/5614
- [ ] **Radio button** invalid state: https://github.com/carbon-design-system/carbon/issues/5390
- [ ] **Checkbox** invalid state: https://github.com/carbon-design-system/carbon/issues/5390
- [x] **Danger button** variations https://github.com/carbon-design-system/carbon/issues/4945 https://github.com/carbon-design-system/carbon/issues/5610
- [x] **Number input** update with new control icons and hovers https://github.com/carbon-design-system/carbon/issues/5417
- [ ] **Data table** add an option to have a 64px cell row that has two lines of text https://github.com/carbon-design-system/carbon/issues/6382
- [ ] **Code snippet** add an option to have a number line in a multi-line code snippet https://github.com/carbon-design-system/carbon/issues/6519
- [ ] **Context menu** https://github.com/carbon-design-system/carbon/issues/6830

## V11:
Breaking changes
- **Default component spacing** https://github.com/carbon-design-system/carbon/issues/5367

**Comment by aagonzales** [comment]
Closing in favor of new priority list
