### ISSUE TITLE
v10.10.0 Release

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5398]
**Status:** Published (behind next tag)
**Target date:** February 27th, 2020
**Changelog**: [Link](https://github.com/carbon-design-system/carbon/pull/5432)

### Timeline

- February 26th
  - Released v10.10.0-rc.3
  - Released v10.10.0-rc.4
- February 25th
  - Released v10.10.0-rc.2 packages
  - Release-blocking bugs:
    - [x] https://github.com/carbon-design-system/carbon/pull/5444
- February 24th
  - Re-running release process, working on downshift updates
- February 19th
  - Update: still working through regressions for downshift updates on #5373
- February 11th
  - Release review resulted in a couple of release-blocking bug reports
- January 31st
  - v10.10.0-rc.0 preview shipped

### Release blocking bugs

- [x] https://github.com/carbon-design-system/carbon/pull/5356
- [x] https://github.com/carbon-design-system/carbon/issues/5399
- [x] https://github.com/carbon-design-system/carbon/issues/5389

### Release checklist

- [ ] Determine scope of changed items (and dependencies)
- [ ] Verify new behavior
- [ ] Verify no regressions have occurred
- [ ] Create release candidate and PR against internal properties
- [ ] Create stable release and publish to next
- [ ] Push git tag and create changelog
- [ ] Switch next tag to latest for changed packages

**Browser support**

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE11

**Screen reader support**

- [ ] JAWS
- [ ] NVDA
- [ ] VoiceOver on macOS
- [ ] VoiceOver on iOS

**Comment by abbeyhrt** [comment]
Have a PR open for #5389!

**Comment by joshblack** [comment]
Functionality to verify:

---

## `carbon-components@10.10.0-rc.1`

### New features :rocket:
- [x] ~feat(select): add height variations to select (#5311) ([`6d23a7044`](https://github.com/carbon-design-system/carbon/commit/6d23a7044))~
  - Reviewers
    - @joshblack
- [x] ~feat(notification): add info icon to notification (#5203) ([`189c1c30f`](https://github.com/carbon-design-system/carbon/commit/189c1c30f))~
  - Reviewers
    - @joshblack
- [x] ~feat(react): add Grid components (#4894) ([`354baa82b`](https://github.com/carbon-design-system/carbon/commit/354baa82b))~
  - Reviewers
    - @joshblack
- [x] ~feat(progress-indicator): update to use carbon icons (#5122) ([`aa33fa0c5`](https://github.com/carbon-design-system/carbon/commit/aa33fa0c5))~
  - Reviewers
    - @joshblack
- [x] ~feat: add Esc key support to dismiss tooltips (#5147) ([`f03a0a122`](https://github.com/carbon-design-system/carbon/commit/f03a0a122))~
  - Reviewers
    - @joshblack
- [x] ~feat(progress-indicator): adds hidden span to announce state of completion (#5125) ([`99fde8e0d`](https://github.com/carbon-design-system/carbon/commit/99fde8e0d))~
  - Reviewers
    - @joshblack
- [x] ~feat(progress-indicator): add vertical progress indicator to react (#5146) ([`1532cf721`](https://github.com/carbon-design-system/carbon/commit/1532cf721))~
  - Reviewers
    - @joshblack
- [x] ~feat(box-shadow): remove deprecated layer, use box-shadow mixin (#5126) ([`aed0ea253`](https://github.com/carbon-design-system/carbon/commit/aed0ea253))~
  - Reviewers
    - @joshblack
- [x] ~feat(text-input): add height variations to text input (#5076) ([`7011d0bf6`](https://github.com/carbon-design-system/carbon/commit/7011d0bf6))~
  - Reviewers
    - @joshblack
- [x] ~feat(grid): add zero span columns (#5052) ([`a0752cd65`](https://github.com/carbon-design-system/carbon/commit/a0752cd65))~
  - Reviewers
    - @joshblack
- [x] ~feat(list-box): update selection style (#4753) ([`9e6335fdf`](https://github.com/carbon-design-system/carbon/commit/9e6335fdf))~
  - Reviewers
    - @joshblack

### Housekeeping :house:
- [x] ~refactor(CopyButton): inherit Copy component (#5006) ([`7d8c0aa3e`](https://github.com/carbon-design-system/carbon/commit/7d8c0aa3e))~
  - Reviewers
    - @joshblack

## `@carbon/grid@10.9.0-rc.1`

### New features :rocket:
- [x] ~feat(react): add Grid components (#4894) ([`354baa82b`](https://github.com/carbon-design-system/carbon/commit/354baa82b))~
  - Reviewers
    - @joshblack
- [x] ~feat(grid): add zero span columns (#5052) ([`a0752cd65`](https://github.com/carbon-design-system/carbon/commit/a0752cd65))~
  - Reviewers
    - @joshblack

## `@carbon/icons@10.9.0-rc.1`

### New features :rocket:
- [x] ~feat(icons): add icons from the January and February batch (#5342) ([`b82f079d5`](https://github.com/carbon-design-system/carbon/commit/b82f079d5))~
  - Reviewers
    - @joshblack
- [x] ~feat(icons): add December icon batch (#5015) ([`66b4833f2`](https://github.com/carbon-design-system/carbon/commit/66b4833f2))~
  - Reviewers
    - @joshblack

### Bug fixes :bug:

### Housekeeping :house:
- [x] ~refactor(icon-build-helpers): update metadata generation (#5372) ([`5db2d1e60`](https://github.com/carbon-design-system/carbon/commit/5db2d1e60))~
  - Reviewers
    - @joshblack

## `@carbon/pictograms@10.9.0-rc.1`

### Housekeeping :house:
- [x] ~refactor(icon-build-helpers): update metadata generation (#5372) ([`5db2d1e60`](https://github.com/carbon-design-system/carbon/commit/5db2d1e60))~
  - Reviewers
    - @joshblack

## `carbon-components-react@7.10.0-rc.1`

### New features :rocket:
- [x] ~feat(select): add height variations to select (#5311) ([`6d23a7044`](https://github.com/carbon-design-system/carbon/commit/6d23a7044))~
  - Reviewers
    - @joshblack
- [x] ~feat(components): support automatic focus sentinel (#5260) ([`0e9c6d525`](https://github.com/carbon-design-system/carbon/commit/0e9c6d525))~
  - Reviewers
    - @joshblack
- [ ] feat(Tooltip): add several ARIA attributes (#5282) ([`45acec0b9`](https://github.com/carbon-design-system/carbon/commit/45acec0b9))
- [x] ~feat(SideNavMenu): collapse submenu on esc keydown (#5198) ([`0853d381a`](https://github.com/carbon-design-system/carbon/commit/0853d381a))~
 - Reviewers
    - @aledavila 
- [x] ~feat(notification): add info icon to notification (#5203) ([`189c1c30f`](https://github.com/carbon-design-system/carbon/commit/189c1c30f))~
  - Reviewers
    - @joshblack
- [x] ~feat(react): add Grid components (#4894) ([`354baa82b`](https://github.com/carbon-design-system/carbon/commit/354baa82b))~
  - Reviewers
    - @joshblack
- [ ] ~feat(react): add support for rollup in bundles (#5185) ([`540889922`](https://github.com/carbon-design-system/carbon/commit/540889922))~
  - This functionality caused a regression and was removed in #5444 
  - Reviewers
    - @joshblack
- [x] ~feat(progress-indicator): update to use carbon icons (#5122) ([`aa33fa0c5`](https://github.com/carbon-design-system/carbon/commit/aa33fa0c5))~
  - Reviewers
    - @joshblack
- [x] ~feat: add Esc key support to dismiss tooltips (#5147) ([`f03a0a122`](https://github.com/carbon-design-system/carbon/commit/f03a0a122))~
  - Reviewers
    - @joshblack
- [x] ~feat(DataTable): allow additional contents to expand cells (#5060) ([`f3422c438`](https://github.com/carbon-design-system/carbon/commit/f3422c438))~
  - Reviewers
    - @joshblack
- [x] ~feat(progress-indicator): adds hidden span to announce state of completion (#5125) ([`99fde8e0d`](https://github.com/carbon-design-system/carbon/commit/99fde8e0d))~
  - Reviewers
    - @joshblack
- [x] ~feat(progress-indicator): add vertical progress indicator to react (#5146) ([`1532cf721`](https://github.com/carbon-design-system/carbon/commit/1532cf721))~
  - Reviewers
    - @joshblack
- [x] ~feat(text-input): add height variations to text input (#5076) ([`7011d0bf6`](https://github.com/carbon-design-system/carbon/commit/7011d0bf6))~
  - Reviewers
    - @joshblack
- [x] ~feat(data-table): add colSpan prop for TableHeader (#5088) ([`c061bccca`](https://github.com/carbon-design-system/carbon/commit/c061bccca))~
  - Reviewers
    - @joshblack
- [x] ~feat(list-box): update selection style (#4753) ([`9e6335fdf`](https://github.com/carbon-design-system/carbon/commit/9e6335fdf))~
  - Reviewers
    - @joshblack
- [x] ~feat(ListBox): fix labels of trigger buttons (#4820) ([`f87a204f6`](https://github.com/carbon-design-system/carbon/commit/f87a204f6))~
  - Reviewers
    - @joshblack
- [x] ~feat(file-uploader): add support for onChange (#4906) ([`66abfcf77`](https://github.com/carbon-design-system/carbon/commit/66abfcf77))~
  - Reviewers
    - @joshblack

### Bug fixes :bug:

### Housekeeping :house:
- [x] ~refactor(react): update wildcard exports (#5220) ([`0000bb214`](https://github.com/carbon-design-system/carbon/commit/0000bb214))~
  - Reviewers
    - @joshblack
- [x] ~refactor(notification): refactor component to use hooks (#5072) ([`cff494c84`](https://github.com/carbon-design-system/carbon/commit/cff494c84))~
  - Reviewers
    - @joshblack
- [x] ~refactor(loading): update from class to function (#5054) ([`02ba91cf4`](https://github.com/carbon-design-system/carbon/commit/02ba91cf4))~
  - Reviewers
    - @joshblack
- [x] ~refactor(code-snippet): update CodeSnippet.Skeleton to hooks ([`c4e8bcdd3`](https://github.com/carbon-design-system/carbon/commit/c4e8bcdd3))~
  - Reviewers
    - @joshblack
- [x] ~refactor(code-snippet): update test suite for CodeSnippet.Skeleton ([`918003fc7`](https://github.com/carbon-design-system/carbon/commit/918003fc7))~
  - Reviewers
    - @joshblack
- [x] ~refactor(CopyButton): inherit Copy component (#5006) ([`7d8c0aa3e`](https://github.com/carbon-design-system/carbon/commit/7d8c0aa3e))~
  - Reviewers
    - @joshblack

## `@carbon/themes@10.10.0-rc.1`

### New features :rocket:
- [x] ~feat(themes): enable dynamic values for interactive color tokens (#5269) ([`437da9895`](https://github.com/carbon-design-system/carbon/commit/437da9895))~
  - Reviewers
    - @joshblack
- [x] ~feat(token): add new $text-error (#5056) ([`fb349c6d7`](https://github.com/carbon-design-system/carbon/commit/fb349c6d7))~
  - Reviewers
    - @joshblack

**Comment by joshblack** [comment]
Final packages published under `next`, will move to `latest` on Monday!
