### ISSUE TITLE
Fluid inputs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#5416]
This issue is to provide a fluid variations for input fields.

* Components will be experimental at the onset, moved to stable once all inputs, documentation, etc is complete
* Each input will be worked on individually and held to the same standard of completion:
  * Website must be updated to provide pattern and component "style tab" documentation 
  * Updated design tooling must be provided
  * Implementation must be complete, including tests, stories, and docs.
* TextInput will be the first to lay groundwork, subsequent inputs will build upon the intial work started.
  * The website pattern will be built up over time
  * A cohesive Form example showing an entire form of fluid inputs will be built up over time

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/issues/11443
- [x] https://github.com/carbon-design-system/carbon/issues/11728
- [x] https://github.com/carbon-design-system/carbon/issues/11785
- [x] https://github.com/carbon-design-system/carbon/issues/12082
- [x] https://github.com/carbon-design-system/carbon/issues/12003
- [x] https://github.com/carbon-design-system/carbon/issues/12019
- [x] https://github.com/carbon-design-system/carbon/issues/12107
- [x] https://github.com/carbon-design-system/carbon/issues/12120
- [x] https://github.com/carbon-design-system/carbon/issues/12124
- [x] https://github.com/carbon-design-system/carbon/issues/12125
- [x] https://github.com/carbon-design-system/carbon/issues/12126
- [x] https://github.com/carbon-design-system/carbon/issues/12127
- [x] https://github.com/carbon-design-system/carbon/issues/12440
- [x] https://github.com/carbon-design-system/carbon/issues/12453
- [x] https://github.com/carbon-design-system/carbon/issues/12475
- [x] https://github.com/carbon-design-system/carbon/issues/12025
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/558
- [x] https://github.com/carbon-design-system/carbon/issues/12817
- [x] https://github.com/carbon-design-system/carbon-website/issues/3123
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/559
```

```[tasklist]
### End game
- [x] Final naming discussion + create issues for any changes that are needed. https://github.com/carbon-design-system/carbon-website/pull/3391
- [x] Publish website branch
- [x] Slack announcement
- [x] Publish Figma branches
```

---

<details>
  <summary>Click here to view the original (now outdated) spec</summary>
  
# Fluid Inputs
Add fluid variations to input fields.
  
- ~Text input~
- Text area
- Dropdown
- ComboBox
- Multi-select
- Date picker
- Number input
- Select

## Text input
![Text-input - White](https://user-images.githubusercontent.com/11670886/75064013-ba4d7280-54ab-11ea-8d91-f71b495165e9.png)

## Text area
![Text area - White](https://user-images.githubusercontent.com/11670886/75064012-b9b4dc00-54ab-11ea-838c-100796203a37.png)

## Dropdown
![Dropdown - White](https://user-images.githubusercontent.com/11670886/75064007-b91c4580-54ab-11ea-99cc-03d4bf8216f2.png)

## ComboBox
![ComboBox - White](https://user-images.githubusercontent.com/11670886/75064003-b6215500-54ab-11ea-8cb7-3c461cc65479.png)

## MultiSelect
![MultiSelect - White](https://user-images.githubusercontent.com/11670886/75064008-b91c4580-54ab-11ea-9716-c8235ec4117c.png)

## Date Picker
![DatePicker - White](https://user-images.githubusercontent.com/11670886/75064006-b7eb1880-54ab-11ea-8192-352576f1d17e.png)

## Number input
![Number Input - White](https://user-images.githubusercontent.com/11670886/75064010-b9b4dc00-54ab-11ea-96f6-4c21ffa98834.png)

## Select
![Select - White](https://user-images.githubusercontent.com/11670886/75064011-b9b4dc00-54ab-11ea-9aad-4f976dfaa587.png)

## No helper text
![White - helper text alt](https://user-images.githubusercontent.com/11670886/75064014-ba4d7280-54ab-11ea-87aa-e50fba4981e6.png)

</details>

**Comment by aagonzales** [comment]
Sketch file: https://ibm.box.com/s/g97s3a2s7l7bn66wkbxnt30rj3j45bbc

**Comment by aagonzales** [comment]
## End game strategy 
- [ ] Final naming discussion + create issues for any changes that are needed.
- [ ] Publish website branch
- [ ] Slack announcement
