### ISSUE TITLE
March 2020 Planning

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5475]
## Timeline

**March 2nd, 2020 - March 6th, 2020**

- Start patch release
- Weekly issue and proposal triage
  - [x] March 6th

**March 9th, 2020 - March 13th, 2020**

- Ship patch release
- Start patch release
- Weekly issue and proposal triage
  - [x] March 13th

**March 16th, 2020 - March 20th, 2020**

- Ship patch release
- Start patch release
- Weekly issue and proposal triage
  - ~March 20th~ _cancelled_

**March 23rd, 2020 - March 27th, 2020**

- Ship patch release
- Start endgame (Release candidate, minor release)
- Demo day
  - [x]  March 26th
- Retro
  - [x] March 26th
- Planning for April Iteration
  - [x] March 26th (leadership)
  - [x]  March 27th (team)
- Weekly issue and proposal triage
  - [x] March 27th

**March 30th, 2020 - April 3rd, 2020**

- Ship minor release
- Weekly issue and proposal triage
  - [x] April 3rd

## Goals

**Increase the quality of components and icons**

- [ ] Migrate the 3 components of varied complexity to use the new template
- [ ] Create component documentation template https://github.com/carbon-design-system/carbon-website/issues/862 @janchild @jillianhowarth + tbd dev
  - [ ] Production guidelines https://github.com/carbon-design-system/carbon-website/issues/934 @jeanservaas @laurenmrice
- [ ] Clear WCAG 2.1 AA violations for 9 remaining components https://github.com/carbon-design-system/carbon/issues/4828
  - [ ] CodeSnippet ~#2523~ #5553 @tw15egan 
  - [ ] Combobox @emyarod
     - [x] #3419
     - [ ] #3418
     - [ ] #3416 
  - [ ] DataTable @asudoh 
      - [ ] #3805 PR- https://github.com/carbon-design-system/carbon/pull/4807
      - [ ] #5242 PR- https://github.com/carbon-design-system/carbon/pull/5631
  - [ ] DatePicker  **tbd designer + dev**
      - [ ] #5308 
      - [ ] #5310 PR-https://github.com/carbon-design-system/carbon/pull/5375
  - [ ] Dropdown @aledavila 
     - [ ] #4373 PR-https://github.com/carbon-design-system/carbon/pull/5193
     - [ ] #5211 
  - [ ] Modal @emyarod
      - [ ] #2739 
      - [x] #2740 
      - [x] #5545 
  - [ ] NumberInput #4185 
  - [ ] FileUploader #3437 @joshblack 
    - Cleared the first PR, just working through DAP violations in test
  - [ ] MultiSelect @abbeyhrt
      - [ ] #4197 
      - [ ] #5093  
  - [ ] StructuredList @dakahn + **tbd designer**
      - [ ] #2820 
      - [ ] #1937 
  - [ ] Tile #5174 @joshblack - PR https://github.com/carbon-design-system/carbon/pull/5667
  - [ ] Tooltip @dakahn  + @aagonzales 
      - [ ] #5488 
      - [ ] #5365 PR? https://github.com/carbon-design-system/carbon/pull/5489
- [ ] Achieve consistent icons and pictograms across all sources, kits, libraries, and docs @joshblack @emyarod @laurenmrice 

**Understand why teams are creating separate sites related to Carbon**

- [x] Publish an audit of all PAL and BX sites @connor-leech
- [ ] Interview 3 PAL/BX site maintainers
- [ ] Create 25 community engagement desired outcome statements
- [ ] Internally visualize possible to-be relationships in a system of systems 
- [x] Develop a Community section for PAL sites and Experimental patterns @janchild @shinytoyrobots 

**Component enhancements**

- [ ] Size variants for components @tw15egan 
   - [ ] [https://github.com/carbon-design-system/carbon/issues/5455](https://github.com/carbon-design-system/carbon/issues/5455) “Proposal: Support for 48px versions of a wider range of components”
    - [x] [https://github.com/carbon-design-system/carbon/issues/5448](https://github.com/carbon-design-system/carbon/issues/5448) “Proposal: Extend ‘short’ field size support to all form inputs”
    - [x] [https://github.com/carbon-design-system/carbon/issues/5441](https://github.com/carbon-design-system/carbon/issues/5441) “[number input] add 48px and 32px size options”
- [ ]  [Design] [Treeview](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/issues/carbon-design-system/carbon/5180) @designertyler @emyarod 
- [ ]  [Dev] [Tabs](https://github.com/carbon-design-system/carbon/issues/4758) @abbeyhrt 

**UI shell**

- [x]  [Design] Define shell theming: https://github.com/carbon-design-system/carbon/issues/4839 @aagonzales
- [ ]  UI Shell tertiary nav 
- [ ]  Inline theming documentation

**Website Enhancements**
_collaboration w/ aux_
- [x]  [Design] Feedback component https://github.com/carbon-design-system/carbon-website/issues/922 
- [x]  [Design] Component status page: define mvp solution https://github.com/carbon-design-system/carbon-website/issues/936
- [ ]  Image component enhancements
   - [ ]  Dev] Size options for "image--fixed" https://github.com/carbon-design-system/carbon-website/issues/943
   - [ ]  [Dev] Group image component https://github.com/carbon-design-system/carbon-website/issues/945 

**Support**
- Thank you card (design) @jeanservaas (production) @aagonzales
- Design kit backlog
- [ ]  [Elements documentation](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/issues/carbon-design-system/carbon-website/841) improvements @alisonjoseph _(moving to April, meeting w/ Jan/Connor pushed due to covid-19 website work & other priorities)_
- [ ] Pagination contribution https://github.com/carbon-design-system/carbon/pull/5485
- 1-2 bug-related PRs a week pulled from our the list below or our prioritized backlog
  - [ ] #5515
  - [ ] https://github.com/carbon-design-system/carbon/issues/3911
  - [x] https://github.com/carbon-design-system/carbon/issues/5549
  - [x] https://github.com/carbon-design-system/carbon/issues/5517
  - [x] https://github.com/carbon-design-system/carbon/issues/5506 **(blocking component demo updates)**
  - [ ] https://github.com/carbon-design-system/carbon/issues/5435 **(blocking component demo updates)**
  - [ ] https://github.com/carbon-design-system/carbon/issues/5434 **(blocking component demo updates)**
  - [x] https://github.com/carbon-design-system/carbon/issues/3710
  - [x] https://github.com/carbon-design-system/carbon/issues/4550
  - [x] ~https://github.com/carbon-design-system/carbon/issues/2715~
  - [x] https://github.com/carbon-design-system/carbon/issues/4850
- Answer 5-10 questions a week on Slack or GitHub

**Stretch goals**

- [ ]  [Dev] [Fluid inputs](https://github.com/carbon-design-system/carbon/issues/5416)
- [ ]  [Dev] [Treeview](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/issues/carbon-design-system/carbon/5180)
- [ ]  [Dev] Pagination (small pagination in React) [https://github.com/carbon-design-system/carbon/issues/2634](https://github.com/carbon-design-system/carbon/issues/2634)
- [ ]  [Dev] Textarea (character counter) [https://github.com/carbon-design-system/carbon/issues/1672](https://github.com/carbon-design-system/carbon/issues/1672)
- [ ]  [Dev] Dropdown (move helper text below) [https://github.com/carbon-design-system/carbon/issues/5279](https://github.com/carbon-design-system/carbon/issues/5279)
- [ ]  [Dev] Dropdown (default selection behavior) [https://github.com/carbon-design-system/carbon/issues/3531](https://github.com/carbon-design-system/carbon/issues/3531)n
- [ ]  [Dev] Interactive tooltip alignment [https://github.com/carbon-design-system/carbon/issues/3837](https://github.com/carbon-design-system/carbon/issues/3837)

**Comment by joshblack** [comment]
## Proposed

**Component enhancements**

- Size variants for components
    - [https://github.com/carbon-design-system/carbon/issues/5455](https://github.com/carbon-design-system/carbon/issues/5455) “Proposal: Support for 48px versions of a wider range of components”
    - [https://github.com/carbon-design-system/carbon/issues/5448](https://github.com/carbon-design-system/carbon/issues/5448) “Proposal: Extend ‘short’ field size support to all form inputs”
    - [https://github.com/carbon-design-system/carbon/issues/5441](https://github.com/carbon-design-system/carbon/issues/5441) “[number input] add 48px and 32px size options”
- [Treeview](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/issues/carbon-design-system/carbon/5180)
- [Tabs](https://github.com/carbon-design-system/carbon/issues/4758)
- [Fluid inputs](https://github.com/carbon-design-system/carbon/issues/5416)

**UI Shell**

- [Design] Define shell theming: https://github.com/carbon-design-system/carbon/issues/4839 
- [Design] UI Shell extensions: https://github.com/carbon-design-system/carbon/issues/5152 
- [Design] UI Shell alternatives https://github.com/carbon-design-system/carbon/issues/5143
- UI Shell tertiary nav 
- Inline theming

**Elements and guidelines**

- [Design] ui-03 problems
- [Elements documentation](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/issues/carbon-design-system/carbon-website/841) improvements

**Package performance and infrastructure**

- Offer guidance on how to speed up sass build times
  - Alternatively, alter how we write our sass to help speed up build times
- Coordinate around flat bundle techniques to enable tree-shaking

**Theming**

- Inline theming support and best practices

**Icons**

- Revisit icon size requirements and experiment with options to fix asset issues

**Comment by ghost** [comment]
You should also update the docs entirely. A lot of the stuff about styling, feature flags, experimental status, available props, component usage, and examples are simply outdated. As a user myself, this was especially frustrating to try to replicate the examples only to be told "Oh ya that's an old version, add these changes we didn't document anywhere" after spending hours on it. Obviously beggars can't be choosers but I'm just providing some honest feedback that this would be really nice.

**Comment by joshblack** [comment]
Hi @jibberishclient! 👋 Thanks so much for the feedback 😄 

Always happy to take the time to update docs that you have found to be outdated, alongside accepting PRs that help to update these things as well. Feel free to reach out on Slack with specifics or create issues for things that are wrong and we can help out 👍

**Comment by ghost** [comment]
Well for one thing, the UI shell no longer appears to be experimental, and including it as a feature flag actually breaks the grid underneath in the `Content` creating an overlap. I'm honestly not sure why the Content component needs a grid offset div inside to avoid the sidenav ... isn't that the whole point of the Content component?

Where exactly can I join the slack?

**Comment by joshblack** [comment]
@jibberishclient is there a specific documenting that you were following for the UI Shell?

And if you're an IBMer, you can join us in the carbon channels from any workspace! Specifically, #carbon-react might be the most helpful. If you're outside of IBM, you could join us over at:

- https://spectrum.chat/carbon?tab=posts
- https://gitter.im/carbondesignsystem/community

**Comment by ghost** [comment]
Yes I was following the react tutorial which stated that the UI Shell was still experimental (despite not being listed under experimental) and thus would need to be be marked under `$feature-flags`. What was happening is that there would be an overlap between the SideNav and the Content.

Furthermore, the tutorial demonstrates a header navigation that doesn't collapse on smaller displays #5457. Just through trial and error I've found many inconsistencies between the docs and the actual component usage.

**Comment by ghost** [comment]
And both those communities are visibly inactive

**Comment by joshblack** [comment]
@jibberishclient thanks! Definitely seems like the tutorial is out of date, will make sure to make an issue to fix it 👍 

With respect to the communities, we can't control how people engage in those channels but we have them open for people to ask questions 😄 Similarly you can always create an issue on this project with a question and we'll get to it as soon as we can!

**Comment by ghost** [comment]
The docs have a UI Shell such that when expanded and you click outside of the SideNav (i.e. on the overlay) it closes instead of having to click the HeaderMenuButton. There's also a huge hole in the docs on the use of the grid system and why one would need to offset inside a Content component so avoid the SideNav from covering it when Content should inherently take care of that according to the design system.

There's also some issues with the DataTable as well #5518. Not to mention #5497. Also forcing the id's to be strings makes no sense because most REST APIs will return primary keys as integers anyway. There's also no clarification between ComboBox and Select. There's also no mention of margin and padding helper classes if they even exist; it appears you have to style them in yourself which would defeat the whole purpose of a "design system" if you're choosing margins (for example in a form between fields) on a whim.

**Comment by joshblack** [comment]
@jibberishclient for questions/feedback I definitely recommend making issues or reaching out in the communities linked above. This issue is more so for team coordination/planning. Hope that makes sense!

**Comment by ghost** [comment]
Ok I've made a few issues. Thanks for your time
