### ISSUE TITLE
April 2020

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5733]
## Timeline

**March 30th - April 3rd**

- Endgame week
- Weekly issue and proposal triage
  - [x] April 3rd

**April 6th - April 10th**

- Ship minor release
- Start patch release
- Weekly issue and proposal triage
  - [x] April 10th

**April 13th - April 17th**

- Ship patch release
- Start patch release
- Weekly issue and proposal triage
  - [x] April 17th

**April 20th - April 24th**

- Ship patch release
- Start endgame (Release candidate, minor release)
- Demo day
  - [ ]  April 30th
- Retro
  - [ ] May 1st
- Planning for May Iteration
  - [ ] April 30th/May 1st (leadership)

**May 4th - May 8th**
- Ship minor release
- Planning for May Iteration
  - [ ] May 4th (team)

#### Component documentation

**Owners:** @janchild @aagonzales @joshblack 
EPIC: https://github.com/carbon-design-system/carbon-website/issues/862

- [Dev] Author development implementation usage docs for components and include coded examples for the components below (dev needs to work closely with design to mirror usage docs, _"this is how to use X component in design and this is how you implement it"_ This is just one example: https://reacttraining.com/reach-ui/accordion/ @joshblack @asudoh @emyarod 
- [Design] Assessment of existing design usage component content against new template @jillianhowarth @aagonzales @janchild @laurenmrice @designertyler
  - [ ] https://github.com/carbon-design-system/carbon-website/issues/1062
- [Design/Dev] Update 7 components to new template: [EPIC](https://github.com/carbon-design-system/carbon-website/pull/1081#workspaces/system-squad-593830641344b813db10934d/board?epics=199501316_862&filterLogic=any&repos=84835535,86360855,199501316) @jillianhowarth @aagonzales @laurenmrice @janchild @designertyler 
  - [x] Accordion https://github.com/carbon-design-system/carbon-website/issues/1064 @joshblack / @aagonzales 
  - [ ] Breadcrumb @jillianhowarth @emyarod 
  - [x] Checkbox https://github.com/carbon-design-system/carbon-website/issues/1067 @laurenmrice @emyarod 
  - [ ] Data table https://github.com/carbon-design-system/carbon-website/issues/1063 @designertyler @joshblack 
  - [ ] Dropdown https://github.com/carbon-design-system/carbon-website/issues/1065 @laurenmrice @joshblack (in progress)
  - [ ] Link @jillianhowarth @emyarod 
  - [x] Modal https://github.com/carbon-design-system/carbon-website/issues/1068 @asudoh / @aagonzales 
  - [x] Notification @jillianhowarth  
- [Design] Update "How to contribute" docs on site to reflect new component template and @janchild 
  - [ ] https://github.com/carbon-design-system/carbon-website/issues/1070
- [Design] Production guidelines @jeanservaas 
  - [ ] https://github.com/carbon-design-system/carbon-website/issues/934
- [Design] Update to general "Content guidelines" to support component content guidelines @janchild 
  - [ ] https://github.com/carbon-design-system/carbon-website/issues/1071
- [Dev] Author accessibility verification testing docs for reviewers to follow
- [Design] Create docs for UI shell rail @designertyler 

### Icons and Pictograms 

**Owners:** @joshblack @laurenmrice 
- [ ] [Epic] Icon and pictogram tooling and updates #5137 
- [ ] Pictogram work from March
   - [ ] https://github.com/carbon-design-system/carbon/issues/4130
   - [x] https://github.com/carbon-design-system/carbon/issues/5567
   - [ ] https://github.com/carbon-design-system/carbon/issues/5693
   - [x] https://github.com/carbon-design-system/carbon/issues/5692

### Guidelines documentation
 - [x] Incorporate feedback from Accessibility team into our Accessibility guidelines pages @connor-leech 
   - [ ] https://github.com/carbon-design-system/carbon-website/issues/1101
 - [ ] Add developer guidelines around how to use our elements packages to the website @connor-leech @alisonjoseph 
   - [ ] https://github.com/carbon-design-system/carbon-website/issues/841

### Community
- [ ] Finalize proposed community model description @mattrosno @shinytoyrobots + **task force**
- [ ] Validate / invalidate community model @mattrosno 
- [ ] [Design] Stand up site for Onboarding guidance @connor-leech @janchild
- [x] Explore where / how to link from Carbon to Brand sites @janchild 

### Data Visualization
- [ ] Update usage images for Dashboards and Advanced Charts @jeanservaas 

### Planning for future
- [ ] Determine strategy and rationale for IE11 support and validate/invalidate _(propose drop support in October, need to validate with teams)_ 
- [ ] Create plan for October release @aagonzales @joshblack @jeanservaas @alisonjoseph @janchild @shinytoyrobots 

### Component enhancements

- [ ] [Dev] [Treeview](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/issues/carbon-design-system/carbon/5180)
  - Contributed by Cloud PAL @emyarod 
- [ ] [Dev] [Fluid inputs](https://github.com/carbon-design-system/carbon/issues/5416)
  - Start with Text Input and scope out effort @tw15egan @aledavila 
- [ ] [Design] [Fluid inputs] Usage doc updates @jeanservaas @aagonzales 
- [ ] [Dev] Pagination (small pagination in React) [#2634](https://github.com/carbon-design-system/carbon/issues/2634)
  - Contributed by SPSS @emyarod 
- [ ] [Design] Pagination (small) Usage doc updates @designertyler 
  - [ ] https://github.com/carbon-design-system/carbon/issues/5546
- [ ] [Dev] Tabs https://github.com/carbon-design-system/carbon/issues/4758
    - contributed by @abbeyhrt

### Collaboration on expressive theme

- [ ] Review RFC from IBM Dotcom team (team)
- [x] Review components that would be good candidates as size variants in Carbon @aagonzales 

### Support
- [x] https://github.com/carbon-design-system/carbon/issues/5730
- [ ] https://github.com/carbon-design-system/carbon-website/issues/919
- [x] https://github.com/carbon-design-system/carbon/issues/5515 Progress Bar step labels look like a link tag but nothing happens when clicking on it 
- [ ] https://github.com/carbon-design-system/carbon/issues/5568 Icon bug: Using `information--filled` and `closed` icons together causes the info icon to render incorrectly
- [x] [Data Table Skeleton](https://github.com/carbon-design-system/carbon/issues/3032)
- [ ] Determine how range mode date selection in calendar dropdown should work https://github.com/carbon-design-system/carbon/issues/5572 @designertyler 
- **WCAG 2.1 AA Issues**
  - [ ] https://github.com/carbon-design-system/carbon/issues/5687
  - [ ] https://github.com/carbon-design-system/carbon/issues/5547
   - [ ] CodeSnippet #5553 @tw15egan 
    - [ ] Combobox @emyarod
       - [x] #3419
       - [ ] #3418
       - [ ] #3416 
    - [ ] DatePicker  **tbd designer + dev**
        - [ ] #5308 
    - [ ] Dropdown @aledavila 
       - [ ] #5211 - PR #5373 
    - [ ] Modal @emyarod
        - [ ] #2739 
        - [x] #2740 
        - [x] #5545 
    - [ ] NumberInput #4185 
    - [ ] FileUploader #3437 @joshblack 
    - [ ] MultiSelect 
        - [ ] #4197 
        - [ ] #5093  
    - [ ] StructuredList @dakahn 
        - [ ] #2820 
        - [ ] #1937 
    - [ ] Tooltip @dakahn  + @aagonzales 
        - [ ] #5488 
        - [ ] #5365 PR? https://github.com/carbon-design-system/carbon/pull/5489
- https://github.com/carbon-design-system/carbon/issues/5757

#### Component packages
- Explore 

#### Release tooling

- [ ] Automate tagging and publishing a release
- [ ] Automate generation of Sketch plugin

#### Component enhancements
- [Dev] Character counter text input [#5702](https://github.com/carbon-design-system/carbon/issues/5702) 
 - Tabs with arrow support
- [Dev] Textarea (character counter) [#1672](https://github.com/carbon-design-system/carbon/issues/1672)
- [Dev] Dropdown (move helper text below) [#5279](https://github.com/carbon-design-system/carbon/issues/5279)
- ~[Dev] Dropdown (default selection behavior) [#3531](https://github.com/carbon-design-system/carbon/issues/3531)~
- [Dev] Interactive tooltip alignment [#3837](https://github.com/carbon-design-system/carbon/issues/3837)

**Comment by GJor** [comment]
Hi @joshblack , what is the timeline of  #5547 to become available?

**Comment by joshblack** [comment]
Hi @GJor! 👋 I don't know if there is an ETA yet for when that issue will be addressed. We'll always accept contributions for fixes if the timeline for this is urgent!

**Comment by matthewgallo** [comment]
Hey @joshblack, similar question to @GJor, is there a status update for https://github.com/carbon-design-system/carbon/issues/5687?

**Comment by joshblack** [comment]
Hey @matthewgallo! Sorry about the delay, taking a look now and will try and see if we can get one of the devs on our team to verify/triage so we can get it fixed!
