### ISSUE TITLE
May 2020

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#5999]
## Timeline

**May 4th - May 8th**
- Planning for May Iteration
  - [x] May 4th (team)
- Weekly issue and proposal triage
  - [x] May 8th

**May 11th - May 15th**

- Ship minor release
- Weekly issue and proposal triage
  - [x] May 15th

**May 18th - May 22nd**

- Ship patch release
- Start patch release
- Weekly issue and proposal triage
  - [x] May 22nd

**May 25th - May 29th**

- Ship patch release
- Start endgame (Release candidate, minor release)
- Demo day
  - [x]  May 28th
- Retro
  - [ ] May 29th
- Planning for May Iteration
  - [x] May 29th (leadership)

**June 1st - June 5th**
- Ship minor release
- Planning for June Iteration
  - [ ] June 1st (team)

## Goals
1. Tutorial
2. Documentation (Component / Guidelines)
3. Icons/Pictograms 

## Tutorial
https://github.com/carbon-design-system/carbon-website/issues/986
- [x] Automate PR reviews: [https://github.com/carbon-design-system/carbon-tutorial/issues/4236](https://github.com/carbon-design-system/carbon-tutorial/issues/4236)
- [ ] Automate badging 

## [Component documentation](https://www.notion.so/carbondesignsystem/Component-documentation-2ffec1e5c38443f3bfbcf354c9504d59)

- [x] Component tab order change: https://github.com/carbon-design-system/carbon-website/issues/1152
- [x] [Design] Content cleanup for components after tab order change: https://github.com/carbon-design-system/carbon-website/issues/1169 @janchild 
- [x] [Design] Update "How to contribute" docs on site to reflect new component template @janchild
    - [x] [carbon-design-system/carbon-website#1070](https://github.com/carbon-design-system/carbon-website/issues/1070)
- [ ] [Design] Production guidelines https://github.com/carbon-design-system/carbon-website/issues/934 @jeanservaas
- [ ] [Dev] ~Versioning strategy with content (tied to release version, publish previous versions)~

### Components

_**todo: create issue for code tab and add links here**_
- Modal @asudoh @aagonzales
  - [x] Usage https://github.com/carbon-design-system/carbon-website/issues/1068
  - [ ] Code [PR](https://github.com/carbon-design-system/carbon-website/pull/1126) 
- Accordion @joshblack @aagonzales 
  - [x] Usage https://github.com/carbon-design-system/carbon-website/issues/1064
  - [x] Code https://github.com/carbon-design-system/carbon/issues/6006
- Checkbox  @laurenmrice @asudoh 
  - [x] Usage https://github.com/carbon-design-system/carbon-website/issues/1067
  - [ ] Code 
- Notification  @jillianhowarth @dakahn 
  - [x] Usage https://github.com/carbon-design-system/carbon-website/issues/1081
  - [ ] Code https://github.com/carbon-design-system/carbon-website/pull/1217
- Breadcrumb @jillianhowarth @aledavila 
  - [x] Usage https://github.com/carbon-design-system/carbon-website/issues/1069 
  - [X] Code https://github.com/carbon-design-system/carbon-website/pull/1192
- Dropdown @laurenmrice @tw15egan 
  - [x] Usage https://github.com/carbon-design-system/carbon-website/issues/1065
  - [ ] Code 
- Link @jillianhowarth @emyarod
  - [x] Usage https://github.com/carbon-design-system/carbon-website/pull/1138
  - [ ] Code 
- Button @jillianhowarth @tw15egan @jeanservaas 
  - [ ] Usage https://github.com/carbon-design-system/carbon-website/pull/971
  - [ ] Code 
- Data table  @designertyler @joshblack 
  - [ ] Usage https://github.com/carbon-design-system/carbon-website/issues/1063
  - [ ] Code https://github.com/carbon-design-system/carbon/issues/6115
- Date Picker @aagonzales 
   - [x] Usage https://github.com/carbon-design-system/carbon-website/issues/1158
- Content switcher @jillianhowarth @aledavila 
   - [ ] Usage https://github.com/carbon-design-system/carbon-website/issues/1207
   - [ ] Code https://github.com/carbon-design-system/carbon-website/pull/1223

_Next in the list:
Data table(code), UI shell header, Code snippet, List, File uploader, Inline loading, Link, Tabs, Loading, Overflow menu, Text input, Select, Pagination_

## Guidelines documentation
- [ ] Finish Data viz master file for download; respond to Adv Charts feedback in order to merge
- [ ] Grid updates for condensed
- [x] Add developer guidelines around how to use our elements packages to the website
[carbon-design-system/carbon-website#841](https://github.com/carbon-design-system/carbon-website/issues/841) @connor-leech 

## Icons/Pictograms 

- Work with brand to get correct assets for pictograms, we currently have talked about:
  - 32px pictogram variants that no longer include the outer padding
  - Assets are exported such that only fill or stroke are required instead of both
- Take the work from above and verify it with the pictogram plugin work that @emyarod has done over in https://github.com/carbon-design-system/carbon/pull/5827
- Verify plugins work as intended with the Sketch kit
- Process icon updates in Sketch kit
- Add support for using the proper name of an asset instead of auto-generating the name
  - For example, instead of IBM going to Ibm, use IBM
  - This work should include the old assets, as well, to prevent breaking changes

## Ongoing work

- [ ] [Treeview](https://github.com/carbon-design-system/carbon/issues/5180) @emyarod 
- [x] Downshift upgrade https://github.com/carbon-design-system/carbon/pull/5373 @dakahn

## Community

- Phase one definition @mattrosno @joshblack  
  - [ ] Draft statement of intent
  - [ ] Work with sponsor teams to define phase 1

- Gatsby sites online @connor-leech

  - Watson Moments: https://github.com/carbon-design-system/carbon/issues/6041
    - [x] Final content port over 
    - [x] Team enablement / training

  - Onboarding
    - [ ] Github setup
    - [ ] Theme setup
    - [ ] Team enablement / training

## Support

- @emyarod
  - [ ] carbon-design-system/carbon#5726
  - [ ] carbon-design-system/carbon#2200
  - [x] carbon-design-system/carbon#4579
- @joshblack
  - [x] carbon-design-system/carbon#5163 (in PR)
  - [ ] carbon-design-system/carbon#5953
  - [x] ~carbon-design-system/carbon#4979~
- @tw15egan
  - [ ] carbon-design-system/carbon#5956
  - [x] carbon-design-system/carbon#5984
  - [x] carbon-design-system/carbon#5624
- @asudoh
  - [ ] carbon-design-system/carbon#4881
    - Duplicate: carbon-design-system/carbon#5980
  - [ ] carbon-design-system/carbon#5264
- @aledavila
  - [ ] carbon-design-system/carbon#5860
  - [ ] carbon-design-system/carbon#3143
- @dakahn
  - [ ] carbon-design-system/carbon#5065
  - [ ] carbon-design-system/carbon#4185
  - [ ] carbon-design-system/carbon#2595
- blocked
  - [ ] carbon-design-system/carbon#5488
  - [ ] carbon-design-system/carbon#5365

**Comment by mjabbink** [comment]
– Enhanced data table (Cloud contribution) YES

– Page header
– Slide-in panel
– Slide-over panel
– Cards 
– Icon buttons
– Widgets

**Comment by dakahn** [comment]
looks like @emyarod has the tooltip work locked down so I moved that over to him and added my assigned structured list/number input stuff 👍

**Comment by emyarod** [comment]
the related tooltip PR (https://github.com/carbon-design-system/carbon/pull/5489) has been blocked for some time due to unclear a11y requirements which I still need clarification on

**Comment by alisonjoseph** [comment]
Seems like there are still a bunch of questions around requirements for tooltip, maybe something we need to pair up on to define and then look at prioritizing early June?
