### ISSUE TITLE
support(community): Scaffold and spin up Watson Moments site

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon#6041]
## Overview

The Watson Moments team reached out for help setting up a Gatsby theme site to present their guidance, patterns, and components. We will help them set up the site structure and migrate their existing content into the theme.

This is part of our ongoing support of subsystems for domain-specific guidance. 

## To-do

- [ ] Collect existing assets and scope the amount of work
- [ ] Set up TravisCI and GitHub pages for automatic deployment
- [ ] Determine long-term maintainers and establish expectations about ongoing support and maintenance 
- [ ] Merge into CD&AI Watson Moments repo and hand off maintenance responsibility
