### ISSUE TITLE
Sprint 1: The Pilot ✈️

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#6438]
## Timeline July 27 - August 7

🗒️ **[Q3 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/roadmap)**

## 💡[Objective: Fix foundational issues that inhibit Carbon adoption](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/50)
- [x] Assign dates to key results
- [x] Patterns presentation for dev team from design @designertyler @jillianhowarth 
- Resolve guidance inconsistencies @jeanservaas 
  - [ ] [Investigate how to do hanging grid in code ](https://github.com/carbon-design-system/carbon/issues/5892) @tw15egan @joshblack 
  - [x] **(PR)** [Fluid button group](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/issues/carbon-design-system/carbon/5638) @emyarod @laurenmrice 
  - [x] [Update design kits](https://github.com/carbon-design-system/carbon-design-kit/issues/349
) @laurenmrice 
  - [x] [Update modal images on website](https://github.com/carbon-design-system/carbon-website/pull/1534)**(PR)** @laurenmrice 

### Docs
- Component usage docs
    - [ ] UI shell header (creating new images. PR soon) @designertyler 
    - [ ] List (working on images, PR coming soon) @jillianhowarth 
    - [ ] Inline loading @aagonzales (not started)
    - [x] [File uploader](https://github.com/carbon-design-system/carbon-website/pull/1527) **(PR)** @laurenmrice 
- Dev docs (entire dev team)
  - [x] ~Determine strategy to import mdx docs from storybook to website~ https://github.com/carbon-design-system/carbon/issues/6548 
  - Add docs to storybook for 6 components (1 dev each)
    - [x] Accordion https://github.com/carbon-design-system/carbon/issues/6547 @joshblack @rjhenriquez 
    - [x] Breadcrumb https://github.com/carbon-design-system/carbon/pull/6580 @aledavila @andreancardona 
    - [ ] Modal @emyarod 
    - [ ] **([PR](https://github.com/carbon-design-system/carbon/pull/6565))** Button @tw15egan 
    - [ ] **([PR](https://github.com/carbon-design-system/carbon/pull/6606))** Code snippet @dakahn 

## 💡[Objective: Surface the components that IBM teams have built, so that others can consume them](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/51)
- [ ] Production guidelines @jeanservaas 

### [Component index ](https://github.com/carbon-design-system/carbon-website/issues/1266)
- [ ] Create images (design) @aagonzales [Box folder](https://ibm.box.com/s/xycb4c9c49xpa4dnjmlqffwqyrihtlmq) 75% complete
- [x] Finalize content @jillianhowarth @aagonzales [Notion doc](https://www.notion.so/carbondesignsystem/67b90bb253504d428e5298a56ed18902?v=10176c9bf6124af59ad96d88eef20020) 
- [x] Integrate research findings @aagonzales [#1266](https://github.com/carbon-design-system/carbon-website/issues/1266#issuecomment-665756950)
- [x] **(PR)** Development @andreancardona @joshblack 

## 💡 [Objective: Quantify where and how Carbon assets are being used](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/53)
_starting next sprint_

## 🛠 Support 
- [ ] **(PR)** treeview (experimental) #5180 @emyarod 
-  Issues linked to sprint epic
