### ISSUE TITLE
[icons] sketch plugin has bug issues

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#6485]
- [x] While doing a test with the latest sketch plugin I noticed that some icons are rendering incorrectly by skewing their proportions.

- We originally thought that this was only happening to icons that did not have a transparent rectangle layer applied to them in their svgs, but that is not the case. This is also happening to icons that do have the transparent rectangle.

- I made an audit here of the icons this is happening to for each size and if there is a transparent rectangle or not. I also addressed when they are being put into a new file vs rendered onto an existing id.

https://www.notion.so/carbondesignsystem/Rendering-problems-c85a5d53e45b4716b6b1bb6a1776c4ea

----------------------------------------------------------------------------------------------------------------------------
In addition to the rendering issues the following problems are also happening:

- [x] **Deprecated icons:** Resolved by #8060
-The plugin is not deleting the deprecated icon artwork/artboards out of the sketch library

- [x] **Editing existing icons:** Resolved by #7711  
-If an existing icon on artboard is edited in the code svg asset, the update the library receives changes the size of the edited icon but skews the original artwork.(it does not replace the artwork with the new artwork version) #5758 #5749 #5597

- [x] **Brand new icons:** Resolved by #7711 
-Artwork and artboards import fine with correct naming 👍🏻 #7712
-Attached colors for new icons are coming in differently than the existing ones. They are both black but are coming from different places. (Can we get them all to have the same attached color style? And can we decide where it connects to?)

**Comment by emyarod** [comment]
after #7648 it seems that new icons are being added on sync, WIP still under way on the sync itself skewing icons as well as removing deprecated icon symbols and artboards

**Comment by emyarod** [comment]
resolved by #5597 #5749 #5758 #7711 #7712 #8060
