### ISSUE TITLE
Sprint 2: Alpaca and Furious 🦙

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#6626]
## Timeline August 10 - August 21

🗒️ **[Q3 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/roadmap)**

## Sprint 1 PRs
- [x] Button docs https://github.com/carbon-design-system/carbon/pull/6565 @tw15egan 
- [x] Code snippet docs https://github.com/carbon-design-system/carbon/pull/6606 @dakahn 
- [ ] Treeview https://github.com/carbon-design-system/carbon/pull/6008 @emyarod 
- [x] Button set and modal footer buttons https://github.com/carbon-design-system/carbon/pull/6608 @emyarod 
- [x] [Modal button images](https://github.com/carbon-design-system/carbon-website/pull/1534) @laurenmrice 
- [x] [File uploader usage docs](https://github.com/carbon-design-system/carbon-website/pull/1527) @laurenmrice 
## 💡[Objective: Fix foundational issues that inhibit Carbon adoption](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/50)
- [x] Design presentation to new hires @designertyler @jillianhowarth 
- [x] [IA work](https://github.com/carbon-design-system/carbon-website/issues/1516) @janchild @alisonjoseph **PR** https://github.com/carbon-design-system/carbon-website/pull/1571
- [x] [Case studies - create base page](https://github.com/carbon-design-system/carbon-website/issues/1520) @jillianhowarth 
- [ ] [Review FAQs](https://github.com/carbon-design-system/carbon-website/issues/1539) @jillianhowarth 
- [ ] [[icons] sketch plugin has bug issues](https://github.com/carbon-design-system/carbon/issues/6485) @emyarod @tw15egan 
- [x] React Prop name audit ([**KR**](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/61)) team workshop. https://github.com/carbon-design-system/carbon/issues/6690#issuecomment-675669096
- [x] [Investigate how to do hanging grid in code ](https://github.com/carbon-design-system/carbon/issues/5892)  ([**KR**](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/64))@jeanservaas  @joshblack @dakahn 

#### Docs - ([**KR**](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/65))
- Component usage docs
    - _Next in the list: Tabs, Loading, Overflow menu, Text input, Select, Pagination_
    - [ ] UI shell header (creating new images. PR soon) @designertyler 
    - [ ] List (working on images, PR coming soon) @jillianhowarth [ON HOLD]
    - [x] Inline loading [PR](https://github.com/carbon-design-system/carbon-website/pull/1562/) @aagonzales 
    - [ ] @designertyler 
    - [ ] @laurenmrice  (defer till next sprint)
- Component dev docs - storybook
  - [ ] Modal https://github.com/carbon-design-system/carbon/issues/6591 @emyarod 
  - [ ]  Checkbox https://github.com/carbon-design-system/carbon/issues/6628 @aledavila 
  - [ ]  Combobox https://github.com/carbon-design-system/carbon/issues/6629 @dakahn 
  - [x]  Content Switcher https://github.com/carbon-design-system/carbon/issues/6630 @tw15egan 
  - [ ]  Data Table https://github.com/carbon-design-system/carbon/issues/6631 @joshblack **PR** https://github.com/carbon-design-system/carbon/pull/6694
   - [x] Date picker PR - https://github.com/carbon-design-system/carbon/pull/6689

## 💡[Objective: Surface the components that IBM teams have built, so that others can consume them](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/51)

- [ ] Production guidelines @jeanservaas

#### [Component index ](https://github.com/carbon-design-system/carbon-website/issues/1266) - [KR: Ship an index on the Carbon site by 8/31](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/57)
- [x] Finalize images (design) @aagonzales [Box folder](https://ibm.box.com/s/xycb4c9c49xpa4dnjmlqffwqyrihtlmq) 
- [x] Add dynamic rendering of Tags [PR](https://github.com/carbon-design-system/carbon-website/pull/1542) @andreancardona 
- [x] Update links: repo & website [PR](https://github.com/carbon-design-system/carbon-website/pull/1553) @andreancardona 
- [x] Add filtering functionality for the index [PR](https://github.com/carbon-design-system/carbon-website/pull/1584) @joshblack 
- [x] Add support for images for each item in the index  [#1266](https://github.com/carbon-design-system/carbon-website/issues/1266) @andreancardona @joshblack 
- [x] Ship it 🚀  

## 💡 [Objective: Quantify where and how Carbon assets are being used](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/53)
- [ ] Deliver a report of carbon package usage within public projects on GitHub Enterprise that details @joshblack @dakahn 
  - Organizations
  - Repos
  - Packages used (and versions)

## 🛠 Support 
-  Issues linked to sprint epic
- [ ] Design kit: add size variants to inputs [#289](https://github.com/carbon-design-system/carbon-design-kit/issues/289) @aagonzales @laurenmrice 
- [x] Fix React tutorial Mergify @tw15egan 
- [ ] Design and code review of badge application site https://github.com/carbon-design-system/carbon-badges/issues/3 @aledavila + @jeanservaas 
- [ ] website a11y audit https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/reports/release?release=5f185c45ccda2753d030c742 @andreancardona 
- [x] Table batch action visual bug https://github.com/carbon-design-system/carbon/pull/6596 @emyarod
- [x] Prevent form submissions when interacting with filter tags https://github.com/carbon-design-system/carbon/pull/6610 @emyarod
- [ ] Pagination default page range text https://github.com/carbon-design-system/carbon/pull/6675 @emyarod
