### ISSUE TITLE
Sprint 3: Bat to the Future 🦇

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#6697]
## Timeline August 24 - September 4

🗒️ **[Q3 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/roadmap)**

## Sprint 2 PRs
- [x] Treeview https://github.com/carbon-design-system/carbon/pull/6008 @emyarod 
- [x] Checkbox https://github.com/carbon-design-system/carbon/pull/6698
- [x] Component index https://github.com/carbon-design-system/carbon-website/pull/1584

## 💡[Objective: Fix foundational issues that inhibit Carbon adoption](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/50)
- [[icons] Sketch plugin issues](https://github.com/carbon-design-system/carbon/issues/6485) @emyarod 
  - [ ] Rendering issues
  - [ ] Deprecated icon bugs
  - [ ] Editing existing icon bugs
  - [ ] New icon color bug
- [x] [IA work cont'd](https://github.com/carbon-design-system/carbon-website/issues/1516) @janchild @alisonjoseph **PR** https://github.com/carbon-design-system/carbon-website/pull/1571
- [ ] [Review FAQs](https://github.com/carbon-design-system/carbon-website/issues/1539) @jillianhowarth @aagonzales 
- [ ] [Patterns presentation recording](https://github.com/carbon-design-system/carbon-website/issues/1561) for Design tutorials page @designertyler @jillianhowarth 
- [x] [Image for Medium article](https://github.com/carbon-design-system/carbon-website/issues/1558) announcing website changes @jeanservaas 
- [ ] [Update Home page content](https://github.com/carbon-design-system/carbon-website/issues/1519) @jeanservaas @janchild 
- [x] [Events page](https://github.com/carbon-design-system/carbon-website/issues/1541) @jeanservaas @janchild 
- [ ] [Case study research](https://github.com/carbon-design-system/carbon-website/issues/1520) @andreancardona 
- [ ] [Component audit](https://www.notion.so/carbondesignsystem/Token-audit-3be5016e1e0d4b48a15edcff301ca805)  @aagonzales @laurenmrice 
- [ ] Document (new) naming conventions for design tokens based on audit [KR](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/63) @aagonzales @laurenmrice 
- [ ] Figure out next steps - [Investigate how to do hanging grid in code ](https://github.com/carbon-design-system/carbon/issues/5892)  ([**KR**](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/64)) @alisonjoseph 

#### Docs - ([**KR**](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/65))
- Component usage docs
    - _Next in the list: Form, Tile, Tabs, Overflow menu, Text input, Select, Pagination_
    - [x] UI shell header (PR) @designertyler 
    - [x] Treeview docs updates @designertyler 
- Component code docs (storybook)
  - From last sprint
    - [ ] Modal https://github.com/carbon-design-system/carbon/issues/6591 @emyarod 
    - [ ] Combobox https://github.com/carbon-design-system/carbon/issues/6629 @dakahn 
    - [x] DataTable (last sprint missed skeleton) @joshblack 
  - This sprint
    - [x] Dropdown https://github.com/carbon-design-system/carbon/issues/6709 @tw15egan 
    - [x] Grid @joshblack
    - [ ] Tabs @aledavila 
    - [x] DatePicker https://github.com/carbon-design-system/carbon/issues/6688 (PR) @tw15egan 

#### [Component index ](https://github.com/carbon-design-system/carbon-website/issues/1266) - [KR: Ship an index on the Carbon site by 8/31](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/57) @andreancardona 
- [x] Ship it 🚀  
- [ ] Docs (how do I add my component to the index...)
- [ ] Add custom Fathom goal "number of clicks on individual component links" [KR
](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/60)
## 💡 [Objective: Quantify where and how Carbon assets are being used](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/53)

@joshblack @dakahn 

- [ ] Telemetry MVP https://github.ibm.com/carbon/ibm/issues/3

## 🛠 Support 
- [x] Design kit: add size variants to inputs #289 @aagonzales @laurenmrice
- [x] Pagination: update default page range text #6675 
- [x] FloatingMenu: ignore disabled nodes for autofocus #6679 @emyarod
- [x] FormGroup: use node prop type for legend text #6691
- [x] OverflowMenu: check previous open state before calling onClose #6721 @emyarod
- [ ] Tooltip: allow focusTrap prop passthrough #6722 @emyarod
- [x] ComboBox: allow custom onToggleClick handler #6726 @emyarod
- [x] Add Text toolbar sketch file to sketch cloud and to the Patterns page. @laurenmrice  (getting pr ready)
