### ISSUE TITLE
Sprint 4: Cat Me If You Can 🐱

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#6772]
## Timeline September 7 - September 18

🗒️ **[Q3 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/roadmap)**

## Sprint 3 🦇
- [ ] Combobox dev docs PR https://github.com/carbon-design-system/carbon/pull/6734 @dakahn 
- [ ] Tabs code docs https://github.com/carbon-design-system/carbon/issues/6774 @aledavila 
- [ ] Modal code docs https://github.com/carbon-design-system/carbon/issues/6591 @emyarod PR: #6804
- [x] ComposedModal code docs https://github.com/carbon-design-system/carbon/issues/6591 @emyarod PR: #6805
- [ ] ModalWrapper code docs https://github.com/carbon-design-system/carbon/issues/6591 @emyarod PR: #6806
- Sketch plugin updates (flagged under OKR below)
- Hanging grid in code https://github.com/carbon-design-system/carbon/issues/5892

## 💡[Objective: Fix foundational issues that inhibit Carbon adoption](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/50)

- [ ] **Pictogram updates https://github.com/carbon-design-system/carbon/issues/6773** @andreancardona @emyarod (@joshblack)
  - TODO: Sync with brand on asset delivery date 
- [ ] **Icons plugin https://github.com/carbon-design-system/carbon/issues/6485** @andreancardona @emyarod (@joshblack)
- [x] [Review FAQs](https://github.com/carbon-design-system/carbon-website/issues/1539) @jillianhowarth @aagonzales
- [x] [Add page (or minimum define a section) for "kit and kit extension" resources](https://github.com/carbon-design-system/carbon-website/issues/1667) @janchild @jeanservaas @laurenmrice 
- [ ] [Patterns presentation recording](https://github.com/carbon-design-system/carbon-website/issues/1561)for Design tutorials page @jillianhowarth
- [x] [Medium article image for component index](https://github.com/carbon-design-system/carbon-website/issues/1686) @jeanservaas 
- [ ] [Medium article about component index](https://github.com/carbon-design-system/carbon-website/issues/1681) @aagonzales @janchild 
- [ ] [Case study research](https://github.com/carbon-design-system/carbon-website/issues/1520) @mattrosno  @jillianhowarth @janchild 
- [ ] [About Carbon pages re-work](https://github.com/carbon-design-system/carbon-website/issues/1665) @janchild @jeanservaas @mjabbink @shinytoyrobots 
- [x] [Component audit](https://www.notion.so/carbondesignsystem/Token-audit-3be5016e1e0d4b48a15edcff301ca805) @aagonzales @laurenmrice 
- [ ] Document (new) naming conventions for design tokens based on audit KR @aagonzales @laurenmrice
- [ ] [Audit of components and patterns for animations](https://github.com/carbon-design-system/carbon/issues/6776) @johnbister 
- [x] [Update animation in Pattern > Forms](https://github.com/carbon-design-system/carbon-website/issues/1652)@johnbister 
- [x] [Illustrate error text with animation](https://github.com/carbon-design-system/carbon-website/issues/1653) @johnbister 
- [ ] Document first draft of all prop changes for v11 ([**KR**](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/61))  https://github.com/carbon-design-system/carbon/issues/6690#issuecomment-675669096 @joshblack 

#### [Component index ](https://github.com/carbon-design-system/carbon-website/issues/1266) - [KR: Ship an index on the Carbon site by 8/31](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/57) @andreancardona 
- [ ] [Docs (how do I add my component to the index...)](https://github.com/carbon-design-system/carbon-website/issues/1731) @shinytoyrobots 

#### [Data visualization index](https://github.com/carbon-design-system/carbon-website/issues/1647) @shinytoyrobots @aledavila 

[KR

## 💡 [Objective: Quantify where and how Carbon assets are being used](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/53)

@joshblack 

Telemetry MVP: https://github.ibm.com/carbon/ibm/issues/3
- [ ] Assess alternatives to Fathom for more granular/effective tracking - provide recommendation by end of sprint @mattrosno 

## 🛠 Support 
- [ ] [A11y website audit](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/reports/release?release=5f185c45ccda2753d030c742)
 - [x] https://github.com/carbon-design-system/carbon/issues/6000 @tw15egan 
- [x] Website vote banner https://github.com/carbon-design-system/carbon-website/issues/1672
- [x] sync TreeView expanded props and state #6788 @emyarod https://github.com/carbon-design-system/carbon/pull/6791
- [x] add DataTable custom state manager Code Sandbox example @emyarod PR: https://github.com/carbon-design-system/carbon/pull/6801
- [ ] add unstable_Tabs component #6798 @emyarod PR: https://github.com/carbon-design-system/carbon/pull/6803 
- [x] add DataTable playground story @emyarod PR: https://github.com/carbon-design-system/carbon/pull/6842
- [x] diff tablist properties on component update @emyarod PR: https://github.com/carbon-design-system/carbon/pull/6843

**Candidates**

- [ ] Accessibility @dakahn @rjhenriquez @aledavila 
  - [ ] [JAWS does not announce popup after column selection](https://github.com/carbon-design-system/carbon/issues/5242) @dakahn 
  - [ ] [JAWS 2020 Code Snippet "Copied to clipboard" and "Copyable code snippet" announced twice](https://github.com/carbon-design-system/carbon/issues/5553) @aledavila 
  - [ ] [JAWS Screenreader not Reading TextArea Placeholder and InvalidText](https://github.com/carbon-design-system/carbon/issues/5547) PR: https://github.com/carbon-design-system/carbon/pull/6819
  - [ ] [Treeview is not accessible using JAWS 2020](https://github.com/carbon-design-system/carbon/issues/6665) @dakahn 
  - [ ] [Icon tooltip uses a button element, JAWS users are lead to believe there's an action associated to the Icon](https://github.com/carbon-design-system/carbon/issues/6703)
