### ISSUE TITLE
File uploader: Enhanced UX for single file upload

### ISSUE THREAD

**Issue by garythornton** [carbon-design-system/carbon#6775]
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/14502
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3705
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/720
```

### Summary

_Please describe your request in one or two sentences._

The current file uploader UX appears to be optimized for uploading multiple files - we would like to improve the UX for uploading a **single file**.

Existing experience:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/39956961/92133556-6deed200-ee00-11ea-94b5-12c43e8d5aa2.png">

...having the provided-file displayed as a separate element below the drop target is sub-optimal when the drop target is embedded in form with other elements (such as a URL field for importing from a remote system, name and description fields). 

A current workaround is to replace the drop target with the provided file element, however if the drop target changes into a different component when the file is added, it might feel like the file has been 'processed' in some way, when actually nothing happens to the file until the user clicks the primary button (e.g 'Import'). 

_Clarify if you are asking for design, development, or both design and
development._

Needs visual design to update the following to Carbon X, and development. 

### Justification

_Provide the business reasons for this request._

We would like to improve the UX for uploading a single file, and avoid unnecessary work-arounds.

### Desired UX and success metrics

_Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user._

We think it would be good to consider an option where a single file appears in the existing boundary of the drop target, like we have today in IBM App Connect:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/39956961/92131827-557db800-edfe-11ea-9a06-936ba1118b46.png">

Advantages:
- the provided file appears where the user expects (where they dropped it / clicked to provide it).
- no additional screen real estate is required to represent the provided file.
- other surrounding elements are not displaced by the provided file element.

### "Must have" functionality

_Highlight any "must have" needs and functionality for the request._

_This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX._

### Specific timeline issues / requests

_Do you want this work within a specific time period? Is it related to an
upcoming release?_

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

_What resources do you have to assist this effort?_

We have raised this enhancement request internally in IBM here:

https://github.ibm.com/CDAI-design/pal/issues/281

Here is the relevant part of the IBM internal github enhancement request in case you don't have access:

We would like to propose the following behavior for single file import. The following screenshots are of the existing behavior in App Connect which hasn't yet been migrated to the new pattern (much of App Connect already has has been, with workarounds to address the limitations of the current pattern). 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/39956961/92139485-b231a080-ee07-11ea-8998-ae3510b2ea85.png">

As you can see below, the single file that has been provided for upload is shown in the context of the drop target, with the option to clear it. 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/39956961/92137838-93caa580-ee05-11ea-9b1d-f1c702b0d7c8.png">

This works well in a scenario like the one shown in the example because the user also has the option to provide a URL for the file (which then disables the drop target)...

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by Eva-Dage** [comment]
Based on the brief above and the mentioned Github issue ([#281](https://github.ibm.com/CDAI-design/pal/issues/281)) as well as Cloud PAL site+Carbon site material and after a few explorations and further investigation here's where we've landed (for now with expected further guidance and updates). 

********

_Details explained:_
- the standard Carbon drag and drop target with its default behaviour also based on what's on Cloud PAL site
- both, drag&drop and URL link, options are open to the user so they can choose the preferred one
- once one of the import options have been chosen, the other one gets disabled
- when using drag and drop: the uploaded file stays in the drag and drop area, filling that space with the uploaded file
- I've designed this in a side panel rather than a modal and with a little bit of context to see the situ in that location

![image](https://user-images.githubusercontent.com/56256372/92935994-7454fd80-f441-11ea-9918-1ba13aa2e9fb.png)


![image](https://user-images.githubusercontent.com/56256372/92935999-76b75780-f441-11ea-98bc-7b60cc6f6fe9.png)

****

Happy to provide specs if needed. 
Open to suggestions and guidance to make this as good as it can be.

**Comment by andreancardona** [comment]
@laurenmrice Lauren to follow up with other fellow designers and get back to us on whether to move forward or not. :)

**Comment by laurenmrice** [comment]
We would like to move forward with your contribution for a single file upload usecase ! Thank you for providing the ui flow screenshots and detailed steps of your usecase 👍🏻.

Below are some tweaks to the visuals to align with our file uploader component as a whole. I used your same scenario to show the changes to the flow:

-----------------------------------------------------------------------------------------------------------------------------------

**1. Prompt to drag and drop a file into the side panel.**
- I am displaying what file types are allowed in the subheader instead of the description inside of the upload box. You don't have to do this, but once the user uploads a file, that information will disappear. 

![1_drag and drop a file.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/8e3eace6-2894-44b2-9916-9cb87a8a1171)

-----------------------------------------------------------------------------------------------------------------------------------

**2. Uploaded file.**
- Instead of having the same size container as the upload box, we changed the size to match the normal appearance of an uploaded file with a `Replace`link. We did this to minimize the confusion of someone thinking there was more space to add more files and accidentally replacing the same file with a different file.

 ![2_uploaded file.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/8bd93622-9ea6-4274-8e31-05fe9556a8f8)

-----------------------------------------------------------------------------------------------------------------------------------

**3. Replace or change a file.**
- Hovering over the `Replace` link will change the text color, add an underline and provide a cursor change.

![3_replace or change file.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/c3049757-aa38-447d-bd1a-b204af6e1a29)

-----------------------------------------------------------------------------------------------------------------------------------

**4. File name truncation.**
- If the file name is too long for the space provided in the field, the name will truncate 16px before the Replace link. 
- Hovering over the file name will show a browser tooltip providing the full name.

![4_overflow file name.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/bdcf1bb4-3ae7-4d7b-b351-facbbcc99a28)

**Comment by laurenmrice** [comment]
![File uploader- 1 file](https://user-images.githubusercontent.com/43969356/97585917-0902c300-19d0-11eb-9955-7c6e68cf8117.png)
![File uploader- 1 file - spec](https://user-images.githubusercontent.com/43969356/97586194-5c751100-19d0-11eb-9d50-23de99944a5d.png)

**Comment by tay1orjones** [comment]
> Hovering over the file name will show a browser tooltip providing the full name.

This was brought up again just now in https://github.com/carbon-design-system/carbon/issues/13718

Now that we've got Popover and the improved Tooltip/Toggletip in v11, I think we could forego the browser-based tooltip to instead use an actual `Tooltip` to display the entire file name. Perhaps the filename text itself could receive focus to display the tooltip?
