### ISSUE TITLE
High Contrast Mode Bugs

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#6816]
## Outstanding high contrast issues in Carbon

![](http://pixelartmaker.com/art/a6cde5ac8f43d2f.png)

### Bugs
- [x] In Windows High Contrast Select's list has no border and the chevron is difficult to see https://github.com/carbon-design-system/carbon/issues/6755
- [x] Icon Only Ghost Button and Radio selection dots are invisible in Windows High Contrast #6748 
  - [Possible fix](https://github.com/carbon-design-system/carbon/pull/2779/files)
- [x] Checkbox focus outline not visible in high contrast mode  https://github.com/carbon-design-system/carbon/issues/6471
  - Blocked until we can figure out how to handle checkbox focus states
- [x] Table sort icon difficult to see in high contrast black theme https://github.com/carbon-design-system/carbon/issues/6607
- [x] In Windows High Contrast the Pagination's Next and Previous buttons are difficult to see https://github.com/carbon-design-system/carbon/issues/6767

### Enhancements
- [ ] Add support for prefers-contrast in Firefox https://github.com/carbon-design-system/carbon/issues/6530
