### ISSUE TITLE
Sprint 5 : Dingoes Ate My Design System 🐶

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#6856]
## Timeline September 21 - October 2

🗒️ **[Q3 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/roadmap)**

## PRs
- [x] **PR** Combobox dev docs PR https://github.com/carbon-design-system/carbon/pull/6734 @dakahn 
- [x] **PR** Modal code docs https://github.com/carbon-design-system/carbon/issues/6591 @emyarod PR: #6804
- [x] **PR** add unstable_Tabs component #6798 @emyarod PR: #6928 
- [x] **PR** Component Index - visual updates @andreancardona PR: https://github.com/carbon-design-system/carbon-website/pull/1826
- [x] **PR** Component Index - AI App link updates @andreancardona PR: https://github.com/carbon-design-system/carbon-website/pull/1850
## Sprint 4 🐱
- [x] [Medium article about component index](https://github.com/carbon-design-system/carbon-website/issues/1681) @aagonzales @janchild 
- [x] ModalWrapper code docs https://github.com/carbon-design-system/carbon/issues/6591 @emyarod PR: #6806

## 💡[Objective: Fix foundational issues that inhibit Carbon adoption](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/50)
- [x] Determine next steps for hanging grid in code https://github.com/carbon-design-system/carbon/issues/5892 @alisonjoseph 
- [ ] **Pictogram updates https://github.com/carbon-design-system/carbon/issues/6773** @andreancardona @emyarod (@joshblack)
  - TODO: Sync with brand on asset delivery date 
  - Currently waiting for brand to confirm pictogram name updates - working with Michael Dudley 
- [ ] **Icons plugin https://github.com/carbon-design-system/carbon/issues/6485** @andreancardona @emyarod @laurenmrice (@joshblack) (doing pictograms first before doing icons)
  - [x] use 32px assets to generate all variants #5758 @emyarod @andreancardona #6912
- [ ] Document first draft of all prop changes for v11 ([**KR**](https://app.zenhub.com/workspace/o/carbon-design-system/okrs/issues/61))  https://github.com/carbon-design-system/carbon/issues/6690#issuecomment-675669096 @joshblack @tw15egan 
- [ ] Document (new) naming conventions for design tokens based on audit KR @aagonzales @laurenmrice
- [x] FeedbackDialog Motion Specs [#1008](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1008) @johnbister 
- [ ] Audit of components and patterns for animations @johnbister (is there an issue for this?)
- [x] Begin component audit: [notion table](https://www.notion.so/carbondesignsystem/Component-audit-6e9d854209cb47a98255baabaceda3f7) @aagonzales 
- [x] [Team and leadership pages](https://github.com/carbon-design-system/carbon-website/issues/1665) @janchild @jeanservaas @mjabbink @shinytoyrobots  **Add specific deliverables**
  - [x] Add profile component to Carbon website + add team section @alisonjoseph 
- [x] [App switcher exploration](https://github.com/carbon-design-system/design-language-website/issues/718#issuecomment-689318493) review, mockups, and testing @jeanservaas @janchild @jillianhowarth  
- [ ] [What is Carbon?](https://github.com/carbon-design-system/carbon-website/issues/1824) page @janchild 

## 💡[Objective: Surface the components that IBM teams have built, so that others can consume them](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/51)
- [x] Docs (how do I add my component to the index...) @shinytoyrobots https://github.com/carbon-design-system/carbon-website/pull/1740
- [x] Data visualization index @shinytoyrobots @aledavila (Robin to refine deliverable)
- [ ] Component index - add fathom goal to track @shinytoyrobots @mattrosno 
- [ ] Research future more scalable solution to track component index @mattrosno @shinytoyrobots 

## 💡 [Objective: Quantify where and how Carbon assets are being used](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/53)

@joshblack

- [ ] Publish @carbon/telemetry package (alpha)
- [ ] Use @carbon/telemetry with at least one package
- [ ] Have it report data to our GraphQL endpoint
- [ ] Be able to see data on homepage

## 🛠 Support 

**A11y**
  - [x] Windows High Contrast Mode component audit https://github.com/carbon-design-system/carbon/issues/6869 @dakahn 
  - [ ] ~[JAWS 2020 Code Snippet "Copied to clipboard" and "Copyable code snippet" announced twice](https://github.com/carbon-design-system/carbon/issues/5553)~ @aledavila 
  - [x] [JAWS Screenreader not Reading TextArea Placeholder and InvalidText](https://github.com/carbon-design-system/carbon/issues/5547)
  - [ ] [Icon tooltip uses a button element, JAWS users are lead to believe there's an action associated to the Icon](https://github.com/carbon-design-system/carbon/issues/6703)
- [x] Cannot access button in a tooltip via keyboard navigation @emyarod #6823 PR https://github.com/carbon-design-system/carbon/pull/6901
- [x] Accept prop is not working in fileUploader component on windows [bug] #6864 @emyarod https://github.com/carbon-design-system/carbon/pull/6868
- [x] File uploader form requirements are hidden #6866 @emyarod https://github.com/carbon-design-system/carbon/pull/6867
- [x] Tabs overflow not displayed on dynamic addition of tabs #6838 @emyarod https://github.com/carbon-design-system/carbon/pull/6843
- [x] Add DataTable custom state manager example @emyarod https://github.com/carbon-design-system/carbon/pull/6842
- [x] Add `disabled` prop to `<Search/>`  #6915 @emyarod https://github.com/carbon-design-system/carbon/pull/6916
- [x] set aria-current on current active treeview node #6792 @emyarod #6937
- [x] Make placeholder styles consistent across all browsers #6918 #6144 @emyarod https://github.com/carbon-design-system/carbon/pull/6914
- [x] allow interactive elements to be keyboard focused in tooltips #6823 @emyarod https://github.com/carbon-design-system/carbon/pull/6901
- [x] validate filetypes from OS file picker in dnd FileUploader #6864 @emyarod #6868
- [X] content switcher focus styles #6465 @aledavila [PR](https://github.com/carbon-design-system/carbon/pull/6943)

**Carbon website**
- [x] https://github.com/carbon-design-system/carbon-website/issues/1768 @andreancardona 
- [x] https://github.com/carbon-design-system/carbon-website/issues/1802 @andreancardona 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/1313
- [X] https://github.com/carbon-design-system/carbon-website/issues/1310 @aledavila 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/1628 @aledavila [PR](https://github.com/carbon-design-system/carbon-website/pull/1883)
- [x] https://github.com/carbon-design-system/carbon-website/issues/1768 
- [x] [Conduct Carbon Website a11y audit](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/reports/release?release=5f185c45ccda2753d030c742) @andreancardona
