### ISSUE TITLE
Icon content switcher ☂️ 

### ISSUE THREAD

**Issue by dianasanborn** [carbon-design-system/carbon#6982]
```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/issues/12855
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3504
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/606
- [x] https://github.com/carbon-design-system/carbon/issues/12811
- [ ] https://github.com/carbon-design-system/carbon/issues/12461
```

### Summary

Within AI Applications, we have an icon-only variant of the existing Carbon [content switcher](https://www.carbondesignsystem.com/components/content-switcher/usage) that is generic and can potentially live at the Carbon level. This is useful for situations when there is limited space.

Current guidance for the [icon content switcher](https://pages.github.ibm.com/ai-applications/design/components/iconcontentswitcher/usage) on the AI Applications PAL.

### Available extra resources

We have an existing [react component] that is available today (style updates still need to be made (being tracked [here](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1536)), and we are also looking to have this available in Angular as well (tracked [here](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1643))

Design specs:
![image](https://user-images.githubusercontent.com/43549567/95243999-634ca180-07df-11eb-944a-079b88b2fe49.png)

**Comment by aagonzales** [comment]
Note: style should be updated to reflect new visuals specified in this issue: https://github.com/carbon-design-system/carbon/issues/6745

**Comment by dianatran18** [comment]
Hi! 👋 

Just wanted to provide an update on the AI Apps side —

We've updated our icon content switcher guidance to reflect the new Carbon content switcher styling, and we've also included the low-contrast variation that Noah Kawash-Barnes had worked with the Carbon team on contributing. 

![image](https://user-images.githubusercontent.com/43549567/134927845-512fc8c6-e35a-4bd1-8e36-1319dfad8766.png)


Similar to how tabs supports an icon-only version, I think this makes a lot of sense for Carbon's component to support as well for the content switcher. I'm happy to contribute our sketch assets and any guidance we have available to help move this forward! 

- [AI Apps icon content switcher guidance](https://pages.github.ibm.com/ai-applications/design/components/iconcontentswitcher/usage)
- AI Apps icon content switcher sketch assets: 
   sketch://add-library/cloud/6a99c9a7-3ece-4506-b1c7-cd19d3ded8a6:
