### ISSUE TITLE
Sprint 6: The Elephant Seal Man 🐘 🎃

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#7053]
## Timeline: October 19 - 30

🗒️ **[Q4 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/board?labels=squad%3A%20system&milestones=2020Q4%232020-12-31&repos=273306655&showEstimates=false&showReleases=false&showDependencies=false)**

## 💡 [Fix foundational issues that inhibit Carbon adoption and use](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/84)
- [ ] **Pictogram updates https://github.com/carbon-design-system/carbon/issues/6773** @andreancardona @emyarod (@joshblack)
- [ ] **Icons plugin https://github.com/carbon-design-system/carbon/issues/6485** @andreancardona @emyarod 
- [ ] Finish prop audit (v11) https://github.com/carbon-design-system/carbon/issues/6690 @tw15egan @joshblack @aledavila 
- [ ] [component audit](https://www.notion.so/carbondesignsystem/Component-audit-6e9d854209cb47a98255baabaceda3f7): @aagonzales @laurenmrice
- [x] [Document (new) naming conventions for design tokens](https://github.com/carbon-design-system/carbon/issues/7062) based on audit @aagonzales 
- [ ] Continue [motion audit of components/patterns](https://github.com/carbon-design-system/carbon-website/issues/1661) @johnbister 
- [ ] [Develop case study content](https://github.com/carbon-design-system/carbon-website/issues/1919) for the IBM.com checkout improvements @jillianhowarth @janchild 
- [x] [Upload one file usecase](https://github.com/carbon-design-system/carbon/issues/6775) @laurenmrice 
- [ ] [Contextual menu](https://github.com/carbon-design-system/carbon/issues/6830) @laurenmrice 

## 💡 [Community assets can be published at the same standard of completeness and quality as the common assets](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/89)
- [ ] Chart index thumbnail images @jeanservaas 
- [ ] [Production guidelines](https://github.com/carbon-design-system/carbon-website/issues/1939) @jeanservaas 
- [ ] [Content guidelines](https://github.com/carbon-design-system/carbon-website/issues/859) @janchild @jillianhowarth 
  - [x] [Review support channels to gather content issues](https://github.com/carbon-design-system/carbon-website/issues/1902) @jillianhowarth 
  - [x] [Set up PR with proposed new structure](https://github.com/carbon-design-system/carbon-website/issues/1909) @janchild 

## 💡 [Release common layout packages or code examples](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/94)

- ~Write out ideas for CSS Grid integration~ 
- ~Identify common layouts and try to build them out with CSS Grid proposal~
- [x] Conduct user research around usage of our grid and document results @rjhenriquez @alisonjoseph 

### Analytics

- [x] Integrate GraphQL with DB
- [ ] Release version 0.0.1 for test with users
- [x] UI

## Index 
- [x] Component index - add fathom goal to track @mattrosno
- [ ] ~[Repurpose components index to be reusable with charts and patters](https://github.com/carbon-design-system/carbon-website/issues/1903)~ @aledavila hold for now until we figure out what we want to do with this

## 🛠 Support 

- Support days 🎉 

**Website**
- [ ] https://github.com/carbon-design-system/carbon-website/issues/1313
- [x] https://github.com/carbon-design-system/carbon-website/issues/1679 [PR](https://github.com/carbon-design-system/carbon-website/pull/1904) @alisonjoseph 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/1876 (need to check w/ aux if this is a theme or website bug)

**Design System**
- [ ] https://github.com/carbon-design-system/carbon/issues/7016 @tw15egan 
- [ ] https://github.com/carbon-design-system/carbon/issues/7019 @tw15egan [PR](https://github.com/carbon-design-system/carbon/pull/7085)
- [x] fix(OverflowMenu): remove default tabindex and SVG focusable attribute #6976
- [x] feat(TimePicker): add size variants #7046 @emyarod
- [x] fix(Tabs): prevent unnecessary vertical scrolling #7111 @emyarod
- [x] fix(Tabs): remove nested tabs selector #7109 @emyarod
- [x] fix(ComposedModal): remove invalid DOM attribute #7110 @emyarod
- [x] fix(multi-select): update filterable multiselect default styles  #7108 @emyarod
- [x] fix(Tabs): keep selected tab in view #7045 @emyarod
- [x] fix(Tabs): improve screen reader support #6989 @emyarod
- [x] feat(OverflowMenu): add size variants #7116 @emyarod
- [x] fix(Tabs): reduce scroll speed on overflow nav buttons #7148 @emyarod

- **WCAG 2.1 AA issues** 
  - [ ] Refactor and update accessibility testing for Accordion, Link, Breadcrumb, Tabs, ContentSwitcher #7182  @dakahn 
- [ ]  SSL Cert for website https://github.com/carbon-design-system/carbon-website/issues/1847
- [ ] Tutorial / Icons https://github.com/carbon-design-system/carbon-website/issues/1846 @rjhenriquez
