### ISSUE TITLE
Component audit

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7103]
Auditing all components (and variants) to fix existing bugs and to ensure consistency.

Audit table: https://www.notion.so/carbondesignsystem/Component-audit-6e9d854209cb47a98255baabaceda3f7

---------------------------------------------------------------------------------------------------------

### Accordion
- [x] #7000 Missing disabled state
- [x] [#1894](https://github.com/carbon-design-system/carbon-website/issues/1894) Website: Add disabled style to style tab
- [x] [1915](https://github.com/carbon-design-system/carbon-website/issues/1915) Website: Add disabled state to live demo
- [ ] [372](https://github.com/carbon-design-system/carbon-design-kit/issues/372) Design kit: Disabled state bug
- [x] [377](https://github.com/carbon-design-system/carbon-design-kit/issues/377) Design kit: Add large and small sizes
---------------------------------------------------------------------------------------------------------

### Breadcrumb
- [x] #7016 Hover state bug
- [x] #7019 Overflow option
- [x] [1891](https://github.com/carbon-design-system/carbon-website/issues/1891) Website: Update code on style tab
- [x] [1982](https://github.com/carbon-design-system/carbon-website/issues/1982) Website: Update style images
- [x] [374](https://github.com/carbon-design-system/carbon-design-kit/issues/374) Design kit: State bugs
---------------------------------------------------------------------------------------------------------

### Button
- [x] #7025 Inset focus bug
- [x] #7021 Disabled state bug
- [x] #7026 Tertiary button active state bug
- [x] #7091 Ghost button padding bug
- [x] [1926](https://github.com/carbon-design-system/carbon-website/issues/1926) Website: Update style tab tables
- [x] [1982](https://github.com/carbon-design-system/carbon-website/issues/1983) Website: Update style images
- [x] [1927](https://github.com/carbon-design-system/carbon-website/issues/1927) Website: Update usage tab with danger variants
- [x] [378](https://github.com/carbon-design-system/carbon-design-kit/issues/378) Design kit: Ghost button state bugs
- [x] [379](https://github.com/carbon-design-system/carbon-design-kit/issues/379) Design kit: Disabled button text bug
- [x] [380](https://github.com/carbon-design-system/carbon-design-kit/issues/380) Design kit: Add tertiary and ghost variants for danger button
------------------------------------------------------------------------------------------------------------

### Checkbox
- [x] #7119 Checkbox icons incorrect color
- [x] #7125 Disable heading when using disable prop
- [ ] [1925](https://github.com/carbon-design-system/carbon-website/issues/1925) Website: Update live demo
- [x] [381](https://github.com/carbon-design-system/carbon-design-kit/issues/381) Design kit: Icon color bug
- [x] [339](https://github.com/carbon-design-system/carbon-design-kit/issues/339) Design kit: Update focus styles
---------------------------------------------------------------------------------------------------------

### Code snippet
- [x] [#7159](https://github.com/carbon-design-system/carbon/issues/7159) Single line and Multi-line bugs
- [x] [1931](https://github.com/carbon-design-system/carbon-website/issues/1931) Website: Update style tab tables
- [ ] [1932](https://github.com/carbon-design-system/carbon-website/issues/1932) Website: Update live demo
- [x] [1976](https://github.com/carbon-design-system/carbon-website/issues/1976) Website: Add light prop style docs
- [x] [1984](https://github.com/carbon-design-system/carbon-website/issues/1984) Website: Update style images
- [x] https://github.com/carbon-design-system/carbon/issues/7397 Code: change show more btn size
- [ ] [395](https://github.com/carbon-design-system/carbon-design-kit/issues/395) Kit: update show more btn size

---------------------------------------------------------------------------------------------------------

### Content switcher
- [x] [385](https://github.com/carbon-design-system/carbon-design-kit/issues/385) Design kit: Audit bugs
- [x] [367](https://github.com/carbon-design-system/carbon-design-kit/issues/367) Design kit: Add size variants
- [x] [2027](https://github.com/carbon-design-system/carbon-website/issues/2027) Website: add documentation for size variants 

---------------------------------------------------------------------------------------------------------

### Data table
- [x] https://github.com/carbon-design-system/carbon/issues/7219 Assorted bugs
- [x] https://github.com/carbon-design-system/carbon/issues/7283 Assorted bugs v2
- [x] [1975](https://github.com/carbon-design-system/carbon-website/issues/1975) Website: docs updates 
- [ ] [386](https://github.com/carbon-design-system/carbon-design-kit/issues/386) Design kit:  audit bugs
- [ ] [1949](https://github.com/carbon-design-system/carbon-website/issues/1949) Website: Live demo bugs

---------------------------------------------------------------------------------------------------------

### Date Picker

- [x] https://github.com/carbon-design-system/carbon/issues/7334 Code bugs
- [ ] [#2003](https://github.com/carbon-design-system/carbon-website/issues/2003) Website: Live demo bugs
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/393 Kit: various bugs
- [x] https://github.com/carbon-design-system/carbon-website/issues/2005 Website: style and usage tab updates
- [x] [351](https://github.com/carbon-design-system/carbon-design-kit/issues/351) Design kit: Add warning state

---------------------------------------------------------------------------------------------------------

### Dropdown
(dropdown/combobox/multi-select)
- [x] #7325 Code bugs
- [x] [1985](https://github.com/carbon-design-system/carbon-website/issues/1985) Website: Update style tab tables 
- [x] [1997](https://github.com/carbon-design-system/carbon-website/issues/1997) Website: Update style tab images
- [ ] [1987](https://github.com/carbon-design-system/carbon-website/issues/1987) Website: Live demo bugs
- [x] [2004](https://github.com/carbon-design-system/carbon-website/issues/2004) Website: Update usage guidance
- [x] [2037](https://github.com/carbon-design-system/carbon-website/issues/2037) Website: Edit guidance when using "optional" text
- [x] [351](https://github.com/carbon-design-system/carbon-design-kit/issues/351) Design kit: Add warning state
- [x] [391](https://github.com/carbon-design-system/carbon-design-kit/issues/391) Design kit: Multi-select label bug
- [x] [392](https://github.com/carbon-design-system/carbon-design-kit/issues/392) Design kit: Multi-select tag hover bug

---------------------------------------------------------------------------------------------------------

### File uploader
- [x] [#7448](https://github.com/carbon-design-system/carbon/issues/7448) Code bugs
- [x] [2045](https://github.com/carbon-design-system/carbon-website/issues/2045) Website: Update style tab
- [ ] [2046](https://github.com/carbon-design-system/carbon-website/issues/2046) Website: Live demo bugs
- [x] [396](https://github.com/carbon-design-system/carbon-design-kit/issues/396) Design kit: Add focus state

---------------------------------------------------------------------------------------------------------

### Inline loading
- [x] https://github.com/carbon-design-system/carbon/issues/7497 Code bugs
- [x] [ #2059](https://github.com/carbon-design-system/carbon-website/issues/2059) Website: Update style tab

---------------------------------------------------------------------------------------------------------

### Link
- [x] https://github.com/carbon-design-system/carbon/issues/7498 Code bugs
- [x] [#2060](https://github.com/carbon-design-system/carbon-website/issues/2060) Website: update usage and style tab
- [ ] [ #2061](https://github.com/carbon-design-system/carbon-website/issues/2061) Website: live demo bugs

---------------------------------------------------------------------------------------------------------

### List

- [x] https://github.com/carbon-design-system/carbon/issues/7504 Code bugs
- [ ] [#2064](https://github.com/carbon-design-system/carbon-website/issues/2064) Website: live demo bugs
- [x] [#2065](https://github.com/carbon-design-system/carbon-website/issues/2065) Website: Update style tab
- [ ] Website: Usage still needs to major content update*

---------------------------------------------------------------------------------------------------------

### Loading
- [x] https://github.com/carbon-design-system/carbon/issues/7655 Code bugs
- [ ] [#2106](https://github.com/carbon-design-system/carbon-website/issues/2106) Website: Live demo bugs
- [ ] Website: Usage page need major update

---------------------------------------------------------------------------------------------------------

### Modal

---------------------------------------------------------------------------------------------------------

### Notification

---------------------------------------------------------------------------------------------------------

### Number input
- [x] [7570](https://github.com/carbon-design-system/carbon/issues/7570) Code bugs
- [ ] [2082](https://github.com/carbon-design-system/carbon-website/issues/2082) Website: style tab updates
- [ ] [2083](https://github.com/carbon-design-system/carbon-website/issues/2083) Website: usage tab doc updates
- [ ] [300](https://github.com/carbon-design-system/carbon-design-kit/issues/300) Design kit: Audit fixes

**Comment by aagonzales** [comment]
Closing this as we're about to start another audit
