### ISSUE TITLE
Sprint 7: Freaky Frog-Day 🐸

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#7166]
## Timeline: November 2 - 13

🗒️ **[Q4 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/board?labels=squad%3A%20system&milestones=2020Q4%232020-12-31&repos=273306655&showEstimates=false&showReleases=false&showDependencies=false)**

## 💡 [Fix foundational issues that inhibit Carbon adoption and use](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/84)
**Key results**
- Close 50% of issues from the component consistency audit
- Publish scope of next major release by 11/13/20
- Document token naming conventions

**Issues**
- [ ]  [Develop case study content](https://github.com/carbon-design-system/carbon-website/issues/1919) for the IBM.com checkout improvements @jillianhowarth @janchild 
- [ ] Icons, Pictograms, and Sketch
   - [ ] https://github.com/carbon-design-system/carbon/issues/6923
   - [x] Pictograms: Update existing & add net new pictograms #7094 @andreancardona @emyarod 
   - [x] Pictograms: remove marked for _deprecation_ pictograms #7272 
   - Next steps: Work with brand to outline and understand all steps for deprecation process
- [x] [2021 Release Announcement](https://github.com/carbon-design-system/carbon/issues/7177)
- [ ] Continue [motion audit of components/patterns](https://github.com/carbon-design-system/carbon-website/issues/1661) @johnbister 
- [x] [FeedbackDialog Motion Specs](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1008) @johnbister
- [x] [Add playbar, volume, and fullscreen controls to tutorials](https://github.com/carbon-design-system/carbon-website/issues/1899) @johnbister
- [ ] Additional Motion Guidance for design-dev collaboration #7114 @johnbister
- [ ] Prop audit
  - [ ] https://github.com/carbon-design-system/carbon/issues/7201 @aledavila 
- [x] [component audit](https://www.notion.so/carbondesignsystem/Component-audit-6e9d854209cb47a98255baabaceda3f7) (ongoing): @aagonzales @laurenmrice
- [x] [Contextual menu](https://github.com/carbon-design-system/carbon/issues/6830) @laurenmrice 

## 💡 [Community assets can be published at the same standard of completeness and quality as the common assets](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/89)
**Key results**
- Publish updated content guidelines
- Publish production guidelines
- Deliver a Sketch Assistant
- Publish 3 packages for Storybook, testing and linting styles
- Provide a CLI for scaffolding new components

**Issues**
- [ ] [Content guidelines](https://github.com/carbon-design-system/carbon-website/issues/859) @janchild @jillianhowarth
- [ ] [Production guidelines](https://github.com/carbon-design-system/carbon-website/issues/1939) @jeanservaas 
- [x] Investigate patterns contribution process @jeanservaas @aagonzales 
- [ ] Work with Mariuscz on data viz master kit file

## 💡 [Release common layout packages or code examples](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/94)

- [x] [Synthesize Grid Research](https://github.com/carbon-design-system/carbon/issues/7172)
- [x] [Playback Grid Research](https://github.com/carbon-design-system/carbon/issues/7173)

### Analytics

- [x] [Implement mutation for packageInstalls](https://github.ibm.com/carbon/ibm/issues/57) (3)
- [ ] [Publish initial telemetry version with sponsor user](https://github.ibm.com/carbon/ibm/issues/58) (5)
- [x] [Add GraphQL Query for packages page](https://github.ibm.com/carbon/ibm/issues/59) (5)

## 🛠 Support 

- Support days 🎉  (3-4)

**Website**
- [x] [Remove Halloween fun from website](https://github.com/carbon-design-system/carbon-website/issues/1943) @jnm2377 
- [ ] Exchange vote banner from website for a CTA around Cheryl Miller's Digital Leaders' Summit content @jeanservaas 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/1313
- [ ] https://github.com/carbon-design-system/carbon-website/issues/1452 **(a11y)** @dakahn 
- [ ] ~~https://github.com/carbon-design-system/carbon-website/issues/1412~~ 
  - ACTION NEEDED: Bring to theme / aux squad (@joshblack to follow-up with @jnm2377 )
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1049 @alisonjoseph PR https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1050
- [ ] https://github.com/carbon-design-system/carbon-website/issues/1936
- [x] chore: lint and format #1961 @emyarod
- [x] fix: restore function to DataTable live demo knobs #1960 @emyarod
- [x] fix(developer-resources): 1953-aat-avt1-developer-resources-alt-text #7133 @andreancardona 
- [x] fix(partners-page): partners page H3 heading change @janchild @andreancardona #1951
- [x] fix(developer-resources): 1953-aat-avt1-developer-resources-alt-text @andreancardona #1953
- [x] fix(designing-tutorials): inline frame title @andreancardona #1958

**Design System**

- [ ] https://github.com/carbon-design-system/carbon/issues/7016 @tw15egan 
- [x] https://github.com/carbon-design-system/carbon/issues/7219 @tw15egan 
- [ ] Tutorial / Icons https://github.com/carbon-design-system/carbon-website/issues/1846 @rjhenriquez 
- [ ] Storybook fixes
  - [ ] https://github.com/carbon-design-system/carbon/issues/7169 @aledavila 
  - [ ] https://github.com/carbon-design-system/carbon/issues/7168 @aledavila 
- [ ] Refactor and update accessibility testing for Accordion, Link, Breadcrumb, Tabs, ContentSwitcher #7182  @dakahn 
  - [ ] Determine accessibility requirements for Accordion and document in the project #7204 
  - [ ] Determine accessibility requirements for Link and document in the project #7205 
- [x] A11y
  - [x] https://github.com/carbon-design-system/carbon/issues/7132 
- [x] fix(Tabs): update scrollable container tabs selectors #7184 @emyarod
- [x] feat(Tabs): add support for Home and End key navigation #7155 @emyarod
- [x] fix(themes): deprecate danger token #7179 @emyarod
- [x] fix(TextArea): remove placeholder attributes if values are falsy #7156 @emyarod
- [x] fix(button): update button kind prop type #7212 @emyarod
- [x] feat(Search): add Esc button support to clear input field #7230 @emyarod
- [x] fix: word wrap by default in TooltipDefinition and TooltipIcon #7187 @emyarod
- [x] fix: resolve icon-only button tooltip/label regression #7253 @emyarod
- [x] fix(tooltip): add :active:visited styles on links #7276 @emyarod
- [x] feat: add active-light-ui token and update hover-light-ui  #7275 @emyarod
- [x] feat(pictograms): update existing and add net new pictograms #7094 @emyarod @andreancardona 
- [x] fix(code-snippet): update component to spec #7214 @emyarod
