### ISSUE TITLE
Sprint 8: Ghost in the Gazelle 👻

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#7248]
## November 16th - 24th

🗒️ **[Q4 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/board?labels=squad%3A%20system&milestones=2020Q4%232020-12-31&repos=273306655&showEstimates=false&showReleases=false&showDependencies=false)**

## 💡 [Fix foundational issues that inhibit Carbon adoption and use](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/84)
**Key results**
- Close 50% of issues from the component consistency audit
- ~~Publish scope of next major release by 11/13/20~~
- Document token naming conventions

**Issues**
- [ ]  [Develop case study content](https://github.com/carbon-design-system/carbon-website/issues/1919) for the IBM.com checkout improvements @jillianhowarth @janchild 
- [x] Pictograms https://github.com/carbon-design-system/carbon/issues/6923 @emyarod @andreancardona 
- [ ] Continue [motion audit of components/patterns](https://github.com/carbon-design-system/carbon-website/issues/1661) @johnbister 
- [ ] Additional Motion Guidance for design-dev collaboration #7114 @johnbister
- [x] Prop Audit (5 components) https://github.com/carbon-design-system/carbon/issues/7201 @aledavila 
- [x] Accordion a11y tests and docs https://github.com/carbon-design-system/carbon/issues/7204 @dakahn 
- [ ] [component audit](https://www.notion.so/carbondesignsystem/Component-audit-6e9d854209cb47a98255baabaceda3f7) (ongoing): @aagonzales @laurenmrice

## 💡 [Community assets can be published at the same standard of completeness and quality as the common assets](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/89)
**Key results**
- Publish updated content guidelines
- Publish production guidelines
- ~~Deliver a Sketch Assistant~~
- Publish 3 packages for Storybook, testing and linting styles
- Provide a CLI for scaffolding new components

**Issues**
- [ ] [Content guidelines](https://github.com/carbon-design-system/carbon-website/issues/859) @janchild @jillianhowarth 
- [ ] [Production guidelines](https://github.com/carbon-design-system/carbon-website/issues/1939) @jeanservaas 
- [ ] Pattern template for multiple variants @jeanservaas @aagonzales @janchild  
   - [x] [Notion outline](https://www.notion.so/carbondesignsystem/Pattern-template-multiple-with-Types-heading-1fbaa0522eca44b893b5f81bdf755154)
   - [ ] Publish template
- [ ] Explore storybook config package @aledavila @andreancardona 
- [x] Explore Jest config package @dakahn 
- [x] Investigate and ideate on Sketch Assistant: [Repo](https://github.com/carbon-design-system/carbon-sketch-assistant) @aagonzales + AUX 

## 💡 [Release common layout packages or code examples](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/94)

- N/A

## 🛠 Support 

- Support days 🎉  (3-4)

**Website**

- [x] https://github.com/carbon-design-system/carbon-website/issues/1452 @dakahn 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/1936 (in PR)

**Design System**

- Style Audit (Dev + Design) https://github.com/carbon-design-system/carbon/issues/7103 @tw15egan @aagonzales @laurenmrice 
- Storybook
  - [x] https://github.com/carbon-design-system/carbon/issues/7169 @aledavila 
  - [x] https://github.com/carbon-design-system/carbon/issues/7168 @aledavila 
- Candidates
  - Bidirectional support
    - https://github.com/carbon-design-system/carbon/issues/7264
    - https://github.com/carbon-design-system/carbon/issues/7265
    - https://github.com/carbon-design-system/carbon/issues/7266
- [x] [OverflowMenuItem] itemText cannot put Tooltip component #7088 PR #7277 @emyarod
- [x] Code Snippet overflow indicators #7159 PR #7229 @emyarod
- [x] NumberInput: uncontrolled NumperInput not respecting `defaultValue` #7299 PR #7312 @emyarod
