### ISSUE TITLE
Sprint 9: Hyena Hairspray 🐕

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#7352]
## November 30th - December 11th

🗒️ **[Q4 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/board?labels=squad%3A%20system&milestones=2020Q4%232020-12-31&repos=273306655&showEstimates=false&showReleases=false&showDependencies=false)**

## 💡 [Fix foundational issues that inhibit Carbon adoption and use](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/84)
**Key results**
- Close 50% of issues from the component consistency audit
- ~~Publish scope of next major release by 11/13/20~~
- ~~Document token naming conventions~~

**Issues**
- [ ]  [Develop case study content](https://github.com/carbon-design-system/carbon-website/issues/1919) for the IBM.com checkout improvements @jillianhowarth @janchild 
- Pictograms @emyarod @andreancardona 
  - [x] https://github.com/carbon-design-system/carbon/issues/7355
  - [x] Ship pictogram updates on Carbon website (sync with aux for IDL update)
- Icon sketch plugin fixes @andreancardona @emyarod 
  - [ ] https://github.com/carbon-design-system/carbon/issues/6922 PR #7429
- [ ] Address issues from component [consistency audit](https://github.com/carbon-design-system/carbon/issues/7103) @laurenmrice @aagonzales @tw15egan 
- [x] Add warning symbols for date picker, dropdown, number input, multi-select, and text input @laurenmrice 
- [x] Audit file uploader component @laurenmrice 
- [ ] Audit 3 more components: form, inline loading, and link @aagonzales 

## 💡 [Community assets can be published at the same standard of completeness and quality as the common assets](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/89)
**Key results**
- Publish updated content guidelines
- Publish production guidelines
- ~~Deliver a Sketch Assistant~~
- Publish 3 packages for Storybook, testing and linting styles
  - [x] Storybook https://github.com/carbon-design-system/carbon/issues/7361 @aledavila @andreancardona (@joshblack)
  - [x] Testing @dakahn (@joshblack)
  - Linting
    - [x] ESLint
    - [x] StyleLint
- [ ] Provide a CLI for scaffolding new components https://github.com/carbon-design-system/carbon/issues/7360 @joshblack  + dev

**Issues**
- [ ] [Content guidelines] epic (https://github.com/carbon-design-system/carbon-website/issues/859) @janchild @jillianhowarth 
  - [ ] [Audit for content patterns](https://github.com/carbon-design-system/carbon-website/issues/1908) @janchild 
  - [ ] Draft [content patterns](https://github.com/carbon-design-system/carbon-website/issues/2017) @janchild 
- [ ] [Production guidelines](https://github.com/carbon-design-system/carbon-website/issues/1939) @jeanservaas 
- [ ] Pattern template for multiple variants @jeanservaas @aagonzales @janchild  
   - [x] [Notion outline](https://www.notion.so/carbondesignsystem/Pattern-template-multiple-with-Types-heading-1fbaa0522eca44b893b5f81bdf755154)
   - [ ] [Publish template](https://github.com/carbon-design-system/carbon-website/issues/2018) @janchild 

## 💡 [Release common layout packages or code examples](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/94)

-

## 🛠 Support 
- [ ] [Update/overhaul Button Accessibility Testing](https://github.com/carbon-design-system/carbon/issues/7363) @dakahn 
- [ ] [Update/overhaul Checkbox Accessibility Testing](https://github.com/carbon-design-system/carbon/issues/7364) @dakahn 
- [ ] [Update/overhaul CodeSnippet Accessibility Testing @dakahn 
](https://github.com/carbon-design-system/carbon/issues/7365) @dakahn 
- [ ] Combobox: `role="combobox"` attribute is on the wrong element causing Accessibility Checker error #7331 
- [ ] Dropdown is not accessible in Windows High Contrast Mode #6860 
- [ ] Tabs control: tabpanel needs to be in tab order if there's no focusable tabpanel content #7078 
- [x] Data table sortable headers visual and programmatic labels do not match #7369 @jnm2377 
- [x] Bug: issue related to overflow menu item's z-index and position #7308 PR #7323 @emyarod
- [ ] Tabs: Form control element <button> has no associated label #7304 PR #7353 @emyarod
- [x] [Tabs] Offer control to disable scrollIntoView for Tabs #7399 PR #7410 @emyarod
- [x] Tab: renderAnchor/renderButton no longer runs cleanly #7416 PR #7418 @emyarod
- [x] Tooltips disappearing when clicking different tooltips #7260 PR #7319 @emyarod
- [ ] [DataTable]: Expansion clickable area is not up to specification #6589 PR #7392 @emyarod
- [x] [code-snippet]: min-width causes reflow (400%) violation #7406 PR #7420 @emyarod
- [ ] v10.25.0: pagination component padding #7424 PR #7427 @emyarod

**Website**
 
- [x] https://github.com/carbon-design-system/carbon-website/issues/1936 ([PR](https://github.com/carbon-design-system/carbon-website/pull/2007))

**Design System**
- Candidates
  - Bidirectional support @shinytoyrobots + dev
    - [ ] https://github.com/carbon-design-system/carbon/issues/7264
    - [ ] https://github.com/carbon-design-system/carbon/issues/7265
    - [ ] https://github.com/carbon-design-system/carbon/issues/7266
