### ISSUE TITLE
Sprint 10: The Ice Storm Irish Setter  ⛄ 🐶 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#7436]
## December 14th - EOY

🗒️ **[Q4 OKRs](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/board?labels=squad%3A%20system&milestones=2020Q4%232020-12-31&repos=273306655&showEstimates=false&showReleases=false&showDependencies=false)**

## 💡 [Fix foundational issues that inhibit Carbon adoption and use](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/84)
**Key results**
- Close 50% of issues from the component consistency audit
- ~~Publish scope of next major release by 11/13/20~~
- ~~Document token naming conventions~~

**Issues**
- [ ]  [Develop case study content](https://github.com/carbon-design-system/carbon-website/issues/1919) for the IBM.com checkout improvements @jillianhowarth @janchild 
- [ ] Address issues from component [consistency audit](https://github.com/carbon-design-system/carbon/issues/7103) @laurenmrice @aagonzales @tw15egan 
- [x] Add tertiary and ghost danger buttons to design kits @laurenmrice 
- [x] Audit 3 more components: form, inline loading, and link @aagonzales 

## 💡 [Community assets can be published at the same standard of completeness and quality as the common assets](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/89)
**Key results**
- Publish updated content guidelines - Phase 1 complete
- Publish production guidelines
- ~~Deliver a Sketch Assistant~~

**Issues**
- [ ] [Content guidelines] epic (https://github.com/carbon-design-system/carbon-website/issues/859) @janchild @jillianhowarth 
  - [x] [Audit for content patterns](https://github.com/carbon-design-system/carbon-website/issues/1908) @jillianhowarth  
  - [ ] Phase 2 content guidelines -- draft [content patterns](https://github.com/carbon-design-system/carbon-website/issues/2017) @janchild 
- [ ] [Production guidelines](https://github.com/carbon-design-system/carbon-website/issues/1939) @jeanservaas 
- [x] Pattern template for multiple variants @jeanservaas @aagonzales @janchild  
   - [x] [Finalize and publish template](https://github.com/carbon-design-system/carbon-website/issues/2018) @janchild 
   - [x] Update other pattern template to match @janchild 

## 💡 [Release common layout packages or code examples](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/94)

-

## 🛠 Support 
- [ ] Combobox: `role="combobox"` attribute is on the wrong element causing Accessibility Checker error #7331 @dakahn 
- [x] Datepicker: Content not within a landmark #7246 @dakahn #7465  
- [ ] Dropdown is not accessible in Windows High Contrast Mode #6860 
- [ ] Tabs control: tabpanel needs to be in tab order if there's no focusable tabpanel content #7078 

**Website**
 

**Design System**
- Candidates
  - Bidirectional support @shinytoyrobots + @joshblack @andreancardona 
    - [ ] https://github.com/carbon-design-system/carbon/issues/7264
    - [ ] https://github.com/carbon-design-system/carbon/issues/7265
    - [ ] https://github.com/carbon-design-system/carbon/issues/7266
