### ISSUE TITLE
Sprint 1: Jumanji Jellyfish  🎐

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#7520]
## January 11th - January 22nd

**Team issues**
- Grid discussion, planning 

**Ale**
- Continue Storybook config migration to package - Epic: https://github.com/carbon-design-system/carbon/issues/7361
  - [x] Move over custom plugins (pair with Andrea) 
- [ ] https://github.com/carbon-design-system/carbon/issues/7476
- [ ] https://github.com/carbon-design-system/carbon/issues/7330
- [ ] https://github.com/carbon-design-system/carbon/issues/7016 [PR](https://github.com/carbon-design-system/carbon/pull/7085)

**Andrea**
-  Continue Storybook config migration to package - Epic: https://github.com/carbon-design-system/carbon/issues/7361
   -  [x] Move over custom plugins (pair with Andrea) 
- [ ] Sketch plugin with Andrew
- [ ] Website a11y issues (2x)
- BIDI/RTL (pair with Josh)

**Andrew**
- Sketch plugin with Andrea
  - opened #7614
- [x] Continue bug fixes and support
  - [x] Expansion clickable area is not up to specification #6589 https://github.com/carbon-design-system/carbon/pull/7392
  - [x] IE11: Single line code snippet is overflowing bounds #2060 https://github.com/carbon-design-system/carbon/pull/7503
  - [x] CSS styling is not correct for disabled select item in firefox #7475 https://github.com/carbon-design-system/carbon/pull/7477
  - [x] [Tooltip/TooltipDefinition] Support for hover or truncation with ellipses #6484 https://github.com/carbon-design-system/carbon/pull/7437
  - [x] Tabs: apply `scrollIntoView` prop on mount https://github.com/carbon-design-system/carbon/pull/7543
  - [x] [list] audit bugs #7504 https://github.com/carbon-design-system/carbon/pull/7526
  - [x] Tab without id prop fails accessibility #7511 https://github.com/carbon-design-system/carbon/pull/7519
  - [x]  [inline loading] audit bugs #7497 https://github.com/carbon-design-system/carbon/pull/7499
  - [x] PasswordInput: Show/Hide password button is not disabled #7480 https://github.com/carbon-design-system/carbon/pull/7482
  - [x]  A disabled state/attribute for CodeSnippet #7455 https://github.com/carbon-design-system/carbon/pull/7478
  - [x] If I use Dropddown or ComboBox in TableToolbarMenu, the popup menu will be closed upon selecting an option #6412 https://github.com/carbon-design-system/carbon/pull/7456
  - [x] Tabs: Form control element <button> has no associated label #7304 https://github.com/carbon-design-system/carbon/pull/7353

**Anna**
- [Component audit](https://github.com/carbon-design-system/carbon/issues/7103)
  - [x] Resolve website bugs for: date picker, dropdown, file uploader ...
  - [ ] Audit 3 components: loading, modal, notifications ... 

**DA**
- [ ] Continue component a11y testing and docs
- [x] HCM
  - [x] https://github.com/carbon-design-system/carbon/issues/6872
  - [x] https://github.com/carbon-design-system/carbon/issues/6874 https://github.com/carbon-design-system/carbon/pull/7601
  - [x] https://github.com/carbon-design-system/carbon/issues/7562 https://github.com/carbon-design-system/carbon/pull/7601
- [x] https://github.com/carbon-design-system/carbon/issues/6480 https://github.com/carbon-design-system/carbon/pull/7620

**Jan**
- [ ] [Content guidelines] epic (https://github.com/carbon-design-system/carbon-website/issues/859) @janchild 
  - [ ] Phase 2 content guidelines -- draft [content patterns](https://github.com/carbon-design-system/carbon-website/issues/2017) @janchild

**Jeannie**
- [ ] Concept work with Matt

**Jillian**
- [x] [Review and update Slack support audit](https://github.com/carbon-design-system/carbon/issues/7516)  
- [ ] [Develop case study content](https://github.com/carbon-design-system/carbon-website/issues/2071) for the Cloud transition to Carbon 10 @jillianhowarth 

**Josh**
- [x] Add Sass modules for additional style entrypoints
- [ ] Profile compilation time when using Sass Modules 
- [x] Create RFC discussions for v11 features/functionality/change
- BIDI/RTL
  - [ ] Add support for testing RTL in Storybook
  - [ ] Create plan for components to be authored in RTL

**Lauren**
- [Component audit fixes](https://github.com/carbon-design-system/carbon/issues/7103)
  - [x] Audit number input 
  - [x] Kit issue: [Accordion sizes](https://github.com/carbon-design-system/carbon-design-kit/issues/377)
  - [x] Kit issue: [Breadcrumb state bugs](https://github.com/carbon-design-system/carbon-design-kit/issues/374)
  - [x] Kit issue: [Checkbox focus styles](https://github.com/carbon-design-system/carbon-design-kit/issues/339)
  - [x] Kit issue: [Link sizes](https://github.com/carbon-design-system/carbon-design-kit/issues/373) and [Link focus state](https://github.com/carbon-design-system/carbon-design-kit/issues/333)
  - [x] Kit issue: [Tab light variant](https://github.com/carbon-design-system/carbon-design-kit/issues/366)

**TJ**
- Continue component audit fixes
- [x] https://github.com/carbon-design-system/carbon/issues/6480
- [x] https://github.com/carbon-design-system/carbon/issues/6994

**Comment by joshblack** [comment]
## Development

**Ale**
- Continue Storybook config migration to package
  - Move over custom plugins (pair with Andrea)
- https://github.com/carbon-design-system/carbon/issues/7476
- https://github.com/carbon-design-system/carbon/issues/7330
- https://github.com/carbon-design-system/carbon/issues/7016

**Andrea**
- Sketch plugin with Andrew
- Continue Storybook config migration to package
  - Move over custom plugins (pair with Ale)
- Website a11y issues (2x)

**Andrew**
- Sketch plugin with Andrea
- Continue bug fixes and support

**DA**
- Continue component a11y testing and docs
- HCM
  - https://github.com/carbon-design-system/carbon/issues/6872
  - https://github.com/carbon-design-system/carbon/issues/6874
- https://github.com/carbon-design-system/carbon/issues/6480

**Josh**
- Add Sass modules for additional style entrypoints
- Profile compilation time when using Sass Modules
- Create RFC discussions for v11 features/functionality/change
- BIDI/RTL
  - Add support for testing RTL in Storybook
  - Create plan for components to be authored in RTL

**TJ**
- Continue component audit fixes
- https://github.com/carbon-design-system/carbon/issues/6480
- https://github.com/carbon-design-system/carbon/issues/6994
