### ISSUE TITLE
Sprint 2: Karate Kid Koala 🥋

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#7616]
## January 25th - February 5th

**Team issues**
- Grid discussion, planning 
- Release planning

**Ale**
- [ ] https://github.com/carbon-design-system/carbon/issues/7476
- [ ] https://github.com/carbon-design-system/carbon/issues/7330
- [x] https://github.com/carbon-design-system/carbon/issues/7016
- [ ] Popover component, pair with @joshblack 

**Andrea**
- [ ] Sketch pictogram/plugin work - Epic: https://github.com/carbon-design-system/carbon/issues/6485
  - [x] Updated symbol name to existing format - PR #7648 
  - [x] Updated artwork symbol - PR #7711 
- [x] https://github.com/carbon-design-system/carbon-website/issues/2028 - PR (Website): https://github.com/carbon-design-system/carbon-website/pull/2105
- [x] https://github.com/carbon-design-system/carbon-website/issues/1989 - PR (Gatsby): https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1064
- [x] https://github.com/carbon-design-system/carbon-website/issues/1800 - PR (Website): https://github.com/carbon-design-system/carbon-website/pull/2116
- [ ] https://github.com/carbon-design-system/carbon/issues/6938, pair with @joshblack 
- [x] Release - Feb.2021 - Issue: https://github.com/carbon-design-system/carbon/releases/tag/v10.28.0

**Andrew**
- [ ] Sketch pictogram/plugin work - Epic: https://github.com/carbon-design-system/carbon/issues/6485
  - [x] Updated symbol name to existing format  - #7614 PR #7648 
  - [x] Updated artwork symbol - #5749 #7712 PR #7711 
- [x] Search - `onChange` event triggering twice #7481 https://github.com/carbon-design-system/carbon/pull/7613
- [x] TableToolbarSearch is firing onSearch twice for every input #7595 #7613
- [x] Ghost and danger icon button SVGs rendering incorrectly #7631 #7632
- [x] Implement short tag size #7512 #7619 
- [x] <Button hasIconOnly={true} kind="danger-ghost" ...other/> has unnecessary padding #7534 #7618
- [x] [tag] fix hover and focus for filterable tag #7664
- [x] [dropdown/combobox/multiselect] listbox component audit bugs #7325 #7518
- [x] Modal with long selectable data-table in modal body : selecting a row causes modal to content overflow #7682 #7698
- [x] Filterable multiselect input overflows out of the parent container #7723 #7725
- [ ] https://github.com/carbon-design-system/carbon/issues/7562
- [ ] https://github.com/carbon-design-system/carbon/issues/7197

**Anna**
- [Component audit continued](https://github.com/carbon-design-system/carbon/issues/7103): 
   - [x] loading,
   - [x] modal, 
   - [ ] notification. 
- [x] Write up color token v11 discussion topic: https://github.com/carbon-design-system/carbon/discussions/7743#discussion-2784561
- [x] Look into other v11 discussion topics (UI shell theming etc)

**DA**

- [ ] https://github.com/carbon-design-system/carbon/issues/7200
  - [ ] Pair with one developer to help onboard with JAWS
- [x] https://github.com/carbon-design-system/carbon/issues/7341
- [x] Pair with Ale/Josh on Popover component audit
- [x] Pair with TJ on MultiSelect.Filterable support issues

**Jan**
- [x] Concept work with Matt, Jeannie
- [ ] [Content guidelines] epic (https://github.com/carbon-design-system/carbon-website/issues/859) @janchild 
  - [ ] Complete phase 2 content guidelines work -- [content patterns](https://github.com/carbon-design-system/carbon-website/issues/2017) @janchild
 - [ ] Clarification of [Button usage guidance](https://github.com/carbon-design-system/carbon-website/issues/2095) @janchild 

**Jeannie**
- [x] Concept work with Matt

**Jillian**
- [x] [Review and update Slack support audit](https://github.com/carbon-design-system/carbon/issues/7516)  
- [ ] [Develop case study content](https://github.com/carbon-design-system/carbon-website/issues/2071) for the Cloud transition to Carbon 10 @jillianhowarth 

**Josh**
- [ ] Convert themes, types, and elements packages to Sass Modules
- [ ] Continue adding v11 proposals, final cut is next Friday
- [ ] Popover component, pair with @aledavila 
- [ ] https://github.com/carbon-design-system/carbon/issues/6938, pair with @andreancardona 

**Lauren**
- [ ] [Context menu](https://github.com/carbon-design-system/carbon/pull/7350) start content guidance (in progress)
[Popover component](https://github.com/carbon-design-system/carbon/issues/7649)
   - [x] Design research and explorations 
   - [x] Basic design spec #7713 
- [ ] Look into current status of Treeview
- [x] Sketch pictogram/plugin support
   - #7732 
   - #7734 

**Thy**
- [ ] Comms images for Medium @thyhmdo 

**TJ**
- [x] Continue component audit fixes
- [ ] Pair with DA on MultiSelect.Filterable issues
  - [x] ~~https://github.com/carbon-design-system/carbon/issues/6570~~
  - [x] ~~https://github.com/carbon-design-system/carbon/issues/7296~~
  - [ ] Consolidated into https://github.com/carbon-design-system/carbon/issues/7331
- [x] Help breakdown https://github.com/carbon-design-system/carbon/issues/7551 into manageable tasks

**Tracey**
- [ ] [Radio button component usage documentation](https://github.com/carbon-design-system/carbon-website/issues/2096)) @kingtraceyj

**Comment by joshblack** [comment]
### Issues to triage

**Ale**
- ~[Request: Add indicator line - data table row component ](https://github.com/carbon-design-system/carbon/issues/7641)~
- ~[Uncaught TypeError: Cannot read property 'viewBox' of undefined](https://github.com/carbon-design-system/carbon/issues/7590)~
- ~[Default focus is not set to token](https://github.com/carbon-design-system/carbon/issues/7469)~
- ~[Multiselect.Filterable not showing initiallySelectedItems](https://github.com/carbon-design-system/carbon/issues/7047)~


**Andrea**
- ~[ Enhancement tab component padding](https://github.com/carbon-design-system/carbon/issues/7640)~
- ~[Combobox - filter search is inconsistent between single and multi-select versions](https://github.com/carbon-design-system/carbon/issues/7589)~
- ~[Loading indicator svg for batch actions](https://github.com/carbon-design-system/carbon/issues/7459)~
- ~[Modal position inside UIShell with a Header](https://github.com/carbon-design-system/carbon/issues/7015)~ (awaiting author's response)


**Andrew**
- ~~[NumberInput: setting step and value with state doesn't trigger onchange event ](https://github.com/carbon-design-system/carbon/issues/7629)~~
- ~~[CodeSnippet: showMore should only be displayed when there are more then 15 rows](https://github.com/carbon-design-system/carbon/issues/7572)~~
- ~~[Bidi support: Structured text at dynamic components is not supported in Carbon components ](https://github.com/carbon-design-system/carbon/issues/7292)~~
- ~~[Pagnation size select and Page number select should not be enabled/disabled at the same time.](https://github.com/carbon-design-system/carbon/issues/7014)~~


**DA**
- [Which validation library is compatible with Carbon?](https://github.com/carbon-design-system/carbon/issues/7628)
- [Add a new property to component Dropdown to allow specifying the min-width of the` .bx--list-box__menu` class ](https://github.com/carbon-design-system/carbon/issues/6936)
- [Bidi support: Structured text at static components is not supported in Carbon components](https://github.com/carbon-design-system/carbon/issues/7291)
- [[ComboBox]: can I allow an onBlur to trigger the onChange event of a Combobox for a new item entry?](https://github.com/carbon-design-system/carbon/issues/6999)


**Josh**
- ~~[How to open a Toast?](https://github.com/carbon-design-system/carbon/issues/7627)~~
- ~~[Content switcher carries the same visual weight as the primary button. ](https://github.com/carbon-design-system/carbon/issues/7509)~~
- ~~[Combobox inteligent width adjustments](https://github.com/carbon-design-system/carbon/issues/7245)~~
- ~~[In the case of a big horizontal scroll, there should be an option to fix the first column of the table.](https://github.com/carbon-design-system/carbon/issues/6996)~~


**TJ**
- ~~[What should I do to expand the Header Panel, the Switcher?](https://github.com/carbon-design-system/carbon/issues/7626)~~
- ~~[DataTable / Batch Actions / Usage - Possibility to select all value from table with incorrect value in filter](https://github.com/carbon-design-system/carbon/issues/7496)~~
- ~~[Sidebar spacing changes when collapsed and hovered over](https://github.com/carbon-design-system/carbon/issues/7195)~~
- ~~[DataTable - How to make rows disabled in order not to be selected when clicking on the SelectAll checkbox?](https://github.com/carbon-design-system/carbon/issues/6972)~~

**Comment by aagonzales** [comment]
Design epics on deck:
- [Community pattern migration](https://github.com/carbon-design-system/carbon-website/issues/2086)
- [Remaining component usage docs](https://github.com/carbon-design-system/carbon-website/issues/2085)

Design support issues:
- Multiselect active indicator https://github.com/carbon-design-system/carbon/issues/7490
