### ISSUE TITLE
v11 Release

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#7717]
To learn more about the v11 release, check out our announcement post on [Medium](https://medium.com/carbondesign/whats-coming-to-carbon-in-2021-39a4c7d1762a). If you're interested in trying out this release early and giving us feedback, check out our [Release Partner Program](https://github.com/carbon-design-system/carbon/wiki/Release-Partner-Program).

**Timeline**

| Milestone | Date |
| :-------- | :---- |
| [Alpha release](https://medium.com/carbondesign/carbons-2021-release-april-update-9d23242b3dea?source=your_stories_page-------------------------------------) | April 15th, 2021 |
| Beta 0 release | May 13th, 2021 |
| [Beta 1 release](https://medium.com/carbondesign/carbon-v11-beta-1-33488b0280f0) | July 29th, 2021 |
| [Beta 2 release](https://medium.com/carbondesign/carbon-v11-beta-2-7d0aa4e732d1) | September 21st, 2021 |
| [Beta 3 release](https://medium.com/carbondesign/carbon-v11-beta-3-9b6be61bb2af) | December 10th, 2021 |
| Release Candidate 0 release | January 27th, 2022 |
| Release Candidate 1 release | March 3rd, 2022 |
| Stable release | [March 31st, 2022](https://medium.com/carbondesign/carbon-v11-72ace7fac01f) |

**Comment by hcheung87** [comment]
Hey Josh - I am curious to know whether this functionality will be part of the next release scheduled for April (https://github.com/carbon-design-system/carbon/issues/4748)? I cannot find it in the release notes above but just wanted to confirm. If not, do you know when that will be included? Last activity was from July 15, 2020. Thanks!

**Comment by joshblack** [comment]
Hey @hcheung87! 👋  Currently, we're not tracking that issue for this upcoming release. It may be something we'll be able to tackle post v11 after we drop IE11 support but unfortunately it's not something on our radar for v11 at the moment.

**Comment by yabeow** [comment]
Hi @joshblack,

It seems that the team wouldn't be able to meet with this timeline. Do you have any updates on this plan?

**Comment by joshblack** [comment]
Hi @yabeow! 👋 The table above should be kept up-to-date. Sorry if that was not the case before!

**Comment by joshblack** [comment]
## Features

### Website

- Guidelines
  - Icons
    - Library
      - Code snippets have been updated
        - Size update
        - Name update
        - Bug with namespace icons
      - Usage
        - Update name for resource tiles (icons, icons-react)
      - Code
        - Update code content to reflect API changes
  - Pictograms
    - Library
      - Usage
        - Add package links for pictograms
      - Code
        - Update code content to reflect API changes
  - Motion
    - Code
      - Update code content to reflect API changes
  - Spacing
    - Overview
      - Automate generation of spacing scale table
    - Code
      - Update code content to reflect API changes
  - Type
    - Productive
      - Automate generation of token table
    - Expressive
      - Automate generation of token table
    - Code
      - Update code content to reflect API changes

**Comment by joshblack** [comment]
**WIP**

## ⚛️  React

**Changes to props**

- Event handlers

**Changes to components**

- Notification
- Tooltip
- Modal
- Content Switcher

**New components**

- IconButton

**Bundle**

- Rollup

## 🎨  Styles

- [ ] Update styles to use Sass Modules
- [ ] Publish styles under a new `@carbon` scope: `@carbon/styles`
- [ ] Add usage and API docs to `docs/sass.md`
- [ ] Add migration docs for Public API

**Packages**

- [ ] `@carbon/colors`
  - [ ] Update to Sass Modules
  - [ ] Add usage and API docs to `docs/sass.md`
  - [ ] Update entrypoint to point to Sass Modules, switch over `modules` files
- [ ]  `@carbon/elements`
  - [ ] Update to Sass Modules
  - [ ] Add usage and API docs to `docs/sass.md`
  - [ ] Update entrypoint to point to Sass Modules, switch over `modules` files
- [ ]  `@carbon/feature-flags`
  - [ ] Update to Sass Modules
  - [ ] Add usage and API docs to `docs/sass.md`
  - [ ] Update entrypoint to point to Sass Modules, switch over `modules` files
- [ ]  `@carbon/grid`
  - [ ] Update to Sass Modules
  - [ ] Add usage and API docs to `docs/sass.md`
  - [ ] Update entrypoint to point to Sass Modules, switch over `modules` files
- [ ]  `@carbon/import-once`
  - [ ] Deprecate package, no longer needed with Sass Modules
- [ ]  `@carbon/layout`
  - [ ] Update to Sass Modules
  - [ ] Add usage and API docs to `docs/sass.md`
  - [ ] Update entrypoint to point to Sass Modules, switch over `modules` files
- [ ]  `@carbon/motion`
  - [ ] Update to Sass Modules
  - [ ] Add usage and API docs to `docs/sass.md`
  - [ ] Update entrypoint to point to Sass Modules, switch over `modules` files
- [ ]  `@carbon/icons`
  - [ ] Remove Sass file and move to styles
- [ ]  `@carbon/type`
  - [ ] Update to Sass Modules
  - [ ] Generate tokens from JavaScript
  - [ ] Add usage and API docs to `docs/sass.md`
  - [ ] Update entrypoint to point to Sass Modules, switch over `modules` files


## 🚢 Migration

- [ ] Moving from `carbon-components` to `@carbon/styles`
  - [ ] VanillaJS user
  - [ ] Framework implementation
- [ ] Moving from `carbon-components-react` to `@carbon/react`
  - [ ] Update style usage from `carbon-components`
  - [ ] Update imports for changes to `carbon-components-react` exports
    - [ ] Certain internals are no longer available
    - [ ] Certain components are no longer available
  - [ ] Update imports for icons
- [ ] Moving from `@carbon/icons-react`
- [ ] Updates to Design Tokens
- [ ] Updates to Grid

**Packages**

- [ ] Deprecate `carbon-icons`
- [ ] Move VanillaJS implementation into separate repo

## 📝 Website

## 📣 Communication

- [x] Publish alpha post
- [x] Publish beta 1 post
- [ ] Publish beta 2 post
- [ ] Publish release candidate post
- [ ] Publish stable post
