### ISSUE TITLE
Sprint 4: Mad Max Monkey 🙈🔥

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#7860]
## February 22nd - March 5th

**Team issues**

- [ ] Onboard first group of release partners
- [x] Define scope of initial alpha release

**Andrea**

- [ ] Sketch pictogram/plugin work with @emyarod https://github.com/carbon-design-system/carbon/issues/6485
  - [x] chore(icons): add removed icons back to update master file #7964   
- [x] https://github.com/carbon-design-system/carbon/issues/5880 with @jnm2377 https://github.com/carbon-design-system/carbon/pull/7908
- [x] https://github.com/carbon-design-system/carbon/issues/6840 with @dakahn https://github.com/carbon-design-system/carbon/pull/7889
- [x] #6938 Combobox a11y issues: https://github.com/carbon-design-system/carbon/pull/7777

**Andrew**

- [ ] Sketch pictogram/plugin work with @andreancardona  https://github.com/carbon-design-system/carbon/issues/6485
  - [x] chore(icons): add removed icons back to update master file #7964   
- [x] Dive into File uploader issues
  - [x] https://github.com/carbon-design-system/carbon/issues/6321
  - [x] https://github.com/carbon-design-system/carbon/issues/5894
- [x] feat(Modal): implement support for 3 button modals #7775 
- [x] fix(list-box): update hover active item background color #7832 #7490 
- [x] fix(radio-button): avoid outline cutoff in hidden overflow containers #7886 #7873 #7113 
- [x] fix(RadioButton): remove empty span if label text is falsey #7904 
- [x] fix(checkbox): avoid outline cutoff in hidden overflow containers #7887 #6480
- [x] fix(AccordionItem): animate open/close when `open` prop is specified #7876 #7875
- [x] feat(number-input): update number input controls to new spec #7687 #5417
- [x] fix(tabs): remove Safari specific overflow indicator margins #7917 #7906
- [x] fix(NumberInput): deprecate mobile variant #7919 #7570 #5231 #5421
- [x] fix(Tabs): prevent tablist role from stealing focus #7905 #7892
- [x] fix(tag): set vertical alignment #7927 #7920
- [x] feat(Tag): add pointer on hover if component is interactive #7839 #7592

**Anna**

- Grid/layout work
- Color token feedback
- [ ] https://github.com/carbon-design-system/carbon/issues/6745 Content Switch 3:1 Contrast
- [x] [Community Pattern audit](https://www.notion.so/carbondesignsystem/Community-pattern-audit-654a05eb472e4e2db0415d2f66885033) / [Related issue](https://github.com/carbon-design-system/carbon-website/issues/2086)

**DA**

- [x] https://github.com/carbon-design-system/carbon/issues/6881
- [x] https://github.com/carbon-design-system/carbon/issues/6567
- [x] https://github.com/carbon-design-system/carbon/issues/6840 with @andreancardona https://github.com/carbon-design-system/carbon/pull/7889

**Jan**
- [x] Concept work with Matt, Jeannie
- [ ] Pattern guidance review

**Jeannie**
- [x] Concept work with Matt, Jan
- [ ] Pattern guidance review

**Jillian**
- [ ] [Develop case study content](https://github.com/carbon-design-system/carbon-website/issues/2071) for the Cloud transition to Carbon 10  
- [x] Patterns presentation

**~John~**

~- [ ] Create add-on package for animated icons #7346~

**Josefina**

- [x] https://github.com/carbon-design-system/carbon-website/issues/2125
- [ ] Pair with @tay1orjones on Grid work, includes writing out initial scope/deliverable
- [x] https://github.com/carbon-design-system/carbon/issues/5880 with @andreancardona 

**Josh**

- [x] https://github.com/carbon-design-system/carbon/issues/7713, pair with @tw15egan and @laurenmrice on Popover/Disclosure
- [x] Finalize feature flag package https://github.com/carbon-design-system/carbon/pull/7802
  - [x] Integrate into `carbon-components` and `carbon-components-react`
- [ ] Release Partners
  - [x] Finalize onboarding document
  - [ ] Onboard initial group of partners
- [ ] https://github.com/carbon-design-system/carbon/issues/7861

**Lauren**

- Context menu component
  - [ ] [Usage docs](https://www.notion.so/carbondesignsystem/Usage-c57619a1d655414993ef492c2c87c8f7) (wip)
 
- Treeview component
  - [ ] [Usage docs](https://www.notion.so/carbondesignsystem/Usage-941b49cbba5c4f0abc7b072294f61bbf) (wip)
  - [x] [Sketch symbol structure](https://ibm.ent.box.com/file/782410501338)
  - [x] [Design specs](https://github.com/carbon-design-system/carbon/issues/5180)
  - [x] [Make code bug issue](https://github.com/carbon-design-system/carbon/issues/8000) 

- [x] Sketch plugin support/help

**Taylor**
- [x] Continue Grid work from last sprint, pair with @jnm2377 
  - CSS Grid MVP https://github.com/carbon-design-system/carbon/pull/7851
- [x] https://github.com/carbon-design-system/carbon/issues/7731
- [ ] https://github.com/carbon-design-system/carbon/issues/7078

**Thy**

- [ ] Status icons

**TJ**

- [x] https://github.com/carbon-design-system/carbon/issues/6286
- [x] https://github.com/carbon-design-system/carbon/issues/7820
- [x] https://github.com/carbon-design-system/carbon/issues/7713, pair with @joshblack and @laurenmrice on Popover/Disclosure
- [x] https://github.com/carbon-design-system/carbon/issues/7757

**Tracey**

- Component docs
   - [ ] Tabs

**Comment by joshblack** [comment]
## Proposed items

- [Skeleton state bug fixes](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1613486609314400)
- Consolidate spacing and layout scales
- Notification Refactor
- UI Shell Theming
- Refactoring test suite (react testing library, cypress)

**Comment by aagonzales** [comment]
Design epics on deck:
- [Community pattern migration](https://github.com/carbon-design-system/carbon-website/issues/2086)
- [Remaining component usage docs](https://github.com/carbon-design-system/carbon-website/issues/2085)

Design support issues:
- ~Selected buttons https://github.com/carbon-design-system/carbon/issues/7757~
- Content switcher 3:1 contrast issue https://github.com/carbon-design-system/carbon/issues/6745
- Button guidance, non-primary buttons in data tables, v11 suggestions (new secondary btn?)
- Tertiary nav for gatsby theme, accessibility research
- Add accessibility disclaimer to disabled states pattern.
