### ISSUE TITLE
Sprint 5: Naked Gun Narwhal 🐳 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#7979]
## March 8th - March 19th

**Team issues**

**Andrea**
- [x] Sketch pictogram/plugin work https://github.com/carbon-design-system/carbon/issues/6485
  - [x] #7732 - closed with: https://github.com/carbon-design-system/carbon/pull/8060
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/1937 with DA and @laurenmrice 
  - [x] PR pt.1: https://github.com/carbon-design-system/carbon/pull/8084
- [x] Wrap up https://github.com/carbon-design-system/carbon/issues/5880
- [ ] https://github.com/carbon-design-system/carbon/issues/4134
- [x] Pair on https://github.com/carbon-design-system/carbon/issues/7538#issuecomment-758922794 with Josh
     - [x] https://github.com/carbon-design-system/carbon/pull/8021

**Andrew**
- [x] Sketch pictogram/plugin work https://github.com/carbon-design-system/carbon/issues/6485
  - [x] #7732 - closed with: https://github.com/carbon-design-system/carbon/pull/8060
- [x] https://github.com/carbon-design-system/carbon/issues/4185 #8090
- [x] https://github.com/carbon-design-system/carbon/issues/4704 #8048
- [x] https://github.com/carbon-design-system/carbon/issues/4282
- [x] docs: update default size knob description for Tag and Toggle #8049 #8045
- [x] fix(modal): override base paragraph styles in modal content #8046 #8043
- [x] fix(DataTable): return correct sort direction in sort action callback #8048 #4704
- [x] fix(accordion): update disabled divider rule token #8083 #8081
- [x] fix(ListBoxTrigger): support title on ListBoxTrigger #8094
- [x] feat(Select): support warning state #8092 #8082
- [x] fix(NumberInput): set negative tabindex on number controls #8090 #4185
- [x] fix: update vanilla loading spinner markup and replace expanded containers with margin #7968 #7946 #7978

  
**Anna**
- [x] [Color tokens](https://www.notion.so/carbondesignsystem/WIP-Final-List-of-to-be-tokens-fc5985c7331341baa6546064399d36da) pair @tw15egan 
- [x] [Shell theming](https://github.com/carbon-design-system/carbon/issues/8102)
- [ ] Pair @dakahn  [Notification refactor](https://github.com/carbon-design-system/carbon/issues/7538#issuecomment-767151514)

**DA**
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/1937 with Andrea
  - [x] PR pt.1: https://github.com/carbon-design-system/carbon/pull/8084
  - [ ] https://github.com/carbon-design-system/carbon/issues/2820
- [x] Pair on https://github.com/carbon-design-system/carbon/issues/4529 with Josefina @laurenmrice 
- [x] https://github.com/carbon-design-system/carbon/issues/7200 **https://github.com/carbon-design-system/carbon/pull/7789**
- [ ] Start working towards [Notification refactor](https://github.com/carbon-design-system/carbon/issues/7538#issuecomment-767151514) w/ @aagonzales 

**Jan**
- [ ] About Carbon page with Mike Abbink
- [x] Plan training strategy 
 - [ ] Carbon Standards for DPO initiative with Matt, Jeannie

**Jeannie**
 - [ ] Concept work with Matt, Jan
 - [ ] Carbon Standards for DPO initiative with Matt, Jan

**Jillian**
- [x] Finalize case study with Matt and Jan
- [ ] Complete IBM video training class
- [x] [Kit issue: Small tag and state adjustments](https://github.com/carbon-design-system/carbon-design-kit/issues/406) (in progress) pair with @laurenmrice 

**John**
- [x] Audit existing tutorials on site
- [ ] Animated icons https://github.com/carbon-design-system/carbon/issues/7346

**Josefina**
- [x] Pair on https://github.com/carbon-design-system/carbon/issues/4529 with DA
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/7551 with TJ
- [x] Confirm if https://github.com/carbon-design-system/carbon/issues/3418 is still a defect (work with DA as-needed)
- [x] https://github.com/carbon-design-system/carbon/issues/4796
- [x] Wrap up https://github.com/carbon-design-system/carbon/issues/5880

**Josh**
- [x] Release partners
  - [x] Onboard initial group
  - [x] Set initial meeting date
- [ ] #7861
- [x] Convert 25% of codebase to Sass Modules in experiment

**Lauren**
- Treeview component
  - [ ] [Usage docs](https://www.notion.so/carbondesignsystem/Usage-941b49cbba5c4f0abc7b072294f61bbf) (in progress)
- Kit issues
  - [x] [Small tag and state adjustments](https://github.com/carbon-design-system/carbon-design-kit/issues/406) (in progress) pair with @jillianhowarth 
  - [x] [Accordion audit bug](https://github.com/carbon-design-system/carbon-design-kit/issues/372)
  - [x] [Number input enhancement](https://github.com/carbon-design-system/carbon-design-kit/issues/300) (in progress)
- [x] Sketch plugin support/help
- [x] Pair on https://github.com/carbon-design-system/carbon/issues/4529
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/1937
- [x] YouLearning IDL Event setup/support

**Taylor**
- [x] Ship MVP CSS Grid Module https://github.com/carbon-design-system/carbon/pull/7851 🚀 
  - [x] Verify if https://github.com/carbon-design-system/carbon/issues/4555 is still a defect and if we can address it
- [x] Wrap up https://github.com/carbon-design-system/carbon/issues/7078
- [x] https://github.com/carbon-design-system/carbon/issues/7596
- [x] https://github.com/carbon-design-system/carbon/pull/8050
- [x] https://github.com/carbon-design-system/carbon/pull/8072
- [x] https://github.com/carbon-design-system/carbon/issues/8061
- [x] v10.31.0 Release onboarding sidekick w/ @dakahn 

**Thy**
- [ ] Status icons

**TJ**
- [ ] Color tokens sync w/ @aagonzales 
- [x] Combine spacing and layout tokens https://github.com/carbon-design-system/carbon/issues/5602 sync w/ design
- [x] https://github.com/carbon-design-system/carbon/issues/7040
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/7551 with Josefina
- [x] https://github.com/carbon-design-system/carbon/issues/7106
- [ ] Color token updates
  - TODO: write issue for dev task

**Tracey**
- [ ] Component docs: Tabs (in progress)

### Brand/DPO support

**[DPO issues](https://www.notion.so/carbondesignsystem/DPO-b746896b3c234bc587e4c00d8f21f26d)** | **[Brand issues](https://app.zenhub.com/workspaces/auxiliary-squad-5deea70733c75ceaf1bfacae/board?repos=199501316,181498056,181062037&showPRs=false&showClosed=false)**

**Ale**
- [ ] https://github.com/carbon-design-system/design-language-website/issues/883
- [x] EDT https://github.ibm.com/Design/IDTU/issues/5872
- [x] EDT https://github.ibm.com/Design/IDTU/issues/5868-
- [ ] W3 https://github.ibm.com/Design/w3-design/issues/1039
- [x] W3 https://github.ibm.com/Design/w3-design/issues/1049
- [x] W3 https://github.ibm.com/Design/w3-design/issues/1050

**Vince**
- [ ] Plex strategy for v11
- [x] https://github.ibm.com/DUX-Program/dux-program-website/issues/166
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1101
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1100
- [ ] https://github.com/carbon-design-system/design-language-website/issues/885
- [x] D&UX https://github.ibm.com/DUX-Program/dux-program-website/issues/157 (is this done?)

**Matt**
- [ ] Open source health check https://github.com/carbon-design-system/carbon/issues/8093

**Comment by aagonzales** [comment]
Potential design task:
- Compact (24px) components: https://github.com/carbon-design-system/carbon/issues/6202
- [Button guidance](https://github.com/carbon-design-system/carbon-website/issues/2142)
- Tertiary nav for gatsby theme, accessibility research

Design epics on deck:
- [Community pattern migration](https://github.com/carbon-design-system/carbon-website/issues/2086)
- [Remaining component usage docs](https://github.com/carbon-design-system/carbon-website/issues/2085)

**Comment by alisonjoseph** [comment]
https://github.com/carbon-design-system/carbon/issues/7040

**Comment by joshblack** [comment]
**Andrea**

- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/1937 with DA and @laurenmrice 
- [ ] Wrap up https://github.com/carbon-design-system/carbon/issues/5880
- [ ] https://github.com/carbon-design-system/carbon/issues/4134
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/7538#issuecomment-758922794 with Josh

**Andrew**

- [ ] https://github.com/carbon-design-system/carbon/issues/4185
- [ ] https://github.com/carbon-design-system/carbon/issues/4704
- [ ] https://github.com/carbon-design-system/carbon/issues/4282

**DA**

- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/1937 with Andrea
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/4529 with Josefina @laurenmrice 
- [ ] https://github.com/carbon-design-system/carbon/issues/7200
- [ ] Start working towards [Notification refactor](https://github.com/carbon-design-system/carbon/issues/7538#issuecomment-767151514) w/ @aagonzales 

**Josefina**

- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/4529 with DA
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/7551 with TJ
- [ ] Confirm if https://github.com/carbon-design-system/carbon/issues/3418 is still a defect (work with DA as-needed)
- [ ] https://github.com/carbon-design-system/carbon/issues/4796

**Josh**

- [ ] Release partners
  - [ ] Onboard initial group
  - [ ] Set initial meeting date
  - [ ] Run initial meeting
- [ ] #7861
- [ ] Ship Sass Modules MVP

**Taylor**

- [ ] Ship MVP of CSS Grid module
  - [ ] Verify if https://github.com/carbon-design-system/carbon/issues/4555 is still a defect and if we can address it
- [ ] Wrap up https://github.com/carbon-design-system/carbon/issues/7078
- [ ] https://github.com/carbon-design-system/carbon/issues/7596

**TJ**

- [ ] Combine spacing and layout tokens https://github.com/carbon-design-system/carbon/issues/5602 sync w/ design
- [ ] https://github.com/carbon-design-system/carbon/issues/7040
- [ ] Pair on https://github.com/carbon-design-system/carbon/issues/7551 with Josefina
- [ ] https://github.com/carbon-design-system/carbon/issues/7106
- [ ] Color token updates
  - TODO: write issue for dev task
