### ISSUE TITLE
Sprint 6: O' Ostrich Where Art Thou? 🐦

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#8118]
## March 22nd - April 2nd

**Andrea**
- [ ] Continue Sketch Icons & Pictograms with Andrew
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 (need to figure out Sketch sync icon)
- [x] Continue https://github.com/carbon-design-system/carbon/issues/1937 with DA
  - [x] PR:  https://github.com/carbon-design-system/carbon/pull/8172 (pending visual review)
- [x] https://github.com/carbon-design-system/carbon/issues/7861 with Josh
- [x] Verify if no further action needed https://github.com/carbon-design-system/carbon/issues/6306 
  - [x] PR: https://github.com/carbon-design-system/carbon/pull/8258 (pending visual review)
- [ ] https://github.com/carbon-design-system/carbon/issues/4134
- [ ] RadioButtonGroup bug: https://github.com/carbon-design-system/carbon/issues/8225
  - [x] PR: https://github.com/carbon-design-system/carbon/pull/8283 (pending approval) 

**Andrew**
- [ ] Continue Sketch Icons & Pictograms with Andrea
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 PR #8188
- [x] https://github.com/carbon-design-system/carbon/issues/6308 with DA
- [ ] https://github.com/carbon-design-system/carbon/issues/3666 
  - received updated spec on 3/30
- [ ] https://github.com/carbon-design-system/carbon/issues/7759
  - PR #8279
- [x] fix: update vanilla loading spinner markup and replace expanded containers with margin #7968 #7946 #7978 
- [x] fix(treeview): update text and color tokens to match spec #8075 #8000
- [x] fix(Dropdown): prevent unnecessary duplicate VO readings #7768 #7707
- [x] fix(Tab): sync tab id with tab panel id #8074 #8070
- [x] docs(UIShell-story): add missing prop to HeaderMenu #8132 #8131
- [x] fix(ListBox): correctly position menu chevron #8155 #8147 
- [x] fix(UIShell): avoid spreading isSideNavExpanded to non Carbon elements #8135 #3970
- [x] feat(Notification): add onClose support #7918 #7859
- [x] fix(toast-notification): match updated spec #8165 #8115
- [x] fix(ContentSwitcher): resolve text contrast violations #8130 #6745
- [x] fix(structured-list): top align header text #8166 #8157
- [x] fix(ComposedModal): add scrolling content class automatically #8153 #8136
- [x] fix(TableToolbarSearch): allow screen reader navigation #7986 #7915
- [x] fix(date-picker): remove border radius #8198 #8190

**Anna**
- [ ] Component specs: [color token updates](https://github.com/carbon-design-system/carbon/issues/8187) sync with @tw15egan 
- [ ] Create kit versions with new tokens for testing.

**DA**
- [x] https://github.com/carbon-design-system/carbon/pull/8172
- [x] Continue https://github.com/carbon-design-system/carbon/issues/1937 with Andrea
  - [x] https://github.com/carbon-design-system/carbon/issues/2820 https://github.com/carbon-design-system/carbon/pull/8172
- [x] https://github.com/carbon-design-system/carbon/issues/6308 with Andrew
- [ ] https://github.com/carbon-design-system/carbon/issues/7210
  - [ ] https://github.com/carbon-design-system/carbon/issues/6865 if solved by #7210
- [x] https://github.com/carbon-design-system/carbon/issues/8220 https://github.com/carbon-design-system/carbon/pull/8222

**Jan**
- [x] [Domain guidance](https://github.com/carbon-design-system/carbon-website/issues/2193) update with Mike Abbink
- [x] [Designing > Other resources updates] for Gatsby kit and mobile kits and resources 
- [ ] About Carbon page with Mike Abbink
- [ ] Carbon Standards for DPO initiative with Matt, Jeannie

**Jeannie**
 - [ ] Carbon Standards for DPO initiative with Matt, Jan
 - [ ] Concept work with Matt, Jan

**Jillian**
- [x] [Kit issue: Button–add xl and large button sizes](https://github.com/carbon-design-system/carbon-design-kit/issues/383) pair with @laurenmrice 
- [x] [Kit issue: Form component–add warning state](https://github.com/carbon-design-system/carbon-design-kit/issues/351) pair with @laurenmrice  
- [ ] Complete IBM video training class

**John**
- [x] Training pattern development with Jan
- [x] Identify training content from 2019 Design Essentials classes and Slack audit
- [ ] Animated icons https://github.com/carbon-design-system/carbon/issues/7346

**Josefina**
- [x] https://github.com/carbon-design-system/carbon/issues/8149 with TJ
- [x] https://github.com/carbon-design-system/carbon/issues/8238 with TJ
- [x] https://github.com/carbon-design-system/carbon/issues/8142 with Taylor
- [ ] https://github.com/carbon-design-system/carbon/issues/8151 with TJ
- [x] https://github.com/carbon-design-system/carbon/issues/7457
- [x] DUX color bug https://github.ibm.com/DUX-Program/dux-program-website/issues/170

**Josh**
- [x] https://github.com/carbon-design-system/carbon/issues/7861 with Andrea
- [x] https://github.com/carbon-design-system/carbon/issues/8139 with Vince (?)
- [x] Continue https://github.com/carbon-design-system/carbon/issues/7525
- [ ] Finalize initial packages for Alpha release (`@carbon/styles` and `@carbon/react`)
- [x] Update name servers for carbon websites to point to cloudflare for SSL cert (expires 4/4) @alisonjoseph 

**Lauren**
- [x] [Treeview Usage guidance (in notion)](https://www.notion.so/carbondesignsystem/Usage-941b49cbba5c4f0abc7b072294f61bbf)
- [ ] [Treeview Style guidance (in notion)](https://www.notion.so/carbondesignsystem/Style-6ffd3ec0a2a44c34aee3b876ca118ea5) (in progress)
- Kit issues
   - [x] [# 383](https://github.com/carbon-design-system/carbon-design-kit/issues/383) Pair with @jillianhowarth 
   - [ ] [# 351](https://github.com/carbon-design-system/carbon-design-kit/issues/351) Pair with @jillianhowarth 
- [x] Support/testing with Icon/Pictogram plugin

**Taylor**
- [ ] https://github.com/carbon-design-system/carbon/issues/8144 
- [ ] Investigate https://github.com/carbon-design-system/carbon/issues/8145 with TJ
- [ ] https://github.com/carbon-design-system/carbon/issues/8142 with Josefina
- [ ] Refactor three component test suites (TODO: add issue) with Vince

**Thy**
- Status icons
- Dataviz images?

**TJ**
- [ ] https://github.com/carbon-design-system/carbon/issues/8149 with Josefina
- [ ] https://github.com/carbon-design-system/carbon/issues/8088
- [ ] Investigate https://github.com/carbon-design-system/carbon/issues/8145 with Taylor
- [x] https://github.com/carbon-design-system/carbon/issues/8151 with Josefina

**Tracey**
- [ ] Component docs: Tabs (in progress)

### Brand/DPO support

**[DPO backlog](https://www.notion.so/carbondesignsystem/DPO-b746896b3c234bc587e4c00d8f21f26d)** | **[Brand issues](https://app.zenhub.com/workspaces/auxiliary-squad-5deea70733c75ceaf1bfacae/board?repos=199501316,181498056,181062037&showPRs=false&showClosed=false)**

**Ale**
- [x] UE https://github.ibm.com/Design/universal-experiences/issues/49 (added mid sprint as higher priority item)
- [x] w3 update banner on homepage https://github.ibm.com/Design/w3-design/issues/1054 (Meet w/ Allison Biesbober to go through process to update this image herself)
- [ ] carbon-design-system/design-language-website#883 (bug)
- [x] Update switcher - carbon-design-system/gatsby-theme-carbon#1100 pair w/ Vince on theme release process
- [ ] Podcast detail page updates (new component?) https://github.ibm.com/Design/racial-equity-in-design/issues/235

**Vince**
- [ ] https://github.com/carbon-design-system/carbon/issues/8106
- [x] https://github.com/carbon-design-system/carbon/issues/8139 with Josh (?)
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1061 (1:1 card component)
- [ ] carbon-design-system/design-language-website#885
- [x] carbon-design-system/gatsby-theme-carbon#1101 (in a PR)

**Matt**
- [ ]  Open source health check #8093

**Comment by alisonjoseph** [comment]
**Notes**


DPO
- [x] W3 link updates https://github.ibm.com/Design/w3-design/issues/1039
- [x] Universal Experiences page updates https://github.ibm.com/Design/universal-experiences/issues/49
- [x] Update switcher - https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1100

Brand
- [ ]  carbon-design-system/design-language-website#883 (bug)
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1083 (list component)
- [ ] carbon-design-system/gatsby-theme-carbon#1101
- [ ] carbon-design-system/design-language-website#885
- [ ] Explore css grid components / 16 column update

**Comment by laurenmrice** [comment]
Potential design tasks:
- Skeleton state for Toggle: https://github.com/carbon-design-system/carbon/issues/6222
- [Button guidance](https://github.com/carbon-design-system/carbon-website/issues/2142)
- Compact (24px) components: https://github.com/carbon-design-system/carbon/issues/6202
- Tertiary nav for gatsby theme, accessibility research

Design epics on deck:
- [Community pattern migration](https://github.com/carbon-design-system/carbon-website/issues/2086)
- [Remaining component usage docs](https://github.com/carbon-design-system/carbon-website/issues/2085)
- [Component Audit](https://github.com/carbon-design-system/carbon/issues/7103)

**Comment by joshblack** [comment]
**Andrea**

- [ ] Continue Sketch Icons & Pictograms with Andrew
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 
- [ ] Continue https://github.com/carbon-design-system/carbon/issues/1937 with DA
  - [ ] https://github.com/carbon-design-system/carbon/issues/2820
- [ ] https://github.com/carbon-design-system/carbon/issues/7861 with Josh
- [ ] Verify if no further action needed https://github.com/carbon-design-system/carbon/issues/6306 
- [ ] https://github.com/carbon-design-system/carbon/issues/4134

**Andrew**

- [ ] Continue Sketch Icons & Pictograms with Andrea
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 
- [ ] https://github.com/carbon-design-system/carbon/issues/6308 with DA
- [ ] https://github.com/carbon-design-system/carbon/issues/3666
- [ ] https://github.com/carbon-design-system/carbon/issues/7759

**DA**

- [ ] Continue https://github.com/carbon-design-system/carbon/issues/1937 with Andrea
  - [ ] https://github.com/carbon-design-system/carbon/issues/2820
- [ ] https://github.com/carbon-design-system/carbon/issues/6308 with Andrew
- [ ] https://github.com/carbon-design-system/carbon/issues/7210
  - [ ] https://github.com/carbon-design-system/carbon/issues/6865 if solved by #7210

**Josefina**

- [ ] https://github.com/carbon-design-system/carbon/issues/8149 with TJ
- [ ] https://github.com/carbon-design-system/carbon/issues/8142 with Taylor
- [ ] https://github.com/carbon-design-system/carbon/issues/8151 with TJ
- [ ] https://github.com/carbon-design-system/carbon/issues/7457


**Josh**

- [ ] https://github.com/carbon-design-system/carbon/issues/7861 with Andrea
- [ ] https://github.com/carbon-design-system/carbon/issues/8139 with Vince (?)
- [ ] Continue https://github.com/carbon-design-system/carbon/issues/7525
- [ ] Finalize initial packages for Alpha release (`@carbon/styles` and `@carbon/react`)

**Taylor**

- [ ] https://github.com/carbon-design-system/carbon/issues/8144 
- [ ] Investigate https://github.com/carbon-design-system/carbon/issues/8145 with TJ
- [ ] https://github.com/carbon-design-system/carbon/issues/8142 with Josefina
- [ ] Refactor three component test suites (TODO: add issue)

**TJ**

- [ ] https://github.com/carbon-design-system/carbon/issues/8149 with Josefina
- [ ] https://github.com/carbon-design-system/carbon/issues/8088
- [ ] Investigate https://github.com/carbon-design-system/carbon/issues/8145 with Taylor
- [ ] https://github.com/carbon-design-system/carbon/issues/8151 with Josefina

**Vince** (Proposed)

- [ ] https://github.com/carbon-design-system/carbon/issues/8106
- [ ] https://github.com/carbon-design-system/carbon/issues/8139 with Josh (?)
