### ISSUE TITLE
Improve our React test suite

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8143]
Currently, our test suite is a mix of enzyme, React Testing Library, and a custom solution with an RTL-like API. This epic tracks our refactor efforts for our React test suite which should include the following updates:

```[tasklist]
### Tasks
- [x] An official "testing style guide" that maintainers and contributors can reference when authoring or updating components
- [x] #10184
- [x] An exploration into e2e visual testing tools like Cypress or playwright to see how easily we could author tests in these environments and how effective they would be
- [x] https://github.com/carbon-design-system/carbon/pull/11302
- [x] https://github.com/carbon-design-system/carbon/issues/9475
- [x] #11370
- [ ] https://github.com/carbon-design-system/carbon/issues/9048
- [x] #13312
```
