### ISSUE TITLE
Sprint 7: Platypus of the Apes 🦍

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#8267]
## April 5th - April 16th

**Andrea**

- [ ] Continue Sketch Icons & Pictograms with Andrew
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 (need to figure out Sketch sync icon)
- [x] Tile bug: https://github.com/carbon-design-system/carbon/issues/6306
  - [x] PR: https://github.com/carbon-design-system/carbon/pull/8258
- [x] RadioButtonGroup bug: https://github.com/carbon-design-system/carbon/issues/8225
  - [x] PR: https://github.com/carbon-design-system/carbon/pull/8283
- [x] https://github.com/carbon-design-system/carbon/issues/4134
  - [x] PR: https://github.com/carbon-design-system/carbon/pull/8335
- [x] https://github.com/carbon-design-system/carbon/issues/8186 (pending approval) 
  - [x] PR: https://github.com/carbon-design-system/carbon/pull/8346
- [ ] https://github.com/carbon-design-system/carbon/issues/8275
- [x] https://github.com/carbon-design-system/carbon/issues/8274
- [x] https://github.com/carbon-design-system/carbon/issues/6633 start prepping with Josh, Lauren
  - [x] Base development for Disclosure: https://github.com/carbon-design-system/carbon/issues/8316

**Andrew**

- [ ] Continue Sketch Icons & Pictograms with Andrea
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 PR #8188 blocked by Sketch, possible workarounds explored
- [ ] https://github.com/carbon-design-system/carbon/issues/3666 
  - received updated spec on 3/30
  - PR #8296
- [x] https://github.com/carbon-design-system/carbon/issues/7759
  - PR #8279
- [ ] https://github.com/carbon-design-system/carbon/issues/4084 with TJ
  - a11y research and feedback required
- [ ] https://github.com/carbon-design-system/carbon/issues/8069 PR https://github.com/carbon-design-system/carbon/pull/8440
- [x] https://github.com/carbon-design-system/carbon/issues/7047
    - workaround provided 
- [x] https://github.com/carbon-design-system/carbon/issues/7514 PR https://github.com/carbon-design-system/carbon/pull/8313
- [x] fix(data-table): remove inline edit short table styles #8212 #8206
- [x] fix(TooltipDefinition): support child nodes #8227 #8226
- [x] fix(FileUploader): replace `<strong>` with `<p>` in exported component #8255 #8252
- [x] fix(date-picker): remove redundant date picker border radius #8259 
- [x] fix(data-table): add table scope to form control overrides #8295 #8286
- [x] fix(breadcrumb): reduce height of overflow menu trigger #8270 #8265
- [x] fix(date-picker): reduce gap between range inputs #8304 #8234
- [x] fix(SelectableTile): sync selected prop and state #8279 #7759
- [x] fix(Notification): attach timeout prop to toast notification #8362 #8348
- [x] fix(tokens): update g10 highlight #8334 #8327
- [x] fix(tabs): override browser focus styles in tab content container #8343 #8342
- [x] fix(ComboBox): highlight selected item based on item id if present #8313 #7514
- [x] fix(PasswordInput): support custom labels in controlled input #8363 #8359

**Anna**
- [x] Finish new color token Sketch library test files: [kit issue #422](https://github.com/carbon-design-system/carbon-design-kit/issues/422)
- [ ] Investigate density tokens for layout modules

**DA**

- [ ] audit native Windows High Contrast Mode support in Chromium Browsers
- [ ] https://github.com/carbon-design-system/carbon/issues/7210
  - [ ] https://github.com/carbon-design-system/carbon/issues/6865 if solved by #7210
- [x] https://github.com/carbon-design-system/carbon/issues/6703 Tooltip refactor with Josh
- [x] https://github.com/carbon-design-system/carbon/issues/7371
- [x] https://github.com/carbon-design-system/carbon/issues/7160

**Jan**
- [x] Review Tree view for Lauren
- [x] Review Tabs view for Tracey
- [ ] Review Status indicators view for Thy
- [x] Draft comms plan for the 2021 release

**Jeannie**
 - [ ] Carbon Standards for DPO initiative with Matt, Jan
 - [ ] Ship v1 status icons with Thy
 - [ ] Ship v1 tabs with Tracey
 - [x] Chart illustrations
 
**Jillian**
- [x] Sketch kit work, pair with @laurenmrice 
  - [x] [Form component–add warning state](https://github.com/carbon-design-system/carbon-design-kit/issues/351)   
  - [x] [Inline notification](https://github.com/carbon-design-system/carbon-design-kit/issues/413)
  - [x] [Content switcher](https://github.com/carbon-design-system/carbon-design-kit/issues/412)
  - [x] Warning icon fill layer bug
- [ ] Complete IBM video training class
- [x] Patterns garage bootcamp presentation 

**John**
- [ ] Increase production value of existing tutorials on our website
  - [x] Designing with Carbon
  - [ ] Introduction to Carbon

**Josefina**

- [x] https://github.com/carbon-design-system/carbon/issues/8149 with TJ
- [x] https://github.com/carbon-design-system/carbon/issues/8302
- [x] #8142 with Taylor
- [x] https://github.com/carbon-design-system/carbon/issues/8151 with TJ
- [x] https://github.com/carbon-design-system/carbon/issues/6222 work with Lauren on specs
- [x] ~https://github.com/carbon-design-system/carbon/issues/7562~
- [x] https://github.com/carbon-design-system/carbon/issues/5736
- [x] carbon-design-system/carbon-website#2192
- [ ] DUX table updates: https://github.ibm.com/DUX-Program/dux-program-website/issues/174

**Josh**

- [x] https://github.com/carbon-design-system/carbon/issues/6703 Tooltip refactor with DA
- [x] https://github.com/carbon-design-system/carbon/issues/8292
- [x] https://github.com/carbon-design-system/carbon/issues/8294
- [x] https://github.com/carbon-design-system/carbon/issues/6948
- [x] https://github.com/carbon-design-system/carbon/issues/6633 start prepping with Andrea, Lauren

**Lauren**

- [x] [Treeview Style guidance (in notion)](https://www.notion.so/carbondesignsystem/Style-6ffd3ec0a2a44c34aee3b876ca118ea5)
- [ ] [Context menu usage guidance](https://www.notion.so/carbondesignsystem/Usage-c57619a1d655414993ef492c2c87c8f7) (in progress)
 - Adobe XD (pair with @thyhmdo)
    - [x] Make icon library
    - [ ] Connect icons from library to components (in progress)
- [x] Support/testing with Sketch plugin for Icons
   - [x] Push Sketch Icon library update 🎉
 - Popover/Disclosure
   - [x] Basic usage doc outline](https://www.notion.so/carbondesignsystem/Usage-8754dd12bf24485d91abf9039d4333f8) in notion 
   - [ ] Design specs of common disclosures (almost done)

**Taylor**

- [ ] https://github.com/carbon-design-system/carbon/issues/8144 
- [ ] Investigate https://github.com/carbon-design-system/carbon/issues/8145 with TJ
- [x] https://github.com/carbon-design-system/carbon/issues/8142 with Josefina
- [ ] Refactor three component test suites (TODO: add issue) with Vince
- [ ] https://github.com/carbon-design-system/carbon/issues/2343
- [x] 10.32.1 release w/ TJ
- [x] 10.33.0-rc.0 release w/ TJ
- [x] 10.33.0 release w/ TJ

**Thy**
- [ ] Ship v1 status icons with Jeannie
- [ ] [Adobe XD Kit](https://github.com/carbon-design-system/carbon-design-kit/issues/419) work (tbd)

**TJ**

- [x] Color update pt. 1 https://github.com/carbon-design-system/carbon/issues/8149 with Josefina
- [x] https://github.com/carbon-design-system/carbon/issues/8088
- [ ] Investigate https://github.com/carbon-design-system/carbon/issues/8145 with Taylor
- [x] https://github.com/carbon-design-system/carbon/issues/8151 with Josefina
- [ ] https://github.com/carbon-design-system/carbon/issues/4084 with Andrew, support from 
- [x] https://github.com/carbon-design-system/carbon/issues/8314
- [x] https://github.com/carbon-design-system/carbon/issues/8312
- [x] Color update pt. 2 https://github.com/carbon-design-system/carbon/issues/8300
- [x] Color update pt. 4 https://github.com/carbon-design-system/carbon/issues/8303
- [x] https://github.com/carbon-design-system/carbon/issues/8311
- [x] https://github.com/carbon-design-system/carbon/issues/8393
- [x] `v10.33.0` release https://github.com/carbon-design-system/carbon/issues/8384
- [x] https://github.com/carbon-design-system/carbon/issues/8439

**Tracey**
- [ ] Ship v1 tabs with Jeannie

**Ale**
- [x] https://github.ibm.com/Design/universal-experiences/issues/53 (UE design tweaks)
- [x] https://github.ibm.com/Design/racial-equity-in-design/issues/235 (podcast page)
- [x] https://github.ibm.com/Design/IDTU/issues/5868 (add link)
- [x] carbon-design-system/design-language-website#903

**Vince**
- [ ] status icons https://github.com/carbon-design-system/carbon-website/issues/2199
- [ ] carbon-design-system/gatsby-theme-carbon#1061 (1:1 card component)
- [x] carbon-design-system/design-language-website#885
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1110 (confirm this is fixed)
- [x] carbon-design-system/design-language-website#905

**Matt**
- [ ] Open source health check #8093

**Comment by alisonjoseph** [comment]
https://github.com/carbon-design-system/carbon-website/issues/2192
https://github.com/carbon-design-system/carbon-website/issues/2206
https://github.com/carbon-design-system/design-language-website/issues/906
https://github.com/carbon-design-system/design-language-website/issues/905
https://github.com/carbon-design-system/design-language-website/issues/903

**Comment by joshblack** [comment]
Questions:

- Do we want to tee up UI Shell theming for next sprint?
- Do we want to tee up Disclosure work for next sprint?

**Comment by dakahn** [comment]
for sprint 8 #6942

**Comment by dakahn** [comment]
for sprint 8 https://github.com/carbon-design-system/carbon/issues/6102
