### ISSUE TITLE
Component Accessibility Primitives

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8293]
As part of our 2021 Release Proposals, we wanted to create accessibility primitives that would work both for our components and that could be shared as part of our larger set of components for teams to use. These components include:

- [ ] Popovers
- [ ] [Disclosure](https://w3c.github.io/aria-practices/#disclosure)
- [ ] [Dialog](https://w3c.github.io/aria-practices/#dialog_modal)
- [ ] [Menu Button](https://w3c.github.io/aria-practices/#menubutton)
- [ ] [Listbox](https://w3c.github.io/aria-practices/#Listbox)
- [ ] [Combobox](https://w3c.github.io/aria-practices/#combobox)
- [ ] Tooltip

**Comment by joshblack** [comment]
## Terminology

**Popover**

The visual style for a raised surface. It is a generic component, similar to Card, that is used to build up tooltips, menus, disclosure patterns, and more. It refers to the style used when building out these components, most notably containing:

- A raised box with a shadow
- An optional caret
- A direction in relation to the target where the popover appears (above, below, to either side, or auto placement)

**Disclosure**

A Disclosure component uses the disclosure pattern to toggle the visibility of a popover. This is often used for non-structured "menus" that can contain actions, filters, other components, etc. The Disclosure component uses a button to toggle the visibility of the section of content.

**Tooltip**

A Tooltip component triggers the visibility of a popover containing **only** text content on hover or focus. The popover should persist unless dismissed by the ESC key, or the cursor hovers away from trigger/popover, or the trigger is unfocused.

Note: there should be behavior for entrance and exit delays for the appearance of the popover. In other words, the component should support waiting 300ms before the popover appears.

Another situation is when we have a group of components that use a tooltip. In these situations, the tooltip group should behave as one tooltip where there is an optional entrance delay, and then tooltips appear automatically after being revealed for each item in the group, and then exit should happen as expected.

---

**Dialog**

It should support the modal and nonmodal dialog variants to be used both in our Modal component and in other situations, like with popovers as nonmodal dialogs or inside panels.

```jsx
<Dialog focusTrap={false} leastDestructiveRef={buttonRef}>
  <button ref={buttonRef} type="button">X</button>
  <p>Some content</p>
</Dialog>
```

**Listbox**

**Combobox*

**Menu**

**Tree**
