### ISSUE TITLE
Sprint 8: Quarantine Quetzal 🦜

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#8398]
## April 19th - April 23rd

**Andrea**

- [ ] Continue Sketch Icons & Pictograms with Andrew
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 (need to figure out Sketch sync icon)
- [ ] https://github.com/carbon-design-system/carbon/issues/8275
  - [x] https://github.com/carbon-design-system/carbon/pull/8461/files (waiting to hear back from design)
- [ ] https://github.com/carbon-design-system/carbon/issues/8432
  - [x] PR: (pushed up by Jan): https://github.com/carbon-design-system/carbon/pull/8469
- [ ] https://github.com/carbon-design-system/carbon/issues/8301 with Josefina
  - [x] https://github.com/carbon-design-system/carbon/pull/8477 (pending visual feedback)
- [ ] ~~Continue popover, disclosure with Josh + Lauren~~

**Andrew**

- [ ] Continue Sketch Icons & Pictograms with Andrea
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 PR #8188
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2233
  - PR https://github.com/carbon-design-system/carbon-website/pull/2262
- [x] https://github.com/carbon-design-system/carbon/issues/8391 #8486 
- [x] https://github.com/carbon-design-system/carbon/issues/8170 #8476
- [x] fix(button): remove dependency on tooltip component classes #8383 #8372
- [x] fix(modal): set pagination background color within modals #8434 #8433
- [x] fix: update chevron animations #8437 #8360
- [x] fix(colors): initialize color vars with default values #8440 #8069
- [x] fix(toggle): update disabled toggle tokens #8514 #6794
- [x] feat(SideNav): add onOverlayClick handler #8296 #3666
- [x] chore: replace vulnerable rational order stylelint config #8453 #8450

**Anna**
- [ ] Investigate density tokens for layout modules
- [x] Define[ Gray80 theme](https://github.com/carbon-design-system/carbon/issues/8471)
- [ ] Condensed structure list spec

**DA**

- [x] https://github.com/carbon-design-system/carbon/issues/8413 with TJ
- [x] https://github.com/carbon-design-system/carbon/issues/8299
- [x] https://github.com/carbon-design-system/carbon/issues/8406 with Taylor, get support from design (TODO: find design rep)
- [ ] https://github.com/carbon-design-system/carbon/issues/7210
  - [ ] https://github.com/carbon-design-system/carbon/issues/6865 if solved by #7210

**Jan**
- [x] Review Medium article re v11
- [x] Review new Releases page
- [x] New v11 page with Matt
- [ ] Work with Shixie and Jeannie on adding expressive to the site
  - [x] [Button](https://github.com/carbon-design-system/carbon-website/pull/2239)
  - [x] [List](https://github.com/carbon-design-system/carbon-website/pull/2240)
  - [ ] [Typography](https://github.com/carbon-design-system/carbon-website/pull/2242)
- [x] Finalize Carbon Standards for DPO initiative
- [ ] Review Tabs for Tracey
- [ ] Review Status indicators view for Thy
- [ ] EPM case study, begin research

**Jeannie**
 - [ ] Carbon Standards for DPO initiative with Matt, Jan
 - [ ] Ship v1 status icons with Thy
 - [ ] Ship v1 tabs with Tracey
 - [x] Strategy for illustrations for release Medium articles
 - [x] Chart illustrations
 - [ ] Work with Shixie and Jan on adding expressive to the site
   - [x] [Button](https://github.com/carbon-design-system/carbon-website/pull/2239)
   - [x] [List](https://github.com/carbon-design-system/carbon-website/pull/2240)
   - [ ] [Typography](https://github.com/carbon-design-system/carbon-website/pull/2242)
 

**Jillian**
- [x] [Fix broken Storybook links](https://github.com/carbon-design-system/carbon-website/issues/2246) in Code tabs on our site 
- [x] Complete IBM video training class, first half
- [x] Sketch kit updates :tada: 💎  :tada:
  - [x] [High contrast tag](https://github.com/carbon-design-system/carbon-design-kit/issues/421)
  - [x] [Tag number bug](https://github.com/carbon-design-system/carbon-design-kit/issues/369)
  - [x] [Highlight G10](https://github.com/carbon-design-system/carbon-design-kit/issues/420)
  - [x] [Checkbox icons](https://github.com/carbon-design-system/carbon-design-kit/issues/200)

**John**
 - [ ] Grid Tutorial Video script/storyboard

**Josefina**

- [ ] DUX table updates: https://github.ibm.com/DUX-Program/dux-program-website/issues/174
- [ ] https://github.com/carbon-design-system/carbon/issues/8472
- [ ] https://github.com/carbon-design-system/carbon/issues/7226
- [x] https://github.com/carbon-design-system/carbon/issues/8373
- [x] https://github.com/carbon-design-system/carbon/issues/8301 with Andrea
- [x] ~https://github.com/carbon-design-system/carbon/issues/8170 with Andrew~
- [x] ~https://github.com/carbon-design-system/carbon/issues/8370 with TJ~
- [x] ~https://github.com/carbon-design-system/carbon/issues/8395~

**Josh**

- [ ] https://github.com/carbon-design-system/carbon/issues/8408 with TJ
  - Sync'ed with Jan and Morgana, will continue implementation
- [x] https://github.com/carbon-design-system/carbon/issues/8516
- [x] https://github.com/carbon-design-system/carbon/issues/8403
- [ ] https://github.com/carbon-design-system/carbon/issues/8138
  - Need to specify specific outcomes in next sprint for this
- [ ] https://github.com/carbon-design-system/carbon/issues/6885
  - Could not tackle in given sprint
- [ ] ~~Continue popover, disclosure with Andrea + Lauren~~

**Lauren**
 - Popover/Disclosure
   - [ ] Design specs of common disclosures 
   - [ ] [Usage docs](https://www.notion.so/carbondesignsystem/Usage-8754dd12bf24485d91abf9039d4333f8) in notion (in progress)
- [x] Support/testing with Sketch plugin
- Adobe XD (pair with @thyhmdo)
    - [x] Connect icons from library to components

**Taylor**

- [ ] https://github.com/carbon-design-system/carbon/issues/8406 with DA, get support from design (TODO: find design rep)
- [x] https://github.com/carbon-design-system/carbon/issues/8144 
- [ ] Investigate https://github.com/carbon-design-system/carbon/issues/8145
- [ ] https://github.com/carbon-design-system/carbon/issues/2343
- [x] Sync with Tracey to scope out Tab updates

**Thy**
- [ ] Ship v1 status icons with Jeannie
- [ ] Adobe XD kit work
- [ ] Header image for Medium article about release update

**TJ**

- [x] https://github.com/carbon-design-system/carbon/issues/8370 with Josefina
- [x] https://github.com/carbon-design-system/carbon/issues/8413 with DA
- [ ] https://github.com/carbon-design-system/carbon/issues/4084 with Andrew
- [ ] https://github.com/carbon-design-system/carbon/issues/8408 with Josh
- [x] Add G80 theme https://github.com/carbon-design-system/carbon/issues/8471
- [x] https://github.com/carbon-design-system/carbon/issues/8458
- [x] https://github.com/carbon-design-system/carbon/issues/8523
- [ ] https://github.com/carbon-design-system/carbon/issues/8530

**Tracey**
- [ ] Tabs
- [x] Context menu https://github.com/carbon-design-system/carbon/pull/7350

**Ale**
- [x] https://github.ibm.com/Design/universal-experiences/issues/57 (remaining 6 UE content sections)
- [x] https://github.ibm.com/Design/universal-experiences/issues/59
- [x]  carbon-design-system/carbon-website#2192
- [x] SVG tooltip alignment issue[ fixed on ID](https://github.com/carbon-design-system/design-language-website/pull/922)L, need to fix on Carbon website also
- [ ] https://github.ibm.com/Design/w3-design/issues/1058

**Vince**
- [ ] status icons carbon-design-system/carbon-website#2199
- [ ] carbon-design-system/gatsby-theme-carbon#1061 (1:1 card component)
- [ ] Gatsby v3 update
- [ ] Publish theme and update sites to the latest 
_Carbon, IDL, AI, Research, D&UX, w3 design, UE_

**Comment by joshblack** [comment]
## Development

_This list is currently a proposal of tickets to take on during this Sprint_

**Enhancements**

- https://github.com/carbon-design-system/carbon/issues/8299
- https://github.com/carbon-design-system/carbon/pull/6942
- https://github.com/carbon-design-system/carbon/issues/6102

**Comment by alisonjoseph** [comment]
## DPO

- [ ] https://github.ibm.com/Design/w3-design/issues/1058
- [ ] https://github.ibm.com/Design/racial-equity-in-design/issues/235 (podcast page)
- [ ] Update sites to the latest gatsby theme (todo: add list of sites)

## Brand
- [ ] carbon-design-system/gatsby-theme-carbon#1061 (1:1 card component)

**Comment by tw15egan** [comment]
https://github.com/carbon-design-system/carbon/issues/8370 has some outstanding issues I'll need to work on next sprint

**Comment by tw15egan** [comment]
@dakahn and I are also planning to pair on https://github.com/carbon-design-system/carbon/issues/8413 and see if we can use `forced-colors` to handle HCM on all supported browsers
