### ISSUE TITLE
Remove deprecated code before v11 release

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#8410]
An epic to track the effort to remove all deprecated code from the codebase before the next major release.

Before we ship out our next major release, we should comb through the codebase and remove anything that has been marked for deprecation. 

This could include:
- Any react component that has a `deprecated` prop
- Comments in the style package that indicates code to be removed in the next major release
    - Can search the codebase for `deprecate` `remove` `major` or `v11` to see where comments have been added
- [x] https://github.com/carbon-design-system/carbon/issues/8421
- [x] https://github.com/carbon-design-system/carbon/issues/8418
- [x] https://github.com/carbon-design-system/carbon/issues/8419
- [x] https://github.com/carbon-design-system/carbon/issues/8420
