### ISSUE TITLE
Tab Updates and enhancements

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon#8487]
We are updating the usage docs to account for more use cases.
### Improvement on existing tabs

1. Name change (Default tabs we are now calling line tabs and container tabs we are now calling contained tabs)
2. Updating default functionality (We are recommending line tabs use auto-spacing and contained tabs can use either auto-spacing or grid)

### Adding modifiers
**Line tabs**

- Icon-only
- Label with icon

**Contained tabs**
- Icon-only
- Label with icon
- Label with secondary label
- Label with secondary label and icon

**Adding in motion**
- TBD - new issue will come for this

_See below more more details._

Pieces delivered in v11:
- [x] #10086
- [x] https://github.com/carbon-design-system/carbon/issues/9952
- [x] https://github.com/carbon-design-system/carbon/issues/9988
- [x] https://github.com/carbon-design-system/carbon/issues/9991
- [x] #10031
- [x] #10249
- ~Can/should LineTab(s) be separate components as well so `Tabs` can be a common primitive for both contained and line implementations?~

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/issues/11766
- [ ] https://github.com/carbon-design-system/carbon/issues/12844
- [ ] https://github.com/carbon-design-system/carbon/issues/12843
- [ ] https://github.com/carbon-design-system/carbon/issues/12813
- [ ] https://github.com/carbon-design-system/carbon/issues/12845
- [x] https://github.com/carbon-design-system/carbon/issues/12846
- [x] https://github.com/carbon-design-system/carbon/issues/12848
- [ ] https://github.com/carbon-design-system/carbon/issues/13351
- [ ] https://github.com/carbon-design-system/carbon/issues/13353
- [ ] https://github.com/carbon-design-system/carbon/issues/13389
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2660
- [ ] https://github.com/carbon-design-system/carbon/issues/13758
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/682
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3556
```

**Comment by kingtraceyj** [comment]
### Name update
In docs we will now refer to tabs as line tabs and container tabs as contained tabs. We're getting rid of the work default since we use it differently through our components.
 

### Default functionality
We now recommend using auto-spacing for line tabs. Contained tabs can use both auto-spacing or the grid.

**Line:**
![image](https://user-images.githubusercontent.com/20582179/115772618-f365c900-a374-11eb-88e9-e463a4641216.png)

**Contained:**
![image](https://user-images.githubusercontent.com/20582179/115772553-dd580880-a374-11eb-870b-c19260a80943.png)

## New modifiers

### Line tabs
**Icon-only**
![Screen Shot 2021-04-22 at 2 19 59 PM](https://user-images.githubusercontent.com/20582179/115773363-d7165c00-a375-11eb-84ef-fc63988edbc0.png)

**With icon**
![image](https://user-images.githubusercontent.com/20582179/115773557-1644ad00-a376-11eb-9095-7b858ea4b19c.png)

### Contained tabs
**Contained with icon** (auto-spaced and grid)
![image](https://user-images.githubusercontent.com/20582179/115773788-52780d80-a376-11eb-9706-dd6ea700b4f5.png)

Contained with secondary label + icon
![image](https://user-images.githubusercontent.com/20582179/115773871-73d8f980-a376-11eb-8f18-9b2f6887b5da.png)

Contained - icon-only
![image](https://user-images.githubusercontent.com/20582179/115773919-86ebc980-a376-11eb-8921-b20f5217ca65.png)

**Comment by kingtraceyj** [comment]
one small update -- we will have 2 sizes for the icon-only line tabs. a medium/default one (40px) and a large one (48px)
![image](https://user-images.githubusercontent.com/20582179/117199511-e6eb6280-adaf-11eb-9957-c43ad35dfe1c.png)

**Comment by kingtraceyj** [comment]
here are better, hopefully more helpful specs:
![Tabs - white theme](https://user-images.githubusercontent.com/20582179/118532279-69f3ad80-b70c-11eb-839f-ba80c1a1e727.png)
![Tabs - Specs - White theme](https://user-images.githubusercontent.com/20582179/118532441-9a3b4c00-b70c-11eb-91db-ce0035bfe83d.png)

**Comment by marceltrautmann** [comment]
Was any discussion had about aligning the icons to the left side of the tab?  In our trials it seemed to anchor the text better, and since the icons are informational only, they can act as a nice bullet.

This might also solve any possible conflict if the eye gets used to finding the 'X' close icon on the right (as is industry standard), which could suddenly be replaced by an informational metaphor instead possibly causing confusion.

Consider most browser tabs if you need to see a precedence

![image](https://user-images.githubusercontent.com/51379566/143313718-67f22937-df8f-4300-a301-fd255032ad4b.png)

**Comment by aagonzales** [comment]
The question of a dismissible tab with an icon is an interesting point we have not accounted for yet. However, in our system and the IBM Design Language icons are almost always right aligned to text (like button) so I think it would be preferred to keep them on the right. This allows for type inside the tab label to be aligned vertically with other type on the page (this being a major motif in the IBM design language).

**Comment by marceltrautmann** [comment]
OK, I get the rational, so long as carbon understands that is the the opposite of most all else in the industry are doing. Browsers, macOS, winOS, all have icons followed by text, and in the case of tabs, almost always X on hover to dismiss.  I get that our buttons are different, but is it enough to buck such entrenched patterns?

Also noticed in the carbon site itself there are cases where left icons seem to be ok (even tho carbon itself doesn't seem to allow anywhere)

<img width="383" alt="image" src="https://user-images.githubusercontent.com/51379566/144092598-77f124e4-fa59-442e-8dbf-d01f5bf3d487.png">

<img width="287" alt="image" src="https://user-images.githubusercontent.com/51379566/144092210-b370004f-d11d-436d-9b32-938a2ad5981f.png">

The windows 11 example above has an interesting feature that could also conflict with right aligned icons.  They seem to have split button with icon left, and caret right.  This strict 'align-right' policy will likely cause issues in the future when we eventually get more of these advance features.  I guess I should force my leftist views on others tho.  lol :-)

<img width="337" alt="image" src="https://user-images.githubusercontent.com/51379566/144093601-602cf1c5-ad31-4403-b3a1-8960ef3380f8.png">

**Comment by aagonzales** [comment]
I did say "almost always", like most rules there are exceptions, anchor links is one of them, left nav items and notifications are other examples. Most of these other examples don't require type alignment with other elements on the page and that is why they can be different. As a system (decisions made beyond the Carbon team), it has been ruled that type alignment is one of the biggest driving factors of how to place elements in relationship to each other and as such icons in tabs have been relegated to the right side. 

![image](https://user-images.githubusercontent.com/11670886/144096365-5c9157d7-f5e5-40bb-9ec1-3c6e58e10538.png)

**Comment by aagonzales** [comment]
As stated, we hadn't yet thought through dismissible tabs with an informational icon. I haven't run it past the rest of the team but I think that would be a case for an icon placement exception, mostly because an icon is in play on the right side already with the close icon. The default tab with only one icon would still remain on the right however, that would not change. 

![image](https://user-images.githubusercontent.com/11670886/144101820-f3810457-9245-4d39-b3a5-5bcab824f4e2.png)
![image](https://user-images.githubusercontent.com/11670886/144101863-799c7a63-b122-4f57-ad44-9bd9adb86634.png)

**Comment by aagonzales** [comment]
Or alternately, we could do it like safari tabs and have the close icon replace the info icon on the active tab and have the close icon appear on other tabs on hover. That way icon placement always stays consistent (on the right) no matter the kind of tab you have. 

![image](https://user-images.githubusercontent.com/11670886/144109215-6eac80ad-7ef9-40d5-9905-5e296caea4d4.png)

**Comment by marceltrautmann** [comment]
I'll be honest, I think you nailed it with the last scenario.  Much cleaner than the left>right scenario.

That said, and I know it's not the current focus and has been in the pipeline for a couple/few years, but what will be the impact when something like a split button comes along?  Just thinking forward abit.

**Comment by marceltrautmann** [comment]
@aagonzales 

I thought about it some more this AM, and altho I think you latest solution is elegant, I realize it prolly can't work for two reasons;

1. a11y — which meaning ends up in hover text?  both have value hence they are both there
2. device support — this solution can't work in cursor free environments, including full screen touch screen, tablet etc.  This of course leads to more a11y concerns when we offer one feature to one set of users and not the other.

back to left/right? :-(

**Comment by mjabbink** [comment]
Icons on the left and dismiss on right is A OK.

**Comment by alexandertrefz** [comment]
Hiding the close icon "behind" other icons creates the terrible UX that Safari creates for tabs: accidental closing becomes a real issue. In Safari at least there is a direct recourse to accidentally closing a tab, Carbon Apps would have to manually implement this behaviour while Users could not be reasonable expected to know how to get their closed tab back. Big thumbs down to hiding destructive action behind a hover on the same surface that otherwise is non-destructive and also a trigger that one clicks regularly. Safari tabs are probably the example for the worst Tab UX in any major application, copying them would be a disaster.

**Comment by mjabbink** [comment]
@aagonzales we do not need to avoid icons on the left in the Tab

**Comment by aagonzales** [comment]
@mjabbink so which do we want:

A: Descriptive icons always on the left for tabs and only close icon on the right

![image](https://user-images.githubusercontent.com/11670886/150870650-c12b538b-dc34-4979-952d-a52fea20b857.png)


B: Descriptive icons on the right unless there is also a close icon then descriptive icon goes on the left.

![image](https://user-images.githubusercontent.com/11670886/150870856-ecdbaf37-72f9-4228-9b03-39f0066d91a1.png)

C: No hard rules, users choose if descriptive icons goes on the right or left. Both are allowed. 

![image](https://user-images.githubusercontent.com/11670886/150870900-23b336ea-7c04-4175-8e24-5104c4e9b263.png)

**Comment by mjabbink** [comment]
A — 
Default tabs with icons on the left


B —
Dismissible tabs with icons on the left and close (X) on the right.

**Comment by mjabbink** [comment]
How likely for both tab types to be in one experience?


Is that 16px between icon and type?

**Comment by aagonzales** [comment]
All tabs in a set would be the same kind, a dismissible tab wouldn't be beside a default tab (to the best of my knowledge) 

And yes, it would be 16px padding. Might not be exact in the example was just cut and pasting images.

**Comment by aagonzales** [comment]
Talked to Mike in Slack, this is what we concluded for what's allowed with icons in tabs. 

![image](https://user-images.githubusercontent.com/11670886/150884058-bcb3fca8-f119-4dc1-9f27-81e5b9c1ec59.png)

**Comment by tay1orjones** [comment]
I want to provide an update as to the delivery of this. This required quite a bit of unexpected restructuring/foundational work to achieve these design enhancements. @abbeyhrt  has completed that work and it will be shipped in v11. It includes contained tabs, line tabs, icon only tabs, and has feature parity (overflow scrolling, etc) with the existing tabs in v10.

The remaining incomplete items do not require a breaking change. These improvements will be revisited post-v11. 

- Default tabs with descriptive icon
- Dismissible tabs and the related accessibility concerns
- Dismissible tabs with descriptive icon
- ContainedTabs secondary label

**Comment by tay1orjones** [comment]
To be clear, with the new API in v11 there's nothing blocking the configuration of the above items. Consumers can place their own custom elements, markup, components, etc into Tabs.

The revisiting of the items listed above will be aimed at making it easier to configure these types of tabs correctly out of the box.

**Comment by laurenmrice** [comment]
@francinelucca Here is an updated spec of Contained tabs with a secondary label and icon.

<img width="1312" alt="Frame 1" src="https://user-images.githubusercontent.com/43969356/225739370-c2977a6a-b60d-4931-b9bd-6c1e300e4e18.png">
