### ISSUE TITLE
Sprint 9: Raccoon Rambo 🦝

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#8513]
## May 3rd - May 14th

**Andrea**

- [ ] Continue Sketch Icons & Pictograms
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 PR #8188
- [x] #8275
   - [x] PR: https://github.com/carbon-design-system/carbon/pull/8461
- [ ] https://github.com/carbon-design-system/carbon/issues/8409 with Josefina
   - [ ] PR: https://github.com/carbon-design-system/carbon/pull/8579  (in draft)
- [x] https://github.com/carbon-design-system/carbon-website/issues/2252 (support from Alison / Josh)
   - [x] PR: https://github.com/carbon-design-system/carbon-website/pull/2292
- [x] https://github.com/carbon-design-system/carbon-website/issues/1946
   - [x] PR: https://github.com/carbon-design-system/carbon-website/pull/2287 
- [x] https://github.com/carbon-design-system/carbon/issues/8552 with DA
   - [x] PR: https://github.com/carbon-design-system/carbon-website/pull/7133 (in draft)

**Andrew**

- [ ] Continue Sketch Icons & Pictograms
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 PR #8188
  - [ ] #8539
  - [x] #8569
    - PR #8639
- [x] https://github.com/carbon-design-system/carbon-website/issues/2233
  - PR https://github.com/carbon-design-system/carbon-website/pull/2262
- [x] https://github.com/carbon-design-system/carbon/issues/7210
  - [x] #6865 if solved by #7210
- [x] https://github.com/carbon-design-system/carbon-website/issues/2106
  - PR https://github.com/carbon-design-system/carbon-website/pull/2284
- [x] https://github.com/carbon-design-system/carbon-website/issues/2003
  - PR https://github.com/carbon-design-system/carbon-website/pull/2276
- [x] chore: lint and format #2283 #2282
- [x] fix(ComboBox): prevent invalid option retention on Enter #8476 #8170
- [x] fix(ComboBox): add missing dependencies to useEffect #8308 #8306
- [x] fix(modal): add safari media query for overflow indicator #8510
- [x] fix(text-input): increase disabled password toggle specificity #8528 #8375
- [x] fix(button): ignore fill="none" paths on icon svgs #8585 #8583
- [x] feat(TooltipIcon): support renderIcon #8612 #8608
- [x] docs(Tag): remove test story #8669
- [x] fix(number-input): hide light variant stepper pseudoelements on focus #8652 #8649
- [x] feat(PasswordInput): sync input type prop and state #8368
- [x] fix(PasswordInput): resolve visibility toggle style issues #8673 #8672

**Anna**
- [x] V11: [Explore Sketch kit versioning/migration](https://github.com/carbon-design-system/carbon-design-kit/issues/431). 
- [ ] Update color guidelines page with new layering modal. https://github.com/carbon-design-system/carbon-website/issues/2258
- [ ] Audit website content delivered in a Notion table (size prop names, color tokens, cross-reference with prop PR to make sure all updates making it into the docs) with @jillianhowarth 

**DA**

- [x] https://github.com/carbon-design-system/carbon/issues/8406 with Taylor https://github.com/carbon-design-system/carbon/pull/8560
- [x] https://github.com/carbon-design-system/carbon-website/issues/2118 https://github.com/carbon-design-system/carbon-website/pull/2299
- [x] https://github.com/carbon-design-system/carbon/issues/8552 with Andrea https://github.com/carbon-design-system/carbon/pull/8671

**Jan**
- [x] Finish v11 page
- [x] Review Tabs for Tracey
- [x] Add links to Gatsby theme site from Resources
- [x] Put together a creative brief for Carbon Next to define next steps for research and design
- [x] Review Status indicators view for Thy
- [x] Carbon Standards for DPO initiative with Matt, Jan
- [ ] Work with Shixie and Jeannie on adding expressive to the site
  - [ ] [Typography](https://github.com/carbon-design-system/carbon-website/pull/2242)
- [ ] About Carbon pages with Mike

**Jeannie**
 - [ ] Production guidelines up on WIP page
 - [x] Status indicator PR with Vince
 - [ ] Work with Shixie and Jan on adding expressive to the site
   - [ ] [Typography](https://github.com/carbon-design-system/carbon-website/pull/2242)
- [ ] Grid page updates exploration with Taylor, Security designers

**Jillian**
- [ ] Sketch kit updates
  - [x] [Toggle: Update disabled state](https://github.com/carbon-design-system/carbon-design-kit/issues/428)
  - [x] [Modal: Audit bugs](https://github.com/carbon-design-system/carbon-design-kit/issues/409)
  - [ ] [Date picker: Background overrides](https://github.com/carbon-design-system/carbon-design-kit/issues/423)
- [ ] Audit website content delivered in a Notion table (size prop names, color tokens, cross-reference with prop PR to make sure all updates making it into the docs) with @aagonzales  
- [x] Patterns Tech Garage Carbon presentation
- [x] Work on Carbon Next research plan

**John**
- [ ] Grid tutorial video
- [ ] Animated icons

**Josefina**

- [x] https://github.com/carbon-design-system/carbon/issues/8472
- [x] https://github.com/carbon-design-system/carbon/issues/7226
- [ ] https://github.com/carbon-design-system/carbon/issues/8556 with Taylor
- [x] https://github.com/carbon-design-system/carbon/issues/8409 with Andrea

**Josh**

- [ ] https://github.com/carbon-design-system/carbon/issues/8555 with TJ
- [x] https://github.com/carbon-design-system/carbon/issues/8558 with Taylor
- [x] https://github.com/carbon-design-system/carbon/issues/8559
- [  ]  https://github.com/carbon-design-system/carbon/issues/8520

**Lauren**
- [x] EPWT Consent Form specs
- [x] Finish design specs of common disclosures
- [ ] Release Adobe XD kits (pair with @thyhmdo) (in progress)
- Support/testing with Sketch plugin
   - [x] [Artboard loading bug](https://github.com/carbon-design-system/carbon/pull/8639)
   - [ ] [Map color sync to color variables instead of layer styles](https://github.com/carbon-design-system/carbon/issues/8127)
   - [ ] [Artboard repositioning for new and deprecated icons](https://github.com/carbon-design-system/carbon/issues/8650)

**Scott**
Welcome back! 👶 
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1121

**Taylor**

- [ ] https://github.com/carbon-design-system/carbon/issues/8406 with DA
- [ ] https://github.com/carbon-design-system/carbon/issues/8556 with Josefina
  - TODO: find design rep for Grid docs on site
- [x] https://github.com/carbon-design-system/carbon/issues/8557 with TJ (Josh to support)
- [x] https://github.com/carbon-design-system/carbon/issues/8558 with Josh

**Thy**
- [ ] DPO data viz workstream with Kelly Renfro, Karel 
- [ ] Status indicator PR

**TJ**

- [ ] https://github.com/carbon-design-system/carbon/issues/8555 with Josh
- [x] https://github.com/carbon-design-system/carbon/issues/8557 with Taylor (Josh to support)
- [ ] https://github.com/carbon-design-system/carbon/issues/8409 with Andrea
- [x] https://github.com/carbon-design-system/carbon/issues/8563
- [x] https://github.com/carbon-design-system/carbon/issues/8542
- [ ] v10.35.0 https://github.com/carbon-design-system/carbon/issues/8636
- [x] https://github.com/carbon-design-system/carbon/issues/8633

**Tracey**
- [ ] Tabs (Specs, symbol, PR)
- [ ] Card pattern and changes to the Carbon site (@jeanservaas writing issue with reference links)
- [ ] Context menu

**Ale**
- [ ] carbon-design-system/gatsby-theme-carbon#1061 (1:1 card component) 

**Vince**
- [ ] https://github.com/IBM/plex/issues/353
- [ ]  status icons carbon-design-system/carbon-website#2199

**Comment by alisonjoseph** [comment]
Website
- [ ] Create v10 site https://github.com/carbon-design-system/carbon-website/issues/2252

**Comment by joshblack** [comment]
Notes for Sprint 9

- [ ] Add storybook v6 to `@carbon/react`
- [ ] Beta
  - [ ] Add guide for enabling features in `carbon-components` and `carbon-components-react`
  - [ ] Add guide for using `@carbon/react`
  - [ ] Add docs for CSS Grid Usage
  - [ ] Add docs for `@carbon/icons-react/next` usage
- [ ] Enhancements
  - [ ] Add container tokens (`$size-<t-shirt>`)
  - [ ] Update component sass files to Sass Modules
  - [ ] Inline Theming
  - [ ] UI Shell variants
- [ ] Migrations
  - [ ] Update `@carbon/upgrade` and enable `icons-react` codemod
  - [ ] Author codemods for size migrations
  - [ ] Author codemod for `bx` migration (?)
- [ ] Website
  - [ ] Add `next.carbondesignsystem.com` domain for v11
  - [ ] Component Demo

**Comment by aagonzales** [comment]
V11 Website tasks:
- [ ] Audit website content
- [ ] Update style and usage tabs with new color tokens. https://github.com/carbon-design-system/carbon-website/issues/2257
- [ ] Update color guidelines page with new layering modal. https://github.com/carbon-design-system/carbon-website/issues/2258
- [ ] Update size props across website docs https://github.com/carbon-design-system/carbon-website/issues/2260

V11 Kit tasks:
- [ ] Update Sketch kits with new color tokens https://github.com/carbon-design-system/carbon-design-kit/issues/429
- [ ] Update Sketch kits with new size props
- [ ] Update Adobe XD kits with new color tokens https://github.com/carbon-design-system/carbon-design-kit/issues/430
- [ ] Update Adobe XD kits with new size props
