### ISSUE TITLE
Sprint 10: Sloths on a Plane 🦥

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#8678]
## May 17th - May 28th

**Andrea**

- [ ] Continue Sketch Icons & Pictograms
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 PR #8188
- [x] https://github.com/carbon-design-system/carbon/issues/8409 with Josefina
   - [x] PR: https://github.com/carbon-design-system/carbon/pull/8579 (in draft)
- [ ] IBM Plex with Vince and TJ
- [ ] https://github.com/carbon-design-system/carbon/issues/6633 with Ale (Scott to shadow)
- [x] PR: https://github.com/carbon-design-system/carbon/pull/8763

**Andrew**

- [ ] Continue Sketch Icons & Pictograms
  - [ ] https://github.com/carbon-design-system/carbon/issues/8127 PR #8188 (blocked)
  - [x] #8539 PR #8762
  - [ ] #8650
  - [ ] #8766 PR #8770
  - [ ] #8786 PR #8787
- [x] help unblock and fix new icons PR https://github.com/carbon-design-system/carbon/pull/8546
  - [x] https://github.com/carbon-design-system/carbon/pull/8724
- [x] docs(TooltipDefinition): remove test button #8717
- [x] fix(button): explicitly set width for expressive theme #8686 #8685
- [x] fix(dropdown): show selected item in menu #8708 #8707
- [x] refactor(sharedStyles): use param object instead of list of params #8700
- [x] fix(structured-list): remove icon from hover state #8734 #8733 
- [x] fix(DatePicker): avoid unknown attribute on div #8747 #8743
- [x] fix(Tooltip): prevent focus hijacking by other tooltips with focus trap #8713 #8653
- [x] fix(DataTableSkeleton): use consistent header data shape #8721 #8719

**Anna**
- [ ] v11: Size props and color token audit for website
-  v11: Leading Lauren, Tracey, Thy, John for implementation of [size props](https://github.com/carbon-design-system/carbon-website/issues/2260) and [color token changes](https://github.com/carbon-design-system/carbon-website/issues/2257) (5 components per sprint)
   - [x] v11: color token implementation of changes [#2257](https://github.com/carbon-design-system/carbon-website/issues/2257)
- [x] v11: Color overview page: In [PR](https://github.com/carbon-design-system/carbon-website/pull/2359)

**DA**

- [ ] https://github.com/carbon-design-system/carbon/issues/8406 with Taylor
- [x] https://github.com/carbon-design-system/carbon/issues/8575
- [ ] Accessibility Primitives
- [x] https://github.com/carbon-design-system/carbon/issues/8687 with Scott https://github.com/carbon-design-system/carbon/pull/8714

**Jan**
- [x] Status indicator PR, naming conventions of the variants
- [x] Carbon Standard content guidelines… Liz’s comments
- [ ] Work with Shixie and Jeannie on adding expressive to the site
  - [ ] [Typography](https://github.com/carbon-design-system/carbon-website/pull/2242)
- [ ] Updating documentation for style council UI elements (Lauren)
- [x] Color overview page review for Anna
- [x] About Carbon pages

**Jeannie**
- [ ] Carbon Next: External site audits
- [ ] Carbon Next: Feature audits
- [ ] [Production guidelines in WIP](https://github.com/carbon-design-system/carbon-website/issues/1939)
- [ ] Write content about circle pack on Data viz advanced charts page

**Jillian**
- [ ] Internal site audits
- [x] Prepare for generative research (sprint 11)

**John**
- [x] v11: color token implementation of changes [#2257](https://github.com/carbon-design-system/carbon-website/issues/2257)
- [ ] Notification hook animation work with @tay1orjones and @dakahn 

**Josefina**

- [ ] https://github.com/carbon-design-system/carbon/issues/8556 with Taylor
- [ ] https://github.com/carbon-design-system/carbon/issues/8409 with Andrea
- [ ] PR: https://github.com/carbon-design-system/carbon-website/pull/8579 (in draft)
- [ ] Accessibility Primitives

**Josh**

- Carbon Next
- [ ] https://github.com/carbon-design-system/carbon/issues/8555 with TJ
- [ ] https://github.com/carbon-design-system/carbon/issues/8408 with TJ
- [ ] https://github.com/carbon-design-system/carbon/issues/8562 with Scott

**Lauren**
- [x] v11: color token implementation of changes [#2257](https://github.com/carbon-design-system/carbon-website/issues/2257)
- [ ] Usage docs for disclosure and popover (in progress)
- XD kits content (in notion)
  - [x] Changelog
  - [x] Adobe XD tab
- Support/testing with Sketch plugin
   - [x] [Map color sync to color variables instead of layer styles](https://github.com/carbon-design-system/carbon/issues/8127)
   - [ ] [Remove layer style command in favor of color variables](https://github.com/carbon-design-system/carbon/issues/8766)

**Scott**

- Carbon Next
- [ ] https://github.com/carbon-design-system/carbon/issues/8562 with Josh
- [x] https://github.com/carbon-design-system/carbon/issues/8687 with DA
- [ ] Shadow https://github.com/carbon-design-system/carbon/issues/6633 (Andrea, Ale)

**Taylor**

- [ ] https://github.com/carbon-design-system/carbon/issues/8556 with Josefina
- [x] https://github.com/carbon-design-system/carbon/issues/8406 with DA
- [ ] Remove deprecated React components in `next` branch after TJ has set it up
- [ ] https://github.com/carbon-design-system/carbon/issues/8475
- [ ] https://github.com/carbon-design-system/carbon/issues/8703 after visual design spec
- [x] https://github.com/carbon-design-system/carbon/pull/8705

**Thy**
- [x] v11: color token implementation of changes [#2257](https://github.com/carbon-design-system/carbon-website/issues/2257)
- [ ] Cards with Tracey

**TJ**

- [ ] https://github.com/carbon-design-system/carbon/issues/8555 with Josh
- [ ] IBM Plex with Vince and Andrea
- [ ] https://github.com/carbon-design-system/carbon/issues/8408 with Josh
- [x] Setup `next` branch for the monorepo

**Tracey**
- [x] v11: color token implementation of changes [#2257](https://github.com/carbon-design-system/carbon-website/issues/2257)
- [ ] Cards with Thy
- [ ] Finalizing tabs
- [x] Research a way for designers to do Support (talk with Alison & Josh about how they do it)

**Ale**
- [ ] carbon-design-system/gatsby-theme-carbon#1061 (1:1 card component) 
- [ ] Accessibility Primitives
- [ ] https://github.com/carbon-design-system/carbon/issues/6633 with Andrea (Scott to shadow)
- [ ] [1-2 issues from Brand prioritized AUX board](https://app.zenhub.com/workspaces/auxiliary-squad-5deea70733c75ceaf1bfacae/board?repos=181062037,181498056)

**Vince**
- [ ]  status icons carbon-design-system/carbon-website#2199
- [x] [1-2 issues from Brand prioritized AUX board](https://app.zenhub.com/workspaces/auxiliary-squad-5deea70733c75ceaf1bfacae/board?repos=181062037,181498056)
  - [x] https://github.com/carbon-design-system/design-language-website/issues/949
  - [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1109 (edited) 
- [ ] IBM Plex with TJ & Andrea
- [ ] Gastby v3
