### ISSUE TITLE
IBM Plex Integration

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8710]
Currently, we offer support for a handful of font faces (Sans, Mono, Serif) and a handful of weights (light, normal, semibold). We also offer a way for these fonts to be loaded easily through Google Fonts by default.

However, it seems like the usage for IBM Plex has grown broadly to include the following use-cases:

- Able to include different fonts from: http://github.com/ibm/plex for internationalization
- Able to leverage the Variable Font as opposed to Sans plus a variety of weights
- Able to bring in multiple weights as opposed to our limited set

This discussion is for figuring out the best API for providing these font faces across our different style targets, including:

- CSS
- Sass
- CSS-in-JS

Some broad changes that we'd also like to see happen:

- Provide a dedicated API or config for this in Carbon
- Provide a solid default similar to what we have now that works for most use-cases
- Provide a solid ramp for adding additional languages for internationalization
- Use fonts directly from `@ibm/plex` instead of having any checked into our packages

**Links & Resources**

- [IBM Plex on GitHub](https://github.com/ibm/plex)
- [Example with Inter UI](https://www.npmjs.com/package/inter-ui)

**Checklist**

- [ ] [IBM Plex v6.0](https://github.com/IBM/plex/issues/370)
- [ ] https://github.com/carbon-design-system/carbon/issues/8711
- [ ] https://github.com/carbon-design-system/carbon/issues/8712
- [ ] https://github.com/carbon-design-system/carbon/issues/9705
- [x] https://github.com/carbon-design-system/carbon/issues/10874

**Comment by joshblack** [comment]
_Project kick-off May 17th_

Notes:

- Plan for Sprint 10 is to have a Plex beta shipped with support for:
  - Sans
  - Arabic
  - Mono
  - Serif
- Our team will use this plex beta to interop with storybook v6, this work includes
  - How should we forward the plex sass in `@carbon/styles`
  - What's the best way to bring in language-specific fonts by a consumer?

**Comment by tay1orjones** [comment]
Complete from my understanding
