### ISSUE TITLE
Sprint 11: Tazmanian Things I Hate About You 🐀

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#8745]
**Ale**

- [ ] Disclosure (pair with Ale, Scott)
  - [ ] Implement initial useDisclosure hook
  - [ ] Continue writing out stories for disclosure from the Sketch file
  - [ ] Write out stories for combo button
  - [ ] Draft up what kinds of ways we can package up these patterns for teams to use
- [x] EDT - update API https://github.ibm.com/Design/EDT/issues/5890
- [ ] Racial Equity page addition https://github.ibm.com/Design/racial-equity-in-design/issues/255
- [ ] EDT - add link https://github.ibm.com/Design/EDT/issues/5888
- [ ] EDT - medallia update https://github.ibm.com/Design/EDT/issues/5887

**Andrea**

- [ ] Disclosure (pair with Ale, Scott)
  - [ ] [Implement initial useDisclosure hook](https://github.com/carbon-design-system/carbon/issues/8819)
  - [ ] Continue writing out stories for disclosure from the Sketch file
  - [ ] Write out stories for combo button
  - [ ] Draft up what kinds of ways we can package up these patterns for teams to use
- [ ] https://github.com/carbon-design-system/carbon/issues/8441
- [ ] Add initial popover storybook docs (pair with DA)

**Andrew**

- [ ] Continue Sketch plugin integration
  - [ ] #8127 PR #8188 (blocked)
  - [ ] #8650
  - [ ] #8766 PR #8770
  - [ ] #8786 PR #8787
- [ ] https://github.com/carbon-design-system/carbon/issues/8788 blocked, awaiting upstream changes
- [x] https://github.com/carbon-design-system/carbon/issues/8180 #8820
- [ ] https://github.com/carbon-design-system/carbon/issues/7055 awaiting response from author
- [x] fix(Tooltip): avoid stealing focus when dismissing with mouseclick #8820 #8180 

**Anna**
   - [x] v11: color token implementation of changes - UI Shell [#2257](https://github.com/carbon-design-system/carbon-website/issues/2257)
   - [ ] v11: Website color implementation docs
   - [x] v11: Leading Thy, John, ? for [website audit](https://github.com/carbon-design-system/carbon/issues/8815) and implementation of [size props](https://github.com/carbon-design-system/carbon-website/issues/2260)
   - [ ] Think about Figma work stream/planning with @laurenmrice 
   - [x] v11: [values for new tokens](https://www.notion.so/carbondesignsystem/Hybrid-List-of-new-tokens-c507394e43fe4daa9f0cd0eedb25d1e4)

**DA**

- [ ] Tooltip (pair with Josefina)
  - [ ] https://github.com/carbon-design-system/carbon/issues/8814
  - [ ] https://github.com/carbon-design-system/carbon/issues/8817
  - [ ] Add initial storybook docs
- [x] Draft up requirements for `Dialog` component https://github.com/carbon-design-system/carbon/issues/8826
- [x] Add initial popover storybook docs (pair with DA)

**Jeannie**
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2367

**Jillian**

- [x] Generative research for Carbon Next
- [x] Pattens Intern Presentation

**John**
- [ ] v11: website [content audit ](https://github.com/carbon-design-system/carbon/issues/8815)for color tokens and component sizes
- [ ] v11: website implementation of [size props](https://github.com/carbon-design-system/carbon-website/issues/2260) changes

**Josefina**

- [x] Release `v10.37.0` with Andrea
- [x] Tooltip (pair with DA)
  - [x] Implement definition tooltip styles
  - [x] Implement icon tooltip styles (wip)
  - [x] Add initial storybook docs (wip)
- [ ] https://github.com/carbon-design-system/carbon/issues/8744
- [x] https://github.com/carbon-design-system/carbon/issues/8501

**Josh**

- [ ] Bring over ~5 component styles to Sass module format (sync with Taylor, TJ)
- [x] Bring in migration CLI updates for migrate CLI
- [ ] Add migration test runner (pair with Scott)
- [ ] Bring in new tokens from theming strategy update
- [ ] Implement contextual tokens (pair with TJ)
- [x] https://github.com/carbon-design-system/carbon/issues/8811

**Lauren**

- [x] Usage and style docs for [Popover component](https://www.notion.so/carbondesignsystem/Usage-8754dd12bf24485d91abf9039d4333f8?showMoveTo=true) (in progress)
- [x] Usage docs for docs for [Disclosure pattern](https://www.notion.so/carbondesignsystem/Disclosures-5cb98bc7caa7453a8bbdd8d7475c8bed) (in progress)
- [ ] Help with interactive tooltip usage docs changes
- [ ] Think about Figma work stream/planning with @aagonzales  

**Scott**

- [x] Disclosure (pair with Ale, Scott)
  - [x] Implement initial useDisclosure hook
  - [ ] Continue writing out stories for disclosure from the Sketch file
  - [ ] Write out stories for combo button
  - [ ] Draft up what kinds of ways we can package up these patterns for teams to use
- [ ] Add migration test runner (pair with Josh)
- [ ] https://github.com/carbon-design-system/carbon/issues/8812

**Taylor**

- [ ] Create initial `useNotification` proof-of-concept
- [ ] Bring over ~5 component styles to Sass module format (sync with TJ, Josh)
- [ ] https://github.com/carbon-design-system/carbon/issues/8287
- [ ] https://github.com/carbon-design-system/carbon/issues/3922
- [x] ~#8789~

**Thy**
- [x] v11: website [content audit ](https://github.com/carbon-design-system/carbon/issues/8815)for color tokens and component sizes
- [ ] v11: website implementation of [size props](https://github.com/carbon-design-system/carbon-website/issues/2260) changes
   - [ ] Tag 
   - [ ] Toggle

**TJ**

- [ ] Bring over ~5 component styles to Sass module format (sync with Taylor, Josh)
- [ ] https://github.com/carbon-design-system/carbon/issues/8764
- [x] https://github.com/carbon-design-system/carbon/issues/8460
- [ ] Implement contextual tokens (pair with Josh)
- [ ] Start chipping away at storybook v6 interop: https://github.com/carbon-design-system/carbon/issues/8799

**Tracey**

- [ ] Notification actionable visual spec with @tay1orjones https://github.com/carbon-design-system/carbon/issues/8703
- [ ] Update v11 notification docs to incorporate new variants

**Vince**
- [ ] EDT - look into security vulnerability https://github.ibm.com/Design/EDT/issues/5889
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1108
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2372
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1128

**Comment by alisonjoseph** [comment]
**DPO**

- [ ] Racial Equity page addition https://github.ibm.com/Design/racial-equity-in-design/issues/255
