### ISSUE TITLE
Sprint 12: The Unicorn Suspects 🦄

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8870]
## June 14th - 25th

**Ale**
- [x] Racial Equity page addition https://github.ibm.com/Design/racial-equity-in-design/issues/255
- [x] https://github.com/carbon-design-system/carbon/issues/8819
- [x] carbon-design-system/design-language-website#894
- [x] carbon-design-system/gatsby-theme-carbon#1133
- [x] carbon-design-system/gatsby-theme-carbon#1128

**Andrea**
- [x] v10.37.0 release
- [x] v10.37.1 release
- [x] v10.38.0 release
- [x] Migration project kick-off
- [x] https://github.com/carbon-design-system/carbon/issues/8900 (fixed by @emyarod :) - PR: https://github.com/carbon-design-system/carbon/pull/8912#pullrequestreview-684394839)
- [x] Bring over ~3 component styles to Sass module format
- [x] Notification
- Issue: https://github.com/carbon-design-system/carbon/issues/8905
- PR: https://github.com/carbon-design-system/carbon/pull/9004
- [x] Number Input
- Issue: https://github.com/carbon-design-system/carbon/issues/8919
- PR: https://github.com/carbon-design-system/carbon/pull/8935
- [x]  Overflow menu
- Issue: https://github.com/carbon-design-system/carbon/issues/8925
- PR: https://github.com/carbon-design-system/carbon/pull/8970
- [x] https://github.com/carbon-design-system/carbon/issues/8701 (TJ to help out with process)
- https://github.com/carbon-design-system/carbon/pull/9025
- [x] https://github.com/carbon-design-system/carbon/issues/8902 (pair with TJ)
- [x] https://github.com/carbon-design-system/carbon/issues/8819
- PR: https://github.com/carbon-design-system/carbon/pull/9006
- [x] EDT - add link https://github.ibm.com/Design/EDT/issues/5888
- PR: https://github.ibm.com/Design/EDT/pull/5896
- [ ] EDT - medallia update https://github.ibm.com/Design/EDT/issues/5887)

**Andrew**

- [ ] Continue Sketch plugin integration
  - [x] #8127
    - PR #8188 (blocked)
  - [x] #8650
  - [x] #8766
    - PR #8770
  - [x] #8786
    - PR #8787
- [x] https://github.com/carbon-design-system/carbon/issues/8847
  - PR #8945
- [x] https://github.com/carbon-design-system/carbon/issues/8828
  - #8918
- [x] https://github.com/carbon-design-system/carbon/issues/8883
- [x] #8900
  - PR #8912
- [x] #8884
  - PR #8910
- [x] #8893
  - PR #8892
- [x] #8913 
  - PR #8914
- [x] #8932 
  - PR #8933
- [x] #9002

**Anna**

- [ ] v11: [Website color implementation docs](https://ibm.box.com/s/9ls5y59colhnfam7nh8vemyaky9dle8q)
- [x] v11: Size props https://github.com/carbon-design-system/carbon-website/issues/2408

**DA**

- [ ] Tooltip (pair with Josefina)
  - [x] https://github.com/carbon-design-system/carbon/issues/8814
  - [x] https://github.com/carbon-design-system/carbon/issues/8817
  - [ ] Add initial storybook docs
- [x] Search sass module refactor https://github.com/carbon-design-system/carbon/pull/8967
- [x] Tooltip sass module refactor https://github.com/carbon-design-system/carbon/pull/8982
- [x] Radiobutton sass module refactor https://github.com/carbon-design-system/carbon/pull/8980
- [x] https://github.com/carbon-design-system/carbon/issues/8891
- [x] https://github.com/carbon-design-system/carbon/issues/8890

**Jeannie**

- [x] Status indicator PR review https://github.com/carbon-design-system/carbon-website/pull/2377
- [ ] Add production guidelines card to website (w/ Lauren)
- [x] Design Mavens presentation (w/ Mike)

**Jillian**
- [x] Generative research synthesis
- [ ] Internal site audit
- [x] Patterns Tech Garage presentation

**John**
- [ ] Migration project (in progress)
- [x] v11: size tokens

**Josefina**

- [x] `v10.37.1` release
- [x] `v10.38.0` release
- [x] Migration project kick-off
- [ ] Tooltip (pair with DA)
  - [x] https://github.com/carbon-design-system/carbon/issues/8814
  - [x] https://github.com/carbon-design-system/carbon/issues/8817
  - [ ] Add initial storybook docs
- [x] Bring over ~3 component styles to Sass module format
   - [x] Pagination 
   - [x] Progress indicator
   - [x] Select
- [x] https://github.com/carbon-design-system/carbon/issues/8842
- [x] https://github.com/carbon-design-system/carbon/issues/8903 (pair with Josh)
- [x] https://github.com/carbon-design-system/carbon/issues/8904

**Josh**

- [ ] Add migration test runner 
- [x] Bring in new tokens from theming strategy update
- [ ] Implement contextual tokens
- [x] https://github.com/carbon-design-system/carbon/issues/8852
- [x] https://github.com/carbon-design-system/carbon/issues/8822 (pair with Scott)
- [x] https://github.com/carbon-design-system/carbon/issues/8903 (pair with Josefina)

**Lauren**
- [x] Migration project (in progress)
- [ ] [Production guidelines kit](https://github.com/carbon-design-system/carbon-website/issues/2367) (in progress) @jeanservaas 
- [ ] Usage and style docs for [Popover component](https://www.notion.so/carbondesignsystem/Usage-8754dd12bf24485d91abf9039d4333f8?showMoveTo=true) (in progress)
- [ ] Usage docs for docs for [Disclosure pattern](https://www.notion.so/carbondesignsystem/Disclosures-5cb98bc7caa7453a8bbdd8d7475c8bed) (in progress)

**Scott**

- [x] Migration project kick-off
- [x] Bring over 2 components into Sass Module format
- [x] https://github.com/carbon-design-system/carbon/issues/8828 (pair with Andrew)
- [ ] https://github.com/carbon-design-system/carbon/issues/8764 (work with Vince to determine font stack, Josh for integration)
- [x] https://github.com/carbon-design-system/carbon/issues/8819
- [x] https://github.com/carbon-design-system/carbon/issues/8822 (pair with Josh)
- [ ] Remote learning fix / deployment update

**Taylor**

- [x] Bring over 3 components into Sass Module format
- [x] https://github.com/carbon-design-system/carbon/issues/8287
- [x] ~https://github.com/carbon-design-system/carbon/issues/3922~ (investigated, blocked for now)
- [x] https://github.com/carbon-design-system/carbon/issues/8901
- [x] https://github.com/carbon-design-system/carbon/pull/8863
- [x] https://github.com/carbon-design-system/carbon/pull/8958

**Thy**
- [ ] v11: Typography page (w/ Jan)
- [ ] Cards
- [x] https://github.com/carbon-design-system/carbon-website/issues/2408
- [x] https://github.com/carbon-design-system/carbon-website/pull/2418

**TJ**

- [ ] Bring over components into Sass Module format
- [x] https://github.com/carbon-design-system/carbon/issues/8854
- [ ] https://github.com/carbon-design-system/carbon/issues/8701 (assist Andrea with process)
- [x] https://github.com/carbon-design-system/carbon/issues/8902 (pair with Andrea)

**Tracey**

- [ ] v11: Notification docs (w/ Taylor)

**Vince**
- [ ] Plex
- [ ] Gatsby V3
- [x] Status indicator PR https://github.com/carbon-design-system/carbon-website/issues/2377
- [ ] EDT - look into security vulnerability https://github.ibm.com/Design/EDT/issues/5889

**Comment by joshblack** [comment]
## Support

- https://github.com/carbon-design-system/carbon/issues/8847

## Enhancements

- https://github.com/carbon-design-system/carbon/issues/8852

**Comment by alisonjoseph** [comment]
## Brand Support

- https://github.com/carbon-design-system/design-language-website/issues/894
- https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1133
- https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1128
