### ISSUE TITLE
Sass Module Refactor

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8899]
This issue currently tracks our efforts refactoring our codebase to Dart Sass using Sass modules.

**Components**

- [x] Accordion
- [x] Breadcrumb
- [x] Button
- [x] Checkbox
- [x] Code Snippet
- [x] Combobox
- [x] Content Switcher https://github.com/carbon-design-system/carbon/pull/8862
- [x] Copy Button
- [x] Data Table @tay1orjones https://github.com/carbon-design-system/carbon/pull/8844
- [x] Date Picker @tay1orjones  https://github.com/carbon-design-system/carbon/pull/8895
- [x] Dropdown 
- [x] File Uploader @tay1orjones https://github.com/carbon-design-system/carbon/pull/8920
- [x] Floating Menu
- [x] Form
- [x] Grid https://github.com/carbon-design-system/carbon/pull/8797
- [x] #9027
- [x] Link
- [x] Listbox 
- [x] List
- [x] Loading https://github.com/carbon-design-system/carbon/pull/9030
- [x] Menu @tay1orjones https://github.com/carbon-design-system/carbon/pull/8922
- [x] Modal @tay1orjones https://github.com/carbon-design-system/carbon/pull/8923
- [x] MultiSelect 
- [x] Notification https://github.com/carbon-design-system/carbon/pull/9004
- [x] Number Input 
- [x] Overflow Menu
- [x] Pagination Nav https://github.com/carbon-design-system/carbon/issues/9068
- [x] Pagination @jnm2377 https://github.com/carbon-design-system/carbon/pull/8953/
- [x] Popover @dakahn 
- [x] Progress Bar https://github.com/carbon-design-system/carbon/issues/9075 @tw15egan 
- [x] Progress Indicator @jnm2377 https://github.com/carbon-design-system/carbon/pull/9022
- [x] Radio Button @dakahn #8980 
- [x] Search @dakahn #8967 
- [x] Select @jnm2377 https://github.com/carbon-design-system/carbon/pull/8953/
- [ ] Skeleton @jnm2377 https://github.com/carbon-design-system/carbon/issues/9130
- [x] Slider @sstrubberg #8981
- [x] Structured List @sstrubberg #8931
- [x] Tabs @sstrubberg 
- [x] Tag @dakahn 
- [x] Text area #9037 
- [x] Text Input @sstrubberg #8988
- [x] Tile #9049 @tw15egan  https://github.com/carbon-design-system/carbon/pull/9054
- [x] Time Picker https://github.com/carbon-design-system/carbon/pull/9061 @tw15egan 
- [x] Toggle #9026 
- [x] Toolbar @andreancardona https://github.com/carbon-design-system/carbon/pull/9004
- [x] Tooltip https://github.com/carbon-design-system/carbon/pull/8982 @dakahn 
- [x] Tree View @andreancardona #9105 
- [x] UI Shell @jnm2377 https://github.com/carbon-design-system/carbon/issues/9129

**Comment by joshblack** [comment]
**Links & Resources**

- https://github.com/carbon-design-system/carbon/issues/7538#issuecomment-758834140
- https://sass-lang.com/blog/the-module-system-is-launched
- https://css-tricks.com/introducing-sass-modules/
- https://sass-lang.com/documentation/at-rules/use
- https://sass-lang.com/documentation/at-rules/forward

**Comment by joshblack** [comment]
## Reference

### Migration process

1. 

### Common migrations

**`$prefix`**

```diff
+@use '../../config' as *;
```

**`type-style`**

```diff
+@use '../../type';

...

.#{$prefix}--component {
-  @include type-style('body-short-01');
+  @include type.type-style('body-short-01');
}
```

**Button reset**

```diff
-@import '../../globals/scss/helper-mixins';
+@use '../../utilities/button-reset';
```

**Component reset**

```diff
-@import '../../globals/scss/css--reset';
+@use '../../utilities/component-reset';
```

**Tokens**

```diff
-@import '../../globals/scss/vars';
+@use '../../theme' as *;
```

**`duration--*`**

```diff
-@import '../../globals/scss/vars';
@use '../../motion' as *;

...

.#{$prefix}--my-component {
-  transition: color $duration--fast-01 motion(standard, productive);
+  transition: color $duration-fast-01 motion(standard, productive);
}
```

**helper mixins**

```diff
-@import '../../globals/scss/helper-mixins';

// Focus outline
+@use '../../utilities/focus-outline' as *;
```

**spacing**

```diff
-@import '../../globals/scss/vars';
+@use '../../spacing' as *;
```

**rem**

```diff
+@use '../../utilities/convert';

...

-margin: rem(24px);
+margin: convert.rem(24px);
```
