### ISSUE TITLE
Test components with Cypress & Percy

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8943]
We would like to make use of Cypress & Percy to refactor our user-driven e2e tests into two buckets:

- User-driven e2e tests run through the browser with Cypress
- Visual Regression Testing using these user-driven scenarios powered by Percy https://github.com/carbon-design-system/carbon/issues/8911

These tests should follow our [testing guide](https://github.com/carbon-design-system/carbon/blob/main/docs/style.md#testing)

**Prerequisites**

- [ ] Enable the following ESLint plugins:
  - [x] #9047
  - [x] #9048
  - [x] https://www.npmjs.com/package/eslint-plugin-cypress
- [ ] Schedule a meeting with design and development to go over workflow and document in playbook
- [ ] Schedule a meeting with development to go over step-by-step refactor flow and document in this epic

**Components**

- [ ] Accordion
- [ ] Breadcrumb
- [ ] Button
- [ ] Checkbox
- [ ] Code Snippet
- [ ] Combobox
- [ ] Content Switcher
- [ ] Copy Button
- [ ] Data Table
- [ ] Date Picker
- [ ] Dropdown
- [ ] File Uploader
- [ ] Floating Menu
- [ ] Form
- [ ] Grid
- [ ] Inline Loading
- [ ] Link
- [ ] Listbox
- [ ] List
- [ ] Loading
- [ ] Menu
- [ ] Modal
- [ ] MultiSelect
- [ ] Notification 
- [ ] Number Input
- [ ] Overflow Menu
- [ ] Pagination Nav
- [ ] Pagination
- [ ] Popover
- [ ] Progress Bar
- [ ] Progress Indicator
- [ ] Radio Button
- [ ] Search
- [ ] Select
- [ ] Skeleton
- [ ] Slider
- [ ] Structured List
- [ ] Tabs
- [ ] Tag
- [ ] Text Area
- [ ] Text Input
- [ ] Tile
- [ ] Time PIcker
- [ ] Toggle
- [ ] Toolbar
- [ ] Tooltip
- [ ] Tree View
- [ ] UI Shell

**Comment by joshblack** [comment]
### Step by step guide

TODO

**Comment by tay1orjones** [comment]
Closing. We've migrated away from cypress to instead use playwright and added baseline VRT snapshots for all components in https://github.com/carbon-design-system/carbon/pull/11302
