### ISSUE TITLE
Sprint 13: V for Velociraptors 🦖

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8966]
## June 28th - July 9th

Ale

- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1061
- [x] 3 Sass Module Refactors
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1128
- [x] https://github.com/carbon-design-system/design-language-website/issues/894
- [x] https://github.ibm.com/Design/EDT/issues/5887

Andrea

- [x] v10.39.0 Release
- [x] 3 Sass Module Refactors
- [x] PaginationNav -  PR: https://github.com/carbon-design-system/carbon/pull/9076
- [x] Treeview - PR: https://github.com/carbon-design-system/carbon/pull/9105 
- [x] Migration placeholder
- [x] #9079

Andrew

- [x] Update packages/react storybook to v6 (let me know if you want to take this on, wasn't sure if you were tackling it as a part of last sprint's work)
  - [x] #9062
- [x] https://github.com/carbon-design-system/carbon/issues/8793
- [x] https://github.com/carbon-design-system/carbon/issues/8794
- [x] #9072 #9074
- [x] #9112 #9138
- [x] #9134 #9139
- [x] #9140
- [x] #9141

Anna (OOO 6/29-7/2 🌴)

- [x] https://github.com/carbon-design-system/carbon-website/issues/2258
   - [ ] https://github.com/carbon-design-system/carbon-website/pull/2444#event-5002192714 v11: Website color implementation docs
   - [ ] ~v11: Color usage page designs~ moved to sprint 14

DA

- [ ] 3 Sass Module Refactors
- [x] https://github.com/carbon-design-system/carbon/issues/8993
- [x] https://github.com/carbon-design-system/carbon/issues/9047 (pair with Josh)
- [x] https://github.com/carbon-design-system/carbon/issues/9048

Jeannie (OOO 6/28 🌴)
- [x] Add production guidelines card to website (w/ Lauren)
- [x] Redesign typography specs page, handoff specs to Scott

Jillian
 - [x] Internal site audit
 - [x] Patterns for tech garage presentation 
 - [x] Interns research support
 - [x] IBM Design field guide review 

John
- [ ] Migration project

Josefina

- [x] 2 Sass Module Refactors
    - [ ] UI shell (wip) https://github.com/carbon-design-system/carbon/issues/9129
- [x] https://github.com/carbon-design-system/carbon/issues/8744
- [x] https://github.com/carbon-design-system/carbon/issues/8904
- [x] https://github.com/carbon-design-system/carbon/issues/8842
- [x] https://github.com/carbon-design-system/carbon/issues/8965 (pair with TJ)
- [x] Migration placeholder

Josh

- [x] Bring in new tokens from theming strategy update
- [x] Implement contextual tokens
- [ ] https://github.com/carbon-design-system/carbon/issues/8764 (work with Scott)
- [x] Update dependencies for telemetry package
- [x] https://github.com/carbon-design-system/carbon/issues/9047 (pair with DA)

Lauren
- [x] v11 Migration project interviews/synthesizing info/playback
- [x] Figma planning and audits
- [x]  Production guidelines kit @jeanservaas 
   https://github.com/carbon-design-system/carbon-website/issues/2367) 
- [ ] Usage and style docs for [Popover component](https://www.notion.so/carbondesignsystem/Usage-8754dd12bf24485d91abf9039d4333f8?showMoveTo=true) (almost done!)

Scott

- [x] https://github.com/carbon-design-system/carbon/issues/8934
- [ ] https://github.com/carbon-design-system/carbon/issues/8764 (work with Vince for Plex, Josh for integration)
- [ ] Migration placeholder
- [ ] 2 Sass Module Refactors

Taylor - (OOO 6/28-7/7 🌴)

Thy
- [ ] Tile usage docs refresh
- [x] Make announcement for Status indicators release

TJ

- [x] 2 Sass Module Refactors
- [x] https://github.com/carbon-design-system/carbon/issues/8854
- [x] https://github.com/carbon-design-system/carbon/issues/8746
- [x] https://github.com/carbon-design-system/carbon/issues/8965 (pair with Josefina)

Tracey
- [ ] v11: Toast Notification docs
   - https://github.com/carbon-design-system/carbon-website/pull/2420 
   - https://github.com/carbon-design-system/carbon-website/pull/2421
   - https://github.com/carbon-design-system/carbon-website/pull/2422 
- [ ] Update Tooltip docs with a11y changes

Vince

**Comment by joshblack** [comment]
## Support

## Enhancements

## v11

**Comment by alisonjoseph** [comment]
## Brand
- https://github.com/ibm-brand/event-design/issues/49
