### ISSUE TITLE
Sprint 14: War of the Wombats 🐀

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9123]
## July 12th - July 23rd

**Ale**
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1061
- [ ] Experience Standards website (Universal Experiences update) https://github.ibm.com/Design/universal-experiences/issues/68 #standards-website-team (slack channel)

**Andrea**

- [ ] https://github.com/carbon-design-system/carbon/issues/9166 (with Josefina, Scott)
- [ ] https://github.com/carbon-design-system/carbon/issues/9175 with DA, TJ
- [x] https://github.com/carbon-design-system/carbon/issues/9178 with Josh
- [x] https://github.com/carbon-design-system/carbon/issues/9177 with Josh
- [ ] Release (with Josh)
  - [ ] Publish @carbon/react@0.1.0 and tag it as beta
  - [ ] Publish @carbon/styles@0.1.0 and tag it as beta

**Andrew**

- [x] #9145
- [x] https://github.com/carbon-design-system/carbon/issues/8875
  - https://github.com/carbon-design-system/carbon/pull/9215
- [x] https://github.com/carbon-design-system/carbon/issues/9163
  - https://github.com/carbon-design-system/carbon/pull/9209
- [x] https://github.com/carbon-design-system/carbon/issues/9155
  - https://github.com/carbon-design-system/carbon/pull/9189
- [x] #8995
  - https://github.com/carbon-design-system/carbon/pull/9204

**Anna**
- [x] https://github.com/carbon-design-system/carbon-website/pull/2444#event-5002192714 V11: Finish design content for review
- [ ] V11: Update hover color section (no longer doing `adjustLightness`)?
- [x] V11: Add new tokens to Beta Sketch Kit | [White theme](https://www.sketch.com/s/fabc8814-ead2-4eeb-a893-ef3b6ea88875) | [Gray 100 theme](https://www.sketch.com/s/9b33e49d-9b79-4696-9f57-c7a15c1e276a)
      
**DA**

- [ ] https://github.com/carbon-design-system/carbon/issues/9172 with TJ
- [ ] https://github.com/carbon-design-system/carbon/issues/9175 with Andrea, TJ
- [x] Tag sass module refactor https://github.com/carbon-design-system/carbon/pull/9131
- [ ] Popover sass module refactor https://github.com/carbon-design-system/carbon/pull/9257
- [x] https://github.com/carbon-design-system/carbon/issues/9183 with Josh https://github.com/carbon-design-system/carbon/pull/9201
- [x] https://github.com/carbon-design-system/carbon/issues/9184 with Josh

**Jeannie**
- [x] Production guidelines announcement 
- [x] https://github.com/carbon-design-system/carbon-website/issues/2447
- [ ] Spec 8 Column fixed image component for website

**Jillian** (OOO 7/12-7/16 🌴)
- [x] ECP Patterns presentation
- [x] Carbon Next/Experience System planning
- [x] Experience System Jobs to be Done work
 
**John** (OOO 7/12-7/16 )
- [ ] Migration project

**Josefina** (OOO 7/12-7/16 🌴)

- [ ] https://github.com/carbon-design-system/carbon/issues/9166 with (Andrea, Scott)

**Josh**

- [x] https://github.com/carbon-design-system/carbon/issues/9183 with DA
- [x] https://github.com/carbon-design-system/carbon/issues/9184 with DA
- [x] https://github.com/carbon-design-system/carbon/issues/9185
- [x] https://github.com/carbon-design-system/carbon/issues/9176
- [x] https://github.com/carbon-design-system/carbon/issues/9178 with Andrea
- [ ] https://github.com/carbon-design-system/carbon/issues/9171 with TJ
- [ ] Release (with Andrea)
  - [ ] Publish @carbon/react@0.1.0 and tag it as beta
  - [ ] Publish @carbon/styles@0.1.0 and tag it as beta

**Lauren** (OOO 7/12-7/16 🌴)
- [x] Usage/style docs for [Popover component](https://www.notion.so/carbondesignsystem/Usage-8754dd12bf24485d91abf9039d4333f8?showMoveTo=true) 
- [ ] Usage docs for Disclosure pattern (in progress)
- [x] v11 migration
- [x] Figma planning

**Scott**

- [ ] https://github.com/carbon-design-system/carbon/issues/9166 (with Andrea, Josefina)
- [ ] Sass Modules
- [ ] https://github.com/carbon-design-system/carbon/issues/8764 with Josh

**Taylor**

- [x] https://github.com/carbon-design-system/carbon/issues/9174
- [x] https://github.com/carbon-design-system/carbon/issues/9179
- [x] https://github.com/carbon-design-system/carbon/issues/9182
- [ ] Add VRT tests for 3 components, document process for next sprint (pair with TJ)

**Thy**
- [ ] Usage docs: Tile component
- [x] Patterns presentation

**TJ**
- [x] https://github.com/carbon-design-system/carbon/issues/9129
- [x] https://github.com/carbon-design-system/carbon/issues/9203
- [ ] https://github.com/carbon-design-system/carbon/issues/9172 with DA
- [x] https://github.com/carbon-design-system/carbon/issues/9168
- [ ] https://github.com/carbon-design-system/carbon/issues/9175 with Andrea, DA
- [x] https://github.com/carbon-design-system/carbon/issues/9180
- [ ] Add VRT tests for 3 components, document process for next sprint (pair with Taylor)

**Tracey**
- [ ] v11: Update Tooltip docs with a11y changes
- [x] Patterns presentation

**Vince**
- Brand

**Comment by joshblack** [comment]
### 💬  Support


### 🆕  Enhancements


### 🚢  Migration


### 👓   Visual Testing
