### ISSUE TITLE
Sprint 15: Predator X-Ray Tetra 🐠 

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9243]
## 🎨  Styles

- [x] #9175 @tw15egan @andreancardona @dakahn 
- [x] #9358
- [ ] Sass Modules
  - [x] https://github.com/carbon-design-system/carbon/pull/9257 @dakahn 
  - [x] https://github.com/carbon-design-system/carbon/issues/9130 @jnm2377 
- [x] #9348
  - [x] Determine best way to bring in package
  - [x] #9370
  - [x]  carbon-design-system/carbon#8764 @sstrubberg

## ⚛️  React

- [x] carbon-design-system/carbon#9172 @tw15egan @dakahn
- [x] Make a final call on internationalization strategy @joshblack @tay1orjones
- [ ] Determine Component API changes for beta 2 (team)
- [ ] Determine scope of accessibility components for beta 2 (team)

**Experimental**

- [x] https://github.com/carbon-design-system/carbon/issues/9173

## 🚢  Migration

- [x] https://github.com/carbon-design-system/carbon/issues/9166 @andreancardona @sstrubberg @jnm2377 
- [x] https://github.com/carbon-design-system/carbon/issues/9180 @johnbister  @tw15egan 
- [x] #9362
- [ ] V11 Design updates deck @kingtraceyj 
- [x] https://github.com/carbon-design-system/carbon/pull/9339 @tay1orjones 

## 👓 Visual Testing

Taylor to lead implementation, making sure issue templates are up-to-date. Josefina is in the partner role with Taylor showing how to implement the tests.

- [x] https://github.com/carbon-design-system/carbon/issues/9266 @tay1orjones @jnm2377 
- [x] https://github.com/carbon-design-system/carbon/issues/9264 @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/9263 @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/9267 @tay1orjones @jnm2377 
- [x] https://github.com/carbon-design-system/carbon/issues/9279 @jnm2377 
- [x] https://github.com/carbon-design-system/carbon/issues/9278 @tay1orjones 

## 📝  Website

**Bugs:**
- [x] https://github.com/carbon-design-system/carbon-website/issues/2451 @andreancardona 
- [x] https://github.com/carbon-design-system/carbon-website/issues/2448 @tw15egan 

**Docs**
- [x] Start SPSS case study @jillianhowarth 
- [ ] Usage docs for Disclosure pattern @laurenmrice 
- [x] https://github.com/carbon-design-system/carbon-website/pull/2444#event-5002192714  Responding to feedback and publishing draft. @aagonzales 
- [x] https://github.com/carbon-design-system/carbon-website/pull/2473 @aagonzales 
- [x] https://github.com/carbon-design-system/carbon-website/issues/2447 (IN PROGRESS) @jeanservaas  @aagonzales 
- [ ] v11 Grid page updates @jeanservaas 
- [ ] v11 Update Tooltip docs with a11y changes @kingtraceyj 
- [ ] Usage docs: Tile component @thyhmdo 

## 🎨 Design Kit

- [x] #9253 @andreancardona @tay1orjones

**Figma kit**
- [ ] Project planning and management @laurenmrice @aagonzales 

## 💬 Support

- [ ] #9229 @andreancardona 
- [x] #9218 @andreancardona 
- [ ] #9187 @dakahn 
- [x] #9073 @dakahn 
- [x] #8996 @jnm2377 
- [ ] #8961 @sstrubberg 
- [x] #9095 @tw15egan 
- [x] #9082 @tw15egan 
- [ ] #8842 @jnm2377
- [x] #9311 @sstrubberg
- [ ] #9261 @dakahn
- [x] https://github.com/carbon-design-system/carbon/pull/9328 @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/9313 @tay1orjones 

## 🚀  Releases

- [x] Release v10.41 @joshblack 
- [x] Publish @carbon/react@0.1.0 and tag it as beta @joshblack  
- [x] Publish @carbon/styles@0.1.0 and tag it as beta @joshblack 

## Brand
[Brand Zenhub](https://app.zenhub.com/workspaces/auxiliary-squad-5deea70733c75ceaf1bfacae/board?labels=stakeholder%3A%20brand&repos=181062037,181498056)
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1061 @aledavila 
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1108 @vpicone 
- [ ] https://github.com/carbon-design-system/design-language-website/issues/824 @vpicone
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1143 @vpicone
- [ ] https://github.com/IBM/plex/issues/370 @vpicone    

## DPO
- [x] Experience Standards website (Universal Experiences update) https://github.ibm.com/Design/universal-experiences/issues/68 #standards-website-team (slack channel)

**Comment by joshblack** [comment]
### 💬  Support

### 🆕  Enhancements

### 🚢  Migration

### 👓   Visual Testing

### 🔍  Website

### 🎨  Design Kit

**Comment by aagonzales** [comment]
**Anna**
- [ ] https://github.com/carbon-design-system/carbon-website/pull/2444#event-5002192714  Responding to feedback and publishing draft. 
- [ ] Share out v11 color page for feedback
- [ ] V11 updated to color/overview tab: Mike G's feedback, hover color section
- [ ] Figma Project planning

**Jeannie**
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2447 (IN PROGRESS)
- [ ] Spec 8 Column fixed image component for website

**Jillian**
- [ ] Carbon Next work?

**John**
- [ ] Migration project

**Lauren**
- [ ] Usage docs for Disclosure pattern (in progress)
- [ ] Figma Project planning

**Thy**
- [ ] Usage docs: Tile component 
- [ ] ??

**Tracey**
- [ ] v11: Update Tooltip docs with a11y changes
- [ ] ??

**Comment by aagonzales** [comment]
Finished design sprint items that will need future dev:
- https://github.com/carbon-design-system/carbon-website/issues/2476
