### ISSUE TITLE
Sprint 16: Yentl Yak 🐂

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9356]
August 9th - August 20th

## ⚛️  React

- [ ] Accessibility
  - [ ] https://github.com/carbon-design-system/carbon/issues/8703 @tay1orjones @dakahn  
  - [ ] https://github.com/carbon-design-system/carbon/issues/8826 @joshblack @dakahn 
  - [x] #9463
    - Needs sync with design (@laurenmrice?)
  - [x] #9464
    - Needs sync with design (@kingtraceyj?)
- [x] #9462
- [ ] Breaking changes for v11
  - [x] #9465
    - [x] https://github.com/carbon-design-system/carbon/issues/4572
    - [x] https://github.com/carbon-design-system/carbon/issues/5853
  - [x] #9466
  - [ ] https://github.com/carbon-design-system/carbon/issues/5022 @dakahn @tay1orjones 

## 🚢  Migration

- [ ] #9362 @aledavila @jnm2377 
- [ ] V11 Design updates deck @kingtraceyj 
- [x] #9468

## 🎨  Styles

- [ ] #9358 @joshblack 
- [ ] Type token changes https://github.com/carbon-design-system/carbon/issues/9377 @tw15egan @laurenmrice 
- [ ] Finish `math.div` migration for `@carbon/styles` @tay1orjones 
- [ ] Mitigate anything we can for `carbon-components` and elements in terms of `math.div` @tay1orjones 

## 👓 Visual Testing https://github.com/carbon-design-system/carbon/issues/8911

- [x] https://github.com/carbon-design-system/carbon/issues/9274 @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/9283 @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/9268 @tay1orjones @jnm2377 
- [x] Add VRT for Tag @jnm2377  @aledavila 
- [x] Add VRT for Tabs @jnm2377  @aledavila 

## 📝  Website

- [x] Update website to Gatsby and theme V3 @andreancardona @jnm2377 
  - @theiliad can help out here!

**Docs**

- [ ] Usage docs for Disclosure pattern @laurenmrice  (in progress)
- [ ] Usage docs: Tile component @thyhmdo 
—
- [ ] v11: Responding to feedback on color implementation docs @aagonzales 
- [ ] v11 Update Tooltip docs with a11y changes @kingtraceyj 
- [x] https://github.com/carbon-design-system/carbon-website/pull/2500 v11: update theme page with v11 tokens @aagonzales 

## 🎨 Design Kit

- [x] Figma planning and library base elements @aagonzales @laurenmrice 
   - [x] Help add Icon library to Figma @laurenmrice 
- [ ] Update Sketch themed kits Elements page to show type token changes @laurenmrice 

## 💬 Support

- [x] #9229 @andreancardona 
- [ ] #9187 @dakahn 
- [ ] #9261 @dakahn
- [ ] #8961 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/9367 @dakahn 
- [ ] https://github.com/carbon-design-system/carbon/pull/9340 @johnbister 

## 🚀  Releases

- [ ] Release v10.42 @joshblack 

## 🐝  Brand

- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1108 @vpicone 
- [ ] https://github.com/carbon-design-system/design-language-website/issues/824 @vpicone
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1143 @vpicone
- [ ] https://github.com/IBM/plex/issues/370 @vpicone    

## 📣 Communication

- [ ] Deliver the first draft of Beta 2 announcement @joshblack 
  - Figure out any usage images that we would like to share
- [ ] Deliver the first draft of feature flag post @andreancardona 
- [x] Release Partners on 8/19
- [x] Figure out plan for external release partners @joshblack @jnm2377 
  - [x] https://github.com/carbon-design-system/carbon/issues/9438
  - [x] https://github.com/carbon-design-system/carbon/issues/9437
  - [x] https://github.com/carbon-design-system/carbon/issues/8692

**Vacation Calendar**

- @andreancardona 8/19 - 8/20
- @laurenmrice 8/10 - 8/17
- @sstrubberg 8/9 - 8/17
- @tay1orjones 8/13

<details>
<summary>Deferred</summary>

## ⚛️  React

- Accessibility
  - Disclosure pattern
  - ToggleTip
  - Menu
  - Dropdown
  - Combobox
  - MultiSelect
  - Filterable MultiSelect
  - Interactive Tiles
  - DatePicker
- Refactor
  - add Popover to dropdown menu
  - add Popover to overflow menu
- Enhancements
  - https://github.com/carbon-design-system/carbon/issues/5390
  - Fluid inputs (blocker for new token page)
- Breaking changes
  - [ ] All additional props are spread onto the root node
  - [ ] Event consistency across component groups
  - [ ] Prop consistency across component groups
  - [x] https://github.com/carbon-design-system/carbon/issues/5972

## 📝  Website

- https://github.com/carbon-design-system/carbon-website/issues/2474
- https://github.com/carbon-design-system/carbon-website/issues/2475 
</details>

**Comment by joshblack** [comment]
## 🚢 Migration

- Interview designers and developers, going over our beta migration content, and getting feedback

## 🎨 Styles

## ⚛️ React

- Updates to component prop API
- Accessibility components

## 👓 Visual Testing

## 💬 Support

**Comment by alisonjoseph** [comment]
## 🐝 Brand

- fix[type specs component]: inline code snippet incorrect gatsby-theme-carbon#1108 
- Add play/pause button to looping animations design-language-website#824 
- [mobile] Tool tip sticks and does not go away after opening/closing switcher gatsby-theme-carbon#1143
- Plex 6.0 (next) IBM/plex#370 @vpicone
- Enhancement[card]: add 1:1 card to component library gatsby-theme-carbon#1061 @aledavila [PR](https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1151)

## 🖥️  DPO
- ?
