### ISSUE TITLE
Complete `accessibility-checker` baseline for React components 

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9475]
Every component needs to be be covered by `accessibility-checker` tests. 

Update the tracker doc when complete: https://airtable.com/appn78c0fXJzIStn9/tblyyDRffCRFpYmJM/viwWXO0qkJOIRMurg?blocks=hide

- [x] Add `accessibility-checker` tests for Accordion
- [x] Add `accessibility-checker` tests for Breadcrumb
- [x] Add `accessibility-checker` tests for Button
- [x] Add `accessibility-checker` tests for Checkbox
- [x] Add `accessibility-checker` tests for CodeSnippet
- [x] Add `accessibility-checker` tests for Combobox
- [x] Add `accessibility-checker` tests for ContentSwitcher
- [x] Add `accessibility-checker` tests for CopyButton
- [x] Add `accessibility-checker` tests for DataTable
- [x] Add `accessibility-checker` tests for DatePicker
- [x] Add `accessibility-checker` tests for Dropdown
- [x] Add `accessibility-checker` tests for FileUploader
- [x] Add `accessibility-checker` tests for Form
- [x] Add `accessibility-checker` tests for Grid
- [x] Add `accessibility-checker` tests for InlineLoading
- [x] Add `accessibility-checker` tests for Link
- [x] Add `accessibility-checker` tests for List
- [x] Add `accessibility-checker` tests for Loading
- [x] Add `accessibility-checker` tests for Modal
- [x] Add `accessibility-checker` tests for MultiSelect
- [x] Add `accessibility-checker` tests for Notification
- [x] Add `accessibility-checker` tests for NumberInput
- [x] Add `accessibility-checker` tests for OverflowMenu
- [x] Add `accessibility-checker` tests for PaginationNav
- [x] Add `accessibility-checker` tests for Pagination
- [x] Add `accessibility-checker` tests for Popover
- [x] Add `accessibility-checker` tests for ProgressBar
- [x] Add `accessibility-checker` tests for ProgressIndicator
- [x] Add `accessibility-checker` tests for RadioButton
- [x] Add `accessibility-checker` tests for Search
- [x] Add `accessibility-checker` tests for Select
- [x] Add `accessibility-checker` tests for Skeleton
- [x] Add `accessibility-checker` tests for Slider
- [x] Add `accessibility-checker` tests for StructuredList
- [x] Add `accessibility-checker` tests for Tabs
- [x] Add `accessibility-checker` tests for Tag
- [x] Add `accessibility-checker` tests for TextArea
- [x] Add `accessibility-checker` tests for TextInput
- [x] Add `accessibility-checker` tests for Tile
- [x] Add `accessibility-checker` tests for TimePIcker
- [x] Add `accessibility-checker` tests for Toggle
- [x] Add `accessibility-checker` tests for Tooltip
- [x] Add `accessibility-checker` tests for TreeView
- [x] Add `accessibility-checker` tests for UIShell

**Comment by joshblack** [comment]
## CodeSnippet

![image](https://user-images.githubusercontent.com/3901764/157747276-1867763f-7651-42d6-8afb-da3d07a98112.png)

## Combobox

![image](https://user-images.githubusercontent.com/3901764/157747513-43148701-68b5-496c-ba95-85bf8785dc25.png)

**Comment by tay1orjones** [comment]
Complete ia #11338
