### ISSUE TITLE
Sprint 17: Zebra Dark Thirty 🦓

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9492]
## ⚛️  React

**Components**

- [ ] https://github.com/carbon-design-system/carbon/issues/8703 @tay1orjones 
- [x] Figure out test case for Dialog in CAG @dakahn @joshblack 
- [ ] #9463 @joshblack 
- [ ] #9464 @joshblack 
- [ ] #9519 @andreancardona @joshblack 
- [ ] https://github.com/carbon-design-system/carbon/issues/9459 @aledavila [PR](https://github.com/carbon-design-system/carbon/pull/9591)

**Prop changes**

- [x] #9535
- [x] #9465 @tw15egan 
  - [x] https://github.com/carbon-design-system/carbon/issues/4572
  - [x] https://github.com/carbon-design-system/carbon/issues/5853
- [ ] #9466 @tw15egan 
- [x] https://github.com/carbon-design-system/carbon/issues/5022 @dakahn @tay1orjones 

**Globalization**

- [ ] #9462 @tay1orjones 

## 🚢  Migration

- [x] #9362 @aledavila @jnm2377 
    - [x] v11 instructions: https://github.com/carbon-design-system/carbon-website/pull/2527
    - [x] step 2 branch
    - [x] step 3 branch
    - [x] step 4 branch
    - [x] step 5 branch
- [x] Present research from Sprint 16 @andreancardona @jnm2377 @johnbister 
- [x] Update migration guide with React-focused changes @andreancardona @jnm2377 https://github.com/carbon-design-system/carbon-website/pull/2513
  - Changes to props
  - Changes to size prop
  - Changes to components
  - Changes to icons
- [x] Update migration guide with feedback from v11 Beta 1 discussion https://github.com/carbon-design-system/carbon-website/pull/2507
- [x] #9529
- [ ] Upgrade CLI @joshblack @jnm2377 
  - TODO: pair with design @johnbister 
- [x] Update migration guide for Design tab with Beta 2 release items (in notion) @kingtraceyj @laurenmrice 
- [ ] Explore sample UIs/flows to showcase release features (color tokens, inline theming, light/dark mode) @aagonzales
  - @joshblack can help out on the dev side if any questions come up

## 🎨  Styles

- [ ] #9358 @joshblack 
- [x] Type token changes https://github.com/carbon-design-system/carbon/issues/9377 @tw15egan @laurenmrice 
- [x] Finish `math.div` migration for `@carbon/styles` @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/pull/9508 @tay1orjones 
  - Mitigate anything we can for `carbon-components` and elements in terms of `math.div`

## 👓 Visual Testing

Epic: https://github.com/carbon-design-system/carbon/issues/8911

_Note: on hold for this sprint as we work towards beta 2_

## 📝  Website
- [x] [docs: partners and advisory board updates](https://github.com/carbon-design-system/carbon-website/pull/2533)  @laurenmrice 
- [ ] Update website to Gatsby and theme V3 @vpicone 
_
- [ ] Usage docs for Disclosure pattern @laurenmrice 
- [x] Usage and style docs for Tooltip @kingtraceyj 
- [x] Update type tokens on style tab @laurenmrice 
_
- [ ] https://github.com/carbon-design-system/carbon-website/pull/2519 @thyhmdo 
- [ ] https://github.com/carbon-design-system/carbon-website/pull/2518 @aagonzales 

## 🎨 Design Kit

**Figma**
- [x] Figma project kick-off planning @aagonzales @laurenmrice 
- [x] Add categories for Icons @laurenmrice 
- [x] Edit spacers @aagonzales 
- [x] Make presentation templates @aagonzales 

**Sketch**
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/436 @aagonzales 
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/386 @aagonzales 
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/434 @aagonzales 

## 💬 Support

- [x] #9187 @dakahn 
- [x] #9261 ~@dakahn~ @andreancardona 
- [x] #8961 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/9367 @dakahn
- [x] https://github.com/carbon-design-system/carbon/issues/9488 @tw15egan 
- [x] https://github.com/carbon-design-system/carbon/issues/8842 @jnm2377 
- [ ] https://github.com/carbon-design-system/carbon/issues/9112 @aledavila 
- [x] https://github.com/carbon-design-system/carbon/issues/9469 @andreancardona 
- [x] https://github.com/carbon-design-system/carbon/issues/9073 @sstrubberg @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/9471 @andreancardona  @tw15egan 
- [x] https://github.com/carbon-design-system/carbon/issues/8441 @sstrubberg @jnm2377  
- [x] https://github.com/carbon-design-system/carbon/pull/9537 @tay1orjones 

## 🚀  Releases

- [ ] Release v10.43 @joshblack 

## 🐝  Brand

- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1108 @vpicone 
- [ ] https://github.com/carbon-design-system/design-language-website/issues/824 @vpicone
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1143 @vpicone
- [ ] https://github.com/IBM/plex/issues/370 @vpicone    

### Design
- [ ] https://github.com/carbon-design-system/carbon/issues/9520 @thyhmdo pair with @kingtraceyj 

## 🖥️ DPO

- [x] Pre-launch Standards website fixes https://github.ibm.com/Design/universal-experiences/issues/81 @aledavila 
- [x] Launch Standards website updates https://github.ibm.com/Design/universal-experiences/issues/69 @aledavila @sstrubberg 
- [x] **EDT certificate** https://github.ibm.com/Design/EDT/issues/5919 @vpicone @alisonjoseph 

## 🛠 Tooling

- [ ] Update @carbon/cli to be workspace-agnostic for C&CS @joshblack 

## 📣 Communication

- [ ] Publish the Beta 2 announcement @joshblack 10/7
- [ ] Deliver the first draft of feature flag post @andreancardona 
- [ ] Release Partners on 10/2
- [ ] Write first draft / outline for blog post for moving from `node-sass` to `sass` with `carbon-components` @tay1orjones 
- [x] Write first draft / outline for blog post on updating the tutorial to v11 @jnm2377 OUTLINE: https://carbondesignsystem.notion.site/Tutorial-migration-process-0cd4659832ab4daba3c377998be66e08

## 🏖️ **Vacations**

- @johnbister 8/23-8/30
- @aagonzales 8/30 – 8/31 
- @joshblack 8/25-8/27
- @dakahn 8/25-8/27

**Comment by joshblack** [comment]
## 📓  Planning

_Candidate issues for the sprint_

## 🚢 Migration


## 🎨 Styles

## ⚛️ React

- Updates to component prop API
- Accessibility components

### Components
- Fluid inputs (dropdown to use on color tokens page)

## 👓 Visual Testing

## 📝 Website

## 🎨 Design Kit

## 💬 Support

## 🚀 Releases

- Release v10.42

## 📣 Communication

**Comment by alisonjoseph** [comment]
## 🐝 Brand

## 🖥️ DPO
- Standards website fixes & launch (issues tbd)

**Comment by aagonzales** [comment]
## 📝 Website
- [ ] Usage docs for Disclosure pattern @laurenmrice 
- [ ] Usage docs for Tile PR @thyhmdo 
- [ ] Usage and style docs for Tooltip @kingtraceyj 
- [ ] Color implementation PR @aagonzales 
- [ ] Update type tokens on style tab @laurenmrice 

## 🎨 Design Kit
- [ ] Figma project kick-off @aagonzales @laurenmrice 
- [ ] Update type styles and elements page @laurenmrice 

## 🐝 Brand
- [ ] Product splash screen templates @thyhmdo pair with @kingtraceyj 

## ↗️   Carbon Next 
- [ ] Jeannie doing awesome stuff
