### ISSUE TITLE
v11 Prop Changes 

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9535]
**Goal**

We want the props for the components in our React library to be consistent and predictable. Props should follow common or familiar conventions and should be consistent across components in the design system.

**Links & Resources**

- https://carbon-react-explorer.vercel.app/

**Related issues**

- https://github.com/carbon-design-system/carbon/issues/5853
- https://github.com/carbon-design-system/carbon/issues/5972
- https://github.com/carbon-design-system/carbon/issues/5367
- https://github.com/carbon-design-system/carbon/issues/5022
- https://github.com/carbon-design-system/carbon/issues/2343
- https://github.com/carbon-design-system/carbon/issues/2529
- https://github.com/carbon-design-system/carbon/issues/4356

**Checklist**

- [x] Change instances of `handle*` to `on*`
  - [x] [`handleClick`](https://carbon-react-explorer.vercel.app/props/handleClick)
  - [x] [`handleKeyDown`](https://carbon-react-explorer.vercel.app/props/handleKeyDown)
  - [x] [~`handleOpen`~](https://carbon-react-explorer.vercel.app/props/handleOpen) - Only exists in `ModalWrapper` - component no longer maintained.
  - [x] [~`handleOverflowMenuItemFocus`~](https://carbon-react-explorer.vercel.app/props/handleOverflowMenuItemFocus) - Only exists in `OverflowMenu` and is not consumable by the user.
  - [x] [~`handleSubmit`~](https://carbon-react-explorer.vercel.app/props/handleSubmit) - Only exists in `ModalWrapper` - component no longer maintained.
  - [x] [~`handleTabClick`~](https://carbon-react-explorer.vercel.app/props/handleTabClick) - Is a child of `Tabs` and is not consumable by the user.
  - [x] [~`handleTabKeyDown`~](https://carbon-react-explorer.vercel.app/props/handleTabKeyDown) - Is a child of `Tabs` and is not consumable by the user.
- [x] #10317
- [x] #9622
- [x] #9623
- [x] #9624
- [x] #9641
  - [ ] Find a list of components that share state in a event handler and change them
- [x] #9763
- [ ] Update any handlers that use `evt.persist()`
- [ ] titleText vs labelText, different for dropdown and number input
- [ ] placeholder vs placeholderText
  - [ ] Check-in with DA/Taylor because they may be removing this
- [ ] `ariaLabel` to `aria-label`: https://carbon-react-explorer.vercel.app/props/ariaLabel

Questions

- Does the `defaultToggled` prop make sense? Can you have something be in a "toggled" state or should we indicate that as on/open instead?

**Comment by joshblack** [comment]
## Patterns

**Deprecating a prop**

- Use the `deprecate()` helper

```
The <old-prop-name> prop for <component-name> has been deprecated in favor of <new-prop-name>.
It will be removed in the next major release.
```

```js
    handleClick: deprecate(
      PropTypes.func,
      'The handleClick prop for ClickableTile has been deprecated in favor of onClick. It will be removed in the next major release.'
    ),
```

Scenarios

- You are replacing a prop with a new prop
  - The prop can be added safely in v10
  - The prop can not be added safely in v10 (maybe there is a conflicting prop)
- You are removing a prop in the next major release
- ~~You are repurposing a prop, the prop will be used for something else~~
- Event handlers (prop signature changes)
  - `onChange`, `onClick`, `onKeyDown`
  - `(event) => void`, `(event, state) => void`, `(state, event) => void`, `(state) => void`
  - **Option 1:** `(event) => void`, `(event, state) => void`
  - Option 2: we won't ever give you state information in a handler, you must subscribe to `onChange`, `onStateChange`

**Comment by joshblack** [comment]
##  Event handler signatures

Things that we're looking for:

- Props like `onChange`, or `on*`, that have a signature like: `(event, data) => void` or `(data, event) => void`

What we want:

- Either `on*: (event) => void`
- Or `on*: (event, data) => void`
- Or `onChange: (data) => void`

What we don't want:

- `on*: (data, event) => void`

**Comment by joshblack** [comment]
## Components

- [x] Accordion
- [ ] AccordionItem
  - Current: `onHeadingClick: ({ isOpen: boolean, event: Event }) => void`
  - Proposed: should `isOpen` just be value (type `ValueState`)
  - Proposed: should we use `onChange` for all controlled?
- [ ] AccordionSkeleton
- [ ] AspectRatio
- [ ] Breadcrumb
- [ ] BreadcrumbItem
- [ ] BreadcrumbSkeleton
- [ ] Button
- [ ] ButtonSet
- [ ] ButtonSkeleton
- [ ] Checkbox
  -  Proposed `onChange: (event, { checked: boolean, id: string })`
  - Current `onChange: (state: boolean, id: string, event: Event)`
- [ ] CheckboxSkeleton
- [ ] ClickableTile
- [ ] CodeSnippet
- [ ] CodeSnippetSkeleton
- [ ] Column
- [ ] ComboBox
- [ ] ComposedModal
- [ ] Content
- [ ] ContentSwitcher
- [ ] ControlledPasswordInput
- [ ] Copy
- [ ] CopyButton
- [ ] DataTable
- [ ] DataTableSkeleton
- [ ] DatePicker
- [ ] DatePickerInput
- [ ] DatePickerSkeleton
- [ ] DirectionButton
- [ ] Dropdown
- [ ] DropdownSkeleton
- [ ] ErrorBoundary
- [ ] ExpandableTile
- [ ] FeatureFlags
- [ ] Filename
- [ ] FileUploader
- [ ] FileUploaderButton
- [ ] FileUploaderDropContainer
- [ ] FileUploaderItem
- [ ] FileUploaderSkeleton
- [ ] FilterableMultiSelect
- [ ] FluidForm
- [ ] Form
- [ ] FormGroup
- [ ] FormItem
- [ ] FormLabel
- [ ] Grid
- [ ] Header
- [ ] HeaderContainer
- [ ] HeaderGlobalAction
- [ ] HeaderMenu
- [ ] HeaderMenuButton
- [ ] HeaderMenuItem
- [ ] HeaderName
- [ ] HeaderNavigation
- [ ] HeaderPanel
- [ ] HeaderSideNavItems
- [ ] Heading
- [ ] Icon
- [ ] IconSkeleton
- [ ] InlineCheckbox
- [ ] InlineLoading
- [ ] InlineNotification
- [ ] InlineNotification
- [ ] Link
- [ ] ListBox
- [ ] ListBoxField
- [ ] ListBoxMenu
- [ ] ListBoxMenuIcon
- [ ] ListBoxMenuItem
- [ ] ListBoxSelection
- [ ] ListBoxSelection
- [ ] ListBoxTrigger
- [ ] ListItem
- [ ] Loading
- [ ] Menu
- [ ] MenuGroup
- [ ] MenuItem
- [ ] MenuOption
- [ ] MenuOptionContent
- [ ] MenuRadioGroup
- [ ] MenuRadioGroupOptions
- [ ] MenuSelectableItem
- [ ] Modal
- [ ] ModalBody
- [ ] ModalFooter
- [ ] ModalHeader
- [ ] ModalWrapper
- [ ] MultiSelect
- [ ] NotificationActionButton
- [ ] NotificationActionButton
- [ ] NotificationButton
- [ ] NotificationButton
- [ ] NotificationIcon
- [ ] NotificationIcon
- [ ] NotificationTextDetails
- [ ] NumberInput
- [ ] NumberInputSkeleton
- [ ] OrderedList
- [ ] OverflowMenu
- [ ] OverflowMenu
- [ ] OverflowMenuItem
- [ ] PageSelector
- [ ] Pagination
- [ ] Pagination
- [ ] PaginationItem
- [ ] PaginationNav
- [ ] PaginationOverflow
- [ ] PaginationSkeleton
- [ ] PasswordInput
- [ ] ProgressBar
- [ ] ProgressIndicator
- [ ] ProgressIndicatorSkeleton
- [ ] ProgressStep
- [ ] RadioButton
- [ ] RadioButtonGroup
- [ ] RadioButtonSkeleton
- [ ] RadioTile
- [ ] Row
- [ ] Search
- [ ] SearchFilterButton
- [ ] SearchLayoutButton
- [ ] SearchSkeleton
- [ ] Section
- [ ] Select
- [ ] SelectableTile
- [ ] SelectItem
- [ ] SelectItemGroup
- [ ] SelectSkeleton
- [ ] SideNav
- [ ] SideNavDetails
- [ ] SideNavDivider
- [ ] SideNavFooter
- [ ] SideNavHeader
- [ ] SideNavIcon
- [ ] SideNavItem
- [ ] SideNavItems
- [ ] SideNavLink
- [ ] SideNavLinkText
- [ ] SideNavMenu
- [ ] SideNavMenuItem
- [ ] SideNavSwitcher
- [ ] SkeletonPlaceholder
- [ ] SkeletonText
- [ ] SkipToContent
- [ ] Slider
- [ ] SliderSkeleton
- [ ] StructuredListBody
- [ ] StructuredListBody
- [ ] StructuredListCell
- [ ] StructuredListCell
- [ ] StructuredListHead
- [ ] StructuredListHead
- [ ] StructuredListInput
- [ ] StructuredListInput
- [ ] StructuredListRow
- [ ] StructuredListRow
- [ ] StructuredListSkeleton
- [ ] StructuredListWrapper
- [ ] StructuredListWrapper
- [ ] Switch
- [ ] Switcher
- [ ] SwitcherDivider
- [ ] SwitcherItem
- [ ] Tab
- [ ] TabContent
- [ ] Table
- [ ] TableBatchAction
- [ ] TableBatchActions
- [ ] TableBody
- [ ] TableContainer
- [ ] TableExpandedRow
- [ ] TableExpandHeader
- [ ] TableExpandRow
- [ ] TableHeader
- [ ] TableRow
- [ ] TableSelectAll
- [ ] TableSelectRow
- [ ] TableToolbar
- [ ] TableToolbarAction
- [ ] TableToolbarMenu
- [ ] TableToolbarSearch
- [ ] Tabs
- [ ] TabsSkeleton
- [ ] Tag
- [ ] TagSkeleton
- [ ] Text
- [ ] TextArea
- [ ] TextAreaSkeleton
- [ ] TextDirection
- [ ] TextInput
- [ ] TextInputSkeleton
- [ ] Tile
- [ ] TileAboveTheFoldContent
- [ ] TileBelowTheFoldContent
- [ ] TileGroup
- [ ] TimePicker
- [ ] TimePickerSelect
- [ ] ToastNotification
- [ ] ToastNotification
- [ ] Toggle
- [ ] Toggle
- [ ] ToggleSkeleton
- [ ] ToggleSmall
- [ ] ToggleSmallSkeleton
- [ ] Toolbar
- [ ] ToolbarItem
- [ ] ToolbarOption
- [ ] ToolbarSearch
- [ ] ToolbarTitle
- [ ] Tooltip
- [ ] TooltipDefinition
- [ ] TooltipIcon
- [ ] TreeNode
- [ ] TreeView
- [ ] UnorderedList
