### ISSUE TITLE
Sprint 18: Alice in Artichokes 🥬 

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9536]
## ⚛️  React

**Components**

- [ ] https://github.com/carbon-design-system/carbon/issues/8703 @tay1orjones 
- [ ] #9463 @joshblack 
- [ ] #9464 @joshblack 
- [ ] #9616 @tw15egan @dakahn 
  - [ ] Set prefix to `cds` for styles 

**Prop changes**

- [ ] #9535 @joshblack @aledavila @sstrubberg @vpicone 
- [ ] #9466 @tw15egan 

**Globalization**

- [ ] #9462 @tay1orjones 

## 🚢  Migration

- [x] Upgrade CLI @joshblack @jnm2377
- [x] #9618 @sstrubberg @jnm2377 

## 🎨  Styles

- [x] #9358 @joshblack 
- [x] #9617 @joshblack 

## 👓 Visual Testing

Epic: https://github.com/carbon-design-system/carbon/issues/8911

_Note: on hold for this sprint as we work towards beta 2_
## 📝  Website
- [ ] Usage docs for Disclosure pattern @laurenmrice 
- [x] Review CCS spreadsheet pattern documentation @laurenmrice 
- [ ] PR issue for Tooltip @kingtraceyj
- [ ] Toggle tip investigation @kingtraceyj 
- [ ] Style doc for tile @thyhmdo 
_
- [ ] https://github.com/carbon-design-system/carbon-website/pull/2519 @thyhmdo 

## 📈  Dataviz
**New charts**
- [x] Tree diagram
- [x] Alluvial/sankey

**MISC**
- [x] Multiple radar chart bugs 

## 🎨 Design Kit
**Figma**
- [x] Figma project kick-off and workstream @aagonzales @laurenmrice

**Sketch**
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/436 @aagonzales 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/411 @aagonzales 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/386 @aagonzales 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/434 @aagonzales 

## 💬 Support

- [x] https://github.com/carbon-design-system/carbon/issues/9609 @aledavila 
- [ ] https://github.com/carbon-design-system/carbon/issues/9112 @aledavila 
- [ ] https://github.com/carbon-design-system/carbon/issues/9367 @dakahn
- [ ] https://github.com/carbon-design-system/carbon/issues/9444 @dakahn 
- [ ] https://github.com/carbon-design-system/carbon/issues/9261 @dakahn 
- [x] https://github.com/carbon-design-system/carbon/issues/9511 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/9431 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/8373 @jnm2377 

## 🚀  Releases

- [ ] Release v10.44

## 🐝  Brand
- [ ] https://github.com/carbon-design-system/carbon/issues/9520 @kingtraceyj @thyhmdo 
- [x] https://github.com/carbon-design-system/design-language-website/issues/1010
- [x] https://github.com/carbon-design-system/design-language-website/issues/824
- [x] https://github.com/carbon-design-system/carbon/issues/9521
- [ ] IBM/plex#370 @vpicone
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1151 Square Card PR @jeanservaas @aledavila 

## 🛠 Tooling

- [ ] Update @carbon/cli to be workspace-agnostic for C&CS @joshblack 

## 📣 Communication

- [ ] Publish the Beta 2 announcement @joshblack 9/16
- [x] Release Partners 10/16
- [x] Publish "migrating from node-sass to sass" blog post @tay1orjones 9/10
- [ ] Publish "updating the carbon tutorial project" blog post @jnm2377 9/16

## 🏖️ **Vacations**

- @andreancardona 9/7 - 9/17
- @tw15egan intermittent connection week of 9/7
- Taylor OOO 🏥  Tuesday 9/14 - Friday 9/17
- Thy Vacation  |  Monday 9/6 - Friday 9/10
- John OOO/parental leave
- Ale Vacation - Wednesday 9/15 - Friday 9/17
- Alison OOO / TBD 9/13-17  🏥

**Comment by joshblack** [comment]
## 📓  Planning

_Candidate issues for the sprint_

## ⚛️  React



## 🚢  Migration



## 🎨  Styles




## 👓 Visual Testing



## 📝  Website



## 🎨 Design Kit


## 💬 Support



## 🚀  Releases

- [ ] Release v10.44 



## 🐝  Brand


## 🖥️ DPO


## 🛠 Tooling



## 📣 Communication



## 🏖️ **Vacations**

**Comment by alisonjoseph** [comment]
## 🖥️ DPO


## 🐝 Brand
