### ISSUE TITLE
Upgrade CLI

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9640]
We would like to offer up an upgrade experience to people looking to migrate from v10 to v11 through the `@carbon/upgrade` package. This CLI should help us do the following:

- Detect packages with available migrations
- Prompt the user for which migrations they would like to run on their project
- Apply the migrations (either in preview mode or change the files)

Some of the migrations that we would like to do include:

- Update the `package.json` file with the migrated package version
- Update import paths for React components
- Run codemods for changes to the props of a React component
- Update import paths for Sass styles
- Update design tokens used in Sass 

**Checklist**

- [x] Add check for `git status` in the CLI bin file ([Inspiration](https://github.com/reactjs/react-codemod/blob/master/bin/cli.js#L22))
- [x] https://github.com/carbon-design-system/carbon/issues/10190
- [x] #10466
- [x] #10467

**Links & Resources**

- [Excalidraw](https://excalidraw.com/#json=5377882268368896,gcxNH7X9v1Lc1ZwVCvNKhw)

**Comment by joshblack** [comment]
Tasks


- [ ] Add Carbon ASCII Banner
- [ ] Don't check git status if in development mode
- [ ] CLI Commands
  - [ ] Default command
    - [ ] Should find an "upgrade path" or available migrations
    - [ ] Ask the user what migrations or upgrades to run
    - [ ] Run the migrations or upgrades in "write" or "dry" mode
    - [ ] Report results
  - [ ] Add a `migrate` command to migrate a specific package `@carbon/upgrade migrate package_name`


Notes

- Which part of the program is responsible for changing the package.json for a dependency upgrade or migration
- How should the UI work for choosing what to apply?
- How do we limit diff views to be digestible because sometimes they're really long
- IDEA: could we use the `yarn upgrade-interactive` UI as inspiration for how we lay out migrations?
- How do we get the actual version of a dependency, not its range, from the dependencies of a workspace
  - `npm view <package-name> version`
  - `yarn why`
