### ISSUE TITLE
Upgrade class components to functional components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9712]
**Why are we doing this?**

According to the React team, switching a component from a class component to a functional component is technically a breaking change. This is because class components accept a `ref` that points to the class instance by default. There is no way to opt-out of this behavior. As a result, if we switched a component to a functional component it would no longer have a `ref`, and existing code that uses a `ref` would break. Similarly, using `React.forwardRef` would produce a component where the `ref` would no longer point to a class instance and code could similarly break.

We have moved some components over to the new format despite these situations. The rationale at the time was that we weren't intending people to use these parts of a component (specifically class instance methods) and if teams were trying to use the `ref` to find a node in the document their code would work if we used `React.forwardRef`.

With v11, it seemed like a great opportunity to convert our remaining class components to the new functional component style with hooks.

**Effort size legend**
❇️ - sm
✴️ - md
🆘 - lg

**Tasks**

We would like to convert the following components to functional components that use hooks where appropriate:

- [x] ✴️ src/components/UIShell/SideNavMenu.js @joshblack 
  - [x] ✴️ SideNavMenu 
- [x] ❇️ src/components/UIShell/HeaderNavigation.js @joshblack 
  - [x] ❇️ HeaderNavigation 
- [ ] ❇️ src/components/UIShell/HeaderMenu.js @joshblack 
  - [ ] ❇️ HeaderMenu
- [x] ~~src/components/ToggleSmall/ToggleSmall.Skeleton.js~~ (this component is deprecated)
  - [x] ~~ToggleSmallSkeleton~~
- [x] ~~src/components/Toggle/Toggle.Skeleton.js~~ (this component is deprecated)
  - [x] ~~ToggleSkeleton~~
- [x] ~~src/components/Tooltip/Tooltip.js~~
  - [x] ~~Tooltip~~ (component is being replaced in another update)
- [ ] ✴️ src/internal/ClickListener.js
  - [ ] ✴️ ClickListener
- [x] ~~src/internal/FloatingMenu.js~~
  - [x] ~~FloatingMenu~~ (component will be replaced by popover)
- [x] ~~src/components/ToolbarSearch/ToolbarSearch.js~~
  - [x] ~~ToolbarSearch~~
- [x] ~~src/components/Toggle/Toggle.js~~
  - [x] ~~Toggle~~ (already covered in Toggle/next)
- [x] ❇️ src/components/TimePickerSelect/TimePickerSelect.js @sstrubberg 
  - [x] ❇️ TimePickerSelect
- [x] ✴️ src/components/TimePicker/TimePicker.js @sstrubberg 
  - [x] ✴️ TimePicker 
- [ ] ✴️ src/components/TileGroup/TileGroup.js @motou
  - [ ] ✴️ TileGroup @motou
- [x] src/components/Tile/Tile.js @sstrubberg 
  - [x] ❇️ Tile
  - [x] ✴️ ClickableTile
  - [x] 🆘 ExpandableTile (@abbeyhrt)
  - [x] ❇️ TileAboveTheFoldContent
  - [x] ❇️ TileBelowTheFoldContent
- [x] 🆘 src/components/Tabs/Tabs.js @jnm2377 
  - [x] 🆘 Tabs
- [x] ❇️  src/components/Tab/Tab.js @jnm2377 
  - [x] ❇️ Tab
- [ ] 🆘 src/components/Slider/Slider.js @vpicone 
  - [ ] 🆘 Slider
  - [x] #10018
- [ ] ✴️ src/components/Search/Search.js @aledavila 
  - [ ] ✴️ Search
  - [x] #10019
- [x] ~~src/components/SearchLayoutButton/SearchLayoutButton.js~~
  - [x] ~~SearchLayoutButton~~ (component has been deprecated)
- [x] ✴️ src/components/RadioButtonGroup/RadioButtonGroup.js @jnm2377 
  - [x] ✴️ RadioButtonGroup
- [x] ❇️ src/components/RadioButton/RadioButton.js @jnm2377 
  - [x] ❇️ RadioButton
- [ ] ✴️ src/components/ProgressIndicator/ProgressIndicator.js
  - [ ] ✴️ ProgressIndicator
  - [x] #10020
- [ ] 🆘 src/components/Pagination/Pagination.js
  - [ ] 🆘 Pagination
  - [x] #10021
- [x] ✴️ src/components/OverflowMenuItem/OverflowMenuItem.js
  - [x] ✴️ OverflowMenuItem
  - [x] #10022
- [ ] 🆘 src/components/OverflowMenu/OverflowMenu.js
  - [ ] 🆘 OverflowMenu
  - [x] #10022
- [ ] 🆘 src/components/NumberInput/NumberInput.js @vpicone 
  - [ ] 🆘 NumberInput
  - [x] #10017
- [ ] 🆘 src/components/MultiSelect/FilterableMultiSelect.js
  - [ ] 🆘 FilterableMultiSelect
  - [x] #10023
- [x] ~~src/internal/Selection.js~~
  - [x] ~~Selection~~ (will be unnecessary after moving listbox components to `useSelection`)
- [x] ~~src/components/ModalWrapper/ModalWrapper.js~~
  - [x] ~~ModalWrapper~~ (component is deprecated)
- [ ] 🆘 src/components/Modal/Modal.js
  - [ ] 🆘 Modal
  - [x] #10015
- [ ] ✴️ src/components/FileUploader/FileUploader.js
  - [ ] ✴️ FileUploader
  - [x] #10016
- [x] ~~src/components/ErrorBoundary/ErrorBoundary.js~~
  - [x] ~~ErrorBoundary~~ (has no hooks equivalent)
- [x] ❇️ src/components/DatePickerInput/DatePickerInput.js @jnm2377 
  - [x] ❇️ DatePickerInput
  - [x] #10010
- [x] 🆘 src/components/DatePicker/DatePicker.js
  - [x] 🆘 DatePicker
  - [x] #10009
- [ ] ✴️ src/components/InlineCheckbox/InlineCheckbox.js
  - [ ] ✴️ InlineCheckbox
  - [x] #10011
- [x] ~~src/components/DataTable/DataTable.js~~
  - [x] ~~DataTable~~ (too big to migrate, may use hook format in the future)
- [x] ~~src/components/ContentSwitcher/ContentSwitcher.js~~
  - [x] ~~ContentSwitcher~~ (currently being updated separately)
- [x] src/components/ComposedModal/ComposedModal.js
  - [x] 🆘 ComposedModal
    - [x] #10012
  - [x] ❇️ ModalHeader
    - [x] #10013
  - [ ] ✴️ ModalFooter
    - [x] #10014
- [x] #10281

**Comment by joshblack** [comment]
**Recipes**

```jsx
// TEMPLATE
const HeaderMenu = React.forwardRef(
  function HeaderMenu(props, ref) {}
);

HeaderMenu.propTypes = {};
```

1. Start off with the template of the component
2. Grab the `render()` method and paste it into your new component
3. Grab the `propTypes` and paste them into your new component
4. Move over any default props, where appropriate
5. Initialize state in local variables using `React.useState` from the `constructor`
6. Move over any event handlers into the body of the component
7. Fix everything that breaks (change `this.*` to local variables)

Special cases

- Instance fields/properties (`React.useRef`)

**Comment by sstrubberg** [comment]
example for how to handle `getDerivedStateFromProps`

```jsx

function TestComponent({ example }) {
  const [value, setValue] = useState(example);

  useEffect(() => {
    setValue(example);
  }, [example]);
}

```

becomes

```jsx

function TestComponent({ example }) {
  const [value, setValue] = useState(example);
  const [prevExample, setPrevExample] = useState(example);

  if (example !== prevExample) {
    setValue(example);
    setPrevExample(example);
  }
}

```

**Comment by tay1orjones** [comment]
Another thing to note on default vs named exports - the `src/index.js` is typically expecting a default export. So if you're going to do a conditional export, it might be easiest to ensure it's default exports all the way through the export chain.

For instance:
```js
// MyFunComponent/next/MyFunComponent.js

export default function MyFunComponent({...props}) {
return (
    <div>{...props}</div>
  );
}

// MyFunComponent/index.js
import { default as MyFunComponentNext } from './next/MyFunComponent';
import { default as MyFunComponentClassic } from './MyFunComponent';

export default MyFunComponent = FeatureFlags.enabled('enable-v11-release') ? MyFunComponentNext : MyFunComponentClassic;
```

**Comment by jnm2377** [comment]
Another thing to keep in mind, is that we should add a new test file in the `/next` folder for each component and update the test to pull in the v11 component, as well as make any other necessary changes. Here's an example done in `Notification`:
https://github.com/carbon-design-system/carbon/pull/9494/files

**Comment by tay1orjones** [comment]
Priority of these can be divided into three sections:

1. Components that are likely to receiving enhancement work post v11
2. Components that are commonly used
3. Everything else

### 1. Components that are likely to receiving enhancement work post v11
- https://github.com/carbon-design-system/carbon/issues/5416
  - Dropdown
  - ComboBox
  - Multi-select
  - Filterable Multi-select
  - Date picker
  - Number input
  - Select

### 2. Components that are commonly used
- OverflowMenu
- Search
- Modal (composed modal?)

### 3. Everything else
- InlineCheckbox
- ProgressIndicator
- TileGroup
- Pagination
- UIShell
- FileUploader
- Slider

**Comment by tay1orjones** [comment]
Looks like this can be marked as complete based on status of https://github.com/carbon-design-system/carbon/issues/10281 👍
