### ISSUE TITLE
Sprint 20: Counting Crow-sants 🥐

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9756]
## ⚛️  React
- [ ] #9535 @sstrubberg @dakahn 
- [ ] #9712 @jnm2377 @sstrubberg @aledavila
- [ ] #8487 @tay1orjones @abbeyhrt 
- [ ] #9843 @dakahn https://github.com/carbon-design-system/carbon/pull/9869
- [x] #9763 @abbeyhrt @aledavila 
- [ ] Tooltip @dakahn 
- [ ] https://github.com/carbon-design-system/carbon/issues/9831 (after #5367) @tay1orjones 

## 🚢  Migration
- [ ] #9640 @jnm2377 @tay1orjones 
  - [ ] Go through upgrade flow with design [NEEDS DESIGN REP]
  - [ ] Finalize initial upgrade flow
  - [ ] Implement package upgrade (preview, write)
  - [ ] Implement migration runner (preview, write)

## 🎨  Styles
- [ ] #5367 (remove margin) @tay1orjones 

## 📝  Website
 - [ ] https://github.com/carbon-design-system/carbon-website/pull/2421 (update to latest w/ ActionableNotification) - @tay1orjones 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2538 @andreancardona 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2489 @andreancardona 
- [x] https://github.com/carbon-design-system/carbon-website/pull/2562 @sstrubberg 
- [ ] Usage docs for Disclosure pattern @laurenmrice
- [ ] Overview form spacing problem https://github.com/carbon-design-system/carbon/issues/5367 @aagonzales 
- [ ] PR issue for Toggle tip @kingtraceyj 
- [ ] PR issue for optional and required fields @kingtraceyj 
- [ ] Pairing with a dev on deliverables on tabs @kingtraceyj 
- [ ] Syncing on actionable notification @kingtraceyj 
- [ ] Clean up and update Status indicators icons @thyhmdo 
- [x] Spec for 8 column (mini) live demo component @thyhmdo 
- [x] Update fixed image component spec https://github.com/carbon-design-system/carbon-website/issues/943@thyhmdo @thyhmdo  

## 🎨 Design Kit

- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/429 @aagonzales 

**Figma**

- [ ] Figma project reviews @aagonzales @laurenmrice  

## 💬 Support

- [x] https://github.com/carbon-design-system/carbon/pull/9740 @andreancardona 
- [ ] https://github.com/carbon-design-system/carbon/issues/9686 @abbeyhrt 
- [ ] https://github.com/carbon-design-system/carbon/issues/9442 @abbeyhrt
- [x] https://github.com/carbon-design-system/carbon/issues/9744 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/9762 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/9725 @dakahn 
- [ ] https://github.com/carbon-design-system/carbon/issues/9789 @aledavila 
- [ ] https://github.com/carbon-design-system/carbon/pull/8445 @jnm2377 
- [ ] https://github.com/carbon-design-system/carbon/issues/9698 @jnm2377 @abbeyhrt @tay1orjones 
- [ ] https://github.com/carbon-design-system/carbon/issues/9521 @aledavila 
- [x] https://github.com/carbon-design-system/carbon/issues/9630#issuecomment-933709487 @dakahn https://github.com/carbon-design-system/carbon/pull/9873
- [ ] https://github.com/carbon-design-system/carbon/issues/9732 ( context: https://github.com/carbon-design-system/carbon/pull/7698#issuecomment-926345722, is https://github.com/carbon-design-system/carbon/issues/9766 a duplicate? ) @dakahn 
- [ ] https://github.com/carbon-design-system/carbon/issues/9610 @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/9577 @tay1orjones 
- [ ] https://github.com/carbon-design-system/carbon/pull/9817 @tay1orjones

## 🚀  Releases

- [x] https://github.com/carbon-design-system/carbon/issues/9848 @tay1orjones @dakahn 

## 🐝  Brand
@vpicone 
- [x] https://github.com/carbon-design-system/design-language-website/issues/365
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1156 (might be duplicates)
- [x] https://github.com/carbon-design-system/design-language-website/issues/1009
- [x] https://github.com/carbon-design-system/design-language-website/issues/1010
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1168

## 📈     Dataviz
- [ ] RTL explorations

## 📣 Communication
- [ ] Blog post about Toggle tip, tooltip, disclosure, pop-over @laurenmrice @kingtraceyj  
  - [ ] Needs artwork
- [x] Publish [tutorial migration blog](https://medium.com/carbondesign/the-most-complete-and-thorough-guide-to-migrating-carbon-tutorial-v10-to-v11-e8b5a1eb331c) post @jnm2377 
- [ ] Finish draft for feature flags post @andreancardona 
  - [ ] Needs artwork
- [ ] Drafting for Carbon tabs and content switcher @kingtraceyj 
  - [ ] Needs artwork

## 🧙‍♂️ Meeting facilitators
- Backlog Grooming @dakahn 
- Sprint Retro @dakahn 
- Sprint Planning (next sprint 21)
  - Dev/System: @tay1orjones 

## 🏖️ **Vacations**
- Josh 
- John
- Josefina 10/14-15 🎂 
- Lauren 10/15

**Comment by alisonjoseph** [comment]
## Brand
- [ ] https://github.com/carbon-design-system/design-language-website/issues/365

**Comment by thyhmdo** [comment]
## ⚛️  React


## 🚢  Migration

## 🎨  Styles

## 📝  Website
- [ ] Usage docs for Disclosure pattern @laurenmrice
- [ ] Overview form spacing problem https://github.com/carbon-design-system/carbon/issues/5367 @aagonzales 
- [ ] PR issue for Toggle tip @kingtraceyj 
- [ ] PR issue for optional and required fields @kingtraceyj 
- [ ] Pairing with a dev on deliverables on tabs @kingtraceyj 
- [ ] Syncing on actionable notification @kingtraceyj 
- [ ] Clean up and update Status indicators icons @thyhmdo 
- [ ] Spec for 8 column (mini) live demo component @thyhmdo 
- [ ] Update fixed image component spec https://github.com/carbon-design-system/carbon-website/issues/943@thyhmdo @thyhmdo  

## 🎨 Design Kit

- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/429 @aagonzales 

**Figma**

- [ ] Figma project reviews @aagonzales @laurenmrice  
**Figma**

## 💬 Support

- [ ] https://github.com/carbon-design-system/carbon/issues/9725


## 🚀  Releases

- [ ] Release v10.46 @tay1orjones @dakahn 


## 🐝  Brand


## 🖥️ DPO


## 📣 Communication

- [ ] Blog post about Toggle tip, tooltip, disclosure, pop-over @laurenmrice @kingtraceyj  
  - [ ] Needs artwork
- [ ] Finish draft for feature flags post @andreancardona 
  - [ ] Needs artwork
- [ ] Drafting for Carbon tabs and content switcher @kingtraceyj 
  - [ ] Needs artwork

## 🏖️ **Vacations**

**Comment by tay1orjones** [comment]
## ⚛️ React
- [ ] #9535 @sstrubberg @dakahn 
- [ ] #9712 @jnm2377 @sstrubberg @aledavila
- [ ] #8487 @tay1orjones @abbeyhrt 
- [ ] ContentSwitcher @dakahn 
- [ ] #9763 @abbeyhrt @aledavila 
- [ ] Tooltip ?
- [ ] Stack, vertical layout helper (after #5367) @tay1orjones 
## 🚢 Migration
- [ ] #9640 @jnm2377 @tay1orjones 
  - [ ] Go through upgrade flow with design [NEEDS DESIGN REP]
  - [ ] Finalize initial upgrade flow
  - [ ] Implement package upgrade (preview, write)
  - [ ] Implement migration runner (preview, write)
## 🎨 Styles
- [ ] #5367 (remove margin) @tay1orjones 
## 📝 Website
 - [ ] https://github.com/carbon-design-system/carbon-website/pull/2421 (update to latest w/ ActionableNotification) - @tay1orjones 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2538 @andreancardona 
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2489 @andreancardona 

## 💬 Support
- [ ]  #9725  @aledavila  
- [ ] https://github.com/carbon-design-system/carbon/pull/9740 @andreancardona 
- [ ] https://github.com/carbon-design-system/carbon/issues/9686 @abbeyhrt 
- [ ] https://github.com/carbon-design-system/carbon/issues/9442 @abbeyhrt
- [ ] https://github.com/carbon-design-system/carbon/issues/9744 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/9762 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/9725 @aledavila 
- [ ] https://github.com/carbon-design-system/carbon/issues/9789 @aledavila 
- [ ] https://github.com/carbon-design-system/carbon/issues/9698 @jnm2377 @abbeyhrt @tay1orjones 
- [ ] https://github.com/carbon-design-system/carbon/issues/9521 @dakahn 
- [ ] https://github.com/carbon-design-system/carbon/issues/9732 ( context: https://github.com/carbon-design-system/carbon/pull/7698#issuecomment-926345722, is https://github.com/carbon-design-system/carbon/issues/9766 a duplicate? ) @dakahn 
- [ ] https://github.com/carbon-design-system/carbon/issues/9610 @tay1orjones 
- [ ] https://github.com/carbon-design-system/carbon/issues/9577 @tay1orjones 

## 🧙‍♂️ Meeting facilitators
- Backlog Grooming @dakahn 
- Sprint Retro @dakahn 
- Sprint Planning (next sprint 21)
  - Dev/System: @tay1orjones

**Comment by theiliad** [comment]
## 📈     Dataviz
- [ ] RTL explorations
