### ISSUE TITLE
[Bug]: Token "field-disabled" not involved into layering model

### ISSUE THREAD

**Issue by Eugeno** [carbon-design-system/carbon#9832]
### Package

@carbon/colors

### Package version

v11 beta 2

### Description

For example, we have a theme gray10, there is a white card (layering model). So disabled field is white on white background.
Looks like there should be filed-disabled-01, -02, -03.

### CodeSandbox example

—

### Steps to reproduce

check https://github.com/carbon-design-system/carbon/blob/36a6fdc307/packages/themes/src/next/g10.js

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aagonzales** [comment]
Re-opening issue as all concerns weren't addressed.

**To-dos:**
- [ ] Remove `$field-disabled` token
- [ ] Remove `$layer-disabled` token

**Consequences:**
Any place were `$field-disabled` and `layer-disabled were used will now simply just continue using `$field` and `$layer`. There is not visual change in the backgrounds of disabled elements. Only text and icons change color and there these tokens are not needed.

Components that were using these tokens and will need to be updated:
- text input
- search
- select
- number input
- date picker
- dropdown 
- text area
