### ISSUE TITLE
Sprint 21: Durian Duran 🍍 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#9864]
## ⚛️  React

- [x] #9712
  - [x] SideNavMenu @joshblack 
  - [x] HeaderNavigation @joshblack 
  - [x] ~~HeaderMenu~~ Deferred @joshblack 
  - [x] TimePicker @sstrubberg 
  - [x] TimePickerSelect @sstrubberg 
  - [ ] ModalHeader @aledavila 
  - [x] RadioButtonGroup @jnm2377 
  - [x] RadioButton @jnm2377 
  - [ ] DatePickerInput @jnm2377 
  - [ ] Slider @vpicone 
  - [ ] NumberInput @vpicone 
- [ ] Updated components
  - [ ] #8487 @tay1orjones @abbeyhrt
  - [x] ~~https://github.com/carbon-design-system/carbon/pull/9869~~ Deferred @dakahn
  - [x] #9941
  - [x] #9967
  - [x] #9966
  - [ ] https://github.com/carbon-design-system/carbon/issues/9902 @dakahn 
- [x] New components
  - [x] #9831 @tay1orjones @joshblack 

## 🚢  Migration

- [x] Create initial end-to-end flow for `@carbon/upgrade` @jnm2377 @joshblack @tay1orjones 
- [x] Sample App, create initial template and implement available pages from design @joshblack

## 🎨  Styles

- [ ] #9888 @sstrubberg @joshblack 

## 📦  Components

**Design**
- [ ] Read-only text inputs @thyhmdo https://github.com/carbon-design-system/carbon/issues/3018
- [ ] Progress bar @thyhmdo https://github.com/carbon-design-system/carbon-website/pull/2494

## 📝  Website

**Enhancements:**
- [ ] Usage docs for Disclosure pattern @laurenmrice
- [ ] Design layer section to Style tab @aagonzales 
- [ ] PR issue for Toggle tip @kingtraceyj 
- [x] PR issue for optional and required fields @laurenmrice 
- [ ] Animate usage images @johnbister 
   - [ ] Disclosure gif for Lauren
- [x] Update Notification accessibility page with new implementation from ActionableNotification/etc. @tay1orjones 
   -  https://github.com/carbon-design-system/carbon-website/pull/2422
- [x] https://github.com/carbon-design-system/carbon-website/pull/2592 @tay1orjones 

**Support/bugs:**
- [ ] Clean up and update Status indicators icons @thyhmdo 
- [x] Add a11y kit to website: @laurenmrice 
- [ ] Add type style info to data viz section @aagonzales 

## 🎨 Design Kit

**Sketch**
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/429 @aagonzales 
- [ ] Add in input component for all themes @aagonzales 

**Figma**
- [x] Component reviews @laurenmrice @aagonzales 

## 💬 Support

- [x] https://github.com/carbon-design-system/carbon/issues/9444 @sstrubberg 
- [x] Add default type mixin to `@carbon/react` (Reference: https://github.com/carbon-design-system/carbon/discussions/9723) @joshblack 
- [x] Figure out issue with font rendering (Reference: https://github.com/carbon-design-system/carbon/discussions/9723#discussioncomment-1375632) @joshblack 
- [ ] #9879 @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/6477 @tay1orjones 
- [x] https://github.com/carbon-design-system/carbon/issues/8502 @tay1orjones @abbeyhrt 
- [ ] #9686 @abbeyhrt
- [ ] #9442 @abbeyhrt
- [x] #9725 @dakahn
- [x] #9837 @jnm2377 
- [x] #9860 @aledavila 
- [x] #8445 @jnm2377 
- [x] https://github.com/carbon-design-system/carbon/issues/9927

## 🚀  Releases

- [x] https://github.com/carbon-design-system/carbon/issues/9949 @dakahn @tay1orjones @sstrubberg 

## 🐝  Brand

- [x] https://github.com/carbon-design-system/design-language-website/issues/1009
- [x] https://github.com/carbon-design-system/design-language-website/issues/1010
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1180 @alisonjoseph 
- [x] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1176 @vpicone 

## 📈     Dataviz

- [x] RTL evaluations
- [x] Area chart rendering bugfixes
- [x] Histogram ruler bugfixes

## 📣 Communication

- [ ] medium article toggle tip, tooltip, disclosure, pop-over @kingtraceyj @laurenmrice @joshblack 

## 🧙‍♂️ Meeting facilitators
- Backlog Grooming @jnm2377 
- Sprint Retro @abbeyhrt 
- Sprint Planning (next sprint 22)
  - Dev/System: @tay1orjones 

## 🏖️ **Vacations**
- Abbey - 10/21-22
- Josefina - Clarity Conference 10/27-29

**Comment by joshblack** [comment]
## ⚛️  React

- [ ] [Add usage docs for `Theme` and Theme and verify usage](https://github.com/carbon-design-system/carbon/discussions/9723#discussioncomment-1430963)
- [ ] [Figure out how portal components work with `Theme`](https://github.com/carbon-design-system/carbon/discussions/9723#discussioncomment-1432447)
- [ ] [Take a look at new grid column definitions vs flexbox](https://github.com/carbon-design-system/carbon/discussions/9723#discussioncomment-1431078)


## 🚢  Migration

- [ ] [Update migration docs to include quick start in instructions for using styles, setting, theme, using layers, etc](https://github.com/carbon-design-system/carbon/discussions/9723)
- [ ] [Update migration docs to include notice for missing styles](https://github.com/carbon-design-system/carbon/discussions/9723#discussioncomment-1376021)


## 🎨  Styles

- [ ] Update components using the compat theme to latest tokens
- [ ] Updates to grid based on feedback from v11 beta 2
- [ ] [Update text rendering in dark mode](https://github.com/carbon-design-system/carbon/discussions/9723#discussioncomment-1375632)
- [ ] [Add missing exports from type package](https://github.com/carbon-design-system/carbon/discussions/9723#discussioncomment-1375611)
- [ ] [Update subgrid logic to work with column offsets](https://github.com/carbon-design-system/carbon/discussions/9723#discussioncomment-1430432)


## 📝  Website


## 🎨 Design Kit


## 💬 Support

- [ ] https://github.com/carbon-design-system/carbon/issues/9444

## 🚀  Releases


## 🐝  Brand

- [ ] https://github.com/carbon-design-system/design-language-website/issues/1009
- [ ] https://github.com/carbon-design-system/design-language-website/issues/1010


## 🖥️ DPO

## 📈     Dataviz



## 📣 Communication



## 🧙‍♂️ Meeting facilitators
- Backlog Grooming
- Sprint Retro
- Sprint Planning (next sprint 22)
  - Dev/System: 

## 🏖️ **Vacations**
- Abbey - 10/21-22
- Josefina - Clarity Conference 10/27-29

**Comment by theiliad** [comment]
## 📈     Dataviz

- [ ] RTL evaluations
- [ ] Area chart rendering bugfixes
- [ ] Histogram ruler bugfixes

**Comment by antoinog** [comment]
Sandbox with issue.   Click button , no flicker.  Click header, flicker
https://codesandbox.io/s/quiet-rain-ruh6o?file=/package.json

Sandbox of 7.25 No flicker issue
https://codesandbox.io/s/cool-ride-p6o3e?file=/package.json

Possible reason:
https://github.com/carbon-design-system/carbon/pull/7876
setAnimate is called twice when header clicked, once in onclick, and once when open changes (if parent component saves state)
