### ISSUE TITLE
v11 Sample App

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9900]
We want to have a Sample App that we can use for v11 to demonstrate new and updated functionality along with providing a resource that is helpful for workshops and getting started with Carbon.

**Boilerplate**

- [ ] Uses Next.js under the hood
- [ ] Provides the following configuration:
  - [ ] ESLint
  - [ ] Stylelint
  - [ ] Jest
  - [ ] Husky for commitlint and lint-staged
  - [ ] Cypress for e2e testing
- [ ] Provides the following integrations:
  - [ ] Brings in dart sass
  - [ ] Brings in `@carbon/react`

**Features**

This sample app should demonstrate the following new or updated functionality from v10:

- [ ] Using the new package `@carbon/react`
- [ ] Using dart sass and new styles with Sass Modules
- [ ] Design Tokens
  - [ ] CSS Custom Properties
  - [ ] Layering with contextual tokens
- [ ] CSS Grid with updated Grid component
  - [ ] Could combine with other layout helpers / templates like `Stack`
- [ ] Theming
  - [ ] Light/dark mode
  - [ ] Inline Theming
- [ ] Using icons from `@carbon/react/icons`
- [ ] New or updated components
  - [ ] Notifications
  - [ ] Tabs
  - [ ] Popover
  - [ ] Tooltip
  - [ ] IconButton
- [ ] Laying out a form using `Grid` and `Stack`

**Stories**

There are a couple of notable page/interaction types that we could try and support with this resource, including:

- Ecommerce
- Catalog
- Global search
- Notifications
- Login page, authenticated experience
- Theme switching/preferences
- Dashboard
- Forms
- Blog
- Marketing page
- Pricing page

**Links & Resources**

- [Next.js e-commerce example](https://demo.vercel.store/)
- [MUI templates](https://mui.com/getting-started/templates/)
